import type { Language } from './translations';

interface StepContent {
  title: string;
  desc: string;
  tips: string[];
  linkLabel: string;
}

interface FaqItem {
  q: string;
  a: string;
}

const STEP_META = [
  { step: 1, link: '/pricing' },
  { step: 2, link: '/eras' },
  { step: 3, link: '/timeline' },
  { step: 4, link: '/tutor' },
  { step: 5, link: '/eras' },
  { step: 6, link: '/smart-quiz' },
  { step: 7, link: '/flashcards' },
  { step: 8, link: '/notes' },
  { step: 9, link: '/progress' },
  { step: 10, link: '/essay' },
  { step: 11, link: '/debate' },
  { step: 12, link: '/video-review' },
  { step: 13, link: '/timeline-map' },
  { step: 14, link: '/crisis' },
  { step: 15, link: '/study-plan' },
  { step: 16, link: '/studio' },
  { step: 17, link: '/imperium' },
  { step: 18, link: '/friends' },
  { step: 19, link: '/leaderboard' },
];

const STEPS_EN: StepContent[] = [
  { title: 'Choose Your Plan', desc: 'Start for free with 6 intro lessons (one per era). Upgrade to Pro for all 132 lessons and AI Tutor access, or go Master for unlimited AI and downloads.', tips: ['Free plan: no credit card needed', 'Beginner Student: $4.99/month — timeline, flashcards, 10 Clio messages/day', 'Pro Student: $9.99/month, most popular', 'Master Student: $17.99/month — the complete experience'], linkLabel: 'View Plans' },
  { title: 'Explore Eras & Lessons', desc: 'Navigate to Eras & Lessons from the sidebar. Six eras await — Prehistoric Ages, Ancient World, The Byzantine World, Middle Ages, Early Modern, and Modern — each walked strictly in order: finish a lesson, pass Clio\'s written analysis (grade B or better), and the next one unseals.', tips: ['Twenty-two lessons per era — 132 in all', 'Lessons unlock strictly in sequence on every plan', 'After each lesson, Clio\'s 150–300-word analysis gate opens the path forward', 'A 30-minute reflection cooldown runs between lessons'], linkLabel: 'Go to Eras' },
  { title: 'Explore the Timeline', desc: 'The interactive timeline charts 150+ pivotal events across all six eras — from the first stone tools to the digital age. Click any event to read a summary and jump directly to its lesson.', tips: ['Filter by era using the tab bar', 'Events link directly to lessons', 'Pro users see all categories and filters'], linkLabel: 'Open Timeline' },
  { title: 'Ask Clio — Your AI Tutor', desc: 'Clio is your personal AI history tutor. Ask anything about history, get explanations, compare events, or dig deeper into any topic from your lessons.', tips: ['Available on Pro and Master plans', 'Pro: 50 messages/month', 'Master: unlimited messages', 'Clio also appears as a chatbot on the landing page'], linkLabel: 'Open AI Tutor' },
  { title: 'Take Quizzes & Earn XP', desc: 'Each era ends in a 50-question mastery quiz. The bar is high — 48 of 50 to pass — because passing means you truly own the era. Correct answers earn XP, level you up, and track your score per era.', tips: ['50 questions per era quiz — 300 in all', 'Score 48/50 to pass: mastery, not luck', 'Quiz explanations available on Pro+'], linkLabel: 'Go to Eras' },
  { title: 'Try the Smart Quiz', desc: 'Smart Quiz is an adaptive 10-question session drawn from all 6 eras. The algorithm targets your weakest areas and calibrates difficulty to your performance.', tips: ['Available on Pro and Master plans', '10 questions per session', 'Algorithm weights weak eras higher', 'Earn up to +150 XP per session'], linkLabel: 'Try Smart Quiz' },
  { title: 'Review with Flashcards', desc: 'Flashcards let you drill key terms, dates, and concepts from every lesson. Flip cards to reveal answers and mark them as known or unknown.', tips: ['Cards drawn from all lessons', 'Great for revision before quizzes', 'Track how many you know'], linkLabel: 'Open Flashcards' },
  { title: 'Write Personal Notes', desc: 'Capture your thoughts, insights, and summaries as you study. Notes are linked to lessons and saved locally — always there when you come back.', tips: ['Notes saved per lesson', 'Accessible from the My Notes page', 'All data stored locally on your device'], linkLabel: 'Open Notes' },
  { title: 'Track Your Progress', desc: 'The Progress page shows your XP history, era completion rates, quiz scores, streak, and achievement badges. See exactly where you stand.', tips: ['Streak resets if you miss a day', 'Achievements unlock at milestones', 'Charts update after every quiz'], linkLabel: 'View Progress' },
  { title: 'Essay Challenge', desc: 'Put your historical knowledge to the test with a timed essay challenge. Clio grades your essay live with detailed analysis on argument, evidence, depth, and writing quality.', tips: ['Available on Pro and Master plans', 'Essays are graded by Clio — strict but constructive', 'Choose from multiple historical topics', 'Earn XP proportional to your grade (A = max XP)'], linkLabel: 'Try Essay Challenge' },
  { title: 'Debate a Philosopher', desc: 'A new philosopher is featured every 12 hours. Engage them in vigorous philosophical debate — they have pre-loaded arguments and a strong command of their own philosophy. Make them concede to earn XP.', tips: ['Available on Pro Learner and above', 'A new philosopher appears every 12 hours', 'Earn XP by making the philosopher concede', 'Greater philosophers yield more XP', 'Use pre-loaded starter arguments or write your own'], linkLabel: 'Open Debate' },
  { title: 'Video Review Challenge', desc: 'Watch a curated educational history video (≤10 min), then write your analysis identifying the main motive or argument. Clio grades your review sentence-by-sentence with a live 3D animation.', tips: ['Exclusive to Master Student plan', 'A new video unlocks every 12 hours', 'Earn special Video XP — separate from regular XP', 'Video XP advances your Historical Chess Rank', 'Chess Rank gives 2× advantage on the Leaderboard'], linkLabel: 'Open Video Review' },
  { title: 'Timeline Territory Map', desc: 'Explore real geographic territories for 40+ historical periods on a live map — from the Out-of-Africa migrations to the Cold War, now including the Olmec, the Khmer Empire, Songhai, and the Polynesian voyagers. Every territory carries researched borders, capitals, battles, and trade routes. Switch between Explore mode (toggle layers, read annotated markers), Story mode (auto-animated tour), and Quiz mode with full explanations.', tips: ['Requires Pro Learner or Master Student plan', 'Switch between Explore, Story, and Quiz modes', 'Every territory has real geometry: borders, capitals, battles, routes', 'Quiz XP capped at 500 per session to keep it fair'], linkLabel: 'Open Territory Map' },
  { title: 'Chronos Crisis Room', desc: 'Step into a real historical turning point as the leader who faced it. The Chronos Engine — an AI game master — narrates the crisis, offers three genuine strategic options each turn (or accepts any plan you type), and evaluates every decision in real time against real historical constraints. After six turns you receive the Verdict: your counterfactual timeline compared with real history, a final score out of 100, and the lesson the episode teaches.', tips: ['Nine scenarios — from Salamis (480 BCE) and the Rubicon to Hattin (1187), Constantinople (1453), the Armada (1588), the July Crisis (1914), and the Cuban Missile Crisis (1962)', 'Every decision is scored live: Stability, Legitimacy, and Legacy out of 10', 'Type any free-form plan — the Engine takes it seriously and plays out the consequences', 'Simulations run exactly six turns and end with a full historical verdict', 'Exclusive to the Master Student plan'], linkLabel: 'Enter the Crisis Room' },
  { title: 'Follow Your Study Plan', desc: 'The Study Plan reads your mastery of every era — lesson coverage, quiz scores, adaptive accuracy — and schedules a week of study aimed at your weakest area. Steps deep-link to real lessons and check themselves off as you complete the underlying activity.', tips: ['Available on Pro Student and above', 'Regenerate the week any time', '"Enhance with Clio" coaching notes are Master Student exclusive', 'Steps auto-complete as you learn'], linkLabel: 'Open Study Plan' },
  { title: 'Build Kits in the AI Studio', desc: 'Paste any historical text — a textbook chapter, an article, your own notes — and the studio engineers it into a validated study kit: summary, key facts, flashcards, and quiz questions. Curate what to keep, save the set, and practice it forever.', tips: ['Available on Pro Student and above', 'Every question is mechanically validated before you see it', 'Practice runs award XP at 60%+ scores', 'Your library holds up to 30 sets'], linkLabel: 'Open AI Studio' },
  { title: 'Rule in Chronos Imperium', desc: 'The grand campaign: govern a historical realm era by era. Two-thirds of every victory is intellect — dilemmas drawn from real history, policy decisions Clio examines, and knowledge checks that decide your fate — and one-third is the game of armies, provinces, and battles that plays out on the strategic map.', tips: ['Exclusive to the Master Student plan', 'Every decision is scored against real historical reasoning', 'Clio rates each move and narrates consequences', 'Battles resolve in an animated on-map theater'], linkLabel: 'Enter Chronos Imperium' },
  { title: 'Learn with Friends', desc: 'Add friends by username, message them, and challenge them to a History 1v1 — a head-to-head battle of historical knowledge where the sharper mind wins. Rivalry is a study technique.', tips: ['Add friends by exact username', 'Built-in private messaging', 'History 1v1: knowledge duels with XP at stake'], linkLabel: 'Open Friends' },
  { title: 'Climb the Leaderboard', desc: 'Every XP point counts toward your standing. The leaderboard ranks all learners globally; Video Review Chess Rank multiplies your climb. Check where you stand — then study your way higher.', tips: ['Ranked by total XP', 'Chess Rank (Video Review) gives a 2× leaderboard advantage', 'Updates live as you learn'], linkLabel: 'View Leaderboard' },
];

const STEPS_ES: StepContent[] = [
  { title: 'Elige tu Plan', desc: 'Comienza gratis con 6 lecciones introductorias (una por era). Actualiza a Pro para todas las 132 lecciones y el Tutor IA, o elige Master para IA ilimitada y descargas.', tips: ['Plan gratuito: sin tarjeta de crédito', 'Beginner Student: $4.99/mes — línea de tiempo, tarjetas, 10 mensajes de Clío/día', 'Pro Student: $9.99/mes, el más popular', 'Master Student: $17.99/mes — la experiencia completa'], linkLabel: 'Ver Planes' },
  { title: 'Explora Eras y Lecciones', desc: 'Navega a Eras y Lecciones desde la barra lateral. Te esperan seis eras — Edad Prehistórica, Mundo Antiguo, El Mundo Bizantino, Edad Media, Época Moderna Temprana y Era Moderna — recorridas estrictamente en orden: termina una lección, aprueba el análisis escrito de Clío (nota B o mejor) y la siguiente se abre.', tips: ['Veintidós lecciones por era — 132 en total', 'Las lecciones se desbloquean en secuencia estricta en todos los planes', 'Tras cada lección, el análisis de 150–300 palabras de Clío abre el camino', 'Entre lecciones corre una pausa de reflexión de 30 minutos'], linkLabel: 'Ir a Eras' },
  { title: 'Explora la Línea de Tiempo', desc: 'La línea de tiempo interactiva traza más de 150 eventos cruciales de las seis eras — de las primeras herramientas de piedra a la era digital. Haz clic en cualquier evento para leer un resumen y saltar directamente a su lección.', tips: ['Filtra por era con la barra de pestañas', 'Los eventos enlazan directamente a lecciones', 'Los usuarios Pro ven todas las categorías y filtros'], linkLabel: 'Abrir Línea de Tiempo' },
  { title: 'Pregunta a Clio — Tu Tutor IA', desc: 'Clio es tu tutor personal de historia con IA. Pregunta cualquier cosa sobre historia, obtén explicaciones, compara eventos o profundiza en cualquier tema de tus lecciones.', tips: ['Disponible en planes Pro y Master', 'Pro: 50 mensajes/mes', 'Master: mensajes ilimitados', 'Clio también aparece como chatbot en la página de inicio'], linkLabel: 'Abrir Tutor IA' },
  { title: 'Haz Quizzes y Gana XP', desc: 'Cada era termina en un quiz de maestría de 50 preguntas. El listón es alto — 48 de 50 para aprobar — porque aprobar significa dominar la era de verdad. Las respuestas correctas ganan XP, suben de nivel y rastrean tu puntuación por era.', tips: ['50 preguntas por quiz de era — 300 en total', 'Aprueba con 48/50: maestría, no suerte', 'Explicaciones del quiz disponibles en Pro+'], linkLabel: 'Ir a Eras' },
  { title: 'Prueba el Quiz Inteligente', desc: 'El Quiz Inteligente es una sesión adaptativa de 10 preguntas de las 6 eras. El algoritmo se enfoca en tus áreas más débiles y calibra la dificultad según tu rendimiento.', tips: ['Disponible en planes Pro y Master', '10 preguntas por sesión', 'El algoritmo prioriza las eras débiles', 'Gana hasta +150 XP por sesión'], linkLabel: 'Probar Quiz Inteligente' },
  { title: 'Repasa con Tarjetas', desc: 'Las tarjetas te permiten practicar términos clave, fechas y conceptos de cada lección. Voltea las tarjetas para ver respuestas y márcalas como conocidas o desconocidas.', tips: ['Tarjetas de todas las lecciones', 'Ideal para repasar antes de quizzes', 'Rastrea cuántas conoces'], linkLabel: 'Abrir Tarjetas' },
  { title: 'Escribe Notas Personales', desc: 'Captura tus pensamientos, ideas y resúmenes mientras estudias. Las notas están vinculadas a lecciones y guardadas localmente — siempre disponibles cuando vuelves.', tips: ['Notas guardadas por lección', 'Accesibles desde la página Mis Notas', 'Todos los datos guardados localmente en tu dispositivo'], linkLabel: 'Abrir Notas' },
  { title: 'Sigue tu Progreso', desc: 'La página de Progreso muestra tu historial de XP, tasas de completación por era, puntuaciones de quiz, racha y logros. Ve exactamente dónde estás.', tips: ['La racha se reinicia si pierdes un día', 'Los logros se desbloquean en hitos', 'Los gráficos se actualizan después de cada quiz'], linkLabel: 'Ver Progreso' },
  { title: 'Desafío de Ensayo', desc: 'Pon a prueba tu conocimiento histórico con un desafío de ensayo. Clio evalúa tu ensayo en vivo con análisis detallado sobre argumento, evidencia, profundidad y calidad de escritura.', tips: ['Disponible en planes Pro y Master', 'Los ensayos son evaluados por Clio — estricto pero constructivo', 'Elige entre múltiples temas históricos', 'Gana XP proporcional a tu nota (A = XP máximo)'], linkLabel: 'Probar Desafío de Ensayo' },
  { title: 'Debate con un Filósofo', desc: 'Cada 12 horas se presenta un nuevo filósofo. Debátelos filosóficamente — tienen argumentos pre-cargados y dominio de su propia filosofía. Hazlos conceder para ganar XP.', tips: ['Disponible en Pro Learner y superior', 'Nuevo filósofo cada 12 horas', 'Gana XP haciendo conceder al filósofo', 'Los filósofos más grandes dan más XP', 'Usa argumentos de inicio o escribe los tuyos'], linkLabel: 'Abrir Debate' },
  { title: 'Desafío de Revisión de Vídeo', desc: 'Mira un vídeo educativo de historia (≤10 min), luego escribe tu análisis identificando el motivo o argumento principal. Clio evalúa tu revisión frase por frase con una animación 3D en vivo.', tips: ['Exclusivo del plan Master Student', 'Nuevo vídeo cada 12 horas', 'Gana XP de Vídeo especial — separado del XP regular', 'El XP de Vídeo avanza tu Rango de Ajedrez Histórico', 'El Rango de Ajedrez da ventaja 2× en el Marcador'], linkLabel: 'Abrir Revisión de Vídeo' },
  { title: 'Mapa de Territorios Históricos', desc: 'Explora territorios geográficos reales de más de 40 períodos históricos en un mapa en vivo — de las migraciones fuera de África a la Guerra Fría, ahora con los olmecas, el Imperio jemer, Songhai y los navegantes polinesios. Cada territorio lleva fronteras investigadas, capitales, batallas y rutas comerciales. Cambia entre modo Explorar (filtra capas, lee marcadores), modo Historia (tour animado) y modo Quiz con explicaciones completas.', tips: ['Requiere plan Pro Learner o Master Student', 'Cambia entre modos Explorar, Historia y Quiz', 'Cada territorio tiene geometría real: fronteras, capitales, batallas, rutas', 'XP del quiz limitado a 500 por sesión para mantener la equidad'], linkLabel: 'Abrir Mapa de Territorios' },
  { title: 'Sala de crisis Chronos', desc: 'Entra en un punto de inflexión histórico real como el líder que lo enfrentó. El Motor Chronos — un director de juego con IA — narra la crisis, ofrece tres opciones estratégicas genuinas por turno (o acepta cualquier plan que escribas) y evalúa cada decisión en tiempo real contra las restricciones históricas reales. Tras seis turnos recibes el Veredicto: tu línea temporal contrafactual comparada con la historia real, una puntuación final sobre 100 y la lección que enseña el episodio.', tips: ['Nueve escenarios — de Salamina (480 a.C.) y el Rubicón a Hattin (1187), Constantinopla (1453), la Armada (1588), la crisis de julio (1914) y la crisis de los misiles (1962)', 'Cada decisión se puntúa en vivo: Estabilidad, Legitimidad y Legado sobre 10', 'Escribe cualquier plan libre — el Motor lo toma en serio y desarrolla las consecuencias', 'Las simulaciones duran exactamente seis turnos y terminan con un veredicto histórico completo', 'Exclusivo del plan Master Student'], linkLabel: 'Entrar en la Sala de Crisis' },
  { title: 'Sigue tu Plan de Estudio', desc: 'El Plan de Estudio lee tu dominio de cada era — cobertura de lecciones, puntuaciones de quiz, precisión adaptativa — y programa una semana de estudio dirigida a tu área más débil. Los pasos enlazan a lecciones reales y se marcan solos al completar la actividad.', tips: ['Disponible en Pro Student y superior', 'Regenera la semana cuando quieras', 'Las notas de coaching «Mejorar con Clío» son exclusivas de Master Student', 'Los pasos se completan automáticamente mientras aprendes'], linkLabel: 'Abrir Plan de Estudio' },
  { title: 'Crea Kits en el Estudio IA', desc: 'Pega cualquier texto histórico — un capítulo, un artículo, tus propios apuntes — y el estudio lo convierte en un kit de estudio validado: resumen, datos clave, tarjetas y preguntas de quiz. Elige qué conservar, guarda el set y practícalo para siempre.', tips: ['Disponible en Pro Student y superior', 'Cada pregunta se valida mecánicamente antes de mostrarse', 'Las prácticas dan XP con puntuaciones de 60%+', 'Tu biblioteca guarda hasta 30 sets'], linkLabel: 'Abrir Estudio IA' },
  { title: 'Gobierna en Chronos Imperium', desc: 'La gran campaña: gobierna un reino histórico época tras época. Dos tercios de cada victoria son intelecto — dilemas de la historia real, decisiones políticas que Clío examina y pruebas de conocimiento que deciden tu destino — y un tercio es el juego de ejércitos, provincias y batallas sobre el mapa estratégico.', tips: ['Exclusivo del plan Master Student', 'Cada decisión se puntúa contra el razonamiento histórico real', 'Clío califica cada movimiento y narra las consecuencias', 'Las batallas se resuelven en un teatro animado sobre el mapa'], linkLabel: 'Entrar en Chronos Imperium' },
  { title: 'Aprende con Amigos', desc: 'Añade amigos por nombre de usuario, envíales mensajes y desafíalos a un 1v1 de Historia — un duelo de conocimiento histórico donde gana la mente más aguda. La rivalidad es una técnica de estudio.', tips: ['Añade amigos por nombre de usuario exacto', 'Mensajería privada integrada', '1v1 de Historia: duelos de conocimiento con XP en juego'], linkLabel: 'Abrir Amigos' },
  { title: 'Sube en la Clasificación', desc: 'Cada punto de XP cuenta para tu posición. La clasificación ordena a todos los estudiantes globalmente; el Rango de Ajedrez de Revisión de Vídeo multiplica tu ascenso. Mira dónde estás — y estudia para subir.', tips: ['Ordenada por XP total', 'El Rango de Ajedrez (Revisión de Vídeo) da ventaja 2×', 'Se actualiza en vivo mientras aprendes'], linkLabel: 'Ver Clasificación' },
];

const STEPS_RU: StepContent[] = [
  { title: 'Выберите свой план', desc: 'Начните бесплатно с 6 вводных уроков (по одному на эпоху). Обновитесь до Pro для доступа ко всем 132 урокам и ИИ-Наставнику, или выберите Master для неограниченного ИИ и загрузок.', tips: ['Бесплатный план: без кредитной карты', 'Beginner Student: $4.99/мес — хронология, карточки, 10 сообщений Клио/день', 'Pro Student: $9.99/мес, самый популярный', 'Master Student: $17.99/мес — полный опыт'], linkLabel: 'Посмотреть Планы' },
  { title: 'Изучайте Эпохи и Уроки', desc: 'Перейдите в раздел «Эпохи и Уроки» из боковой панели. Вас ждут шесть эпох — Доисторическая эпоха, Древний мир, Византийский мир, Средние века, Раннее Новое время и Новейшее время — и путь через каждую проходится строго по порядку: завершите урок, сдайте письменный анализ Клио (оценка B или выше), и следующий откроется.', tips: ['Двадцать два урока в каждой эпохе — всего 132', 'Уроки открываются строго по порядку на любом плане', 'После каждого урока анализ Клио на 150–300 слов открывает путь дальше', 'Между уроками действует 30-минутная пауза на осмысление'], linkLabel: 'Перейти к Эпохам' },
  { title: 'Исследуйте Хронологию', desc: 'Интерактивная хронология показывает более 150 ключевых событий всех шести эпох — от первых каменных орудий до цифровой эры. Нажмите на любое событие, чтобы прочитать описание и перейти прямо к уроку.', tips: ['Фильтрация по эпохам через панель вкладок', 'События ведут напрямую к урокам', 'Пользователи Pro видят все категории и фильтры'], linkLabel: 'Открыть Хронологию' },
  { title: 'Спросите Клио — ИИ-Наставника', desc: 'Клио — ваш персональный репетитор истории на базе ИИ. Задавайте любые вопросы по истории, получайте объяснения, сравнивайте события или углубляйтесь в любую тему.', tips: ['Доступно на планах Pro и Master', 'Pro: 50 сообщений/мес', 'Master: неограниченные сообщения', 'Клио также доступна как чат-бот на главной странице'], linkLabel: 'Открыть ИИ-Наставника' },
  { title: 'Проходите Викторины и Зарабатывайте XP', desc: 'Каждая эпоха завершается викториной мастерства из 50 вопросов. Планка высока — 48 из 50 для сдачи — потому что сдать значит по-настоящему владеть эпохой. Правильные ответы приносят XP, повышают уровень и отслеживают результат по эпохам.', tips: ['50 вопросов в викторине по эпохе — всего 300', 'Сдача с 48/50: мастерство, а не удача', 'Объяснения к вопросам доступны на Pro+'], linkLabel: 'Перейти к Эпохам' },
  { title: 'Попробуйте Умную Викторину', desc: 'Умная Викторина — адаптивная сессия из 10 вопросов из всех 6 эпох. Алгоритм нацелен на ваши слабые места и регулирует сложность по результатам.', tips: ['Доступно на планах Pro и Master', '10 вопросов за сессию', 'Алгоритм приоритизирует слабые эпохи', 'Зарабатывайте до +150 XP за сессию'], linkLabel: 'Попробовать Умную Викторину' },
  { title: 'Повторяйте с Карточками', desc: 'Карточки позволяют повторять ключевые термины, даты и концепции из каждого урока. Переворачивайте карточки и отмечайте как «знаю» или «не знаю».', tips: ['Карточки из всех уроков', 'Отлично для подготовки к викторинам', 'Отслеживайте, сколько вы уже знаете'], linkLabel: 'Открыть Карточки' },
  { title: 'Ведите Личные Заметки', desc: 'Записывайте мысли, идеи и краткие конспекты во время учёбы. Заметки привязаны к урокам и хранятся локально — всегда под рукой.', tips: ['Заметки сохраняются по урокам', 'Доступны на странице «Мои Заметки»', 'Данные хранятся локально на вашем устройстве'], linkLabel: 'Открыть Заметки' },
  { title: 'Следите за Прогрессом', desc: 'Страница Прогресса показывает историю XP, завершённость эпох, результаты викторин, серию и достижения. Узнайте, где именно вы находитесь.', tips: ['Серия сбрасывается, если пропустить день', 'Достижения открываются на определённых вехах', 'Графики обновляются после каждой викторины'], linkLabel: 'Смотреть Прогресс' },
  { title: 'Эссе-Задание', desc: 'Проверьте свои знания истории в эссе-задании. Клио оценивает ваше эссе в реальном времени с детальным анализом аргументации, доказательств, глубины и качества написания.', tips: ['Доступно на планах Pro и Master', 'Эссе оцениваются Клио — строго, но конструктивно', 'Выбирайте из нескольких исторических тем', 'Зарабатывайте XP пропорционально оценке (A = максимум XP)'], linkLabel: 'Попробовать Эссе-Задание' },
  { title: 'Дискуссия с Философом', desc: 'Каждые 12 часов появляется новый философ. Вступите с ним в философскую дискуссию — у него есть предустановленные аргументы и глубокое знание своей философии. Заставьте его признать поражение и получите XP.', tips: ['Доступно на Pro Learner и выше', 'Новый философ каждые 12 часов', 'Зарабатывайте XP, заставляя философа сдаться', 'Более великие философы дают больше XP', 'Используйте стартовые аргументы или пишите свои'], linkLabel: 'Открыть Дискуссию' },
  { title: 'Видео-Задание', desc: 'Посмотрите обучающее историческое видео (≤10 мин), затем напишите анализ, определив главный мотив или аргумент. Клио оценивает ваш обзор предложение за предложением с живой 3D-анимацией.', tips: ['Только для плана Master Student', 'Новое видео доступно каждые 12 часов', 'Зарабатывайте специальный Видео XP — отдельно от обычного XP', 'Видео XP повышает ваш Исторический Шахматный Ранг', 'Шахматный Ранг даёт преимущество 2× в рейтинге'], linkLabel: 'Открыть Видео-Задание' },
  { title: 'Карта Исторических Территорий', desc: 'Исследуйте реальные географические территории более 40 исторических периодов на живой карте — от миграций из Африки до холодной войны, теперь включая ольмеков, Кхмерскую империю, Сонгай и полинезийских мореплавателей. Каждая территория несёт исследованные границы, столицы, битвы и торговые пути. Переключайтесь между режимом Исследования (слои, аннотированные маркеры), режимом Истории (анимированный тур) и режимом Викторины с полными объяснениями.', tips: ['Требуется план Pro Learner или Master Student', 'Переключайтесь между режимами: Исследование, История и Викторина', 'У каждой территории реальная геометрия: границы, столицы, битвы, пути', 'XP от викторины ограничен до 500 за сессию для справедливости'], linkLabel: 'Открыть Карту Территорий' },
  { title: 'Кризисный штаб «Хронос»', desc: 'Окажитесь в реальном поворотном моменте истории в роли лидера, который его пережил. Движок «Хронос» — ИИ-ведущий — описывает кризис, предлагает три подлинно разные стратегии каждый ход (или принимает любой ваш собственный план) и оценивает каждое решение в реальном времени с учётом реальных исторических ограничений. После шести ходов вы получаете Вердикт: сравнение вашей контрфактической линии времени с реальной историей, итоговый балл из 100 и урок, который преподаёт этот эпизод.', tips: ['Девять сценариев — от Саламина (480 г. до н.э.) и Рубикона до Хаттина (1187), Константинополя (1453), Армады (1588), Июльского кризиса (1914) и Карибского кризиса (1962)', 'Каждое решение оценивается в реальном времени: стабильность, легитимность и наследие по 10-балльной шкале', 'Пишите любой собственный план — движок серьёзно его отыграет', 'Симуляция длится ровно шесть ходов и завершается полным историческим вердиктом', 'Эксклюзив плана Master Student'], linkLabel: 'Войти в Кризисный штаб' },
  { title: 'Следуйте Плану занятий', desc: 'План занятий читает ваше освоение каждой эпохи — покрытие уроков, результаты викторин, адаптивную точность — и составляет неделю занятий, нацеленную на самое слабое место. Шаги ведут к реальным урокам и отмечаются сами по мере выполнения.', tips: ['Доступно на Pro Student и выше', 'Пересоставляйте неделю в любой момент', 'Тренерские заметки «Усилить с Клио» — эксклюзив Master Student', 'Шаги отмечаются автоматически по мере обучения'], linkLabel: 'Открыть План занятий' },
  { title: 'Создавайте наборы в ИИ-студии', desc: 'Вставьте любой исторический текст — главу учебника, статью, собственный конспект — и студия превратит его в проверенный учебный набор: краткое содержание, ключевые факты, карточки и вопросы викторины. Отберите нужное, сохраните набор и практикуйтесь.', tips: ['Доступно на Pro Student и выше', 'Каждый вопрос механически проверяется до показа', 'Практика даёт XP при результате 60%+', 'Библиотека вмещает до 30 наборов'], linkLabel: 'Открыть ИИ-студию' },
  { title: 'Правьте в Chronos Imperium', desc: 'Великая кампания: управляйте историческим государством эпоха за эпохой. Две трети каждой победы — интеллект: дилеммы из реальной истории, политические решения, которые разбирает Клио, и проверки знаний, решающие вашу судьбу; и одна треть — игра армий, провинций и битв на стратегической карте.', tips: ['Эксклюзив плана Master Student', 'Каждое решение оценивается по реальной исторической логике', 'Клио оценивает каждый ход и рассказывает последствия', 'Битвы разыгрываются в анимированном театре на карте'], linkLabel: 'Войти в Chronos Imperium' },
  { title: 'Учитесь с Друзьями', desc: 'Добавляйте друзей по имени пользователя, переписывайтесь и вызывайте их на Историческую дуэль 1 на 1 — битву исторических знаний, где побеждает более острый ум. Соперничество — это техника обучения.', tips: ['Добавляйте друзей по точному имени пользователя', 'Встроенные личные сообщения', 'Дуэль 1 на 1: поединки знаний со ставкой XP'], linkLabel: 'Открыть Друзей' },
  { title: 'Поднимайтесь в Рейтинге', desc: 'Каждое очко XP влияет на вашу позицию. Таблица лидеров ранжирует всех учеников глобально; Шахматный ранг Видео-разбора умножает ваш подъём. Посмотрите, где вы, — и учитесь, чтобы подняться выше.', tips: ['Ранжирование по общему XP', 'Шахматный ранг (Видео-разбор) даёт преимущество 2×', 'Обновляется вживую по мере обучения'], linkLabel: 'Открыть Рейтинг' },
];

const STEPS_MK: StepContent[] = [
  { title: 'Избери го твојот план', desc: 'Започни бесплатно со 6 вводни лекции (по една за секоја епоха). Надгради на Pro за пристап до сите 132 лекции и ВИ Тутор, или избери Master за неограничен ВИ и преземања.', tips: ['Бесплатен план: без кредитна картичка', 'Beginner Student: $4.99/месец — временска линија, картички, 10 пораки на Клио/ден', 'Pro Student: $9.99/месец, најпопуларен', 'Master Student: $17.99/месец — целосното искуство'], linkLabel: 'Погледни Планови' },
  { title: 'Истражи Епохи и Лекции', desc: 'Оди на Епохи и Лекции преку страничната лента. Избери епоха — Праисториско Доба, Античко Доба, Среден Век, Рано Модерно Доба или Модерна Ера — и отвори која сакаш отклучена лекција.', tips: ['Дваесет и две лекции по епоха', 'Лекциите содржат богати историски детали', 'Заврши лекција за да го отклучиш квизот за таа епоха'], linkLabel: 'Оди на Епохи' },
  { title: 'Истражи ја Временската Линија', desc: 'Интерактивната временска линија прикажува повеќе од 150 клучни настани од сите шест епохи — од првите камени алатки до дигиталната ера. Кликни на кој било настан за да прочиташ краток опис и да скокнеш директно на неговата лекција.', tips: ['Филтрирај по епоха со лентата за картички', 'Настаните водат директно до лекции', 'Корисниците на Pro ги гледаат сите категории и филтри'], linkLabel: 'Отвори Временска Линија' },
  { title: 'Прашај ја Клио — твојот ВИ Тутор', desc: 'Клио е твојот личен ВИ тутор за историја. Прашај за сè поврзано со историјата, добивај објаснувања, споредувај настани или задлабочи се во која тема сакаш.', tips: ['Достапно на плановите Pro и Master', 'Pro: 50 пораки/месец', 'Master: неограничени пораки', 'Клио исто така се наоѓа на почетната страница'], linkLabel: 'Отвори ВИ Тутор' },
  { title: 'Прави Квизови и Заработувај XP', desc: 'Секоја епоха завршува со мајсторски квиз од 50 прашања. Лествичката е висока — 48 од 50 за положување — бидејќи положувањето значи вистинско владеење на епохата. Точните одговори носат XP, те креваат на ниво и го следат твојот резултат по епоха.', tips: ['50 прашања по квиз на епоха — вкупно 300', 'Положи со 48/50: мајсторство, не среќа', 'Објаснувања за квизот достапни на Pro+'], linkLabel: 'Оди на Епохи' },
  { title: 'Обиди се со Паметниот Квиз', desc: 'Паметниот Квиз е адаптивна сесија со 10 прашања од сите 6 епохи. Алгоритмот ги таргетира твоите слаби области и ја калибрира тежината според твоите резултати.', tips: ['Достапно на плановите Pro и Master', '10 прашања по сесија', 'Алгоритмот ги приоритизира слабите епохи', 'Освои до +150 XP по сесија'], linkLabel: 'Обиди се со Паметниот Квиз' },
  { title: 'Повторувај со Картички', desc: 'Картичките ти овозможуваат да вежбаш клучни термини, датуми и концепти од секоја лекција. Превртувај ги картичките и означи ги како познати или непознати.', tips: ['Картички од сите лекции', 'Одлично за ревизија пред квизови', 'Следи колку знаеш'], linkLabel: 'Отвори Картички' },
  { title: 'Пишувај Лични Белешки', desc: 'Запиши ги своите мисли, согледувања и резимеа додека учиш. Белешките се поврзани со лекции и зачувани локално — секогаш ти се достапни кога ќе се вратиш.', tips: ['Белешките се зачувани по лекции', 'Достапни на страницата Мои Белешки', 'Сите податоци зачувани локално на твојот уред'], linkLabel: 'Отвори Белешки' },
  { title: 'Следи го Напредокот', desc: 'Страницата за Напредок ги прикажува историјата на XP, стапките на завршување по епохи, резултатите од квизови, серијата и достигнувањата. Виж точно каде се наоѓаш.', tips: ['Серијата се ресетира ако пропуштиш ден', 'Достигнувањата се отклучуваат на пресвртни точки', 'Графиконите се ажурираат по секој квиз'], linkLabel: 'Погледни Напредок' },
  { title: 'Есеј Предизвик', desc: 'Провери го своето историско знаење со есеј предизвик. Клио го оценува твојот есеј во реално време со детална анализа на аргументот, доказите, длабочината и квалитетот на пишување.', tips: ['Достапно на плановите Pro и Master', 'Есеите ги оценува Клио — строго но конструктивно', 'Бирај од повеќе историски теми', 'Освои XP пропорционално на твојата оценка (А = максимален XP)'], linkLabel: 'Обиди се со Есеј Предизвик' },
  { title: 'Дебатирај со Филозоф', desc: 'Секои 12 часа се прикажува нов филозоф. Вклучи се во жестока филозофска дебата — тие имаат претходно вчитани аргументи и силно познавање на сопствената филозофија. Натерај ги да се предадат за да освоиш XP.', tips: ['Достапно на Pro Learner и повисоко', 'Нов филозоф на секои 12 часа', 'Освои XP со тоа што ќе го натераш филозофот да се предаде', 'Поголеми филозофи носат повеќе XP', 'Користи претходно вчитани аргументи или пиши свои'], linkLabel: 'Отвори Дебата' },
  { title: 'Видео Предизвик за Преглед', desc: 'Гледај образователно историско видео (≤10 мин), потоа напиши ја твојата анализа со идентификување на главниот мотив или аргумент. Клио го оценува твојот преглед реченица по реченица со живи 3D анимации.', tips: ['Ексклузивно за планот Master Student', 'Ново видео се отклучува на секои 12 часа', 'Освои специјален Видео XP — одделно од обичниот XP', 'Видео XP го напредува твојот Историски Шаховски Ранг', 'Шаховскиот Ранг дава предност 2× на Листата'], linkLabel: 'Отвори Видео Преглед' },
  { title: 'Карта на Историски Територии', desc: 'Истражувај реални географски територии за повеќе од 40 историски периоди на жива карта — од миграциите надвор од Африка до Студената војна, сега вклучувајќи ги Олмеките, Кмерската империја, Сонгај и полинезиските морепловци. Секоја територија носи истражени граници, престолнини, битки и трговски патишта. Префрлај се меѓу режим Истражување (слоеви, анотирани маркери), режим Приказна (анимирана тура) и режим Квиз со целосни објаснувања.', tips: ['Потребен план Pro Learner или Master Student', 'Префрлај се меѓу режимите: Истражување, Приказна и Квиз', 'Секоја територија има реална геометрија: граници, престолнини, битки, патишта', 'XP од квизот е ограничен на 500 по сесија за правичност'], linkLabel: 'Отвори Карта на Територии' },
  { title: 'Кризна соба „Хронос“', desc: 'Влези во вистинска историска пресвртница како лидерот што ја доживеал. Моторот „Хронос“ — ИИ водител на играта — ја раскажува кризата, нуди три вистински различни стратегии секој потег (или прифаќа кој било твој план) и ја оценува секоја одлука во реално време според реалните историски ограничувања. По шест потези го добиваш Вердиктот: твојата контрафактуална временска линија споредена со вистинската историја, финален резултат од 100 и лекцијата што ја учи епизодата.', tips: ['Девет сценарија — од Саламина (480 п.н.е.) и Рубикон до Хатин (1187), Константинопол (1453), Армадата (1588), Јулската криза (1914) и Кубанската ракетна криза (1962)', 'Секоја одлука се оценува во живо: стабилност, легитимност и наследство од 10', 'Напиши кој било слободен план — моторот сериозно ќе ги одигра последиците', 'Симулациите траат точно шест потези и завршуваат со целосен историски вердикт', 'Ексклузивно за планот Master Student'], linkLabel: 'Влези во Кризната соба' },
  { title: 'Следи го твојот План за учење', desc: 'Планот за учење ја чита твојата совладаност на секоја епоха — покриеност со лекции, резултати од квизови, адаптивна точност — и составува недела на учење насочена кон твојата најслаба област. Чекорите водат до вистински лекции и сами се одбележуваат додека учиш.', tips: ['Достапно на Pro Student и повисоко', 'Состави нова недела кога сакаш', 'Тренерските белешки „Засили со Клио" се ексклузивни за Master Student', 'Чекорите се комплетираат автоматски додека учиш'], linkLabel: 'Отвори План за учење' },
  { title: 'Создавај комплети во ВИ Студиото', desc: 'Залепи кој било историски текст — поглавје од учебник, статија, свои белешки — и студиото го претвора во валидиран комплет за учење: резиме, клучни факти, картички и прашања за квиз. Избери што да задржиш, зачувај го комплетот и вежбај засекогаш.', tips: ['Достапно на Pro Student и повисоко', 'Секое прашање механички се проверува пред да го видиш', 'Вежбањето носи XP при резултат од 60%+', 'Твојата библиотека собира до 30 комплети'], linkLabel: 'Отвори ВИ Студио'},
  { title: 'Владеј во Chronos Imperium', desc: 'Големата кампања: владеј со историско царство епоха по епоха. Две третини од секоја победа се интелект — дилеми од вистинската историја, политички одлуки што Клио ги испитува и проверки на знаење што ја одлучуваат твојата судбина — а една третина е играта на војски, провинции и битки на стратешката карта.', tips: ['Ексклузивно за планот Master Student', 'Секоја одлука се оценува според вистинско историско расудување', 'Клио го оценува секој потег и ги раскажува последиците', 'Битките се решаваат во анимиран театар на картата'], linkLabel: 'Влези во Chronos Imperium' },
  { title: 'Учи со Пријатели', desc: 'Додај пријатели по корисничко име, разменувај пораки и предизвикај ги на Историски дуел 1 на 1 — битка на историско знаење каде победува поостриот ум. Ривалството е техника за учење.', tips: ['Додај пријатели по точно корисничко име', 'Вградени приватни пораки', 'Историски 1 на 1: дуели на знаење со XP на коцка'], linkLabel: 'Отвори Пријатели' },
  { title: 'Искачи се на Ранг-листата', desc: 'Секој XP поен се брои за твојата позиција. Ранг-листата ги рангира сите ученици глобално; Шаховскиот ранг од Видео прегледот го множи твоето искачување. Види каде си — па учи за да се искачиш повисоко.', tips: ['Рангирање по вкупен XP', 'Шаховскиот ранг (Видео преглед) дава 2× предност', 'Се ажурира во живо додека учиш'], linkLabel: 'Види Ранг-листа' },
];

const FAQ_EN: FaqItem[] = [
  { q: 'Is my data saved?', a: 'All progress, notes, and settings are saved locally in your browser. Clearing browser data will reset everything.' },
  { q: 'Can I use Historify on mobile?', a: 'Yes — the app is fully responsive. Use the hamburger menu in the top-left to open the sidebar on mobile.' },
  { q: 'How do I upgrade my plan?', a: 'Go to the Pricing page or click "Upgrade Plan" in the sidebar. Changes apply instantly.' },
  { q: 'What happens to my progress if I upgrade?', a: 'All XP, quiz scores, notes, and streaks carry over seamlessly when you upgrade.' },
  { q: 'How does the Smart Quiz algorithm work?', a: 'It assigns higher weight to eras where your quiz score is low or where you have never attempted a quiz. Difficulty calibrates based on your average score across all quizzes.' },
  { q: 'Why is the next lesson locked?', a: 'Lessons open strictly in order on every plan. A lesson unseals when the one before it is completed, its written analysis is passed with grade B or better, and the 30-minute reflection cooldown has run out.' },
  { q: "What is Clio's analysis gate?", a: 'After you complete a lesson, Clio asks for a 150–300-word written analysis of it. She grades it strictly on understanding, analysis, specificity, and clarity — grade B (80%) or better opens the next lesson and earns bonus XP.' },
];

const FAQ_ES: FaqItem[] = [
  { q: '¿Están guardados mis datos?', a: 'Todo el progreso, notas y configuraciones se guardan localmente en tu navegador. Borrar los datos del navegador reiniciará todo.' },
  { q: '¿Puedo usar Historify en móvil?', a: 'Sí — la app es completamente responsiva. Usa el menú hamburguesa en la esquina superior izquierda para abrir la barra lateral en móvil.' },
  { q: '¿Cómo actualizo mi plan?', a: 'Ve a la página de Precios o haz clic en "Actualizar Plan" en la barra lateral. Los cambios se aplican al instante.' },
  { q: '¿Qué pasa con mi progreso si actualizo?', a: 'Todo el XP, puntuaciones de quiz, notas y rachas se mantienen al actualizar.' },
  { q: '¿Cómo funciona el algoritmo del Quiz Inteligente?', a: 'Asigna mayor peso a las eras donde tu puntuación es baja o donde nunca has intentado un quiz. La dificultad se calibra basándose en tu puntuación media en todos los quizzes.' },
  { q: '¿Por qué está bloqueada la siguiente lección?', a: 'Las lecciones se abren estrictamente en orden en todos los planes. Una lección se desbloquea cuando la anterior está completada, su análisis escrito está aprobado con nota B o mejor, y la pausa de reflexión de 30 minutos ha terminado.' },
  { q: '¿Qué es el análisis de Clío?', a: 'Al completar una lección, Clío te pide un análisis escrito de 150–300 palabras. Lo califica estrictamente según comprensión, análisis, especificidad y claridad — nota B (80%) o mejor abre la siguiente lección y da XP extra.' },
];

const FAQ_RU: FaqItem[] = [
  { q: 'Сохраняются ли мои данные?', a: 'Весь прогресс, заметки и настройки сохраняются локально в браузере. Очистка данных браузера сбросит всё.' },
  { q: 'Можно ли использовать Historify на мобильном?', a: 'Да — приложение полностью адаптивно. Используйте кнопку меню в верхнем левом углу, чтобы открыть боковую панель на мобильном устройстве.' },
  { q: 'Как обновить план?', a: 'Перейдите на страницу Тарифов или нажмите «Обновить план» в боковой панели. Изменения применяются мгновенно.' },
  { q: 'Что происходит с прогрессом при обновлении плана?', a: 'Весь XP, результаты викторин, заметки и серии сохраняются при обновлении.' },
  { q: 'Как работает алгоритм Умной Викторины?', a: 'Он присваивает больший вес эпохам, где ваш результат низкий или где вы никогда не проходили викторину. Сложность регулируется на основе вашего среднего результата по всем викторинам.' },
  { q: 'Почему следующий урок заблокирован?', a: 'Уроки открываются строго по порядку на любом плане. Урок открывается, когда предыдущий завершён, его письменный анализ сдан с оценкой B или выше, и 30-минутная пауза на осмысление истекла.' },
  { q: 'Что такое анализ Клио?', a: 'После завершения урока Клио просит письменный анализ на 150–300 слов. Она строго оценивает понимание, анализ, конкретику и ясность — оценка B (80%) или выше открывает следующий урок и даёт бонусный XP.' },
];

const FAQ_MK: FaqItem[] = [
  { q: 'Дали моите податоци се зачувани?', a: 'Целиот напредок, белешки и поставки се зачувани локално во твојот пребарувач. Бришењето на податоците ќе го ресетира сè.' },
  { q: 'Дали можам да го користам Historify на мобилен?', a: 'Да — апликацијата е целосно одговарачка. Користи го мени копчето во горниот лев агол за да ја отвориш страничната лента на мобилен.' },
  { q: 'Како да го надградам мојот план?', a: 'Оди на страницата за Цени или кликни на „Надгради го Планот" во страничната лента. Промените се применуваат веднаш.' },
  { q: 'Што се случува со мојот напредок ако надградам?', a: 'Целиот XP, резултати од квизови, белешки и серии се пренесуваат беспрекорно при надградување.' },
  { q: 'Како функционира алгоритмот на Паметниот Квиз?', a: 'Тој доделува поголема тежина на епохите каде твојот резултат е низок или каде никогаш не си пробувал квиз. Тежината се калибрира врз основа на твојот просечен резултат од сите квизови.' },
  { q: 'Зошто е заклучена следната лекција?', a: 'Лекциите се отвораат строго по ред на секој план. Лекцијата се отклучува кога претходната е завршена, нејзината писмена анализа е положена со оценка B или подобра, и 30-минутната пауза за размислување е истечена.' },
  { q: 'Што е анализата на Клио?', a: 'Откако ќе завршиш лекција, Клио бара писмена анализа од 150–300 збора. Таа строго оценува разбирање, анализа, конкретност и јасност — оценка B (80%) или подобра ја отвора следната лекција и носи бонус XP.' },
];

export function getTranslatedGuideContent(language: Language) {
  // de/fr serve the English guide until their translations land (same fallback contract as the content layer).
  const stepsMap: Record<Language, StepContent[]> = { en: STEPS_EN, es: STEPS_ES, ru: STEPS_RU, mk: STEPS_MK, de: STEPS_EN, fr: STEPS_EN };
  const faqMap: Record<Language, FaqItem[]> = { en: FAQ_EN, es: FAQ_ES, ru: FAQ_RU, mk: FAQ_MK, de: FAQ_EN, fr: FAQ_EN };
  const stepsContent = stepsMap[language] ?? STEPS_EN;
  const faqContent = faqMap[language] ?? FAQ_EN;
  return {
    steps: STEP_META.map((meta, i) => ({ ...meta, ...stepsContent[i] })),
    faq: faqContent,
  };
}
