// ─── The Byzantine World: era + lesson meta translations (es/ru/mk/de/fr) ────
// Era metadata and per-lesson meta (title, subtitle, keyFacts, sectionHeadings)
// for the sixth era. Merged into ERA_TRANS / LESSON_TRANS by
// contentTranslations.ts; section BODIES fall back to English until the
// byzantineBodies file lands (same rollout order used for the Prehistoric era).
import type { Language } from './translations';

type ContentLang = Exclude<Language, 'en'>;
interface EraContent { name: string; shortName: string; dateRange: string; description: string; }
interface LessonContent { title: string; subtitle: string; keyFacts: string[]; sectionHeadings: string[]; }

export const BYZANTINE_ERA_TRANS: Partial<Record<ContentLang, EraContent>> = {
  es: { name: 'El Mundo Bizantino', shortName: 'Bizancio', dateRange: '330 – 1453 d.C.', description: 'El imperio romano de Oriente que duró mil años. De la Nueva Roma de Constantino a la caída de Constantinopla: las leyes de Justiniano, Santa Sofía, el fuego griego, el alfabeto de Cirilo y Metodio, y el auge del cristianismo ortodoxo que moldeó media Europa.' },
  ru: { name: 'Византийский мир', shortName: 'Византия', dateRange: '330 – 1453 гг.', description: 'Тысячелетняя Римская империя Востока. От Нового Рима Константина до падения Константинополя: законы Юстиниана, Святая София, греческий огонь, азбука Кирилла и Мефодия и подъём православия, сформировавшего пол-Европы.' },
  mk: { name: 'Византискиот Свет', shortName: 'Византија', dateRange: '330 – 1453 н.е.', description: 'Илјадагодишната Римска империја на Истокот. Од Новиот Рим на Константин до падот на Константинопол: законите на Јустинијан, Света Софија, грчкиот оган, азбуката на Кирил и Методиј и подемот на православното христијанство што обликуваше половина Европа.' },
  de: { name: 'Die byzantinische Welt', shortName: 'Byzanz', dateRange: '330 – 1453 n. Chr.', description: 'Das tausendjährige Römische Reich des Ostens. Von Konstantins Neuem Rom bis zum Fall Konstantinopels: Justinians Gesetze, die Hagia Sophia, das griechische Feuer, das Alphabet von Kyrill und Method und der Aufstieg des orthodoxen Christentums, das halb Europa prägte.' },
  fr: { name: 'Le monde byzantin', shortName: 'Byzance', dateRange: '330 – 1453 apr. J.-C.', description: "L'Empire romain d'Orient qui dura mille ans. De la Nouvelle Rome de Constantin à la chute de Constantinople : les lois de Justinien, Sainte-Sophie, le feu grégeois, l'alphabet de Cyrille et Méthode, et l'essor du christianisme orthodoxe qui façonna la moitié de l'Europe." },
};

export const BYZANTINE_LESSON_TRANS: Record<string, Partial<Record<ContentLang, LessonContent>>> = {
  'byzantine-01': {
    es: { title: 'La Nueva Roma: la fundación de Constantinopla', subtitle: 'Constantino y la ciudad deseada por el mundo', keyFacts: ['Constantino dedicó Constantinopla como su nueva capital el 11 de mayo de 330', 'La ciudad dominaba el Bósforo, el comercio entre Europa y Asia', 'Constantino fue el primer emperador romano en convertirse al cristianismo', 'El Imperio romano de Oriente sobreviviría al de Occidente casi 1.000 años'], sectionHeadings: ['Un imperio elige un nuevo corazón', 'El primer emperador cristiano', 'La reina de las ciudades', 'La Roma que no cayó'] },
    ru: { title: 'Новый Рим: основание Константинополя', subtitle: 'Константин и город желаний мира', keyFacts: ['Константин освятил Константинополь как новую столицу 11 мая 330 года', 'Город стоял на Босфоре, управляя торговлей между Европой и Азией', 'Константин — первый римский император, принявший христианство', 'Восточная Римская империя переживёт Западную почти на 1000 лет'], sectionHeadings: ['Империя выбирает новое сердце', 'Первый христианский император', 'Царица городов', 'Рим, который не пал'] },
    mk: { title: 'Новиот Рим: основањето на Константинопол', subtitle: 'Константин и градот на светската желба', keyFacts: ['Константин го посвети Константинопол како нова престолнина на 11 мај 330', 'Градот стоеше на Босфорот, владеејќи со трговијата меѓу Европа и Азија', 'Константин беше првиот римски император што прими христијанство', 'Источното Римско Царство ќе го надживее Западното речиси 1.000 години'], sectionHeadings: ['Империја избира ново срце', 'Првиот христијански император', 'Кралицата на градовите', 'Римот што не падна'] },
    de: { title: 'Das Neue Rom: die Gründung Konstantinopels', subtitle: 'Konstantin und die Stadt der Sehnsucht der Welt', keyFacts: ['Konstantin weihte Konstantinopel am 11. Mai 330 als neue Hauptstadt', 'Die Stadt lag am Bosporus und beherrschte den Handel zwischen Europa und Asien', 'Konstantin war der erste römische Kaiser, der zum Christentum übertrat', 'Das Oströmische Reich überlebte das Westreich um fast 1.000 Jahre'], sectionHeadings: ['Ein Reich wählt ein neues Herz', 'Der erste christliche Kaiser', 'Die Königin der Städte', 'Das Rom, das nicht fiel'] },
    fr: { title: 'La Nouvelle Rome : la fondation de Constantinople', subtitle: 'Constantin et la ville que le monde désirait', keyFacts: ['Constantin dédia Constantinople comme nouvelle capitale le 11 mai 330', 'La ville dominait le Bosphore et le commerce entre Europe et Asie', 'Constantin fut le premier empereur romain à se convertir au christianisme', "L'Empire romain d'Orient survécut à l'Occident près de 1 000 ans"], sectionHeadings: ['Un empire choisit un nouveau cœur', 'Le premier empereur chrétien', 'La reine des villes', 'La Rome qui ne tomba pas'] },
  },
  'byzantine-02': {
    es: { title: 'Justiniano y Teodora', subtitle: 'Leyes, revueltas y Santa Sofía', keyFacts: ['Justiniano I reinó 527–565, con la emperatriz Teodora como socia en el poder', 'El Corpus Juris Civilis codificó el derecho romano y fundamenta el derecho europeo actual', 'Los disturbios de Niká de 532 casi derriban el trono hasta que Teodora se negó a huir', 'Santa Sofía, terminada en 537, fue la iglesia más grande del mundo durante 900 años'], sectionHeadings: ['El emperador que nunca dormía', 'Los disturbios de Niká: «la púrpura es un buen sudario»', 'Una cúpula colgada del cielo', 'La ley que gobierna el mundo'] },
    ru: { title: 'Юстиниан и Феодора', subtitle: 'Законы, бунты и Святая София', keyFacts: ['Юстиниан I правил в 527–565 годах, императрица Феодора была его соправительницей', 'Corpus Juris Civilis кодифицировал римское право — основу европейского права', 'Восстание «Ника» 532 года едва не свергло трон, пока Феодора не отказалась бежать', 'Святая София (537) 900 лет оставалась крупнейшим храмом мира'], sectionHeadings: ['Император, который никогда не спал', 'Восстание «Ника»: «пурпур — прекрасный саван»', 'Купол, подвешенный к небу', 'Закон, правящий миром'] },
    mk: { title: 'Јустинијан и Теодора', subtitle: 'Закони, бунтови и Света Софија', keyFacts: ['Јустинијан I владееше 527–565, со царицата Теодора како партнер во власта', 'Corpus Juris Civilis го кодификуваше римското право — темел на европското право денес', 'Бунтот Ника во 532 за малку ќе го собореше тронот, додека Теодора не одби да избега', 'Света Софија, завршена во 537, беше најголемата црква во светот 900 години'], sectionHeadings: ['Императорот што никогаш не спиеше', 'Бунтот Ника: „пурпурот е убав покров“', 'Купола обесена од небото', 'Законот што владее со светот'] },
    de: { title: 'Justinian und Theodora', subtitle: 'Gesetze, Aufstände und die Hagia Sophia', keyFacts: ['Justinian I. regierte 527–565, mit Kaiserin Theodora als Partnerin an der Macht', 'Das Corpus Juris Civilis kodifizierte das römische Recht — Grundlage des heutigen Europarechts', 'Der Nika-Aufstand von 532 hätte den Thron fast gestürzt, bis Theodora die Flucht verweigerte', 'Die Hagia Sophia (537) war 900 Jahre lang die größte Kirche der Welt'], sectionHeadings: ['Der Kaiser, der niemals schlief', 'Der Nika-Aufstand: „Purpur ist ein schönes Leichentuch“', 'Eine vom Himmel hängende Kuppel', 'Das Gesetz, das die Welt regiert'] },
    fr: { title: 'Justinien et Théodora', subtitle: 'Lois, émeutes et Sainte-Sophie', keyFacts: ['Justinien Ier régna de 527 à 565, avec l’impératrice Théodora comme partenaire du pouvoir', 'Le Corpus Juris Civilis codifia le droit romain, socle du droit européen actuel', 'La sédition Nika de 532 faillit renverser le trône, jusqu’au refus de fuir de Théodora', 'Sainte-Sophie, achevée en 537, resta 900 ans la plus grande église du monde'], sectionHeadings: ['L’empereur qui ne dormait jamais', 'La sédition Nika : « la pourpre est un beau linceul »', 'Une coupole suspendue au ciel', 'La loi qui gouverne le monde'] },
  },
  'byzantine-03': {
    es: { title: 'El imperio asediado', subtitle: 'Persas, árabes y fuego griego', keyFacts: ['Heraclio aplastó a Persia en 628 tras una guerra que agotó a ambos imperios', 'Los ejércitos árabes tomaron Siria, Egipto y el norte de África en pocas décadas', 'El fuego griego — arma incendiaria secreta — salvó Constantinopla en 678 y 718', 'El sistema de themas asentó soldados-campesinos para defender Anatolia'], sectionHeadings: ['La última gran guerra de la Antigüedad', 'La tormenta árabe', 'El arma secreta: el fuego griego', 'Reinventar el imperio: los themas'] },
    ru: { title: 'Империя в осаде', subtitle: 'Персы, арабы и греческий огонь', keyFacts: ['Ираклий сокрушил Персию в 628 году после войны, истощившей обе империи', 'Арабские армии за десятилетия отняли Сирию, Египет и Северную Африку', 'Греческий огонь — секретное зажигательное оружие — спас Константинополь в 678 и 718 годах', 'Система фем расселила воинов-земледельцев для обороны Анатолии'], sectionHeadings: ['Последняя великая война античности', 'Арабская буря', 'Секретное оружие: греческий огонь', 'Переизобретение империи: фемы'] },
    mk: { title: 'Опколената империја', subtitle: 'Персијци, Арапи и грчки оган', keyFacts: ['Ираклиј ја смачка Персија во 628 по војна што ги исцрпи двете империи', 'Арапските војски ги зедоа Сирија, Египет и Северна Африка за неколку децении', 'Грчкиот оган — тајно запаливо оружје — го спаси Константинопол во 678 и 718', 'Системот на теми насели војници-земјоделци за одбрана на Анадолија'], sectionHeadings: ['Последната голема војна на антиката', 'Арапската бура', 'Тајното оружје: грчкиот оган', 'Повторно измислување на империјата: темите'] },
    de: { title: 'Das belagerte Reich', subtitle: 'Perser, Araber und griechisches Feuer', keyFacts: ['Herakleios zerschlug Persien 628 nach einem Krieg, der beide Reiche erschöpfte', 'Arabische Heere nahmen Syrien, Ägypten und Nordafrika binnen Jahrzehnten', 'Das griechische Feuer — eine geheime Brandwaffe — rettete Konstantinopel 678 und 718', 'Das Themenwesen siedelte Wehrbauern zur Verteidigung Anatoliens an'], sectionHeadings: ['Der letzte große Krieg der Antike', 'Der arabische Sturm', 'Die Geheimwaffe: griechisches Feuer', 'Das Reich neu erfinden: die Themen'] },
    fr: { title: "L'empire assiégé", subtitle: 'Perses, Arabes et feu grégeois', keyFacts: ['Héraclius écrasa la Perse en 628 après une guerre qui épuisa les deux empires', "Les armées arabes prirent la Syrie, l'Égypte et l'Afrique du Nord en quelques décennies", 'Le feu grégeois — arme incendiaire secrète — sauva Constantinople en 678 et 718', "Le système des thèmes installa des soldats-paysans pour défendre l'Anatolie"], sectionHeadings: ["La dernière grande guerre de l'Antiquité", 'La tempête arabe', "L'arme secrète : le feu grégeois", "Réinventer l'empire : les thèmes"] },
  },
  'byzantine-04': {
    es: { title: 'La iconoclasia: la guerra por las imágenes sagradas', subtitle: 'Cuando el imperio luchó consigo mismo por el arte y Dios', keyFacts: ['Los iconos — imágenes sagradas de Cristo y los santos — son centrales en el culto ortodoxo', 'En 726 el emperador León III inició una campaña de un siglo contra las imágenes', 'La emperatriz Irene restauró los iconos en el Concilio de Nicea de 787', 'El «Triunfo de la Ortodoxia» de 843 aún se celebra en las iglesias ortodoxas'], sectionHeadings: ['¿Qué es un icono?', 'La destrucción de las imágenes', 'Dos emperatrices terminan la guerra', 'El legado en oro y pintura'] },
    ru: { title: 'Иконоборчество: война за святые образы', subtitle: 'Когда империя воевала сама с собой из-за искусства и Бога', keyFacts: ['Иконы — священные образы Христа и святых — сердце православного богослужения', 'В 726 году император Лев III начал вековую кампанию против образов', 'Императрица Ирина восстановила иконы на Никейском соборе 787 года', '«Торжество Православия» 843 года и ныне празднуется православными церквями'], sectionHeadings: ['Что такое икона?', 'Сокрушение образов', 'Две императрицы завершают войну', 'Наследие в золоте и красках'] },
    mk: { title: 'Иконоборството: војната за светите слики', subtitle: 'Кога империјата војуваше сама со себе за уметноста и Бога', keyFacts: ['Иконите — свети слики на Христос и светителите — се средиште на православното богослужение', 'Во 726 императорот Лав III започна вековна кампања против сликите', 'Царицата Ирина ги врати иконите на Никејскиот собор во 787', '„Триумфот на Православието“ од 843 сè уште се празнува во православните цркви'], sectionHeadings: ['Што е икона?', 'Кршењето на сликите', 'Две царици ја завршуваат војната', 'Наследството во злато и боја'] },
    de: { title: 'Der Ikonoklasmus: der Krieg um die heiligen Bilder', subtitle: 'Als das Reich um Kunst und Gott mit sich selbst rang', keyFacts: ['Ikonen — heilige Bilder Christi und der Heiligen — stehen im Zentrum orthodoxer Frömmigkeit', '726 begann Kaiser Leo III. einen jahrhundertlangen Feldzug gegen die Bilder', 'Kaiserin Irene stellte die Ikonen auf dem Konzil von Nizäa 787 wieder her', 'Der „Triumph der Orthodoxie“ von 843 wird bis heute gefeiert'], sectionHeadings: ['Was ist eine Ikone?', 'Das Zerschlagen der Bilder', 'Zwei Kaiserinnen beenden den Krieg', 'Das Erbe in Gold und Farbe'] },
    fr: { title: "L'iconoclasme : la guerre des images saintes", subtitle: "Quand l'empire se déchira pour l'art et pour Dieu", keyFacts: ['Les icônes — images sacrées du Christ et des saints — sont au cœur du culte orthodoxe', "En 726, l'empereur Léon III lança une campagne d'un siècle contre les images", "L'impératrice Irène restaura les icônes au concile de Nicée de 787", "Le « Triomphe de l'Orthodoxie » de 843 est encore célébré dans les églises orthodoxes"], sectionHeadings: ["Qu'est-ce qu'une icône ?", 'Le brisement des images', 'Deux impératrices terminent la guerre', "L'héritage d'or et de peinture"] },
  },
  'byzantine-05': {
    es: { title: 'Cirilo y Metodio: alfabetos para los eslavos', subtitle: 'De Tesalónica y Ohrid al mundo cirílico', keyFacts: ['Los hermanos Cirilo y Metodio de Tesalónica crearon el primer alfabeto eslavo en 863', 'Tradujeron la Biblia y la liturgia al antiguo eslavo eclesiástico', 'Sus discípulos, encabezados por Clemente de Ohrid, desarrollaron el alfabeto cirílico', 'La Escuela Literaria de Ohrid hizo de Macedonia una cuna de la alfabetización eslava'], sectionHeadings: ['Una petición desde Moravia', 'La batalla por una lengua', 'Ohrid: la cuna lacustre de las letras eslavas', 'Un alfabeto que moldeó medio continente'] },
    ru: { title: 'Кирилл и Мефодий: азбуки для славян', subtitle: 'Из Фессалоник и Охрида — в кириллический мир', keyFacts: ['Братья Кирилл и Мефодий из Фессалоник создали первую славянскую азбуку в 863 году', 'Они перевели Библию и литургию на старославянский язык', 'Их ученики во главе с Климентом Охридским разработали кириллицу', 'Охридская книжная школа сделала Македонию колыбелью славянской грамотности'], sectionHeadings: ['Просьба из Моравии', 'Битва за язык', 'Охрид: озёрная колыбель славянской письменности', 'Азбука, сформировавшая полконтинента'] },
    mk: { title: 'Кирил и Методиј: азбуки за Словените', subtitle: 'Од Солун и Охрид до кирилскиот свет', keyFacts: ['Браќата Кирил и Методиј од Солун ја создадоа првата словенска азбука во 863', 'Ги преведоа Библијата и литургијата на старословенски јазик', 'Нивните ученици, предводени од Климент Охридски, ја развија кирилицата', 'Охридската книжевна школа ја направи Македонија лулка на словенската писменост'], sectionHeadings: ['Барање од Моравија', 'Битката за јазикот', 'Охрид: езерската лулка на словенските букви', 'Азбука што обликуваше половина континент'] },
    de: { title: 'Kyrill und Method: Alphabete für die Slawen', subtitle: 'Von Thessalonike und Ohrid in die kyrillische Welt', keyFacts: ['Die Brüder Kyrill und Method aus Thessalonike schufen 863 das erste slawische Alphabet', 'Sie übersetzten Bibel und Liturgie ins Altkirchenslawische', 'Ihre Schüler um Klemens von Ohrid entwickelten das kyrillische Alphabet', 'Die Literarische Schule von Ohrid machte Makedonien zur Wiege slawischer Schriftkultur'], sectionHeadings: ['Eine Bitte aus Mähren', 'Der Kampf um eine Sprache', 'Ohrid: die Wiege der slawischen Buchstaben am See', 'Ein Alphabet, das einen halben Kontinent prägte'] },
    fr: { title: 'Cyrille et Méthode : des alphabets pour les Slaves', subtitle: 'De Thessalonique et Ohrid au monde cyrillique', keyFacts: ['Les frères Cyrille et Méthode de Thessalonique créèrent le premier alphabet slave en 863', 'Ils traduisirent la Bible et la liturgie en vieux-slave', "Leurs disciples, menés par Clément d'Ohrid, développèrent l'alphabet cyrillique", "L'École littéraire d'Ohrid fit de la Macédoine un berceau de l'alphabétisation slave"], sectionHeadings: ['Une requête venue de Moravie', 'La bataille pour une langue', 'Ohrid : le berceau lacustre des lettres slaves', 'Un alphabet qui façonna un demi-continent'] },
  },
  'byzantine-06': {
    es: { title: 'El Gran Cisma de 1054', subtitle: 'Cómo el cristianismo se dividió en Oriente ortodoxo y Occidente católico', keyFacts: ['En 1054 los legados papales y el patriarca de Constantinopla se excomulgaron mutuamente', 'Las disputas giraban en torno a la autoridad papal y la cláusula filioque del Credo', 'El cisma dividió el cristianismo en Occidente católico y Oriente ortodoxo', 'Las excomuniones de 1054 solo se levantaron en 1965'], sectionHeadings: ['Dos mundos cristianos se distancian', 'El verano fatal de 1054', 'Qué hace ortodoxa a la Ortodoxia', 'Consecuencias que sobrevivieron a los imperios'] },
    ru: { title: 'Великая схизма 1054 года', subtitle: 'Как христианство раскололось на православный Восток и католический Запад', keyFacts: ['В 1054 году папские легаты и патриарх Константинопольский предали друг друга анафеме', 'Споры шли о папской власти и вставке филиокве в Символ веры', 'Раскол разделил христианство на католический Запад и православный Восток', 'Анафемы 1054 года были сняты лишь в 1965 году'], sectionHeadings: ['Два христианских мира расходятся', 'Роковое лето 1054 года', 'Что делает Православие православным', 'Последствия, пережившие империи'] },
    mk: { title: 'Големата шизма од 1054', subtitle: 'Како христијанството се раздели на православен Исток и католички Запад', keyFacts: ['Во 1054 папските легати и патријархот на Константинопол меѓусебно се исклучија од црквата', 'Споровите се вртеа околу папската власт и клаузулата филиокве во Символот на верата', 'Шизмата го подели христијанството на католички Запад и православен Исток', 'Исклучувањата од 1054 беа укинати дури во 1965'], sectionHeadings: ['Два христијански света се оддалечуваат', 'Фаталното лето 1054', 'Што ја прави Православието православно', 'Последици што ги надживеаја империите'] },
    de: { title: 'Das Große Schisma von 1054', subtitle: 'Wie sich das Christentum in orthodoxen Osten und katholischen Westen spaltete', keyFacts: ['1054 exkommunizierten sich päpstliche Legaten und der Patriarch von Konstantinopel gegenseitig', 'Die Streitpunkte: päpstliche Autorität und die Filioque-Klausel im Credo', 'Das Schisma teilte die Christenheit in katholischen Westen und orthodoxen Osten', 'Die Exkommunikationen von 1054 wurden erst 1965 aufgehoben'], sectionHeadings: ['Zwei christliche Welten entfremden sich', 'Der verhängnisvolle Sommer 1054', 'Was die Orthodoxie orthodox macht', 'Folgen, die Reiche überdauerten'] },
    fr: { title: 'Le Grand Schisme de 1054', subtitle: "Comment le christianisme se scinda entre Orient orthodoxe et Occident catholique", keyFacts: ['En 1054, les légats du pape et le patriarche de Constantinople s’excommunièrent mutuellement', "Les disputes portaient sur l'autorité papale et la clause du filioque dans le Credo", 'Le schisme divisa la chrétienté en Occident catholique et Orient orthodoxe', 'Les excommunications de 1054 ne furent levées qu’en 1965'], sectionHeadings: ['Deux mondes chrétiens s’éloignent', "L'été fatal de 1054", "Ce qui rend l'Orthodoxie orthodoxe", 'Des conséquences qui survécurent aux empires'] },
  },
  'byzantine-07': {
    es: { title: 'Edad de oro y traición', subtitle: 'De Basilio II al saqueo de 1204', keyFacts: ['Bajo la dinastía macedonia (867–1056) Bizancio alcanzó su cima medieval', 'En 988 el príncipe Vladimir de Kiev convirtió a la Rus al cristianismo ortodoxo', 'La derrota de Manzikert en 1071 abrió Anatolia a los turcos selyúcidas', 'En 1204 la Cuarta Cruzada saqueó Constantinopla — cristianos destruyendo la mayor ciudad cristiana'], sectionHeadings: ['La edad de oro macedonia', 'El bautismo de la Rus', 'Manzikert: la herida que no sanó', '1204: la cruzada que devoró a su anfitrión'] },
    ru: { title: 'Золотой век и предательство', subtitle: 'От Василия II до разграбления 1204 года', keyFacts: ['При Македонской династии (867–1056) Византия достигла средневековой вершины', 'В 988 году князь Владимир Киевский обратил Русь в православие', 'Поражение при Манцикерте в 1071 году открыло Анатолию туркам-сельджукам', 'В 1204 году Четвёртый крестовый поход разграбил Константинополь'], sectionHeadings: ['Македонский золотой век', 'Крещение Руси', 'Манцикерт: незаживающая рана', '1204: крестовый поход, пожравший хозяина'] },
    mk: { title: 'Златно доба и предавство', subtitle: 'Од Василиј II до грабежот во 1204', keyFacts: ['Под Македонската династија (867–1056) Византија го достигна средновековниот врв', 'Во 988 кнезот Владимир од Киев ги преобрати Русите во православие', 'Поразот кај Манцикерт во 1071 ја отвори Анадолија за Турците Селџуци', 'Во 1204 Четвртата крстоносна војна го ограби Константинопол'], sectionHeadings: ['Македонското златно доба', 'Покрстувањето на Русите', 'Манцикерт: раната што не зарасна', '1204: крстоносната војна што го проголта домаќинот'] },
    de: { title: 'Goldenes Zeitalter und Verrat', subtitle: 'Von Basileios II. bis zur Plünderung von 1204', keyFacts: ['Unter der makedonischen Dynastie (867–1056) erreichte Byzanz seinen mittelalterlichen Gipfel', '988 bekehrte Fürst Wladimir von Kiew die Rus zum orthodoxen Christentum', 'Die Niederlage von Manzikert 1071 öffnete Anatolien den Seldschuken', '1204 plünderte der Vierte Kreuzzug Konstantinopel — Christen zerstörten die größte christliche Stadt'], sectionHeadings: ['Das makedonische goldene Zeitalter', 'Die Taufe der Rus', 'Manzikert: die Wunde, die nicht heilte', '1204: der Kreuzzug, der seinen Gastgeber verschlang'] },
    fr: { title: "Âge d'or et trahison", subtitle: 'De Basile II au sac de 1204', keyFacts: ["Sous la dynastie macédonienne (867–1056), Byzance atteignit son apogée médiéval", 'En 988, le prince Vladimir de Kiev convertit la Rus’ au christianisme orthodoxe', 'La défaite de Manzikert en 1071 ouvrit l’Anatolie aux Turcs seldjoukides', 'En 1204, la quatrième croisade mit à sac Constantinople — des chrétiens détruisant la plus grande ville chrétienne'], sectionHeadings: ["L'âge d'or macédonien", 'Le baptême de la Rus’', 'Manzikert : la plaie qui ne guérit pas', '1204 : la croisade qui dévora son hôte'] },
  },
  'byzantine-08': {
    es: { title: 'El Monte Athos y el alma ortodoxa', subtitle: 'Monjes, místicos y el arte del cielo', keyFacts: ['El Monte Athos, la «Montaña Sagrada», es una república monástica desde hace más de 1.000 años', 'La Gran Laura, su primer gran monasterio, fue fundada por San Atanasio en 963', 'El hesicasmo — la oración de la quietud interior — definió la espiritualidad bizantina tardía', 'El arte sacro bizantino alcanzó su última floración incluso mientras el imperio declinaba'], sectionHeadings: ['La Montaña Sagrada', 'Una vida fuera del tiempo', 'El hesicasmo: la luz interior', 'El arte de morir espléndidamente'] },
    ru: { title: 'Афон и православная душа', subtitle: 'Монахи, мистики и искусство неба', keyFacts: ['Гора Афон — «Святая Гора» — уже более 1000 лет монашеская республика', 'Великую Лавру, её первый большой монастырь, основал святой Афанасий в 963 году', 'Исихазм — молитва внутреннего безмолвия — определил позднюю византийскую духовность', 'Византийское сакральное искусство пережило последний расцвет даже при упадке империи'], sectionHeadings: ['Святая Гора', 'Жизнь вне времени', 'Исихазм: свет внутри', 'Искусство умирать великолепно'] },
    mk: { title: 'Света Гора и православната душа', subtitle: 'Монаси, мистици и уметноста на небото', keyFacts: ['Света Гора Атос е монашка република веќе повеќе од 1.000 години', 'Големата Лавра, нејзиниот прв голем манастир, ја основа Свети Атанасиј во 963', 'Исихазмот — молитвата на внатрешната тишина — ја дефинираше доцната византиска духовност', 'Византиската света уметност го достигна последниот процут дури и додека империјата опаѓаше'], sectionHeadings: ['Светата Гора', 'Живот надвор од времето', 'Исихазмот: светлината внатре', 'Уметноста на величествено умирање'] },
    de: { title: 'Der Berg Athos und die orthodoxe Seele', subtitle: 'Mönche, Mystiker und die Kunst des Himmels', keyFacts: ['Der Berg Athos, der „Heilige Berg“, ist seit über 1.000 Jahren eine Mönchsrepublik', 'Die Große Lavra, sein erstes großes Kloster, gründete der hl. Athanasios 963', 'Der Hesychasmus — das Gebet der inneren Stille — prägte die spätbyzantinische Spiritualität', 'Die byzantinische sakrale Kunst erlebte ihre letzte Blüte noch im Niedergang des Reiches'], sectionHeadings: ['Der Heilige Berg', 'Ein Leben außerhalb der Zeit', 'Hesychasmus: das Licht im Innern', 'Die Kunst, prachtvoll zu sterben'] },
    fr: { title: "Le mont Athos et l'âme orthodoxe", subtitle: "Moines, mystiques et l'art du ciel", keyFacts: ['Le mont Athos, la « Sainte Montagne », est une république monastique depuis plus de 1 000 ans', 'La Grande Laure, son premier grand monastère, fut fondée par saint Athanase en 963', "L'hésychasme — la prière du silence intérieur — définit la spiritualité byzantine tardive", "L'art sacré byzantin connut sa dernière floraison alors même que l'empire déclinait"], sectionHeadings: ['La Sainte Montagne', 'Une vie hors du temps', "L'hésychasme : la lumière intérieure", "L'art de mourir avec splendeur"] },
  },
  'byzantine-09': {
    es: { title: '1453: la caída de Constantinopla', subtitle: 'El fin de un imperio milenario — y su larga vida póstuma', keyFacts: ['El sultán Mehmed II sitió Constantinopla con quizá 80.000 hombres en abril de 1453', 'Cañones gigantes abrieron brecha en las murallas teodosianas que habían resistido 1.000 años', 'El último emperador, Constantino XI, murió luchando en las murallas el 29 de mayo de 1453', 'Los refugiados y manuscritos bizantinos ayudaron a alimentar el Renacimiento italiano'], sectionHeadings: ['Una ciudad sola', 'Los cañones de Mehmed', 'El veintinueve de mayo', 'La larga vida póstuma de Bizancio'] },
    ru: { title: '1453: падение Константинополя', subtitle: 'Конец тысячелетней империи — и её долгая посмертная жизнь', keyFacts: ['Султан Мехмед II осадил Константинополь в апреле 1453 года с армией, возможно, в 80 000 человек', 'Гигантские пушки пробили Феодосиевы стены, державшиеся 1000 лет', 'Последний император Константин XI погиб в бою на стенах 29 мая 1453 года', 'Византийские беженцы и рукописи питали итальянское Возрождение'], sectionHeadings: ['Город в одиночестве', 'Пушки Мехмеда', 'Двадцать девятое мая', 'Долгая посмертная жизнь Византии'] },
    mk: { title: '1453: падот на Константинопол', subtitle: 'Крајот на илјадагодишната империја — и нејзиниот долг задгробен живот', keyFacts: ['Султанот Мехмед II го опседна Константинопол со можеби 80.000 луѓе во април 1453', 'Џиновски топови ги пробија Теодосиевите ѕидишта што издржаа 1.000 години', 'Последниот император, Константин XI, загина борејќи се на ѕидините на 29 мај 1453', 'Византиските бегалци и ракописи помогнаа да се разгори италијанската ренесанса'], sectionHeadings: ['Град сам', 'Топовите на Мехмед', 'Дваесет и деветти мај', 'Долгиот задгробен живот на Византија'] },
    de: { title: '1453: der Fall Konstantinopels', subtitle: 'Das Ende eines tausendjährigen Reiches — und sein langes Nachleben', keyFacts: ['Sultan Mehmed II. belagerte Konstantinopel im April 1453 mit vielleicht 80.000 Mann', 'Riesige Kanonen durchbrachen die Theodosianischen Mauern, die 1.000 Jahre gehalten hatten', 'Der letzte Kaiser, Konstantin XI., fiel am 29. Mai 1453 kämpfend an den Mauern', 'Byzantinische Flüchtlinge und Handschriften nährten die italienische Renaissance'], sectionHeadings: ['Eine Stadt allein', 'Die Kanonen Mehmeds', 'Der neunundzwanzigste Mai', 'Das lange Nachleben von Byzanz'] },
    fr: { title: '1453 : la chute de Constantinople', subtitle: "La fin d'un empire millénaire — et sa longue survie", keyFacts: ['Le sultan Mehmed II assiégea Constantinople avec peut-être 80 000 hommes en avril 1453', 'Des canons géants percèrent les murailles théodosiennes qui avaient tenu 1 000 ans', 'Le dernier empereur, Constantin XI, mourut en combattant sur les murailles le 29 mai 1453', 'Réfugiés et manuscrits byzantins nourrirent la Renaissance italienne'], sectionHeadings: ['Une ville seule', 'Les canons de Mehmed', 'Le vingt-neuf mai', 'La longue survie de Byzance'] },
  },
};
