import type { Language } from './translations';
import type { Era } from '@/types';

type ContentLang = Exclude<Language, 'en'>;

interface EraContent { name: string; shortName: string; dateRange: string; description: string; }
interface LessonContent { title: string; subtitle: string; keyFacts: string[]; sectionHeadings: string[]; }

const ERA_TRANS: Record<string, Partial<Record<ContentLang, EraContent>>> = {
  ancient: {
    mk: { name: 'Античко Доба', shortName: 'Антика', dateRange: '~3000 п.н.е. – 500 н.е.', description: 'Од првите системи за пишување во Месопотамија до падот на Западната Римска Империја. Истражувај ги цивилизациите кои ги поставиле темелите на човечката култура, право, филозофија и империја.' },
    es: { name: 'Mundo Antiguo', shortName: 'Antiguo', dateRange: '~3000 a.C. – 500 d.C.', description: 'Desde los primeros sistemas de escritura de Mesopotamia hasta la caída del Imperio Romano de Occidente. Explora las civilizaciones que sentaron las bases de la cultura, el derecho, la filosofía y el imperio humano.' },
    ru: { name: 'Древний мир', shortName: 'Древность', dateRange: '~3000 до н.э. – 500 н.э.', description: 'От первых систем письма Месопотамии до падения Западной Римской империи. Исследуйте цивилизации, заложившие основы человеческой культуры, права, философии и государства.' },
  },
  'middle-ages': {
    mk: { name: 'Среден Век', shortName: 'Среден Век', dateRange: '~500 – 1500 н.е.', description: 'Милениум на витези, катедрали, чуми и крстоносни походи. Открај како средновековниот свет ја обликувал модерна Европа, подемот на исламот и зачувувањето на античкото знаење.' },
    es: { name: 'Edad Media', shortName: 'Medieval', dateRange: '~500 – 1500 d.C.', description: 'Un milenio de caballeros, catedrales, pestes y cruzadas. Descubre cómo el mundo medieval moldeó la Europa moderna, el auge del Islam y la preservación del conocimiento antiguo.' },
    ru: { name: 'Средние века', shortName: 'Средневековье', dateRange: '~500 – 1500 н.э.', description: 'Тысячелетие рыцарей, соборов, чумы и крестовых походов. Узнайте, как средневековый мир сформировал современную Европу, подъём ислама и сохранение древних знаний.' },
  },
  'early-modern': {
    mk: { name: 'Рано Модерно Доба', shortName: 'Рано Модерно', dateRange: '~1500 – 1800 н.е.', description: 'Епохата на откривање, научна револуција и политички превирања. Од Колумбо до Американската Револуција — ова доба го преобликуваше светот и нашето разбирање на универзумот.' },
    es: { name: 'Época Moderna Temprana', shortName: 'Mod. Temprana', dateRange: '~1500 – 1800 d.C.', description: 'La era de la exploración, la revolución científica y los trastornos políticos. De Colón a la Revolución Americana, esta era remodeló el mundo y nuestra comprensión del universo.' },
    ru: { name: 'Раннее Новое время', shortName: 'Раннее Новое', dateRange: '~1500 – 1800 н.э.', description: 'Эпоха открытий, научной революции и политических потрясений. От Колумба до Американской революции — это время преобразило мир и наше понимание вселенной.' },
  },
  modern: {
    mk: { name: 'Модерна Ера', shortName: 'Модерна', dateRange: '~1800 – денес', description: 'Индустриска револуција до дигиталното доба. Двете светски војни, деколонизацијата, Студената Војна и глобализацијата го трансформираа секој агол на земјата.' },
    es: { name: 'Era Moderna', shortName: 'Moderna', dateRange: '~1800 – presente', description: 'De la Revolución Industrial a la era digital. Las dos Guerras Mundiales, la descolonización, la Guerra Fría y la globalización transformaron cada rincón del planeta.' },
    ru: { name: 'Новейшее время', shortName: 'Современность', dateRange: '~1800 – наши дни', description: 'От промышленной революции до цифровой эпохи. Две мировые войны, деколонизация, холодная война и глобализация преобразили каждый уголок земли.' },
  },
};

const LESSON_TRANS: Record<string, Partial<Record<ContentLang, LessonContent>>> = {
  'ancient-01': {
    mk: { title: 'Првите Цивилизации', subtitle: 'Месопотамија и Египет', keyFacts: ['Шумерите го измислиле клинестото писмо околу 3100 п.н.е.', 'Египетското Старо Кралство ги изградило пирамидите о. 2686–2181 п.н.е.', 'Хамурабиевиот Законик (о. 1754 п.н.е.) е еден од најстарите правни кодекси', 'И двете цивилизации зависеле од речните системи за земјоделство'], sectionHeadings: ['Колевката на Цивилизацијата', 'Античкиот Египет: Дар на Нил', 'Закони, Трговија и Наследство', 'Религија и Космосот', 'Наука, Математика и Медицина'] },
    es: { title: 'Las Primeras Civilizaciones', subtitle: 'Mesopotamia y Egipto', keyFacts: ['Los sumerios inventaron la escritura cuneiforme hacia el 3100 a.C.', 'El Imperio Antiguo egipcio construyó las pirámides c.2686–2181 a.C.', 'El Código de Hammurabi (c.1754 a.C.) es uno de los primeros códigos legales', 'Ambas civilizaciones dependían de los sistemas fluviales para la agricultura'], sectionHeadings: ['La Cuna de la Civilización', 'El Antiguo Egipto: Don del Nilo', 'Leyes, Comercio y Legado', 'Religión y el Cosmos', 'Ciencia, Matemáticas y Medicina'] },
    ru: { title: 'Первые цивилизации', subtitle: 'Месопотамия и Египет', keyFacts: ['Шумеры изобрели клинопись около 3100 г. до н.э.', 'Египетское Древнее царство построило пирамиды ок. 2686–2181 г. до н.э.', 'Кодекс Хаммурапи (ок. 1754 г. до н.э.) — один из древнейших сводов законов', 'Обе цивилизации зависели от речных систем для земледелия'], sectionHeadings: ['Колыбель цивилизации', 'Древний Египет: Дар Нила', 'Законы, торговля и наследие', 'Религия и космос', 'Наука, математика и медицина'] },
  },
  'ancient-02': {
    mk: { title: 'Класична Грција', subtitle: 'Демократија, Филозофија и Војна', keyFacts: ['Атина ја воспоставила првата демократија во светот околу 508 п.н.е.', 'Персиските Војни (499–449 п.н.е.) ги обединиле грчките градови-држави', 'Сократ, Платон и Аристотел ја поставиле западната филозофија', 'Александар Велики ја ширел грчката култура од Египет до Индија'], sectionHeadings: ['Грчките Градови-Држави', 'Војна и Конфликт', 'Филозофите', 'Уметност, Архитектура и Олимписките Игри', 'Хеленистичкото Доба: Грција оди Глобално'] },
    es: { title: 'La Grecia Clásica', subtitle: 'Democracia, Filosofía y Guerra', keyFacts: ['Atenas estableció la primera democracia del mundo hacia el 508 a.C.', 'Las Guerras Médicas (499–449 a.C.) unieron a las ciudades-estado griegas', 'Sócrates, Platón y Aristóteles fundaron la filosofía occidental', 'Alejandro Magno extendió la cultura griega desde Egipto hasta India'], sectionHeadings: ['Las Ciudades-Estado Griegas', 'Guerra y Conflicto', 'Los Filósofos', 'Arte, Arquitectura y los Juegos Olímpicos', 'La Edad Helenística: Grecia va Global'] },
    ru: { title: 'Классическая Греция', subtitle: 'Демократия, философия и война', keyFacts: ['Афины основали первую в мире демократию около 508 г. до н.э.', 'Греко-персидские войны (499–449 г. до н.э.) объединили греческие полисы', 'Сократ, Платон и Аристотель основали западную философию', 'Александр Великий распространил греческую культуру от Египта до Индии'], sectionHeadings: ['Греческие города-государства', 'Война и конфликт', 'Философы', 'Искусство, архитектура и Олимпийские игры', 'Эллинистическая эпоха: Греция идёт в мир'] },
  },
  'ancient-03': {
    mk: { title: 'Римската Република и Царство', subtitle: 'Од Седум Рида до Светско Владеење', keyFacts: ['Рим бил основан како република околу 509 п.н.е.', 'Јулиј Цезар бил убиен на 15 март 44 п.н.е.', 'На своите врв, Римската Империја зафаќала 5 милиони км²', 'Западната Римска Империја паднала во 476 н.е.'], sectionHeadings: ['Римската Република', 'Освојување и Пунските Војни', 'Царство и Pax Romana', 'Римскиот Инженеринг и Секојдневниот Живот', 'Подемот на Христијанството'] },
    es: { title: 'La República y el Imperio Romano', subtitle: 'De Siete Colinas al Dominio Mundial', keyFacts: ['Roma fue fundada como república hacia el 509 a.C.', 'Julio César fue asesinado el 15 de marzo del 44 a.C.', 'En su apogeo, el Imperio Romano cubría 5 millones de km²', 'El Imperio Romano de Occidente cayó en el 476 d.C.'], sectionHeadings: ['La República Romana', 'Conquista y las Guerras Púnicas', 'Imperio y la Pax Romana', 'Ingeniería Romana y Vida Cotidiana', 'El Surgimiento del Cristianismo'] },
    ru: { title: 'Римская республика и империя', subtitle: 'От Семи холмов к мировому господству', keyFacts: ['Рим основан как республика около 509 г. до н.э.', 'Юлий Цезарь убит 15 марта 44 г. до н.э.', 'На пике Римская империя занимала 5 млн км²', 'Западная Римская империя пала в 476 г. н.э.'], sectionHeadings: ['Римская республика', 'Завоевания и Пунические войны', 'Империя и Pax Romana', 'Римская инженерия и повседневная жизнь', 'Возникновение христианства'] },
  },
  'ancient-04': {
    mk: { title: 'Стариот Исток', subtitle: 'Персија, Индија и Кина', keyFacts: ['Ахеменидската Персиска Империја била најголемата империја на античкиот свет', 'Индискиот цар Ашока ги ширел будистичките вредности низ Азија', 'Династијата Хан ја обединила Кина и го воспоставила испитот за државна служба', 'Патот на Свилата ја поврзувал Кина со Медитеранот до 100 п.н.е.'], sectionHeadings: ['Персиската Империја', 'Индија: Маурјанската Империја и Ашока', 'Кина и Патот на Свилата', 'Ведскиот Период и Хиндуистичката Цивилизација', 'Кинеска Филозофија: Конфучиј, Лаоце и Легализам'] },
    es: { title: 'El Antiguo Oriente', subtitle: 'Persia, India y China', keyFacts: ['El Imperio Persa aqueménida fue el mayor del mundo antiguo', 'El emperador Ashoka de India promovió la ética budista por Asia', 'La dinastía Han unificó China y estableció el examen de servicio civil', 'La Ruta de la Seda conectó China con el Mediterráneo hacia el 100 a.C.'], sectionHeadings: ['El Imperio Persa', 'India: El Imperio Maurya y Ashoka', 'China y la Ruta de la Seda', 'La Era Védica y la Civilización Hindú', 'Filosofía China: Confucio, Laozi y el Legalismo'] },
    ru: { title: 'Древний Восток', subtitle: 'Персия, Индия и Китай', keyFacts: ['Персидская империя Ахеменидов была крупнейшей в древнем мире', 'Индийский царь Ашока распространял буддийские ценности по Азии', 'Династия Хань объединила Китай и ввела экзамен на государственную службу', 'Великий шёлковый путь связал Китай со Средиземноморьем к 100 г. до н.э.'], sectionHeadings: ['Персидская империя', 'Индия: Империя Маурьев и Ашока', 'Китай и Великий шёлковый путь', 'Ведическая эпоха и индуистская цивилизация', 'Китайская философия: Конфуций, Лаоцзы и легизм'] },
  },
  'ancient-05': {
    mk: { title: 'Античкиот Египет: Богови, Фараони и Загробниот Живот', subtitle: 'Смртта, Божественоста и Вечната Моќ', keyFacts: ['Фараоните се сметале за живи богови — инкарнации на Хор', 'Мумификацијата се практикувала повеќе од 2.000 години во Египет', 'Книгата на мртвите ги водела душите низ подземниот свет', 'Големата Пирамида стоела како највисока градба на светот 3.800 години', 'Клеопатра VII бил последниот активен фараон на Античкиот Египет'], sectionHeadings: ['Богот-Крал: Моќта на Фараонот', 'Мумификација и Патувањето кон Загробниот Живот', 'Пирамидите: Инженеринг на Вечноста', 'Египетските Богови и Космичката Драма', 'Новото Кралство и Глобалниот Дострел на Египет'] },
    es: { title: 'Antiguo Egipto: Dioses, Faraones y el Más Allá', subtitle: 'Muerte, Divinidad y Poder Eterno', keyFacts: ['Los faraones eran considerados dioses vivos — encarnaciones de Horus', 'La momificación se practicó durante más de 2.000 años en Egipto', 'El Libro de los Muertos guiaba a las almas por el inframundo', 'La Gran Pirámide fue la estructura más alta del mundo durante 3.800 años', 'Cleopatra VII fue la última faraona activa del Antiguo Egipto'], sectionHeadings: ['El Dios-Rey: Poder del Faraón', 'La Momificación y el Viaje al Más Allá', 'Las Pirámides: Ingeniería de lo Eterno', 'Los Dioses Egipcios y el Drama Cósmico', 'El Imperio Nuevo y el Alcance Global de Egipto'] },
    ru: { title: 'Древний Египет: боги, фараоны и загробная жизнь', subtitle: 'Смерть, Божественность и Вечная Власть', keyFacts: ['Фараоны считались живыми богами — воплощениями Гора', 'Мумификация практиковалась более 2000 лет в Египте', 'Книга мёртвых вела души через загробный мир', 'Великая пирамида оставалась самым высоким сооружением мира 3800 лет', 'Клеопатра VII была последним действующим фараоном Древнего Египта'], sectionHeadings: ['Бог-царь: власть фараона', 'Мумификация и путешествие в загробный мир', 'Пирамиды: инженерия вечности', 'Египетские боги и космическая драма', 'Новое царство и глобальное влияние Египта'] },
  },
  'ancient-06': {
    mk: { title: 'Феничаните: Господари на Морето', subtitle: 'Азбуката, Трговијата и Пурпурната Империја', keyFacts: ['Феничаните го измислиле првиот азбучен систем за пишување околу 1050 п.н.е.', 'Картагина — основана од Тир околу 814 п.н.е. — стана главниот ривал на Рим во Медитеранот', 'Феничанската пурпурна боја (од морскиот полжав мурекс) вредела повеќе од злато по тежина', 'Феничанските морепловци го заобиколиле Африка за Фараонот Нечо II околу 600 п.н.е.', 'Зборот „азбука" потекнува од првите две феничански букви: алеф и бет'], sectionHeadings: ['Пурпурниот Народ од Леванта', 'Подарокот на Азбуката', 'Трговци на Медитеранот', 'Картагина: Ќерката-Град Која Ја Надмина Мајката', 'Наследството на Едeн Морепловачки Народ'] },
    es: { title: 'Los Fenicios: Maestros del Mar', subtitle: 'El Alfabeto, el Comercio y el Imperio Púrpura', keyFacts: ['Los fenicios inventaron el primer sistema de escritura alfabético hacia el 1050 a.C.', 'Cartago — fundada por Tiro hacia el 814 a.C. — se convirtió en el gran rival de Roma', 'El tinte púrpura fenicio (del caracol murex) valía más que el oro por peso', 'Los navegantes fenicios circunnavegaron África para el Faraón Necao II hacia el 600 a.C.', 'La palabra "alfabeto" deriva de las dos primeras letras fenicias: alef y bet'], sectionHeadings: ['Los Pueblos Púrpura del Levante', 'El Don del Alfabeto', 'Mercaderes del Mediterráneo', 'Cartago: La Ciudad Hija que Superó a su Madre', 'El Legado de un Pueblo Navegante'] },
    ru: { title: 'Финикийцы: владыки моря', subtitle: 'Алфавит, торговля и пурпурная империя', keyFacts: ['Финикийцы создали первый алфавит около 1050 г. до н.э.', 'Карфаген — основан Тиром около 814 г. до н.э. — стал главным соперником Рима', 'Финикийский пурпур (из улитки мурекс) стоил дороже золота', 'Финикийские мореплаватели обогнули Африку для фараона Нехо II около 600 г. до н.э.', 'Слово «алфавит» происходит от первых двух финикийских букв: алеф и бет'], sectionHeadings: ['Пурпурный народ Леванта', 'Дар алфавита', 'Торговцы Средиземноморья', 'Карфаген: дочерний город, превзошедший мать', 'Наследие мореплавательского народа'] },
  },
  'medieval-01': {
    mk: { title: 'Падот на Рим и Раниот Среден Век', subtitle: 'Од Царство до Феудална Европа', keyFacts: ['Западната Римска Империја паднала во 476 н.е.', 'Карло Велики бил крунисан за Свет Римски Цар во 800 н.е.', 'Феудализмот го организирал средновековното општество во лордови и кметови', 'Католичката Црква ја зачувала писменоста и знаењето по падот на Рим'], sectionHeadings: ['Падот на Рим', 'Карло Велики и Каролиншката Ренесанса', 'Феудализмот и Средновековното Општество', 'Византиската Империја: Источниот Наследник на Рим', 'Викиншкото Доба и Нордиското Ширење'] },
    es: { title: 'La Caída de Roma y la Alta Edad Media', subtitle: 'Del Imperio a la Europa Feudal', keyFacts: ['El Imperio Romano de Occidente cayó en el 476 d.C.', 'Carlomagno fue coronado Sacro Emperador Romano en el 800 d.C.', 'El feudalismo organizó la sociedad medieval en señores y siervos', 'La Iglesia Católica preservó la alfabetización y el conocimiento tras la caída de Roma'], sectionHeadings: ['El Colapso de Roma', 'Carlomagno y el Renacimiento Carolingio', 'El Feudalismo y la Sociedad Medieval', 'El Imperio Bizantino: El Heredero Oriental de Roma', 'La Era Vikinga y la Expansión Nórdica'] },
    ru: { title: 'Падение Рима и раннее Средневековье', subtitle: 'От империи к феодальной Европе', keyFacts: ['Западная Римская империя пала в 476 г. н.э.', 'Карл Великий был коронован Святым Римским императором в 800 г. н.э.', 'Феодализм организовал средневековое общество на лордов и крепостных', 'Католическая церковь сохранила грамотность после падения Рима'], sectionHeadings: ['Крушение Рима', 'Карл Великий и Каролингский ренессанс', 'Феодализм и средневековое общество', 'Византийская империя: восточный наследник Рима', 'Эпоха викингов и скандинавская экспансия'] },
  },
  'medieval-02': {
    mk: { title: 'Крстоносните Походи и Исламскиот Златен Век', subtitle: 'Вера, Знаење и Конфликт', keyFacts: ['Исламот се ширел од Арабија низ Блискиот Исток и Северна Африка во рок од 100 години по смртта на Мухамед', 'Исламскиот Златен Век (VIII–XIII век) го зачувал и унапредил грчкото знаење', 'Првиот Крстоносен Поход го зазел Ерусалим во 1099 година', 'Крстоносните Походи ги засилиле трговијата и културната размена меѓу Европа и Исток'], sectionHeadings: ['Подемот на Исламот', 'Исламскиот Златен Век', 'Крстоносните Походи', 'Саладин, Витештвото и Подоцнежните Крстоносни Походи', 'Средновековната Трговија и Италијанските Градови-Држави'] },
    es: { title: 'Las Cruzadas y la Edad de Oro Islámica', subtitle: 'Fe, Conocimiento y Conflicto', keyFacts: ['El Islam se extendió desde Arabia por Oriente Medio y el norte de África en 100 años tras la muerte de Mahoma', 'La Edad de Oro Islámica (siglos VIII–XIII) preservó y avanzó la ciencia griega', 'La Primera Cruzada capturó Jerusalén en 1099', 'Las Cruzadas intensificaron el comercio y el intercambio cultural entre Europa y Oriente'], sectionHeadings: ['El Surgimiento del Islam', 'La Edad de Oro Islámica', 'Las Cruzadas', 'Saladino, la Caballería y las Cruzadas Posteriores', 'El Comercio Medieval y las Ciudades-Estado Italianas'] },
    ru: { title: 'Крестовые походы и исламский золотой век', subtitle: 'Вера, знания и конфликт', keyFacts: ['Ислам распространился из Аравии по Ближнему Востоку и Северной Африке за 100 лет после смерти Мухаммада', 'Исламский золотой век (VIII–XIII вв.) сохранил и развил греческую науку', 'Первый крестовый поход взял Иерусалим в 1099 году', 'Крестовые походы усилили торговлю и культурный обмен между Европой и Востоком'], sectionHeadings: ['Возникновение ислама', 'Исламский золотой век', 'Крестовые походы', 'Саладин, рыцарство и поздние крестовые походы', 'Средневековая торговля и итальянские города-государства'] },
  },
  'medieval-03': {
    mk: { title: 'Црната Чума и Доцносредновековната Криза', subtitle: 'Чума, Бунт и Културна Промена', keyFacts: ['Црната Чума убила 30–60% од европското население (1347–1353)', 'Чумата потекнала од Централна Азија и се ширела преку трговски патишта', 'Недостигот на работна сила по чумата ги зајакнал преживеаните селани', 'Кризата го забрзала крајот на феудализмот и подемот на Ренесансата'], sectionHeadings: ['Потекло и Ширење на Чумата', 'Смртта, Хаосот и Отпорноста', 'Општествени и Културни Последици', 'Стогодишната Војна (1337–1453)', 'Семиња на Ренесансата'] },
    es: { title: 'La Peste Negra y la Crisis Bajomedieval', subtitle: 'Peste, Revuelta y Cambio Cultural', keyFacts: ['La Peste Negra mató al 30–60% de la población europea (1347–1353)', 'La plaga se originó en Asia Central y se extendió por las rutas comerciales', 'La escasez de mano de obra tras la peste empoderó a los campesinos supervivientes', 'La crisis aceleró el fin del feudalismo y el auge del Renacimiento'], sectionHeadings: ['Orígenes y Difusión de la Peste', 'Muerte, Caos y Resiliencia', 'Consecuencias Sociales y Culturales', 'La Guerra de los Cien Años (1337–1453)', 'Semillas del Renacimiento'] },
    ru: { title: 'Чёрная смерть и кризис позднего Средневековья', subtitle: 'Чума, восстание и культурные перемены', keyFacts: ['Чёрная смерть убила 30–60% населения Европы (1347–1353)', 'Чума возникла в Центральной Азии и распространялась по торговым путям', 'Нехватка рабочей силы после чумы усилила выживших крестьян', 'Кризис ускорил конец феодализма и подъём Ренессанса'], sectionHeadings: ['Происхождение и распространение чумы', 'Смерть, хаос и стойкость', 'Социальные и культурные последствия', 'Столетняя война (1337–1453)', 'Зёрна Ренессанса'] },
  },
  'medieval-04': {
    mk: { title: 'Средновековна Економија: Еснафи и Подемот на Градовите', subtitle: 'Трговија, Занает и Раѓањето на Буржоазијата', keyFacts: ['Средновековните еснафи го контролирале квалитетот и обуката за занаети', 'Хансеатската Лига поврзувала повеќе од 200 трговски града до XIV век', 'Панаѓурите во Шампањ привлекувале трговци од целата Евроазија', 'Банкарското семејство Медичи ги воспоставило двојното книговодство и меничните пари'], sectionHeadings: ['Возобновувањето на Трговијата', 'Еснафите: Господари на Занаетчиската Економија', 'Хансеатска Лига: Средновековна Глобализација', 'Црната Чума: Катастрофа и Трансформација', 'Банкарство, Кредит и Зората на Капитализмот'] },
    es: { title: 'Economía Medieval: Gremios y el Auge de las Ciudades', subtitle: 'Comercio, Oficio y el Nacimiento de la Burguesía', keyFacts: ['Los gremios medievales controlaban la calidad y formación de los oficios', 'La Liga Hanseática conectó más de 200 ciudades comerciales en el siglo XIV', 'Las ferias de Champaña atraían comerciantes de toda Eurasia', 'La familia Medici pioneros en la contabilidad por partida doble y letras de cambio'], sectionHeadings: ['El Renacimiento del Comercio', 'Los Gremios: Maestros de la Economía Artesanal', 'La Liga Hanseática: Globalización Medieval', 'La Peste Negra: Catástrofe y Transformación', 'Banca, Crédito y los Albores del Capitalismo'] },
    ru: { title: 'Средневековая экономика: цеха и рост городов', subtitle: 'Торговля, ремесло и рождение буржуазии', keyFacts: ['Средневековые цеха контролировали качество и обучение ремёслам', 'Ганзейский союз связал более 200 торговых городов к XIV веку', 'Ярмарки в Шампани привлекали купцов со всей Евразии', 'Медичи ввели двойную бухгалтерию и вексельные операции'], sectionHeadings: ['Возрождение торговли', 'Цеха: мастера ремесленной экономики', 'Ганзейский союз: средневековая глобализация', 'Чёрная смерть: катастрофа и преобразование', 'Банковское дело, кредит и заря капитализма'] },
  },
  'medieval-05': {
    mk: { title: 'Монголската Империја', subtitle: 'Џингис Кан и Монголскиот Мир', keyFacts: ['Џингис Кан ги обединил монголските племиња во 1206 н.е.', 'Монголската Империја станала најголемата копнена империја во историјата', 'Монголскиот Мир ја олеснил трговијата од Кина до Европа', 'Монголите го уништиле Багдад во 1258, завршувајќи го Абасидскиот Калифат', 'Кублај Кан ја основал Династијата Јуан во Кина во 1271'], sectionHeadings: ['Подемот на Џингис Кан', 'Стратегијата на Освојување', 'Империјата на Врвот', 'Монголскиот Мир: Трговија и Културна Размена', 'Наследство: Уништување и Создавање'] },
    es: { title: 'El Imperio Mongol', subtitle: 'Gengis Kan y la Pax Mongólica', keyFacts: ['Gengis Kan unió las tribus mongolas en 1206 d.C.', 'El Imperio Mongol se convirtió en el mayor imperio terrestre contiguo de la historia', 'La Pax Mongólica facilitó el comercio desde China hasta Europa', 'Los mongoles destruyeron Bagdad en 1258, poniendo fin al Califato Abasí', 'Kublai Kan fundó la Dinastía Yuan en China en 1271'], sectionHeadings: ['El Ascenso de Gengis Kan', 'La Estrategia de Conquista', 'El Imperio en su Apogeo', 'La Pax Mongólica: Comercio e Intercambio Cultural', 'Legado: Destrucción y Creación'] },
    ru: { title: 'Монгольская империя', subtitle: 'Чингисхан и монгольский мир', keyFacts: ['Чингисхан объединил монгольские племена в 1206 г. н.э.', 'Монгольская империя стала крупнейшей сухопутной империей в истории', 'Монгольский мир способствовал торговле от Китая до Европы', 'Монголы разрушили Багдад в 1258 году, покончив с Аббасидским халифатом', 'Хубилай-хан основал династию Юань в Китае в 1271 году'], sectionHeadings: ['Возвышение Чингисхана', 'Стратегия завоевания', 'Империя на пике могущества', 'Монгольский мир: торговля и культурный обмен', 'Наследие: разрушение и созидание'] },
  },
  'medieval-06': {
    mk: { title: 'Средновековна Јапонија: Самураји, Шогуни и Бушидо', subtitle: 'Воини, Чест и Патот на Мечот', keyFacts: ['Самурајската класа се појавила во X век како провинциски воини', 'Генпеи Војната (1180–1185) го воспоставила првиот шогунат под Минамото но Јоритомо', 'Зен Будизмот длабоко влијаел на самурајската култура и естетика', 'Монголските инвазии на Јапонија во 1274 и 1281 биле одбиени делумно благодарение на тајфуните наречени „камиказе"', 'Периодот Сенгоку („Војујачки Држави") траел од 1467 до 1615'], sectionHeadings: ['Раѓањето на Самурајот', 'Генпеи Војната и Подемот на Шогунатот', 'Зен Будизмот и Самурајската Естетика', 'Монголските Инвазии и Јапонскиот Идентитет', 'Периодот Сенгоку и Обединувањето'] },
    es: { title: 'Japón Medieval: Samuráis, Shogunes y Bushido', subtitle: 'Guerreros, Honor y el Camino de la Espada', keyFacts: ['La clase samurái surgió en el siglo X como guerreros provinciales', 'La Guerra Genpei (1180–1185) estableció el primer shogunato bajo Minamoto no Yoritomo', 'El budismo zen influyó profundamente en la cultura y estética samurái', 'Las invasiones mongolas de Japón en 1274 y 1281 fueron repelidas parcialmente por tifones llamados "kamikaze"', 'El período Sengoku ("Estados Guerreros") duró de 1467 a 1615'], sectionHeadings: ['El Nacimiento del Samurái', 'La Guerra Genpei y el Surgimiento del Shogunato', 'El Budismo Zen y la Estética Samurái', 'Las Invasiones Mongolas y la Identidad Japonesa', 'El Período Sengoku y la Unificación'] },
    ru: { title: 'Средневековая Япония: самураи, сёгуны и бусидо', subtitle: 'Воины, честь и путь меча', keyFacts: ['Класс самураев возник в X веке как провинциальные воины', 'Война Гэмпэй (1180–1185) установила первый сёгунат под руководством Минамото-но Ёритомо', 'Дзен-буддизм глубоко повлиял на культуру и эстетику самураев', 'Монгольские вторжения в Японию в 1274 и 1281 годах были отражены отчасти благодаря тайфунам «камикадзе»', 'Период Сэнгоку («Воюющих государств») длился с 1467 по 1615 год'], sectionHeadings: ['Рождение самурая', 'Война Гэмпэй и возникновение сёгуната', 'Дзен-буддизм и самурайская эстетика', 'Монгольские вторжения и японская идентичность', 'Период Сэнгоку и объединение'] },
  },
  'earlymod-01': {
    mk: { title: 'Ренесансата и Епохата на Откривање', subtitle: 'Преродба на Идеите, Откривање на Светот', keyFacts: ['Ренесансата започнала во италијанските градови-држави во XIV век', 'Хуманизмот го ставил човештвото, а не Бог, во центарот на интелектуалното истражување', 'Колумбо стигнал до Америките во 1492 година', 'Колумбовата Размена ги трансформирала и двете хемисфери'], sectionHeadings: ['Италијанската Ренесанса', 'Хуманизмот и Печатарската Преса', 'Епохата на Откривање', 'Конквистадорите и Америките', 'Северната Ренесанса'] },
    es: { title: 'El Renacimiento y la Era de la Exploración', subtitle: 'Renacimiento de Ideas, Descubrimiento de Mundos', keyFacts: ['El Renacimiento comenzó en las ciudades-estado italianas en el siglo XIV', 'El humanismo situó a la humanidad, no a Dios, en el centro del pensamiento', 'Colón llegó a las Américas en 1492', 'El Intercambio Colombino transformó ambos hemisferios'], sectionHeadings: ['El Renacimiento Italiano', 'El Humanismo y la Imprenta', 'La Era de la Exploración', 'Los Conquistadores y las Américas', 'El Renacimiento del Norte'] },
    ru: { title: 'Ренессанс и эпоха Великих открытий', subtitle: 'Возрождение идей, открытие миров', keyFacts: ['Ренессанс начался в итальянских городах-государствах в XIV веке', 'Гуманизм поставил человека, а не Бога, в центр интеллектуальной жизни', 'Колумб достиг Америки в 1492 году', 'Колумбийский обмен преобразил оба полушария'], sectionHeadings: ['Итальянский Ренессанс', 'Гуманизм и печатный станок', 'Эпоха Великих открытий', 'Конкистадоры и Америки', 'Северный Ренессанс'] },
  },
  'earlymod-02': {
    mk: { title: 'Протестантската Реформација', subtitle: 'Религиска Револуција и Верски Војни', keyFacts: ['Мартин Лутер ги закачил своите 95 Тези во 1517 година', 'Реформацијата го поделила западното христијанство на католичко и протестантско', 'Триесетгодишната Војна (1618–1648) убила 8 милиони луѓе', 'Вестфалскиот Мир го воспоставил принципот на национален суверенитет'], sectionHeadings: ['Криза во Црквата', 'Лутер и Реформацијата', 'Верски Војни и Мирот во Вестфалија', 'Англиската Реформација: Хенри VIII и Елизабета I', 'Католичката Контрареформација'] },
    es: { title: 'La Reforma Protestante', subtitle: 'Revolución Religiosa y Guerras de Fe', keyFacts: ['Martín Lutero clavó sus 95 Tesis en 1517', 'La Reforma dividió el cristianismo occidental en católico y protestante', 'La Guerra de los Treinta Años (1618–1648) mató a 8 millones de personas', 'La Paz de Westfalia estableció el principio de soberanía nacional'], sectionHeadings: ['Crisis en la Iglesia', 'Lutero y la Reforma', 'Guerras de Religión y la Paz de Westfalia', 'La Reforma Inglesa: Enrique VIII e Isabel I', 'La Contrarreforma Católica'] },
    ru: { title: 'Протестантская реформация', subtitle: 'Религиозная революция и религиозные войны', keyFacts: ['Мартин Лютер прибил свои 95 тезисов в 1517 году', 'Реформация разделила западное христианство на католическое и протестантское', 'Тридцатилетняя война (1618–1648) унесла 8 миллионов жизней', 'Вестфальский мир установил принцип национального суверенитета'], sectionHeadings: ['Кризис в Церкви', 'Лютер и Реформация', 'Религиозные войны и Вестфальский мир', 'Английская Реформация: Генрих VIII и Елизавета I', 'Католическая контрреформация'] },
  },
  'earlymod-03': {
    mk: { title: 'Научната Револуција и Просветителството', subtitle: 'Разумот го Менува Светот', keyFacts: ['Коперник го предложил хелиоцентризмот во 1543 година', 'Принципите на Њутн (1687) го воспоставиле класичниот механизам', 'Просветителствениот мислители ги оспориле монархиите и Црквата', 'Американската и Француската Револуција ги примениле просветителствените идеали'], sectionHeadings: ['Пресврт на Космосот', 'Њутн и Новата Наука', 'Просветителството', 'Американската Револуција: Просветителството во Практика', 'Наследството и Ограничувањата на Просветителството'] },
    es: { title: 'La Revolución Científica y la Ilustración', subtitle: 'La Razón Transforma el Mundo', keyFacts: ['Copérnico propuso el heliocentrismo en 1543', 'Los Principia de Newton (1687) establecieron la mecánica clásica', 'Los pensadores ilustrados desafiaron las monarquías y la Iglesia', 'Las revoluciones americana y francesa aplicaron los ideales ilustrados'], sectionHeadings: ['Trastocando el Cosmos', 'Newton y la Nueva Ciencia', 'La Ilustración', 'La Revolución Americana: La Ilustración en Práctica', 'El Legado y los Límites de la Ilustración'] },
    ru: { title: 'Научная революция и Просвещение', subtitle: 'Разум преображает мир', keyFacts: ['Коперник предложил гелиоцентризм в 1543 году', '"Начала" Ньютона (1687) заложили основы классической механики', 'Мыслители Просвещения бросили вызов монархиям и Церкви', 'Американская и Французская революции воплотили идеалы Просвещения'], sectionHeadings: ['Переворот в космологии', 'Ньютон и новая наука', 'Просвещение', 'Американская революция: Просвещение на практике', 'Наследие и границы Просвещения'] },
  },
  'earlymod-04': {
    mk: { title: 'Епохата на Апсолутизам: Луј XIV и Версај', subtitle: 'Кралот-Сонце и Врвот на Кралската Моќ', keyFacts: ['Луј XIV управувал со Франција 72 години — најдолгото владеење на секој голем монарх', 'Дворецот Версај сместувал повеќе од 20.000 луѓе на врвот', '„L\'état, c\'est moi" (Јас сум државата) го олицетворува апсолутната монархија', 'Луј XIV го отповикал Едиктот за Нант во 1685, протерувајќи ги французките Протестанти', 'Војната за Шпанско Наследство (1701–1714) ја преобликувала рамнотежата во Европа'], sectionHeadings: ['Теоријата на Апсолутна Монархија', 'Кралот-Сонце: Луј XIV', 'Версај: Дворецот Како Политичко Средство', 'Религија, Отповикување и Хугенотите', 'Ограничувањата и Наследството на Апсолутизмот'] },
    es: { title: 'La Era del Absolutismo: Luis XIV y Versalles', subtitle: 'El Rey Sol y el Cénit del Poder Real', keyFacts: ['Luis XIV gobernó Francia durante 72 años — el reinado más largo de cualquier monarca importante', 'El Palacio de Versalles albergó más de 20.000 personas en su apogeo', '«L\'état, c\'est moi» (Yo soy el Estado) epitomiza la monarquía absoluta', 'Luis XIV revocó el Edicto de Nantes en 1685, expulsando a los protestantes franceses', 'La Guerra de Sucesión Española (1701–1714) remodeló el equilibrio de poder en Europa'], sectionHeadings: ['La Teoría de la Monarquía Absoluta', 'El Rey Sol: Luis XIV', 'Versalles: El Palacio como Instrumento Político', 'Religión, Revocación y los Hugonotes', 'Los Límites y el Legado del Absolutismo'] },
    ru: { title: 'Эпоха абсолютизма: Людовик XIV и Версаль', subtitle: 'Король-Солнце и зенит королевской власти', keyFacts: ['Людовик XIV правил Францией 72 года — дольше любого крупного монарха', 'Версальский дворец вмещал более 20 000 человек в период расцвета', '«L\'état, c\'est moi» («Государство — это я») олицетворяет абсолютную монархию', 'Людовик XIV отменил Нантский эдикт в 1685 году, выслав французских протестантов', 'Война за испанское наследство (1701–1714) изменила баланс сил в Европе'], sectionHeadings: ['Теория абсолютной монархии', 'Король-Солнце: Людовик XIV', 'Версаль: дворец как политический инструмент', 'Религия, отзыв и гугеноты', 'Пределы и наследие абсолютизма'] },
  },
  'earlymod-05': {
    mk: { title: 'Трансатлантската Трговија со Робови', subtitle: 'Ропство, Трговија и Создавањето на Атлантскиот Свет', keyFacts: ['Проценети 12,5 милиони Африканци биле превезени преку Атлантикот меѓу 1500 и 1900', 'Средниот Пролаз убил грубо 15–20% од сите поробени луѓе за време на преминот', 'Шеќерната економија на Карибите зависела целосно од поробениот африкански труд', 'Автобиографијата на Олауда Ековано (1789) помогна да се изгради британското движење за укинување на ропството', 'Велика Британија ја укинала трговијата со робови во 1807, а ропството во 1833'], sectionHeadings: ['Потекло: Шеќер, Профит и Побарување за Работна Сила', 'Трговијата со Робови во Дејство', 'Средниот Пролаз: Ужас на Море', 'Ропство во Америките: Живот и Отпор', 'Укинувањето и Наследството'] },
    es: { title: 'La Trata Transatlántica de Esclavos', subtitle: 'Cautiverio, Comercio y la Creación del Mundo Atlántico', keyFacts: ['Aproximadamente 12,5 millones de africanos fueron transportados a través del Atlántico entre 1500 y 1900', 'El Pasaje Medio mató a aproximadamente el 15–20% de los esclavizados durante la travesía', 'La economía azucarera del Caribe dependía completamente del trabajo africano esclavizado', 'La autobiografía de Olaudah Equiano (1789) ayudó a construir el movimiento abolicionista británico', 'Gran Bretaña abolió la trata de esclavos en 1807 y la esclavitud en 1833'], sectionHeadings: ['Orígenes: Azúcar, Beneficio y Demanda de Mano de Obra', 'La Trata de Esclavos en Operación', 'El Pasaje Medio: Horror en el Mar', 'La Esclavitud en las Américas: Vida y Resistencia', 'La Abolición y el Legado'] },
    ru: { title: 'Трансатлантическая работорговля', subtitle: 'Плен, торговля и создание атлантического мира', keyFacts: ['Около 12,5 миллиона африканцев были перевезены через Атлантику между 1500 и 1900 годами', 'Средний проход убил около 15–20% порабощённых во время перехода', 'Сахарная экономика Карибских островов полностью зависела от труда порабощённых африканцев', 'Автобиография Олаудаха Эквиано (1789) помогла построить британское аболиционистское движение', 'Великобритания отменила работорговлю в 1807 году, а рабство — в 1833-м'], sectionHeadings: ['Истоки: сахар, прибыль и спрос на рабочую силу', 'Работорговля в действии', 'Средний проход: ужас на море', 'Рабство в Америках: жизнь и сопротивление', 'Отмена и наследие'] },
  },
  'earlymod-06': {
    mk: { title: 'Отоманската Империја: Сулејман Величествениот', subtitle: 'Ислам, Право и Врвот на Отоманската Моќ', keyFacts: ['Отоманската Империја на врвот контролирала три континенти и 15–25 милиони луѓе', 'Сулејман I владеел 46 години (1520–1566), најдолгото владеење на секој отомански султан', 'Опсадата на Виена во 1529 го означила западниот дострел на отоманската експанзија', 'Отоманскиот закон (канун) бил кодифициран од Сулејман, кој ја заработил титулата „Законодавецот"', 'Битката кај Лепант (1571) бил првиот голем морнарички пораз на Отоманите'], sectionHeadings: ['Подемот на Отоманската Држава', 'Сулејман Величествениот: Законодавецот', 'Воени Кампањи и Границите на Империјата', 'Отоманското Општество: Мулти-Верска Империја', 'Отоманската Култура и Наследство'] },
    es: { title: 'El Imperio Otomano: Solimán el Magnífico', subtitle: 'Islam, Derecho y el Cénit del Poder Otomano', keyFacts: ['El Imperio Otomano en su apogeo controlaba tres continentes y 15–25 millones de personas', 'Solimán I reinó durante 46 años (1520–1566), el reinado más largo de cualquier sultán otomano', 'El Sitio de Viena en 1529 marcó el límite occidental de la expansión otomana', 'La ley otomana (kanun) fue codificada por Solimán, ganándole el título de «el Legislador»', 'La Batalla de Lepanto (1571) fue la primera gran derrota naval otomana'], sectionHeadings: ['El Surgimiento del Estado Otomano', 'Solimán el Magnífico: El Legislador', 'Campañas Militares y los Límites del Imperio', 'La Sociedad Otomana: Un Imperio Multireligioso', 'La Cultura y el Legado Otomano'] },
    ru: { title: 'Османская империя: Сулейман Великолепный', subtitle: 'Ислам, право и зенит османской мощи', keyFacts: ['Османская империя на пике контролировала три континента и 15–25 миллионов человек', 'Сулейман I правил 46 лет (1520–1566) — дольше любого османского султана', 'Осада Вены в 1529 году обозначила западный предел османской экспансии', 'Османский закон (канун) был кодифицирован Сулейманом, заслужившим титул «Законодатель»', 'Битва при Лепанто (1571) стала первым крупным морским поражением османов'], sectionHeadings: ['Возникновение Османского государства', 'Сулейман Великолепный: Законодатель', 'Военные кампании и пределы империи', 'Османское общество: многоконфессиональная империя', 'Османская культура и наследие'] },
  },
  'earlymod-07': {
    mk: { title: 'Епохата на Револуции', subtitle: 'Америка, Франција и Раѓањето на Модерната Демократија', keyFacts: ['Американската Декларација за Независност была потпишана на 4 јули 1776', 'Француската Револуција започнала во 1789 со бурењето на Бастилјата', 'Декларацијата за Правата на Човекот (1789) ја прогласила универзалната слобода и еднаквост', 'Владеењето на Теророт (1793–94) погубило повеќе од 17.000 луѓе, вклучувајќи ја Марија Антоанета', 'Наполеон Бонапарта дошол на власт во 1799, ширејќи ги револуционерните идеали низ Европа'], sectionHeadings: ['Американската Револуција: Просветителството во Акција', 'Освојување на Независноста', 'Француската Револуција: Слобода, Еднаквост, Братство', 'Владеењето на Теророт и Неговите Последици', 'Наполеон и Револуционерното Наследство'] },
    es: { title: 'La Era de las Revoluciones', subtitle: 'América, Francia y el Nacimiento de la Democracia Moderna', keyFacts: ['La Declaración de Independencia americana fue firmada el 4 de julio de 1776', 'La Revolución Francesa comenzó en 1789 con la toma de la Bastilla', 'La Declaración de los Derechos del Hombre y del Ciudadano (1789) proclamó la libertad y la igualdad universales', 'El Reinado del Terror (1793–94) ejecutó a más de 17.000 personas, incluyendo a María Antonieta', 'Napoleón Bonaparte llegó al poder en 1799, extendiendo los ideales revolucionarios por Europa'], sectionHeadings: ['La Revolución Americana: La Ilustración en Acción', 'Ganando la Independencia', 'La Revolución Francesa: Libertad, Igualdad, Fraternidad', 'El Reinado del Terror y sus Consecuencias', 'Napoleón y el Legado Revolucionario'] },
    ru: { title: 'Эпоха революций', subtitle: 'Америка, Франция и рождение современной демократии', keyFacts: ['Американская Декларация независимости подписана 4 июля 1776 года', 'Французская революция началась в 1789 году со взятия Бастилии', 'Декларация прав человека и гражданина (1789) провозгласила всеобщую свободу и равенство', 'Террор (1793–94) казнил более 17 000 человек, включая Марию-Антуанетту', 'Наполеон Бонапарт пришёл к власти в 1799 году, распространив революционные идеалы по Европе'], sectionHeadings: ['Американская революция: Просвещение в действии', 'Завоевание независимости', 'Французская революция: Liberté, Égalité, Fraternité', 'Террор и его последствия', 'Наполеон и революционное наследие'] },
  },
  'modern-01': {
    mk: { title: 'Индустриската Револуција', subtitle: 'Пареа, Челик и Општествени Промени', keyFacts: ['Индустриската Револуција започнала во Британија околу 1760 година', 'Парната сила ги трансформирала производството, транспортот и земјоделството', 'Урбанизацијата создала нови општествени класи — фабричарот и индустрискиот работник', 'До 1900, индустриските нации го доминирале светот'], sectionHeadings: ['Британските Корени', 'Железниците и Намалувањето на Светот', 'Општествени Последици', 'Втората Индустриска Револуција: Челик, Електрицитет и Хемија', 'Империја, Национализам и Семиња на Светска Војна'] },
    es: { title: 'La Revolución Industrial', subtitle: 'Vapor, Acero y Cambio Social', keyFacts: ['La Revolución Industrial comenzó en Gran Bretaña hacia 1760', 'La energía a vapor transformó la manufactura, el transporte y la agricultura', 'La urbanización creó nuevas clases sociales — el dueño de fábrica y el obrero industrial', 'Para 1900, las naciones industriales dominaban el mundo'], sectionHeadings: ['Los Orígenes Británicos', 'Los Ferrocarriles y la Reducción del Mundo', 'Consecuencias Sociales', 'La Segunda Revolución Industrial: Acero, Electricidad y Química', 'Imperio, Nacionalismo y las Semillas de la Guerra Mundial'] },
    ru: { title: 'Промышленная революция', subtitle: 'Пар, сталь и социальные перемены', keyFacts: ['Промышленная революция началась в Британии около 1760 года', 'Паровые машины преобразили производство, транспорт и сельское хозяйство', 'Урбанизация создала новые социальные классы — фабриканта и промышленного рабочего', 'К 1900 году промышленные нации господствовали в мире'], sectionHeadings: ['Британские истоки', 'Железные дороги и сжимающийся мир', 'Социальные последствия', 'Вторая промышленная революция: сталь, электричество и химия', 'Империализм, национализм и зёрна мировой войны'] },
  },
  'modern-02': {
    mk: { title: 'Светските Војни', subtitle: 'Векот на Тотална Војна', keyFacts: ['Првата светска војна (1914–1918) убила 20 милиони луѓе и уништила четири империи', 'Версајскиот Договор (1919) наметнал тешки услови на Германија', 'Втората светска војна (1939–1945) бил најсмртоносниот конфликт во историјата, со 70–85 милиони мртви', 'Холокаустот убил 6 милиони Евреи и милиони други'], sectionHeadings: ['Големата Војна', 'Патот кон Втората Светска Војна', 'Втората Светска Војна и Холокаустот', 'Меѓувоената Криза: Депресија и Тоталитаризам', 'Постратниот Поредок: ОН, НАТО и Атомскиот Век'] },
    es: { title: 'Las Guerras Mundiales', subtitle: 'El Siglo de la Guerra Total', keyFacts: ['La Primera Guerra Mundial (1914–1918) mató a 20 millones de personas y destruyó cuatro imperios', 'El Tratado de Versalles (1919) impuso duras condiciones a Alemania', 'La Segunda Guerra Mundial (1939–1945) fue el conflicto más mortífero de la historia, con 70–85 millones de muertos', 'El Holocausto asesinó a 6 millones de judíos y millones de otros'], sectionHeadings: ['La Gran Guerra', 'El Camino hacia la Segunda Guerra Mundial', 'La Segunda Guerra Mundial y el Holocausto', 'La Crisis de Entreguerras: Depresión y Totalitarismo', 'El Orden Posguerra: ONU, OTAN y la Era Atómica'] },
    ru: { title: 'Мировые войны', subtitle: 'Век тотальной войны', keyFacts: ['Первая мировая война (1914–1918) убила 20 миллионов человек и уничтожила четыре империи', 'Версальский договор (1919) наложил суровые условия на Германию', 'Вторая мировая война (1939–1945) стала самым смертоносным конфликтом в истории — 70–85 миллионов погибших', 'Холокост убил 6 миллионов евреев и миллионы других людей'], sectionHeadings: ['Великая война', 'Путь ко Второй мировой войне', 'Вторая мировая война и Холокост', 'Межвоенный кризис: депрессия и тоталитаризм', 'Послевоенный порядок: ООН, НАТО и атомный век'] },
  },
  'modern-03': {
    mk: { title: 'Студената Војна и Деколонизацијата', subtitle: 'Две Суперсили, Еден Поделен Свет', keyFacts: ['Студената Војна (1947–1991) беше идеолошка борба меѓу САД и СССР', 'И двете страни развиле нуклеарно оружје способно да ја уништи цивилизацијата', 'Десетици африкански и азиски нации здобиле независност во 1950-тите–1970-тите', 'Советскиот Сојуз се распаднал во 1991 година'], sectionHeadings: ['Студената Војна Започнува', 'Прокси Војни и Натпревар', 'Деколонизација и Советскиот Распад', 'Кубанската Ракетна Криза: Тринаесет Дена на Работ', 'Детант, Распад и Новиот Светски Поредок'] },
    es: { title: 'La Guerra Fría y la Descolonización', subtitle: 'Dos Superpotencias, Un Mundo Dividido', keyFacts: ['La Guerra Fría (1947–1991) fue una lucha ideológica entre EE.UU. y la URSS', 'Ambos lados desarrollaron armas nucleares capaces de destruir la civilización', 'Decenas de naciones africanas y asiáticas obtuvieron la independencia en los años 50–70', 'La Unión Soviética se disolvió en 1991'], sectionHeadings: ['Comienza la Guerra Fría', 'Guerras por Delegación y Competencia', 'La Descolonización y el Colapso Soviético', 'La Crisis de los Misiles en Cuba: Trece Días al Borde', 'Distensión, Colapso y el Nuevo Orden Mundial'] },
    ru: { title: 'Холодная война и деколонизация', subtitle: 'Две сверхдержавы, один разделённый мир', keyFacts: ['Холодная война (1947–1991) была идеологическим противостоянием между США и СССР', 'Обе стороны разработали ядерное оружие, способное уничтожить цивилизацию', 'Десятки африканских и азиатских стран обрели независимость в 1950–70-х годах', 'Советский Союз распался в 1991 году'], sectionHeadings: ['Начало холодной войны', 'Прокси-войны и соперничество', 'Деколонизация и крах СССР', 'Карибский ракетный кризис: тринадцать дней на краю', 'Разрядка, крах и новый мировой порядок'] },
  },
  'modern-04': {
    mk: { title: 'Глобализацијата и Современиот Свет', subtitle: 'Една Планета, Многу Предизвици', keyFacts: ['Светската Мрежа (World Wide Web) ја измислил Тим Бернерс-Ли во 1989 година', 'Глобалната трговија како дел од БДП се удвоила меѓу 1960 и 2000', 'Нападите на 11 септември 2001 ги трансформирале глобалната политика и безбедност', 'Климатските промени се дефинирачкиот еколошки предизвик на XXI век'], sectionHeadings: ['Дигиталната Револуција', 'Економска Глобализација', '21-от Век', 'Подемот на Кина и Мултиполарниот Свет', 'ВИ Револуцијата и Следните Предизвици на Човештвото'] },
    es: { title: 'La Globalización y el Mundo Contemporáneo', subtitle: 'Un Planeta, Muchos Desafíos', keyFacts: ['Tim Berners-Lee inventó la World Wide Web en 1989', 'El comercio global como parte del PIB se duplicó entre 1960 y 2000', 'Los ataques del 11 de septiembre de 2001 transformaron la política y la seguridad globales', 'El cambio climático es el desafío ambiental definitorio del siglo XXI'], sectionHeadings: ['La Revolución Digital', 'La Globalización Económica', 'El Siglo XXI', 'El Ascenso de China y el Mundo Multipolar', 'La Revolución de la IA y los Próximos Desafíos de la Humanidad'] },
    ru: { title: 'Глобализация и современный мир', subtitle: 'Одна планета, много вызовов', keyFacts: ['Тим Бернерс-Ли изобрёл World Wide Web в 1989 году', 'Мировая торговля как доля ВВП удвоилась между 1960 и 2000 годами', 'Теракты 11 сентября 2001 года изменили мировую политику и безопасность', 'Изменение климата — определяющий экологический вызов XXI века'], sectionHeadings: ['Цифровая революция', 'Экономическая глобализация', '21-й век', 'Возвышение Китая и многополярный мир', 'Революция ИИ и следующие вызовы человечества'] },
  },
  'modern-05': {
    mk: { title: 'Епохата на Империјализам и Трката за Африка', subtitle: 'Империја, Експлоатација и Отпор', keyFacts: ['До 1914, европските сили контролирале 84% од светската површина на копно', 'Берлинската Конференција од 1884–85 ја поделила Африка без африканско учество', 'Белгискиот Слободен Конго убил проценети 10 милиони Конголежани', 'Зулите ги поразиле Британците во Битката кај Исандлвана во 1879', 'Етиопија останала независна поразувајќи ја Италија во Битката кај Адва во 1896'], sectionHeadings: ['Моторите на Империјата', 'Трката за Африка', 'Ужасот на Конго', 'Отпор: Африка се Брани', 'Империјалистичко Наследство: Светот Кој го Наследивме'] },
    es: { title: 'La Era del Imperialismo y la Carrera por África', subtitle: 'Imperio, Explotación y Resistencia', keyFacts: ['Para 1914, las potencias europeas controlaban el 84% de la superficie terrestre del mundo', 'La Conferencia de Berlín de 1884–85 dividió África sin participación africana', 'El Estado Libre del Congo belga mató a una estimación de 10 millones de congoleños', 'Los zulúes derrotaron a los británicos en la Batalla de Isandlwana en 1879', 'Etiopía permaneció independiente derrotando a Italia en la Batalla de Adwa en 1896'], sectionHeadings: ['Los Motores del Imperio', 'El Reparto de África', 'El Horror del Congo', 'Resistencia: África Contraataca', 'El Legado Imperial: El Mundo que Heredamos'] },
    ru: { title: 'Эпоха империализма и раздел Африки', subtitle: 'Империя, эксплуатация и сопротивление', keyFacts: ['К 1914 году европейские державы контролировали 84% мировой суши', 'Берлинская конференция 1884–85 годов разделила Африку без участия африканцев', 'Бельгийское Конго убило около 10 миллионов конголезцев', 'Зулусы разгромили британцев в битве при Исандлване в 1879 году', 'Эфиопия сохранила независимость, разгромив Италию в битве при Адуа в 1896 году'], sectionHeadings: ['Движущие силы империализма', 'Раздел Африки', 'Ужас Конго', 'Сопротивление: Африка даёт отпор', 'Имперское наследие: мир, который мы унаследовали'] },
  },
  'modern-06': {
    mk: { title: 'Југословенските Војни', subtitle: 'Национализам, Геноцид и Распадот на Југославија', keyFacts: ['Југославија се распаднала насилно меѓу 1991 и 2001 година', 'Босанската Војна (1992–1995) го вклучила масакрот во Сребреница — најлошиот геноцид во Европа по Втората светска војна', 'НАТО ја бомбардирала Србија во 1999 за да ја запре Косовската Војна', 'Меѓународниот Кривичен Трибунал за поранешна Југославија (МКТЈ) гонел воени злосторства', 'Слободан Милошевиќ бил прв шеф на државата оптужен за воени злосторства'], sectionHeadings: ['Социјалистичката Федерација и Нејзините Пукнатини', 'Распадот Започнува: Словенија и Хрватска', 'Босна: Најкрвавата Европска Војна од 1945', 'Сребреница: Повторно Се Случи „Никогаш Повторно"', 'Косово, Интервенцијата на НАТО и Последиците'] },
    es: { title: 'Las Guerras Yugoslavas', subtitle: 'Nacionalismo, Genocidio y el Colapso de Yugoslavia', keyFacts: ['Yugoslavia se disolvió violentamente entre 1991 y 2001', 'La Guerra de Bosnia (1992–1995) incluyó la masacre de Srebrenica — el peor genocidio en Europa desde la Segunda Guerra Mundial', 'La OTAN bombardeó Serbia en 1999 para detener la Guerra de Kosovo', 'El Tribunal Penal Internacional para la ex Yugoslavia (TPIY) procesó crímenes de guerra', 'Slobodan Milošević fue el primer jefe de Estado acusado de crímenes de guerra'], sectionHeadings: ['La Federación Socialista y sus Fisuras', 'El Desglose Comienza: Eslovenia y Croacia', 'Bosnia: La Guerra más Sangrienta en Europa desde 1945', 'Srebrenica: "Nunca Más" Volvió a Pasar', 'Kosovo, la Intervención de la OTAN y las Consecuencias'] },
    ru: { title: 'Югославские войны', subtitle: 'Национализм, геноцид и распад Югославии', keyFacts: ['Югославия распалась в ходе насилия с 1991 по 2001 год', 'Боснийская война (1992–1995) включала резню в Сребренице — худший геноцид в Европе со времён Второй мировой', 'НАТО бомбардировало Сербию в 1999 году, чтобы остановить Косовскую войну', 'Международный трибунал по бывшей Югославии (МТБЮ) привлёк к ответственности военных преступников', 'Слободан Милошевич стал первым действующим главой государства, обвинённым в военных преступлениях'], sectionHeadings: ['Социалистическая федерация и её трещины', 'Распад начинается: Словения и Хорватия', 'Босния: кровопролитнейшая война в Европе с 1945 года', 'Сребреница: «Никогда снова» случилось снова', 'Косово, вмешательство НАТО и последствия'] },
  },
  'modern-07': {
    mk: { title: 'Македонската Борба', subtitle: 'Борбата на Еден Народ за Идентитет и Независност', keyFacts: ['Македонската Борба (1904–1908) беше вооружен конфликт меѓу грчки, бугарски и српски сили за контрола на отоманска Македонија', 'ВМРО го покренало неуспешното Илинденско Востание во 1903 година', 'Грчки вооружени чети (андарти) се бореле против бугарски комитаџии во герилска војна', 'Младотурската Револуција од 1908 привремено ја завршила борбата', 'Македонија беше поделена меѓу Грција, Србија и Бугарија по Балканските Војни (1912–1913)'], sectionHeadings: ['Македонија: Наградата за Која Се Натпреваруваат Сите', 'ВМРО и Илинденското Востание', 'Герилската Војна: Грчките наспроти Бугарските Чети', 'Отоманскиот Контекст и Младотурската Револуција', 'Балканските Војни и Поделбата на Македонија'] },
    es: { title: 'La Lucha Macedonia', subtitle: 'La Batalla de una Nación por la Identidad y la Independencia', keyFacts: ['La Lucha Macedonia (1904–1908) fue un conflicto armado entre fuerzas griegas, búlgaras y serbias por el control de Macedonia otomana', 'La ORIM lanzó el fallido Levantamiento de Ilinden en 1903', 'Bandas armadas griegas (andartes) lucharon contra comitadji búlgaros en una guerra de guerrillas', 'La Revolución de los Jóvenes Turcos de 1908 terminó temporalmente la lucha', 'Macedonia fue dividida entre Grecia, Serbia y Bulgaria tras las Guerras de los Balcanes (1912–1913)'], sectionHeadings: ['Macedonia: El Premio que Todos Codiciaban', 'El ORIM y el Levantamiento de Ilinden', 'La Guerra de Guerrillas: Griegos vs. Búlgaros', 'El Contexto Otomano y la Revolución de los Jóvenes Turcos', 'Las Guerras Balcánicas y la Partición de Macedonia'] },
    ru: { title: 'Македонская борьба', subtitle: 'Борьба народа за идентичность и независимость', keyFacts: ['Македонская борьба (1904–1908) — вооружённый конфликт между греческими, болгарскими и сербскими силами за контроль над Македонией', 'ВМРО подняло неудавшееся Илинденское восстание в 1903 году', 'Греческие вооружённые отряды (андарты) боролись против болгарских комитаджей в партизанской войне', 'Младотурецкая революция 1908 года временно завершила борьбу', 'Македония была разделена между Грецией, Сербией и Болгарией после Балканских войн (1912–1913)'], sectionHeadings: ['Македония: приз, которого добиваются все', 'ВМРО и Илинденское восстание', 'Партизанская война: греки против болгар', 'Османский контекст и младотурецкая революция', 'Балканские войны и раздел Македонии'] },
  },
};

export function getTranslatedEra(era: Era, lang: Language): Era {
  if (lang === 'en') return era;
  const trans = ERA_TRANS[era.id]?.[lang as ContentLang];
  return trans ? { ...era, ...trans } : era;
}

export function getTranslatedLesson<T extends { id: string; title: string; subtitle: string; keyFacts: string[]; sections: { heading: string; body: string }[] }>(
  lesson: T,
  lang: Language
): T {
  if (lang === 'en') return lesson;
  const trans = LESSON_TRANS[lesson.id]?.[lang as ContentLang];
  if (!trans) return lesson;
  return {
    ...lesson,
    title: trans.title,
    subtitle: trans.subtitle,
    keyFacts: trans.keyFacts,
    sections: lesson.sections.map((s, i) => ({
      ...s,
      heading: trans.sectionHeadings[i] ?? s.heading,
    })),
  };
}
