import type { Language } from './translations';
type ContentLang = Exclude<Language, 'en'>;

export const ANCIENT_MEDIEVAL_BODY_TRANS: Record<string, Partial<Record<ContentLang, string[]>>> = {
  'ancient-01': {
    es: [
      "Alrededor del 3500 a. C., los sumerios del sur de Mesopotamia —la tierra entre los ríos Tigris y Éufrates en el actual Irak— construyeron las primeras ciudades del mundo. Uruk, la más grande, pudo haber albergado a 50 000 personas. Para gestionar los excedentes de grano y las cuentas de los templos, los escribas sumerios inventaron la escritura cuneiforme alrededor del 3100 a. C., presionando marcas en forma de cuña sobre tablillas de arcilla.\n\nEste sistema de escritura se extendió por todo el Oriente Próximo y se convirtió en el guión dominante durante más de 3000 años. Las ciudades-estado mesopotámicas también desarrollaron herramientas de bronce, la rueda y sofisticados canales de riego que transformaron el desierto en tierras de cultivo.",
      "La civilización egipcia surgió a lo largo del Nilo aproximadamente al mismo tiempo que Súmer. La inundación anual del Nilo depositaba rico limo, convirtiendo a Egipto en una de las regiones más fértiles del mundo antiguo. Unificado bajo el faraón Narmer alrededor del 3100 a. C., Egipto desarrolló un sólido Estado centralizado gobernado por reyes-dioses.\n\nDurante el Imperio Antiguo (c. 2686–2181 a. C.), los faraones ordenaron la construcción de las grandes pirámides de Giza —hazañas de ingeniería que siguen siendo asombrosas hoy en día—. Los jeroglíficos egipcios, las matemáticas y la medicina se encontraban entre los más avanzados del mundo antiguo.",
      "El rey babilónico Hammurabi (r. 1792–1750 a. C.) unificó Mesopotamia y promulgó uno de los primeros códigos legales escritos del mundo. El Código de Hammurabi estableció castigos para los crímenes y reguló el comercio, reflejando una sociedad construida sobre el intercambio y el orden jurídico.\n\nTanto Egipto como Mesopotamia mantuvieron extensas redes comerciales. El oro y el grano egipcios fluían hacia el Levante; los mercaderes mesopotámicos comerciaban con el Valle del Indo. Estas primeras civilizaciones establecieron el modelo para el gobierno organizado, la religión, la agricultura y la vida urbana sobre el que todas las sociedades posteriores se construirían.",
      "La religión era inseparable del poder político en ambas civilizaciones. Los sumerios veneraban a un panteón de dioses que controlaban las fuerzas naturales —tormentas, inundaciones, fertilidad— y construyeron imponentes zigurats como templos para honrarlos. Los sacerdotes ejercían una enorme influencia, administrando las tierras de los templos y supervisando vastos almacenes de grano. La deidad más importante, Enlil, era considerada el rey de los dioses cuyo favor determinaba el destino de una ciudad.\n\nLa religión egipcia se centraba en la vida después de la muerte y el orden cósmico (Ma'at). Los faraones eran considerados dioses vivientes —manifestaciones de Horus en vida y de Osiris en la muerte—. El elaborado proceso de momificación y la construcción de tumbas piramidales tenían como objetivo preservar el cuerpo del faraón para la vida eterna. Estos sistemas religiosos daban sentido a las personas, legitimaban la autoridad política e impulsaban logros arquitectónicos de una ambición asombrosa.",
      "Bajo su visión del mundo religiosa, los eruditos mesopotámicos y egipcios lograron avances prácticos asombrosos. Los matemáticos babilónicos desarrollaron un sistema numérico de base 60 —el origen de nuestra hora de 60 minutos y el círculo de 360 grados—. Resolvieron ecuaciones cuadráticas y siguieron los movimientos planetarios durante siglos con una precisión meticulosa.\n\nLa medicina egipcia era igualmente impresionante. El Papiro Edwin Smith (c. 1600 a. C.) describe tratamientos quirúrgicos con observación clínica, reconociendo que las lesiones cerebrales causan parálisis específicas. Los médicos egipcios comprendían la anatomía gracias a la momificación y desarrollaron tratamientos para huesos rotos e infecciones. Este conjunto de conocimientos prácticos, aunque mezclado con remedios mágicos, sentó las bases para la medicina griega posterior y, en última instancia, para la ciencia moderna.",
    ],
    ru: [
      "Около 3500 г. до н. э. шумеры южной Месопотамии — земли между реками Тигр и Евфрат на территории современного Ирака — построили первые в мире города. Урук, крупнейший из них, мог насчитывать до 50 000 жителей. Для управления запасами зерна и храмовыми счетами шумерские писцы около 3100 г. до н. э. изобрели клинописное письмо, выдавливая клинообразные знаки на глиняных табличках.\n\nЭта система письма распространилась по всему Ближнему Востоку и оставалась господствующей письменностью на протяжении более 3000 лет. Месопотамские города-государства также разработали бронзовые орудия труда, колесо и сложные ирригационные каналы, превратившие пустыню в плодородные угодья.",
      "Египетская цивилизация возникла вдоль Нила примерно в то же время, что и шумерская. Ежегодные разливы Нила откладывали богатый ил, делая Египет одним из наиболее плодородных регионов древнего мира. Объединённый фараоном Нармером около 3100 г. до н. э., Египет выстроил сильное централизованное государство, которым правили цари-боги.\n\nВ эпоху Древнего царства (ок. 2686–2181 гг. до н. э.) фараоны повелели возвести великие пирамиды в Гизе — инженерные свершения, которые по сей день вызывают изумление. Египетские иероглифы, математика и медицина были в числе наиболее развитых в древнем мире.",
      "Вавилонский царь Хаммурапи (правл. 1792–1750 гг. до н. э.) объединил Месопотамию и издал один из древнейших письменных сводов законов. Кодекс Хаммурапи устанавливал наказания за преступления и регулировал торговлю, отражая общество, построенное на обмене и правовом порядке.\n\nИ Египет, и Месопотамия поддерживали обширные торговые сети. Египетские золото и зерно поступали на Левант; месопотамские купцы торговали с долиной Инда. Эти ранние цивилизации заложили образец организованного управления, религии, сельского хозяйства и городской жизни, на котором строились все последующие общества.",
      "Религия была неотделима от политической власти в обеих цивилизациях. Шумеры почитали пантеон богов, управлявших силами природы — бурями, наводнениями, плодородием, — и воздвигали величественные зиккураты как храмы в их честь. Жрецы обладали огромным влиянием, управляя храмовыми землями и надзирая за обширными зернохранилищами. Главное божество, Энлиль, почиталось как царь богов, чья благосклонность определяла судьбу города.\n\nЕгипетская религия сосредотачивалась на загробной жизни и космическом порядке (Маат). Фараоны считались живыми богами — воплощением Гора при жизни и Осириса после смерти. Сложный процесс мумификации и строительство пирамид-гробниц были призваны сохранить тело фараона для вечной жизни. Эти религиозные системы придавали людям смысл, легитимизировали политическую власть и вдохновляли на архитектурные свершения поразительного масштаба.",
      "За религиозным мировоззрением месопотамские и египетские учёные совершали поразительные практические открытия. Вавилонские математики разработали шестидесятеричную систему счисления — источник нашего шестидесятиминутного часа и трёхсот шестидесяти градусов окружности. Они решали квадратные уравнения и на протяжении столетий с тщательной точностью отслеживали движения планет.\n\nЕгипетская медицина была не менее впечатляющей. Папирус Эдвина Смита (ок. 1600 г. до н. э.) описывает хирургические методы лечения с клиническими наблюдениями, фиксируя, что травмы мозга вызывают определённые виды паралича. Египетские врачи понимали анатомию через мумификацию и разрабатывали методы лечения переломов и инфекций. Этот массив практических знаний, хотя и переплетённый с магическими средствами, заложил основу для последующей греческой медицины и в конечном счёте для современной науки.",
    ],
    mk: [
      "Околу 3500 г. пр. н. е., Сумерите од јужна Месопотамија — земјата меѓу реките Тигар и Еуфрат на просторот на денешен Ирак — ги изградиле првите градови на светот. Урук, најголемиот, можеби имал 50 000 жители. За да управуваат со вишоците жито и сметките на храмовите, сумерските писари ја измислиле клинестата писменост околу 3100 г. пр. н. е., притискајќи клинести знаци во глинени плочки.\n\nОвој систем на пишување се проширил низ Блискиот Исток и станал доминантна писменост повеќе од 3000 години. Месопотамските градови-држави развиле и бронзени алатки, тркалото и сложени канали за наводнување кои ја претвориле пустината во обработлива земја.",
      "Египетската цивилизација се pojавила долж Нил приближно во исто време кога и Сумер. Годишното поплавување на Нил таложело богат тиња, правејќи го Египет еден од најплодните региони на античкиот свет. Обединет под фараонот Нармер околу 3100 г. пр. н. е., Египет развил силна централизирана држава со владетели-богови.\n\nЗа време на Старото Кралство (ок. 2686–2181 г. пр. н. е.), фараоните наредиле изградба на големите пирамиди во Гиза — инженерски достигнувања кои и денес будат восхит. Египетските хиероглифи, математиката и медицината биле меѓу најнапредните во античкиот свет.",
      "Вавилонскиот крал Хамураби (вл. 1792–1750 г. пр. н. е.) ја обединил Месопотамија и издал еден од најраните писмени правни кодекси на светот. Законикот на Хамураби утврдил казни за злосторства и ја регулирал трговијата, одразувајќи општество изградено врз размена и правен поредок.\n\nИ Египет и Месопотамија одржувале широки трговски мрежи. Египетското злато и жито текло кон Левантот; месопотамските трговци тргувале со Долината на Инд. Овие рани цивилизации го поставиле образецот за организирана власт, религија, земјоделство и градски живот врз кој ќе се надградуваат сите подоцнежни општества.",
      "Религијата беше неодвоива од политичката власт во двете цивилизации. Сумерите се клањале на пантеон богови кои ги контролирале природните сили — бури, поплави, плодност — и градиле импозантни зигурати како храмови за да ги почитуваат. Свештениците имале огромно влијание, управувајќи со храмовните земји и надгледувајќи огромни складишта за жито. Најважното божество, Енлил, бил сметан за крал на боговите чија наклоност ја одредувала судбината на еден град.\n\nЕгипетската религија се фокусирала на задгробниот живот и космичкиот поредок (Ма'ат). Фараоните биле сметани за живи богови — манифестации на Хор во животот и на Озирис во смртта. Сложениот процес на мумифицирање и изградбата на пирамидални гробници имале за цел да го зачуваат телото на фараонот за вечен живот. Овие религиозни системи им давале смисла на луѓето, ја легитимизирале политичката власт и поттикнувале архитектонски достигнувања со изненадувачка амбиција.",
      "Под нивниот религиски поглед на светот, месопотамските и египетските учени правеле неверојатни практични напредоци. Вавилонските математичари развиле бројна систем со основа 60 — изворот на нашиот час од 60 минути и кругот од 360 степени. Решавале квадратни равенки и со педантна прецизност ги следеле движењата на планетите во текот на векови.\n\nЕгипетската медицина беше исто толку впечатлива. Папирусот Едвин Смит (ок. 1600 г. пр. н. е.) опишува хируршки третмани со клиничко набљудување, препознавајќи дека повредите на мозокот предизвикуваат специфична парализа. Египетските лекари ја разбирале анатомијата преку мумифицирање и развиле третмани за скршени коски и инфекции. Овој збир на практично знаење, иако измешан со магични лекови, ги поставил темелите за подоцнежната грчка медицина и, во крајна линија, за модерната наука.",
    ],
  },
  'ancient-02': {
    es: [
      "La antigua Grecia no era una nación unificada, sino una colección de ciudades-estado independientes (poleis), cada una con su propio gobierno y cultura. Atenas y Esparta eran las más poderosas. Esparta desarrolló una sociedad militarista; cada ciudadano varón se entrenaba como soldado desde los siete años. Atenas, por el contrario, se convirtió en un centro del arte, la filosofía y la innovación política.\n\nHacia el 508 a. C., el reformador ateniense Clístenes introdujo la demokratia —el gobierno del pueblo—, el primer gobierno democrático del mundo. Los ciudadanos (varones adultos libres) votaban directamente sobre leyes y políticas en la Asamblea, una idea revolucionaria que influiría en todas las democracias futuras.",
      "Cuando el Imperio Persa invadió Grecia en el 490 a. C., los atenienses los derrotaron en Maratón. Una segunda invasión persa en el 480 a. C. fue testigo de la legendaria resistencia espartana en las Termópilas antes de que los atenienses destruyeran la flota persa en Salamina.\n\nLa victoria sobre Persia llevó a Atenas a la cima de su poder. El líder ateniense Pericles utilizó el dinero de los tributos para construir el Partenón en la Acrópolis, una obra maestra de la arquitectura clásica. Pero la rivalidad entre Atenas y Esparta estalló en la devastadora Guerra del Peloponeso (431–404 a. C.), que agotó a ambas potencias.",
      "La Atenas clásica produjo algunos de los más grandes pensadores de la historia. Sócrates enseñaba mediante el cuestionamiento, desafiando a los atenienses a examinar sus creencias. Su método —el método socrático— sigue siendo fundamental en la educación hoy en día. Sócrates fue condenado a muerte en el 399 a. C. por 'corromper a la juventud'.\n\nSu discípulo Platón escribió diálogos que exploraban la justicia, la belleza y el Estado ideal. El alumno de Platón, Aristóteles, sistematizó la lógica, la biología, la ética y la política, y fue tutor del joven Alejandro de Macedonia. Alejandro Magno (r. 336–323 a. C.) conquistó un imperio que se extendía desde Grecia hasta Egipto e India, difundiendo la lengua y la cultura griegas —el helenismo— por todo el mundo antiguo.",
      "El arte y la arquitectura griegos reflejaban una búsqueda de la belleza y la proporción ideales. El Partenón en la Acrópolis de Atenas —construido entre el 447 y el 432 a. C. bajo la supervisión del escultor Fidias— ejemplifica esta búsqueda. Sus columnas se abomban sutilmente en el centro para corregir ilusiones ópticas, creando la impresión de perfecta rectitud. Escultores griegos como Mirón y Praxíteles representaron el cuerpo humano en poses idealizadas y naturalistas, superando con creces la rígida frontalidad de los estilos artísticos anteriores.\n\nLos Juegos Olímpicos, fundados en el 776 a. C. en Olimpia en honor a Zeus, reunían a atletas de todo el mundo griego cada cuatro años. Durante los juegos, las guerras se suspendían bajo una tregua sagrada. Las pruebas incluían carreras, lucha, lanzamiento de disco, carreras de carros y el pentatlón. Los vencedores olímpicos ganaban únicamente una corona de olivo —pero eran celebrados como héroes en sus ciudades de origen e inmortalizados en odas de victoria por poetas como Píndaro—. Los Juegos encarnaban el ideal griego de areté: excelencia, virtud y afán de superación.",
      "Las conquistas de Alejandro Magno difundieron la lengua, la cultura y las instituciones griegas por una vasta franja del mundo antiguo —desde Egipto hasta Bactriana (el actual Afganistán)—. Este mundo 'helenístico' albergó magníficas ciudades: Alejandría en Egipto, con su legendaria Biblioteca que guardaba quizás 500 000 rollos; Antioquía en Siria; Pérgamo en Anatolia. Estos cosmopolitas centros fusionaron las tradiciones griega, persa, egipcia e india.\n\nLos eruditos helenísticos lograron espectaculares avances. Eratóstenes calculó la circunferencia de la Tierra con notable exactitud usando sombras y geometría. Euclides sistematizó la geometría; Arquímedes calculó el número pi y descubrió los principios de la flotabilidad y la palanca. Aristarco incluso propuso que la Tierra orbitaba alrededor del Sol —diecisiete siglos antes que Copérnico—. Cuando Roma absorbió finalmente los reinos helenísticos, preservó y transmitió esta herencia intelectual, convirtiendo a la Grecia clásica en la fuente de la civilización occidental.",
    ],
    ru: [
      "Древняя Греция была не единым государством, а совокупностью независимых городов-государств (полисов), каждый со своим правительством и культурой. Афины и Спарта были наиболее могущественными. Спарта создала милитаристское общество; каждый гражданин мужского пола обучался военному делу с семи лет. Афины, напротив, стали центром искусства, философии и политических новаций.\n\nОколо 508 г. до н. э. афинский реформатор Клисфен ввёл демократию — власть народа — первое в мире демократическое правление. Граждане (свободные взрослые мужчины) непосредственно голосовали по законам и решениям на Народном собрании — революционная идея, повлиявшая на все будущие демократии.",
      "Когда Персидская империя вторглась в Грецию в 490 г. до н. э., афиняне разгромили её при Марафоне. Во время второго персидского вторжения в 480 г. до н. э. произошло легендарное Фермопильское сражение спартанцев, после чего афиняне уничтожили персидский флот при Саламине.\n\nПобеда над Персией вознесла Афины на вершину могущества. Афинский стратег Перикл использовал союзнические взносы для строительства Парфенона на Акрополе — шедевра классической архитектуры. Однако соперничество между Афинами и Спартой переросло в опустошительную Пелопоннесскую войну (431–404 гг. до н. э.), которая истощила обе державы.",
      "Классические Афины дали миру величайших мыслителей в истории. Сократ учил методом вопросов, побуждая афинян проверять свои убеждения. Его метод — сократовский диалог — по сей день остаётся основой образования. В 399 г. до н. э. Сократ был приговорён к смерти за «развращение юношества».\n\nЕго ученик Платон писал диалоги, исследующие справедливость, красоту и идеальное государство. Ученик Платона Аристотель систематизировал логику, биологию, этику и политику и был наставником юного Александра Македонского. Александр Великий (правл. 336–323 гг. до н. э.) завоевал империю, простиравшуюся от Греции до Египта и Индии, распространяя греческий язык и культуру — эллинизм — по всему античному миру.",
      "Греческое искусство и архитектура отражали стремление к идеальной красоте и пропорции. Парфенон на афинском Акрополе — построенный между 447 и 432 гг. до н. э. под руководством скульптора Фидия — воплощает это стремление. Его колонны слегка выпуклы посередине, чтобы исправить оптические иллюзии и создать впечатление совершенной прямолинейности. Греческие скульпторы — Мирон и Пракситель — изображали человеческое тело в идеализированных, натуралистических позах, далеко превзойдя жёсткую фронтальность более ранних художественных стилей.\n\nОлимпийские игры, основанные в 776 г. до н. э. в Олимпии в честь Зевса, собирали атлетов со всего греческого мира каждые четыре года. На время игр войны прекращались по условиям священного перемирия. Состязания включали бег, борьбу, метание диска, гонки на колесницах и пятиборье. Победители Олимпийских игр получали лишь оливковый венок — однако их чтили как героев в родных городах и увековечивали в победных одах такие поэты, как Пиндар. Игры воплощали греческий идеал арете: совершенства, добродетели и стремления к победе.",
      "Завоевания Александра Великого распространили греческий язык, культуру и институты на огромные просторы античного мира — от Египта до Бактрии (современного Афганистана). В этом «эллинистическом» мире процветали великолепные города: Александрия в Египте с легендарной Библиотекой, хранившей, возможно, 500 000 свитков; Антиохия в Сирии; Пергам в Анатолии. Эти космополитические центры смешивали греческие, персидские, египетские и индийские традиции.\n\nЭллинистические учёные совершили выдающиеся открытия. Эратосфен с замечательной точностью вычислил длину окружности Земли, используя тени и геометрию. Евклид систематизировал геометрию; Архимед вычислил число пи и открыл принципы плавучести и рычага. Аристарх даже предположил, что Земля вращается вокруг Солнца — за семнадцать веков до Коперника. Когда Рим в конечном счёте поглотил эллинистические царства, он сохранил и передал это интеллектуальное наследие, сделав Классическую Грецию колыбелью западной цивилизации.",
    ],
    mk: [
      "Античка Грција не беше обединета нација, туку збир на независни градови-држави (полиси), секој со своја влада и култура. Атина и Спарта беа најмоќните. Спарта развила милитаристичко општество; секој маж-граѓанин се обучувал за војник од седумгодишна возраст. Атина, напротив, станала центар на уметноста, филозофијата и политичките иновации.\n\nОколу 508 г. пр. н. е., атинскиот реформатор Клистен ја воведол демократијата — владеење на народот — прва демократска влада на светот. Граѓаните (слободни возрасни мажи) гласале директно за законите и политиките на Собранието — револуционерна идеја која ќе влијае на сите идни демократии.",
      "Кога Персиската Империја ја нападнала Грција во 490 г. пр. н. е., Атињаните ги поразиле кај Маратон. Второто персиско освојување во 480 г. пр. н. е. го донесло легендарното спартанско држење кај Термопили, по кое Атињаните ја уништиле персиската флота кај Саламина.\n\nПобедата над Персија ја издигнала Атина на врвот на моќта. Атинскиот водач Перикле ги искористил tribутните пари за изградба на Партенонот на Акрополот — ремек-дело на класичната архитектура. Но ривалството меѓу Атина и Спарта еруптирало во опустошувачката Пелопонеска Војна (431–404 г. пр. н. е.), која ги исцрпила двете сили.",
      "Класичната Атина произвела некои од највеликите мислители во историјата. Сократ поучувал преку прашања, предизвикувајќи ги Атињаните да ги испитаат своите верувања. Неговиот метод — сократскиот метод — останува централен во образованието и денес. Сократ бил осуден на смрт во 399 г. пр. н. е. за 'расипување на младите'.\n\nНеговиот ученик Платон пишувал дијалози кои истражуваат правда, убавина и идеалната држава. Платоновиот ученик Аристотел ги систематизирал логиката, биологијата, етиката и политиката, туторирајќи го младиот Александар Македонски. Александар Велики (вл. 336–323 г. пр. н. е.) освоил империја која се протегала од Грција до Египет и Индија, ширејќи го грчкиот јазик и култура — хеленизмот — низ античкиот свет.",
      "Грчката уметност и архитектура одразувале потрага по идеална убавина и пропорција. Партенонот врз атинскиот Акропол — изграден меѓу 447 и 432 г. пр. н. е. под надзор на вајарот Фидија — го претставува ова стремење. Неговите столбови суптилно се издуваат во средината за да ги исправат оптичките илузии, создавајќи впечаток на совршена правост. Грчки вајари како Мирон и Праксител го прикажувале човечкото тело во идеализирани, натуралистички пози, далеку надминувајќи ги цврстите фронтални стилови на поранешната уметност.\n\nОлимписките Игри, основани во 776 г. пр. н. е. во Олимпија во чест на Зевс, собирале атлети од целиот грчки свет на секои четири години. За време на игрите, војните биле суспендирани под свето примирје. Натпреварите вклучувале трчање, борење, фрлање диск, трки со коли и петобој. Олимписките победници освојувале само маслинов венец — но биле прославувани како херои во нивните домашни градови и овековечувани во победнички оди од поети како Пиндар. Игрите го отелотворувале грчкиот идеал на арете: извонредност, доблест и натпреварувачко тежнење.",
      "Освојувањата на Александар Велики го ширеле грчкиот јазик, културата и институциите низ огромен дел од античкиот свет — од Египет до Бактрија (денешен Авганистан). Овој 'хеленистички' свет поддржувал величествени градови: Александрија во Египет, со легендарната Библиотека која чувала можеби 500 000 свитоци; Антиохија во Сирија; Пергамон во Анатолија. Овие космополитски центри ги мешале грчките, персиските, египетските и индиските традиции.\n\nХеленистичките учени постигнале спектакуларен напредок. Ератостен ја пресметал обиколката на Земјата со забележителна точност користејќи сенки и геометрија. Евклид ја систематизирал геометријата; Архимед го пресметал пи и ги открил принципите на лебдење и потпора. Аристарх дури предложил дека Земјата орбитира околу Сонцето — седумнаесет века пред Коперник. Кога Рим конечно ги апсорбирал хеленистичките кралства, ја зачувал и пренел оваа интелектуална наследина, правејќи ја Класичната Грција извориштето на западната цивилизација.",
    ],
  },
  'ancient-03': {
    es: [
      "Según la tradición, Roma fue fundada en el 753 a. C. sobre siete colinas junto al río Tíber. Tras expulsar a sus reyes hacia el 509 a. C., Roma se convirtió en una república gobernada por cónsules elegidos y un Senado de aristócratas. Con el tiempo, los plebeyos obtuvieron mayores derechos a través de las Doce Tablas —el primer código legal escrito de Roma—.\n\nRoma se expandió de manera constante por toda Italia, venciendo a sus rivales mediante la disciplina militar y la hábil diplomacia. En el 264 a. C., Roma controlaba la península itálica y ponía sus miras en el vasto mundo mediterráneo.",
      "El choque de Roma con Cartago produjo las tres Guerras Púnicas (264–146 a. C.). El general cartaginés Aníbal cruzó famosamente los Alpes con elefantes de guerra y devastó a los ejércitos romanos en Cannas en el 216 a. C. Sin embargo, la resiliencia romana prevaleció; Cartago fue finalmente destruida en el 146 a. C.\n\nLa conquista romana trajo gran riqueza, pero también tensión social. Generales como Mario y Sila comandaban ejércitos personales leales a ellos antes que al Senado. El genio militar de Julio César en la Galia lo convirtió en el hombre más poderoso de Roma —hasta su asesinato en los Idus de Marzo del 44 a. C.",
      "El heredero de César, Octaviano, derrotó a sus rivales y se convirtió en el primer emperador de Roma como Augusto en el 27 a. C. La era augustana inauguró la Pax Romana —dos siglos de relativa estabilidad, prosperidad y logros culturales—. La red de calzadas romanas, los acueductos y el sistema jurídico unificaron un vasto imperio desde Britania hasta Mesopotamia.\n\nEn su apogeo bajo el emperador Trajano, el Imperio Romano cubría 5 millones de kilómetros cuadrados y albergaba quizás 70 millones de personas. Pero la sobreexpansión, la tensión económica y la presión militar de las tribus germánicas debilitaron gradualmente el imperio. En el 476 d. C., el último emperador romano de Occidente fue depuesto.",
      "La civilización romana fue tanto una hazaña de ingeniería como de política. Los romanos construyeron más de 80 000 km de calzadas pavimentadas con piedra tallada. Inventaron el hormigón, que permitió la construcción de la cúpula no reforzada del Panteón —aún la mayor del mundo después de 2000 años—, vastos acueductos que transportaban agua fresca cientos de kilómetros y el Coliseo con capacidad para 80 000 espectadores.\n\nLa vida cotidiana romana era sorprendentemente reconocible. Los romanos urbanos vivían en edificios de apartamentos de varios pisos (insulae), compraban en panaderías y tabernas, visitaban los baños públicos (thermae) para socializar y asistían a combates de gladiadores y carreras de carros. El derecho romano, sistematizado en el Corpus Juris Civilis del emperador Justiniano (529 d. C.), constituye el fundamento de los sistemas jurídicos de toda Europa y América Latina hasta hoy.",
      "Durante el reinado de Augusto, un maestro judío llamado Jesús de Nazaret nació en la Judea romana. Crucificado bajo el gobernador romano Poncio Pilato hacia el 30 d. C., sus seguidores creyeron que había resucitado de entre los muertos. El cristianismo se extendió rápidamente a lo largo de las calzadas romanas, atrayendo especialmente a esclavos, mujeres y pobres con su mensaje de igualdad y redención espiritual. Para el año 300 d. C., quizás el 10 % del imperio era cristiano.\n\nEn el 313 d. C., el emperador Constantino promulgó el Edicto de Milán, legalizando el cristianismo. En el 380 d. C., era la religión oficial. La adopción del cristianismo transformó el imperio y toda la historia occidental —moldeando la educación, el arte, la filosofía y el derecho—. Cuando el Imperio de Occidente cayó en el siglo V, la Iglesia sobrevivió como la principal continuidad institucional entre el mundo antiguo y el medieval, preservando la alfabetización latina y transmitiendo la sabiduría acumulada de Roma a las generaciones futuras.",
    ],
    ru: [
      "По преданию, Рим был основан в 753 г. до н. э. на семи холмах у реки Тибр. Изгнав царей около 509 г. до н. э., Рим превратился в республику, управляемую выборными консулами и Сенатом аристократов. Со временем плебеи добились бо́льших прав благодаря Законам двенадцати таблиц — первому письменному правовому кодексу Рима.\n\nРим неуклонно расширялся по всей Италии, побеждая соперников военной дисциплиной и искусной дипломатией. К 264 г. до н. э. Рим контролировал Апеннинский полуостров и обратил взоры на широкий средиземноморский мир.",
      "Столкновение Рима с Карфагеном породило три Пунические войны (264–146 гг. до н. э.). Карфагенский полководец Ганнибал прославился переходом через Альпы с боевыми слонами и разгромом римских армий при Каннах в 216 г. до н. э. Однако стойкость Рима взяла верх: Карфаген был окончательно разрушен в 146 г. до н. э.\n\nРимские завоевания принесли огромные богатства, но и социальную напряжённость. Полководцы Марий и Сулла командовали личными армиями, преданными им, а не Сенату. Военный гений Юлия Цезаря в Галлии сделал его могущественнейшим человеком в Риме — вплоть до его убийства на мартовские иды 44 г. до н. э.",
      "Наследник Цезаря Октавиан победил своих соперников и в 27 г. до н. э. стал первым императором Рима под именем Август. Эпоха Августа открыла Pax Romana — два века относительной стабильности, процветания и культурных достижений. Римская сеть дорог, акведуки и правовая система объединили огромную империю от Британии до Месопотамии.\n\nВ зените могущества при императоре Траяне Римская империя занимала 5 миллионов квадратных километров и насчитывала, возможно, 70 миллионов жителей. Но чрезмерное расширение, экономическое истощение и военное давление германских племён постепенно ослабляли империю. В 476 г. н. э. последний западноримский император был низложен.",
      "Римская цивилизация была столь же выдающимся инженерным свершением, как и политическим. Римляне проложили более 80 000 км дорог, вымощенных тёсаным камнем. Они изобрели бетон, что позволило возвести неармированный купол Пантеона — по сей день крупнейший в мире спустя 2000 лет, — огромные акведуки, несущие пресную воду на сотни километров, и Колизей вместимостью 80 000 зрителей.\n\nПовседневная жизнь римлян была поразительно узнаваема. Городские римляне жили в многоэтажных доходных домах (инсулах), закупались в пекарнях и тавернах, посещали общественные бани (термы) для общения и ходили на гладиаторские игры и гонки на колесницах. Римское право, систематизированное в Corpus Juris Civilis императора Юстиниана (529 г. н. э.), по сей день составляет основу правовых систем по всей Европе и Латинской Америке.",
      "В правление Августа в римской Иудее родился еврейский учитель по имени Иисус из Назарета. Распятый по приказу римского наместника Понтия Пилата около 30 г. н. э., он, по убеждению его последователей, воскрес из мёртвых. Христианство стремительно распространялось вдоль римских дорог, привлекая особенно рабов, женщин и бедняков своим посланием о равенстве и духовном искуплении. К 300 г. н. э. христианами были, возможно, 10% жителей империи.\n\nВ 313 г. н. э. император Константин издал Миланский эдикт, легализовавший христианство. К 380 г. н. э. оно стало официальной религией. Принятие христианства преобразило империю и всю западную историю — определив облик образования, искусства, философии и права. Когда в V веке пала Западная империя, Церковь выжила как главный институциональный мост между античным и средневековым мирами, сохраняя латинскую грамотность и передавая накопленную мудрость Рима будущим поколениям.",
    ],
    mk: [
      "Според преданието, Рим бил основан во 753 г. пр. н. е. на седум ридови покрај реката Тибар. По протерувањето на кралевите околу 509 г. пр. н. е., Рим станал република управувана од избрани конзули и Сенат на аристократи. Со текот на времето, плебејците добиле поголеми права преку Законите на дванаесетте таблици — првиот пишан правен законик на Рим.\n\nРим се ширел постепено низ цела Италија, победувајќи ги ривалите преку воена дисциплина и вешта дипломатија. До 264 г. пр. н. е., Рим го контролирал Апенинскиот Полуостров и ги насочил своите погледи кон поширокиот медитерански свет.",
      "Судирот на Рим со Картагина ги произвел трите Пунски Војни (264–146 г. пр. н. е.). Картагинскиот генерал Ханибал прочуено ги преминал Алпите со воени слонови и ги уништил римските армии кај Кана во 216 г. пр. н. е. Но отпорноста на Рим победила; Картагина конечно била уништена во 146 г. пр. н. е.\n\nРимското освојување донело големо богатство, но и социјална напнатост. Генерали како Мариј и Сула командувале лични армии лојални на нив, а не на Сенатот. Воениот гениј на Јулиј Цезар во Галија го направил најмоќниот човек во Рим — сè до неговото убиство на Мартовските иди, 44 г. пр. н. е.",
      "Наследникот на Цезар, Октавијан, ги поразил своите ривали и станал прв римски император како Август во 27 г. пр. н. е. Августовата ера ја поставила Pax Romana — два века на релативна стабилност, просперитет и културни достигнувања. Римската мрежа на патишта, акведуктите и правниот систем обединиле огромна империја од Британија до Месопотамија.\n\nНа врвот под царот Трајан, Римската Империја зафаќала 5 милиони квадратни километри и имала можеби 70 милиони луѓе. Но претераното ширење, економскиот притисок и воениот притисок од германските племиња постепено ја ослабиле империјата. Во 476 г. н. е., последниот западноримски цар бил соборен.",
      "Римската цивилизација беше исто толку инженерска колку и политичка достигнување. Римјаните изградиле повеќе од 80 000 km патишта поплочени со обработен камен. Го измислиле бетонот, овозможувајќи изградба на неармираната купола на Пантеонот — сè уште најголема во светот по 2000 години — огромни акведукти кои носат свежа вода стотици километри и Колосеумот со капацитет од 80 000 гледачи.\n\nСекојдневниот римски живот беше изненадувачки препознатлив. Урбаните Римјани живееле во повеќекатни станбени згради (инсули), купувале во пекари и крчми, посетувале јавни бањи (терми) за да социјализираат и присуствувале на гладијаторски борби и трки со коли. Римското право, систематизирано во Corpus Juris Civilis на царот Јустинијан (529 г. н. е.), ги формира темелите на правните системи низ цела Европа и Латинска Америка до денес.",
      "Во владеењето на Август, еврејски учител по име Исус од Назарет бил роден во римска Јудеа. Распнат под римскиот управник Понтиј Пилат околу 30 г. н. е., неговите следбеници верувале дека воскреснал од мртвите. Христијанството се ширело брзо долж римските патишта, привлекувајќи особено робови, жени и сиромашни со своето послание за еднаквост и духовен откуп. До 300 г. н. е., можеби 10% од империјата биле христијани.\n\nВо 313 г. н. е., царот Константин го издал Миланскиот Едикт, легализирајќи го христијанството. До 380 г. н. е., тоа станало официјална религија. Прифаќањето на христијанството ја трансформирало империјата и целата западна историја — обликувајќи го образованието, уметноста, филозофијата и правото. Кога Западната Империја паднала во 5 век, Црквата преживеала како главен институционален континуитет меѓу античкиот и средновековниот свет, зачувувајќи ја латинската писменост и пренесувајќи ја акумулираната мудрост на Рим на идните генерации.",
    ],
  },
};

  'ancient-04': {
    es: [
      'El Imperio Persa bajo Ciro el Grande alcanzó una extensión sin precedentes, dividido en 30 satrapías gobernadas por sátrapas que rendían cuentas al rey. La Carretera Real de 2.700 km permitía comunicaciones rápidas desde Susa hasta Sardes, con estaciones de relevos que entregaban mensajes en una semana.\n\nLo que distinguió a Persia fue su tolerancia religiosa notable. Ciro permitió que los judíos exiliados regresaran a Judea y reconstruyeran su templo, siendo recordado como libertador en los textos hebreos. Esta política de respeto a las culturas locales facilitó la cohesión de un imperio multiétnico enorme.',
      'El Imperio Maurya fue fundado por Chandragupta hacia 321 a.C., unificando el subcontinente indio por primera vez. Su nieto Ashoka conquistó Kalinga en una guerra brutal que mató a más de 100.000 personas; horrorizado por la violencia, se convirtió al budismo y transformó su gobierno radicalmente.\n\nAshoka grabó sus edictos en rocas y pilares por todo el imperio, promoviendo la no violencia (ahimsa), la tolerancia y el bienestar animal. Envió misioneros budistas a Asia Central, Sri Lanka y el Sudeste Asiático. India también contribuyó el concepto del cero y el sistema decimal, fundamentales para las matemáticas modernas.',
      'La Dinastía Han bajo el Emperador Wu (141-87 a.C.) consolidó China como potencia mundial. La Ruta de la Seda conectó China con Roma a través de Asia Central, transportando seda, especias, jade y vidrio en un intercambio comercial y cultural que transformó Eurasia.\n\nLos inventos chinos de este período fueron extraordinarios: el papel facilitó la administración y la difusión del conocimiento; el sismógrafo permitía detectar terremotos a distancia; el hierro fundido posibilitó herramientas y armas superiores. El servicio civil confuciano basado en exámenes meritocráticos creó una burocracia estable que perduró dos mil años.',
      'Los arios migraron al subcontinente indio hacia 1500 a.C., trayendo el sánscrito y los textos sagrados llamados Vedas. Estos himnos a dioses como Indra (guerra y tormenta), Varuna (orden cósmico) y Agni (fuego) formaron la base de la religión védica, que evolucionó hacia el hinduismo.\n\nLas Upanishads desarrollaron conceptos filosóficos profundos: el Atman (alma individual) y el Brahman (alma universal), la dharma (deber moral), el karma (ley de causa y efecto) y el samsara (ciclo de reencarnaciones). Las épicas Mahabharata y Ramayana, entre los textos más largos de la literatura mundial, transmitieron estos valores a través de narrativas heroicas y simbólicas.',
      'La era de los Reinos Combatientes (475-221 a.C.) produjo el florecimiento filosófico más rico de China. Confucio (551-479 a.C.) enseñó que la sociedad armoniosa requiere relaciones propias entre soberano y súbdito, padre e hijo, esposo y esposa; los conceptos de li (ritual/etiqueta), ren (benevolencia) y yi (rectitud) definieron la ética confuciana.\n\nLaozi fundó el taoísmo, enseñando armonía con el Dao (el Camino natural). El legalismo propugnaba gobierno estricto por ley. Qin Shi Huang utilizó el legalismo para unificar China en 221 a.C., estandarizando escritura, moneda y pesos. La Gran Muralla y los guerreros de terracota —8.000 figuras— atestiguan el poder y ambición de este primer emperador.',
    ],
    ru: [
      'Персидская империя при Кире Великом достигла небывалых размеров, разделённая на 30 сатрапий, управляемых сатрапами, подотчётными царю. Царская дорога протяжённостью 2700 км обеспечивала быстрые коммуникации от Суз до Сард — гонцы доставляли сообщения за неделю.\n\nОтличительной чертой Персии была замечательная религиозная терпимость. Кир разрешил евреям-изгнанникам вернуться в Иудею и восстановить храм, за что был прославлен в еврейских текстах как освободитель. Эта политика уважения к местным культурам способствовала сплочённости огромной многонациональной империи.',
      'Империя Маурьев была основана Чандрагуптой около 321 г. до н.э., впервые объединив индийский субконтинент. Его внук Ашока завоевал Калингу в жестокой войне, унёсшей более 100 000 жизней; потрясённый насилием, он обратился в буддизм и радикально изменил своё правление.\n\nАшока высекал свои указы на скалах и столбах по всей империи, пропагандируя ненасилие (ахимсу), терпимость и защиту животных. Он направил буддийских миссионеров в Среднюю Азию, Шри-Ланку и Юго-Восточную Азию. Индия также подарила миру концепцию нуля и десятичную систему счисления, ставшие основой современной математики.',
      'Династия Хань при императоре У (141–87 гг. до н.э.) утвердила Китай в качестве мировой державы. Великий шёлковый путь связал Китай с Римом через Центральную Азию, по нему перевозились шёлк, пряности, яшма и стекло в торговом и культурном обмене, преобразившем всю Евразию.\n\nКитайские изобретения этого периода были выдающимися: бумага облегчила управление и распространение знаний; сейсмограф позволял фиксировать землетрясения на расстоянии; чугун дал возможность создавать превосходные орудия и оружие. Конфуцианская гражданская служба, основанная на экзаменах по заслугам, создала стабильную бюрократию, просуществовавшую две тысячи лет.',
      'Арии мигрировали на индийский субконтинент около 1500 г. до н.э., принеся санскрит и священные тексты — Веды. Эти гимны богам — Индре (война и гроза), Варуне (космический порядок) и Агни (огонь) — составили основу ведической религии, эволюционировавшей в индуизм.\n\nУпанишады развили глубокие философские концепции: Атман (индивидуальная душа) и Брахман (мировая душа), дхарма (моральный долг), карма (закон причины и следствия) и сансара (цикл перерождений). Эпосы «Махабхарата» и «Рамаяна», входящие в число самых длинных произведений мировой литературы, передавали эти ценности через героические и символические повествования.',
      'Эпоха Воюющих царств (475–221 гг. до н.э.) породила богатейший философский расцвет в истории Китая. Конфуций (551–479 гг. до н.э.) учил, что гармоничное общество требует правильных отношений между государем и подданным, отцом и сыном, мужем и женой; понятия ли (ритуал/этикет), жэнь (человеколюбие) и и (справедливость) определяли конфуцианскую этику.\n\nЛаоцзы основал даосизм, проповедуя гармонию с Дао (естественным Путём). Легизм отстаивал строгое управление посредством закона. Цинь Шихуанди использовал легизм для объединения Китая в 221 г. до н.э., стандартизировав письменность, монету и меры. Великая стена и терракотовые воины — 8000 фигур — свидетельствуют о мощи и амбициях первого императора.',
    ],
    mk: [
      'Персиската Империја под Кир Велики достигна невидена големина, поделена на 30 сатрапии управувани од сатрапи кои му одговараа на кралот. Кралскиот пат од 2.700 км овозможуваше брза комуникација од Суза до Сардис — гласниците доставуваа пораки за една недела.\n\nОна што ја издвојуваше Персија беше нејзината забележителна верска толеранција. Кир им дозволи на еврејските егзиланти да се вратат во Јудеја и да го обноват храмот, па бил паметен како ослободител во еврејските текстови. Оваа политика на почит кон локалните култури ја олесни кохезијата на огромната мултиетничка империја.',
      'Царството Маурија го основа Чандрагупта околу 321 г. пр. н. е., обединувајќи го индискиот потконтинент за прв пат. Неговиот внук Ашока ја освои Калинга во жестока војна која уби повеќе од 100.000 луѓе; згрозен од насилството, се сврте кон будизмот и радикално ја трансформира својата власт.\n\nАшока ги врежа своите едикти на карпи и столбови низ целата империја, промовирајќи ненасилство (ахимса), толеранција и хуман однос кон животните. Испрати будистички мисионери во Централна Азија, Шри Ланка и Југоисточна Азија. Индија исто така го подари концептот на нулата и децималниот систем, кои се темел на современата математика.',
      'Династијата Хан под Царот У (141–87 г. пр. н. е.) ја утврди Кина како светска сила. Патот на свилата ја поврза Кина со Рим преку Централна Азија, пренесувајќи свила, зачини, јаспис и стакло во трговска и културна размена која ја трансформираше Евразија.\n\nКинеските пронајдоци од овој период беа извонредни: хартијата ја олесни управата и ширењето на знаењето; сеизмографот овозможи откривање на земјотреси на далечина; леаното железо создаде супериорни алатки и оружје. Конфучијанската државна служба заснована на испити по заслуги создаде стабилна бирократија која траеше две илјади години.',
      'Аријците мигрираа на индискиот потконтинент околу 1500 г. пр. н. е., носејќи санскрит и свети текстови наречени Веди. Овие химни на богови како Индра (војна и бура), Варуна (космички ред) и Агни (оган) ја формираа основата на ведската религија, која еволуира во хиндуизам.\n\nУпанишадите развија длабоки филозофски концепти: Атман (индивидуалната душа) и Брахман (универзалната душа), дарма (морална должност), карма (законот на причина и последица) и самсара (циклусот на преродба). Епиките Махабхарата и Рамајана, меѓу најдолгите текстови во светската литература, ги пренесуваа овие вредности преку херојски и симболички раскази.',
      'Ерата на Зараќаните кралства (475–221 г. пр. н. е.) го произведе најбогатиот филозофски процут во историјата на Кина. Конфучиј (551–479 г. пр. н. е.) учеше дека хармоничното општество бара правилни односи меѓу владетелот и поданикот, таткото и синот, сопругот и сопругата; концептите ли (ритуал/етикет), рен (добросрдечност) и ји (правичност) ја дефинираа конфучијанската етика.\n\nЛаози го основа таоизмот, учејќи хармонија со Дао (природниот Пат). Легализмот пропагираше строга власт преку закон. Цин Ши Хуанг го искористи легализмот за да ја обедини Кина во 221 г. пр. н. е., стандаризирајќи го писмото, монетата и мерките. Кинескиот ѕид и теракотните воини — 8.000 фигури — сведочат за моќта и амбицијата на првиот цар.',
    ],
  },
  'ancient-05': {
    es: [
      'El faraón ocupaba una posición única en el cosmos egipcio: era un dios viviente, encarnación de Horus el halcón celeste. Al morir, se fusionaba con Osiris, dios de los muertos, asegurando la continuidad del poder divino. Su función principal era mantener la Ma'at —orden cósmico, verdad y justicia— que sustentaba el universo.\n\nEsta concepción teológica impregnaba cada aspecto del gobierno. El faraón era el único mediador entre los dioses y los humanos, realizando rituales esenciales en los templos. La estabilidad del Nilo, las cosechas abundantes y la victoria en la guerra dependían, en la creencia popular, de la virtud del faraón.',
      'Los egipcios creían que la vida eterna requería preservar el cuerpo físico. La momificación eliminaba los órganos internos, guardados en vasos canopos, y deshidrataba el cuerpo con sal de natrón durante 40 días antes de envolverlo en lino. El ka (espíritu vital) necesitaba el cuerpo para existir en el más allá.\n\nEl Libro de los Muertos guiaba al difunto por el peligroso viaje hacia el Campo de las Cañas. El juicio más temido era ante Anubis, dios chacal, quien pesaba el corazón del muerto contra la pluma de Ma'at. Un corazón más pesado —cargado de pecados— era devorado por Ammit, el monstruo compuesto, destruyendo al alma para siempre.',
      'La Gran Pirámide de Giza, construida hacia 2560 a.C. para el faraón Keops, fue la estructura más alta del mundo durante 3.800 años. Sus 2,3 millones de bloques de piedra encajan con una precisión asombrosa: la base está nivelada con un margen de error de apenas 2,1 centímetros.\n\nLejos del mito de los esclavos, evidencia arqueológica moderna revela que las pirámides fueron construidas por trabajadores pagados: obreros permanentes y equipos rotativos de campesinos durante las inundaciones del Nilo. Los registros muestran raciones de pan, cerveza y carne. Estos trabajadores se enorgullecían de su labor, firmando sus equipos con nombres como "Amigos de Keops".',
      'El panteón egipcio era rico y complejo. Ra, el dios sol, navegaba el cielo en su barca solar durante el día y atravesaba el inframundo por la noche. Osiris fue asesinado y desmembrado por su hermano Set, pero Isis, su esposa devota, reunió los fragmentos y lo resucitó para que gobernara el reino de los muertos.\n\nEl culto de Isis se extendió eventualmente por todo el Imperio Romano, convirtiéndose en una de las religiones mistéricas más populares del mundo antiguo. Thoth, el ibis-dios, presidía la escritura, la magia y el conocimiento. Sekhmet, la diosa leona, representaba tanto la guerra devastadora como la curación de enfermedades —una dualidad que refleja la naturaleza ambivalente del poder divino.',
      'El Imperio Nuevo (1550–1070 a.C.) fue la época de mayor esplendor militar egipcio. Tutmosis III, a menudo llamado el "Napoleón de Egipto", dirigió 17 campañas militares expandiendo el dominio desde Nubia hasta Siria. Ramsés II (r. 1279–1213 a.C.) gobernó 66 años, firmó el primer tratado de paz conocido con los hititas y construyó monumentos colosales como Abu Simbel.\n\nCleopatra VII (69–30 a.C.) fue la última gobernante de la dinastía ptolemaica. Políglota que hablaba 9 idiomas, fue la primera de su dinastía en aprender egipcio. Aliada con Julio César y luego con Marco Antonio, intentó preservar la independencia egipcia frente a Roma. Su muerte en 30 a.C., según la tradición por la picadura de una serpiente, marcó el fin del Egipto faraónico.',
    ],
    ru: [
      'Фараон занимал уникальное положение в египейском космосе: он был живым богом, воплощением Хора — небесного сокола. После смерти он сливался с Осирисом, богом мёртвых, обеспечивая непрерывность божественной власти. Его главной функцией было поддержание Маат — космического порядка, истины и справедливости, — на котором держалась вселенная.\n\nЭта теологическая концепция пронизывала все аспекты управления. Фараон был единственным посредником между богами и людьми, совершавшим необходимые ритуалы в храмах. В народных верованиях разлив Нила, обильные урожаи и победа в войне зависели от добродетели фараона.',
      'Египтяне верили, что вечная жизнь требует сохранения физического тела. Мумификация предполагала извлечение внутренних органов, хранившихся в канопах, и обезвоживание тела натронной солью в течение 40 дней с последующим обматыванием льняными полосами. Ка (жизненный дух) нуждался в теле для существования в загробном мире.\n\n«Книга мёртвых» направляла покойного в опасном путешествии к Полю Тростника. Самым страшным был суд перед Анубисом, богом с головой шакала, который взвешивал сердце умершего на весах против пера Маат. Сердце потяжелее — отягощённое грехами — пожиралось Аммит, составным чудовищем, навсегда уничтожавшим душу.',
      'Великая пирамида Гизы, построенная около 2560 г. до н.э. для фараона Хуфу, была самым высоким сооружением в мире на протяжении 3800 лет. Её 2,3 миллиона каменных блоков уложены с поразительной точностью: основание выровнено с погрешностью всего 2,1 сантиметра.\n\nВопреки мифу о рабах, современные археологические данные показывают, что пирамиды строились наёмными работниками: постоянными рабочими и ротационными командами крестьян в период разлива Нила. Записи свидетельствуют о пайках хлеба, пива и мяса. Работники гордились своим трудом, давая бригадам названия вроде «Друзья Хуфу».',
      'Египетский пантеон был богат и сложен. Ра, бог солнца, плыл по небу на солнечной ладье днём и проходил через подземный мир ночью. Осирис был убит и расчленён своим братом Сетом, но Исида, его преданная жена, собрала части тела и воскресила его, чтобы он правил царством мёртвых.\n\nКульт Исиды в конечном счёте распространился по всей Римской империи, став одной из самых популярных мистических религий античного мира. Тот, ибис-бог, ведал письмом, магией и знанием. Сехмет, богиня-львица, воплощала как опустошительную войну, так и исцеление от болезней — двойственность, отражающая амбивалентную природу божественной силы.',
      'Новое царство (1550–1070 гг. до н.э.) было эпохой наивысшего военного расцвета Египта. Тутмос III, которого нередко называют «Наполеоном Египта», провёл 17 военных походов, расширив владения от Нубии до Сирии. Рамсес II (пр. 1279–1213 гг. до н.э.) правил 66 лет, подписал первый известный мирный договор с хеттами и воздвиг колоссальные памятники, такие как Абу-Симбел.\n\nКлеопатра VII (69–30 гг. до н.э.) была последней правительницей птолемеевской династии. Полиглот, говоривший на 9 языках, она была первой в своей династии, кто выучил египетский. Вступив в союз с Юлием Цезарем, а затем с Марком Антонием, она пыталась сохранить независимость Египта от Рима. Её смерть в 30 г. до н.э., по преданию от укуса змеи, ознаменовала конец фараоновского Египта.',
    ],
    mk: [
      'Фараонот заземаше уникатна позиција во египетскиот космос: тој беше жив бог, отелотворување на Хор — небесниот сокол. По смртта, се спојуваше со Озирис, богот на мртвите, осигурувајќи го континуитетот на божествената власт. Неговата главна функција беше да ја одржува Маат — космичкиот ред, вистината и правдата — кои го одржуваа универзумот.\n\nОвата теолошка концепција ја проникнуваше секоја страна на владеењето. Фараонот беше единствен посредник меѓу боговите и луѓето, извршувајќи неопходни ритуали во храмовите. Поплавата на Нил, богатите жетви и победата во војна зависеа, според народните верувања, од доблеста на фараонот.',
      'Египќаните верувале дека вечниот живот бара зачувување на физичкото тело. Мумификацијата ги отстрануваше внатрешните органи, чувани во канопски садови, и го дехидрираше телото со натронова сол 40 дена пред да се завитка во ленена ткаенина. Ка (животниот дух) имаше потреба од телото за да постои во задгробниот живот.\n\n„Книгата на мртвите" го водеше покојникот низ опасното патување кон Полето на трската. Најстрашниот суд беше пред Анубис, богот со глава на чакал, кој го мереше срцето на мртвецот на вага против пердувот на Маат. Потешко срце — натоварено со гревови — го голташе Амит, составното чудовиште, уништувајќи ја душата засекогаш.',
      'Големата Пирамида во Гиза, изградена околу 2560 г. пр. н. е. за фараонот Хуфу, беше највисоката градба во светот 3.800 години. Нејзините 2,3 милиони камени блокови се монтирани со неверојатна прецизност: основата е израмнета со маргина на грешка од само 2,1 сантиметар.\n\nНаспроти митот за робовите, современите археолошки докази открива дека пирамидите биле градени од платени работници: постојани работници и ротирачки тимови на селани за време на поплавите на Нил. Записите покажуваат оброци од леб, пиво и месо. Работниците се гордееа со трудот, именувајќи ги тимовите со имиња како „Пријатели на Хуфу".',
      'Египетскиот пантеон беше богат и сложен. Ра, богот на сонцето, пловеше по небото на сончева барка преку денот и ја поминуваше подземниот свет ноќе. Озирис беше убиен и расчленет од неговиот брат Сет, но Изида, неговата посветена сопруга, ги собра деловите и го воскресна за да владее со царството на мртвите.\n\nКултот на Изида на крајот се прошири низ целата Римска Империја, станувајќи една од најпопуларните мистични религии на античкиот свет. Тот, богот-ибис, владееше со пишувањето, магијата и знаењето. Сехмет, богињата-лавица, ги претставуваше и опустошувачката војна и лекувањето на болести — двојност која го одразува амбивалентното значење на božествената моќ.',
      'Новото Кралство (1550–1070 г. пр. н. е.) беше ерата на најголемиот воен сјај на Египет. Тутмозис III, кој честопати се нарекува „Наполеон на Египет", водеше 17 воени кампањи проширувајќи ги владенијата од Нубија до Сирија. Рамсес II (вл. 1279–1213 г. пр. н. е.) владееше 66 години, го потпиша првиот познат мировен договор со Хетите и изгради колосални споменици како Абу Симбел.\n\nКлеопатра VII (69–30 г. пр. н. е.) беше последниот владетел на птолемејската династија. Полиглот кој зборуваше 9 јазици, таа беше прва од својата династија да го научи египетскиот. Во сојуз со Јулиј Цезар, а потоа со Марко Антониј, се обиде да ја зачува независноста на Египет од Рим. Нејзината смарт во 30 г. пр. н. е., според преданието од каснување на змија, го означи крајот на фараонскиот Египет.',
    ],
  },
  'ancient-06': {
    es: [
      'Los fenicios habitaban la franja costera del actual Líbano, una tierra de montañas y mar que los impulsó hacia el comercio marítimo. Su bien más preciado era el tinte púrpura extraído del múrice, un caracol marino: producir un gramo requería miles de moluscos, haciendo el púrpura más valioso que el oro. Sus ciudades portuarias —Tiro, Sidón y Biblos— se convirtieron en centros del comercio mediterráneo.\n\nLos griegos los llamaron "Phoinikes", los Hombres Púrpura, y el color quedó para siempre asociado a la realeza y el poder. Biblos dio nombre a los libros (byblos en griego) por ser el principal centro de comercio de papiro egipcio, lo que ya revela el papel fenicio como intermediarios culturales del mundo antiguo.',
      'La contribución más duradera de los fenicios fue su alfabeto, desarrollado hacia 1050 a.C. Con solo 22 signos consonánticos —sin vocales escritas— cualquier mercader podía aprender a leer y escribir en semanas, democratizando la escritura que antes requería años de formación especializada.\n\nLos griegos adoptaron el alfabeto fenicio y añadieron vocales, creando el griego clásico. De este derivaron el latín y, a través del latín, todas las lenguas occidentales modernas. El arameo, otra lengua semítica influenciada por el fenicio, dio origen a los alfabetos hebreo, árabe y numerosos scripts del sur de Asia. Casi toda la humanidad que lee y escribe hoy utiliza un sistema derivado de ese invento fenicio.',
      'Los marineros fenicios dominaron el Mediterráneo durante siglos. Sus naves mercantes (hippos) de 30-50 toneladas transportaban vino, aceite, metales y artesanías por todo el mar interior y más allá. Llamaban a Gibraltar las "Columnas de Melqart" y navegaban hacia la costa atlántica de Europa y África.\n\nEstablecieron colonias en Chipre, Cerdeña, Malta, Sicilia y las costas de España y el norte de África. Estas fundaciones no eran conquistas militares sino factorías comerciales y fuentes de materias primas, especialmente metales preciosos de las minas de Iberia. Su red comercial prefiguró las grandes compañías mercantiles de la modernidad.',
      'La colonia más poderosa fue Cartago, fundada hacia 814 a.C. según la tradición por la reina Dido. Situada en la actual Túnez, desarrolló un sistema portuario triple con capacidad para 220 naves de guerra y controló el Mediterráneo occidental durante siglos.\n\nLa rivalidad con Roma desembocó en las tres Guerras Púnicas. Aníbal, el general cartaginés, cruzó los Alpes con elefantes en 218 a.C. y devastó Italia durante 15 años sin lograr la rendición de Roma. Finalmente Roma destruyó Cartago en 146 a.C., arrasando la ciudad y esparciendo sal sobre sus ruinas según la tradición, aunque esta imagen es probablemente legendaria.',
      'La civilización fenicia fue gradualmente absorbida por los mundos helenístico y romano, pero su legado fue imperecedero. El alfabeto que inventaron se convirtió en la herramienta universal del conocimiento humano, permitiendo registrar historia, ciencia, filosofía y literatura.\n\nSu hazaña náutica más extraordinaria fue la circunnavegación de África para el faraón Neco II hacia 600 a.C.: partiendo del Mar Rojo, bordearon el continente y regresaron por el Mediterráneo, un viaje de tres años que no sería repetido hasta Vasco da Gama en 1488. Heródoto, escéptico ante el relato, inadvertidamente lo autenticó al citar como inverosímil que "el sol quedaba a su derecha" —precisamente lo que ocurre navegando al oeste en el hemisferio sur.',
    ],
    ru: [
      'Финикийцы населяли прибрежную полосу нынешнего Ливана — землю гор и моря, толкавшую их к морской торговле. Их самым ценным товаром был пурпурный краситель, извлечённый из мурекса, морской улитки: для получения одного грамма требовались тысячи моллюсков, что делало пурпур дороже золота. Их портовые города — Тир, Сидон и Библ — стали центрами средиземноморской торговли.\n\nГреки называли их «фойники» — Пурпурные люди, и цвет навсегда остался ассоциироваться с царственностью и властью. Библ дал название книгам (byblos по-гречески), поскольку был главным центром торговли египетским папирусом, — что само по себе свидетельствует о роли финикийцев как культурных посредников древнего мира.',
      'Самым непреходящим вкладом финикийцев стал их алфавит, разработанный около 1050 г. до н.э. Всего 22 согласных знака — без записанных гласных — позволяли любому купцу научиться читать и писать за несколько недель, демократизируя письмо, прежде требовавшее многолетней специализированной подготовки.\n\nГреки заимствовали финикийский алфавит и добавили гласные, создав классический греческий. От него произошла латынь, а через неё — все современные западные языки. Арамейский язык, другой семитский язык, испытавший влияние финикийского, стал предком еврейского, арабского и многочисленных письменностей Южной Азии. Почти всё человечество, умеющее читать и писать, пользуется системой, производной от того финикийского изобретения.',
      'Финикийские мореходы господствовали в Средиземноморье на протяжении столетий. Их торговые суда (hippos) водоизмещением 30–50 тонн перевозили вино, масло, металлы и изделия ремесленников по всему внутреннему морю и далее. Гибралтар они называли «Столпами Мелькарта» и плавали вдоль атлантических берегов Европы и Африки.\n\nОни основали колонии на Кипре, Сардинии, Мальте, Сицилии и побережьях Испании и Северной Африки. Эти поселения были не военными завоеваниями, а торговыми факториями и источниками сырья, особенно драгоценных металлов из иберийских рудников. Их торговая сеть предвосхитила великие торговые компании Нового времени.',
      'Самой мощной колонией стал Карфаген, основанный около 814 г. до н.э. по преданию царицей Дидоной. Расположенный на территории нынешнего Туниса, он развил тройную систему гаваней, способных вместить 220 военных кораблей, и контролировал западное Средиземноморье на протяжении столетий.\n\nСоперничество с Римом вылилось в три Пунических войны. Карфагенский полководец Ганнибал в 218 г. до н.э. перешёл Альпы со слонами и в течение 15 лет опустошал Италию, не добившись капитуляции Рима. В конце концов Рим разрушил Карфаген в 146 г. до н.э., сровняв город с землёй.',
      'Финикийская цивилизация постепенно была поглощена эллинистическим и римским мирами, однако её наследие оказалось нетленным. Изобретённый ею алфавит стал универсальным инструментом человеческого знания, позволив записывать историю, науку, философию и литературу.\n\nИх величайшим мореходным подвигом стало огибание Африки по заданию фараона Нехо II около 600 г. до н.э.: выйдя из Красного моря, они обошли континент и вернулись через Средиземное море в трёхлетнем плавании, которое не будет повторено вплоть до Васко да Гамы в 1488 году. Геродот, скептически относившийся к этому рассказу, невольно его подтвердил, процитировав как неправдоподобное то, что «солнце было по правую руку» — именно так и происходит при плавании на запад в южном полушарии.',
    ],
    mk: [
      'Феничаните ја населуваа крајбрежната лента на денешен Либан — земја на планини и море која ги турна кон поморска трговија. Нивниот најценет производ беше пурпурната боја добиена од мурекс, морски полж: за добивање еден грам биле потребни илјадници мекотели, правејќи ја пурпурата поскапа од злато. Нивните пристанишни градови — Тир, Сидон и Библос — станаа центри на средоземноморската трговија.\n\nГрците ги нарекоа „Фоиники" — Пурпурните луѓе, и бојата засекогаш остана поврзана со кралска моќ. Библос го дaде името на книгите (byblos на грчки) бидејќи беше главниот центар на трговија со египетски папирус — факт кој сам по себе го открива феничанското значење на културни посредници на античкиот свет.',
      'Најтрајниот придонес на Феничаните беше нивната азбука, развиена околу 1050 г. пр. н. е. Со само 22 согласнички знаци — без запишани самогласки — секој трговец можеше да научи да чита и пишува за неколку недели, демократизирајќи го пишувањето кое порано барало години специјализирано обучување.\n\nГрците ја усвоија феничанската азбука и додадоа самогласки, создавајќи класичен грчки. Од него произлезе латинскиот, а преку него — сите современи западни јазици. Арамејскиот, друг семитски јазик под феничанско влијание, стана претходник на еврејската, арапската и бројните писмена на Јужна Азија. Речиси целото човештво кое денес чита и пишува користи систем изведен од тој феничански пронаоѓок.',
      'Феничанските морепловци господареа во Средоземјето со векови. Нивните трговски бродови (hippos) со носивост 30–50 тони превезуваа вино, масло, метали и занаетчиски производи низ целото внатрешно море и понатаму. Гибралтар го нарекуваа „Столбовите на Мелкарт" и пловеа по атлантските брегови на Европа и Африка.\n\nОснована колонии на Кипар, Сардинија, Малта, Сицилија и брегот на Шпанија и Северна Африка. Овие населби не беа воени освојувања туку трговски фактории и извори на суровини, особено скапоцени метали од иберијските рудници. Нивната трговска мрежа ги претходеше на големите трговски компании на модерниот свет.',
      'Најмоќната колонија беше Картагина, основана околу 814 г. пр. н. е. според преданието од кралицата Дидона. Сместена на територијата на денешен Тунис, разви тројна пристанишна система со капацитет за 220 воени бродови и го контролираше западното Средоземје со векови.\n\nРивалството со Рим прерасна во три Пунски војни. Картагинскиот генерал Ханибал ги помина Алпите со слонови во 218 г. пр. н. е. и ја пустоши Италија 15 години без да ја принуди Рим на капитулација. На крај, Рим ја уништи Картагина во 146 г. пр. н. е., срамнувајќи го градот со земја.',
      'Феничанската цивилизација постепено беше апсорбирана од хеленистичкиот и римскиот свет, но нејзиното наследство беше вечно. Азбуката што ја пронајдоа стана универзална алатка за човечкото знаење, овозможувајќи запишување на историјата, науката, филозофијата и литературата.\n\nНивниот најголем поморски подвиг беше опловувањето на Африка за фараонот Нехо II околу 600 г. пр. н. е.: тргнувајќи од Црвеното Море, го заобиколија континентот и се вратија преку Средоземјето во тригодишно патување кое нема да биде повторено сè до Васко да Гама во 1488 година. Херодот, скептичен кон ова раскажување, несвесно го автентицираше, цитирајќи како невозможно дека „сонцето им беше здесна" — токму тоа се случува при пловење кон запад во јужната хемисфера.',
    ],
  },
};
