// ─── German + French lesson metadata (all 36 lessons) ────────────────────────
// Titles, subtitles, key facts, and section headings; merged into LESSON_TRANS
// (contentTranslations.ts) at module init. Bodies live in the body catalogs.
interface LC { title: string; subtitle: string; keyFacts: string[]; sectionHeadings: string[] }
interface EC { name: string; shortName: string; dateRange: string; description: string }

export const DEFR_ERA: Record<string, { de: EC; fr: EC }> = {
  ancient: {
    de: { name: 'Antike', shortName: 'Antike', dateRange: '~3000 v. Chr. – 500 n. Chr.', description: 'Von den ersten Schriftsystemen Mesopotamiens bis zum Fall Westroms. Erkunde die Zivilisationen, die die Grundlagen von Kultur, Recht, Philosophie und Imperium legten.' },
    fr: { name: 'Monde antique', shortName: 'Antique', dateRange: '~3000 av. J.-C. – 500 ap. J.-C.', description: "Des premiers systèmes d'écriture de Mésopotamie à la chute de l'Empire romain d'Occident. Explore les civilisations qui ont posé les fondements de la culture, du droit, de la philosophie et de l'empire." },
  },
  'middle-ages': {
    de: { name: 'Mittelalter', shortName: 'Mittelalter', dateRange: '~500 – 1500 n. Chr.', description: 'Ein Jahrtausend der Ritter, Kathedralen, Seuchen und Kreuzzüge. Entdecke, wie die mittelalterliche Welt das moderne Europa, den Aufstieg des Islam und die Bewahrung antiken Wissens formte.' },
    fr: { name: 'Moyen Âge', shortName: 'Médiéval', dateRange: '~500 – 1500 ap. J.-C.', description: "Un millénaire de chevaliers, de cathédrales, de pestes et de croisades. Découvre comment le monde médiéval a façonné l'Europe moderne, l'essor de l'islam et la préservation du savoir antique." },
  },
  'early-modern': {
    de: { name: 'Frühe Neuzeit', shortName: 'Frühe Neuzeit', dateRange: '~1500 – 1800 n. Chr.', description: 'Das Zeitalter der Entdeckungen, der wissenschaftlichen Revolution und politischer Umwälzungen. Von Kolumbus bis zur Amerikanischen Revolution formte diese Ära die Welt und unser Verständnis des Universums neu.' },
    fr: { name: 'Époque moderne', shortName: 'Moderne', dateRange: '~1500 – 1800 ap. J.-C.', description: "L'ère des explorations, de la révolution scientifique et des bouleversements politiques. De Colomb à la Révolution américaine, cette époque a remodelé le monde et notre compréhension de l'univers." },
  },
  modern: {
    de: { name: 'Moderne', shortName: 'Moderne', dateRange: '~1800 – heute', description: 'Von der industriellen Revolution zum digitalen Zeitalter. Zwei Weltkriege, Entkolonialisierung, Kalter Krieg und Globalisierung verwandelten jeden Winkel der Erde.' },
    fr: { name: 'Ère contemporaine', shortName: 'Contemporain', dateRange: '~1800 – aujourd\'hui', description: "De la révolution industrielle à l'ère numérique. Deux guerres mondiales, la décolonisation, la guerre froide et la mondialisation ont transformé chaque recoin de la planète." },
  },
};

export const DEFR_LESSON: Record<string, { de: LC; fr: LC }> = {
  'ancient-01': {
    de: { title: 'Die ersten Zivilisationen', subtitle: 'Mesopotamien und Ägypten', keyFacts: ['Sumer erfand um 3100 v. Chr. die Schrift (Keilschrift)', 'Das ägyptische Alte Reich baute die Pyramiden ca. 2686–2181 v. Chr.', 'Hammurabis Kodex (ca. 1754 v. Chr.) ist einer der frühesten Rechtstexte', 'Beide Zivilisationen hingen von Flusssystemen ab'], sectionHeadings: ['Die Wiege der Zivilisation', 'Das alte Ägypten: Geschenk des Nils', 'Gesetze, Handel und Vermächtnis', 'Religion und Kosmos', 'Wissenschaft, Mathematik und Medizin'] },
    fr: { title: 'Les premières civilisations', subtitle: "La Mésopotamie et l'Égypte", keyFacts: ["Sumer inventa l'écriture (cunéiforme) vers 3100 av. J.-C.", "L'Ancien Empire égyptien bâtit les pyramides v. 2686–2181 av. J.-C.", 'Le Code de Hammurabi (v. 1754 av. J.-C.) est un des plus anciens codes de lois', 'Les deux civilisations dépendaient des fleuves pour leur agriculture'], sectionHeadings: ['Le berceau de la civilisation', "L'Égypte antique : don du Nil", 'Lois, commerce et héritage', 'Religion et cosmos', 'Science, mathématiques et médecine'] },
  },
  'ancient-02': {
    de: { title: 'Das klassische Griechenland', subtitle: 'Demokratie, Philosophie und Krieg', keyFacts: ['Athen begründete um 508 v. Chr. die erste Demokratie der Welt', 'Die Perserkriege (499–449 v. Chr.) einten die griechischen Stadtstaaten', 'Sokrates, Platon und Aristoteles begründeten die westliche Philosophie', 'Der Parthenon (432 v. Chr. vollendet) krönte Athen auf dem Höhepunkt seines goldenen Zeitalters'], sectionHeadings: ['Die griechischen Stadtstaaten', 'Krieg und Konflikt', 'Die Philosophen', 'Kunst, Architektur und Olympische Spiele', 'Das hellenistische Zeitalter: Griechenland wird global'] },
    fr: { title: 'La Grèce classique', subtitle: 'Démocratie, philosophie et guerre', keyFacts: ['Athènes établit la première démocratie du monde vers 508 av. J.-C.', 'Les guerres médiques (499–449 av. J.-C.) unirent les cités grecques', 'Socrate, Platon et Aristote fondèrent la philosophie occidentale', "Le Parthénon, achevé en 432 av. J.-C., couronna Athènes au sommet de son âge d'or"], sectionHeadings: ['Les cités-États grecques', 'Guerre et conflit', 'Les philosophes', 'Art, architecture et Jeux olympiques', "L'âge hellénistique : la Grèce devient mondiale"] },
  },
  'ancient-03': {
    de: { title: 'Römische Republik und Kaiserreich', subtitle: 'Von sieben Hügeln zur Weltherrschaft', keyFacts: ['Rom wurde um 509 v. Chr. Republik', 'Julius Cäsar wurde am 15. März 44 v. Chr. ermordet', 'Auf dem Höhepunkt umfasste das Römische Reich 5 Millionen km²', 'Westrom fiel 476 n. Chr.'], sectionHeadings: ['Die Römische Republik', 'Eroberung und die Punischen Kriege', 'Kaiserreich und Pax Romana', 'Römische Technik und Alltag', 'Der Aufstieg des Christentums'] },
    fr: { title: "La République et l'Empire romains", subtitle: 'Des sept collines à la domination du monde', keyFacts: ['Rome devint une république vers 509 av. J.-C.', 'Jules César fut assassiné le 15 mars 44 av. J.-C.', "À son apogée, l'Empire romain couvrait 5 millions de km²", "L'Empire romain d'Occident tomba en 476"], sectionHeadings: ['La République romaine', 'Conquêtes et guerres puniques', "L'Empire et la Pax Romana", 'Génie romain et vie quotidienne', "L'essor du christianisme"] },
  },
  'ancient-04': {
    de: { title: 'Der Alte Osten', subtitle: 'Persien, Indien und China', keyFacts: ['Das Achämenidenreich war das größte Reich der Antike', 'Kaiser Ashoka verbreitete buddhistische Ethik in ganz Asien', 'Die Han-Dynastie einte China und schuf die Beamtenprüfung', 'Die Seidenstraße verband China um 100 v. Chr. mit dem Mittelmeer'], sectionHeadings: ['Das Perserreich', 'Indien: Das Maurya-Reich und Ashoka', 'China und die Seidenstraße', 'Das vedische Zeitalter und die hinduistische Zivilisation', 'Chinesische Philosophie: Konfuzius, Laozi und Legalismus'] },
    fr: { title: "L'Orient antique", subtitle: "La Perse, l'Inde et la Chine", keyFacts: ["L'Empire perse achéménide fut le plus grand empire du monde antique", "L'empereur Ashoka diffusa l'éthique bouddhiste à travers l'Asie", 'La dynastie Han unifia la Chine et créa les examens mandarinaux', 'La route de la Soie reliait la Chine à la Méditerranée vers 100 av. J.-C.'], sectionHeadings: ["L'Empire perse", "L'Inde : l'Empire maurya et Ashoka", 'La Chine et la route de la Soie', "L'âge védique et la civilisation hindoue", 'Philosophie chinoise : Confucius, Laozi et le légisme'] },
  },
  'medieval-01': {
    de: { title: 'Der Fall Roms und das Frühmittelalter', subtitle: 'Vom Imperium zum feudalen Europa', keyFacts: ['Westrom fiel 476 n. Chr.', 'Karl der Große wurde 800 zum Kaiser gekrönt', 'Der Feudalismus ordnete die Gesellschaft in Herren und Leibeigene', 'Die Kirche bewahrte nach Roms Fall Schrift und Gelehrsamkeit'], sectionHeadings: ['Der Zusammenbruch Roms', 'Karl der Große und die karolingische Renaissance', 'Feudalismus und mittelalterliche Gesellschaft', 'Das Byzantinische Reich: Roms östlicher Erbe', 'Wikingerzeit und nordische Expansion'] },
    fr: { title: 'La chute de Rome et le haut Moyen Âge', subtitle: "De l'Empire à l'Europe féodale", keyFacts: ["L'Empire romain d'Occident tomba en 476", 'Charlemagne fut couronné empereur en 800', 'La féodalité organisa la société en seigneurs et serfs', "L'Église catholique préserva l'écrit et le savoir après la chute de Rome"], sectionHeadings: ['L\'effondrement de Rome', 'Charlemagne et la renaissance carolingienne', 'Féodalité et société médiévale', "L'Empire byzantin : héritier oriental de Rome", "L'âge viking et l'expansion nordique"] },
  },
  'medieval-02': {
    de: { title: 'Die Kreuzzüge und das Goldene Zeitalter des Islam', subtitle: 'Glaube, Wissen und Konflikt', keyFacts: ['Der Islam verbreitete sich binnen 100 Jahren von Arabien über Nahost und Nordafrika', 'Das Goldene Zeitalter des Islam (8.–13. Jh.) bewahrte und erweiterte die griechische Wissenschaft', 'Der Erste Kreuzzug eroberte 1099 Jerusalem', 'Die Kreuzzüge verstärkten Handel und Kulturaustausch zwischen Europa und dem Osten'], sectionHeadings: ['Der Aufstieg des Islam', 'Das Goldene Zeitalter des Islam', 'Die Kreuzzüge', 'Saladin, Rittertum und die späteren Kreuzzüge', 'Mittelalterlicher Handel und die italienischen Stadtstaaten'] },
    fr: { title: "Les croisades et l'âge d'or de l'islam", subtitle: 'Foi, savoir et conflit', keyFacts: ["L'islam s'étendit d'Arabie au Moyen-Orient et à l'Afrique du Nord en 100 ans", "L'âge d'or islamique (VIIIe–XIIIe s.) préserva et enrichit la science grecque", 'La première croisade prit Jérusalem en 1099', "Les croisades accrurent le commerce et les échanges entre l'Europe et l'Orient"], sectionHeadings: ["L'essor de l'islam", "L'âge d'or islamique", 'Les croisades', 'Saladin, la chevalerie et les croisades tardives', 'Le commerce médiéval et les cités italiennes'] },
  },
  'medieval-03': {
    de: { title: 'Der Schwarze Tod und die spätmittelalterliche Krise', subtitle: 'Pest, Aufstand und kultureller Wandel', keyFacts: ['Der Schwarze Tod tötete 30–60% der Bevölkerung Europas (1347–1353)', 'Die Pest kam aus Zentralasien über die Handelswege', 'Arbeitskräftemangel stärkte die überlebenden Bauern', 'Die Krise beschleunigte das Ende des Feudalismus und den Aufstieg der Renaissance'], sectionHeadings: ['Ursprung und Ausbreitung der Pest', 'Tod, Chaos und Widerstandskraft', 'Soziale und kulturelle Folgen', 'Der Hundertjährige Krieg (1337–1453)', 'Saatkörner der Renaissance'] },
    fr: { title: 'La Peste noire et la crise du bas Moyen Âge', subtitle: 'Peste, révoltes et mutations culturelles', keyFacts: ["La Peste noire tua 30 à 60% de la population d'Europe (1347–1353)", "La peste venue d'Asie centrale se propagea par les routes commerciales", 'La pénurie de main-d\'œuvre renforça les paysans survivants', 'La crise accéléra la fin de la féodalité et l\'essor de la Renaissance'], sectionHeadings: ['Origines et propagation de la peste', 'Mort, chaos et résilience', 'Conséquences sociales et culturelles', 'La guerre de Cent Ans (1337–1453)', 'Les germes de la Renaissance'] },
  },
  'earlymod-01': {
    de: { title: 'Renaissance und Zeitalter der Entdeckungen', subtitle: 'Wiedergeburt der Ideen, Entdeckung der Welten', keyFacts: ['Die Renaissance begann im 14. Jh. in den italienischen Stadtstaaten', 'Der Humanismus stellte den Menschen ins Zentrum des Denkens', 'Kolumbus erreichte 1492 Amerika', 'Der Kolumbische Austausch verwandelte beide Hemisphären'], sectionHeadings: ['Die italienische Renaissance', 'Humanismus und Druckerpresse', 'Das Zeitalter der Entdeckungen', 'Die Konquistadoren und Amerika', 'Die nördliche Renaissance'] },
    fr: { title: 'La Renaissance et les Grandes Découvertes', subtitle: 'Renaissance des idées, découverte des mondes', keyFacts: ['La Renaissance naquit dans les cités italiennes au XIVe siècle', "L'humanisme plaça l'homme au centre de la réflexion", 'Colomb atteignit les Amériques en 1492', "L'échange colombien transforma les deux hémisphères"], sectionHeadings: ['La Renaissance italienne', "L'humanisme et l'imprimerie", 'Les Grandes Découvertes', 'Les conquistadors et les Amériques', 'La Renaissance du Nord'] },
  },
  'earlymod-02': {
    de: { title: 'Die Reformation', subtitle: 'Religiöse Revolution und Glaubenskriege', keyFacts: ['Martin Luther schlug 1517 seine 95 Thesen an', 'Die Reformation spaltete das westliche Christentum', 'Der Dreißigjährige Krieg (1618–1648) tötete 8 Millionen Menschen', 'Der Westfälische Friede begründete das Prinzip nationaler Souveränität'], sectionHeadings: ['Krise der Kirche', 'Luther und die Reformation', 'Religionskriege und der Westfälische Friede', 'Englands Reformation: Heinrich VIII. und Elisabeth I.', 'Die katholische Gegenreformation'] },
    fr: { title: 'La Réforme protestante', subtitle: 'Révolution religieuse et guerres de religion', keyFacts: ['Martin Luther afficha ses 95 thèses en 1517', 'La Réforme divisa la chrétienté occidentale en catholiques et protestants', 'La guerre de Trente Ans (1618–1648) tua 8 millions de personnes', 'La paix de Westphalie établit le principe de souveraineté nationale'], sectionHeadings: ["La crise de l'Église", 'Luther et la Réforme', 'Guerres de religion et paix de Westphalie', "La Réforme anglaise : Henri VIII et Élisabeth Ire", 'La Contre-Réforme catholique'] },
  },
  'earlymod-03': {
    de: { title: 'Wissenschaftliche Revolution und Aufklärung', subtitle: 'Die Vernunft formt die Welt neu', keyFacts: ['Kopernikus schlug 1543 das heliozentrische Weltbild vor', 'Newtons Principia (1687) begründete die klassische Mechanik', 'Aufklärer forderten Monarchien und Kirche heraus', 'Die Amerikanische und die Französische Revolution setzten Aufklärungsideale um'], sectionHeadings: ['Der Umsturz des Kosmos', 'Newton und die neue Wissenschaft', 'Die Aufklärung', 'Die Amerikanische Revolution: Aufklärung in der Praxis', 'Vermächtnis und Grenzen der Aufklärung'] },
    fr: { title: 'Révolution scientifique et Lumières', subtitle: 'La raison refaçonne le monde', keyFacts: ["Copernic proposa l'héliocentrisme en 1543", 'Les Principia de Newton (1687) fondèrent la mécanique classique', "Les penseurs des Lumières défièrent monarchies et Église", 'Les révolutions américaine et française appliquèrent les idéaux des Lumières'], sectionHeadings: ['Renverser le cosmos', 'Newton et la nouvelle science', 'Les Lumières', 'La Révolution américaine : les Lumières en pratique', 'Héritage et limites des Lumières'] },
  },
  'modern-01': {
    de: { title: 'Die industrielle Revolution', subtitle: 'Dampf, Stahl und sozialer Wandel', keyFacts: ['Die industrielle Revolution begann um 1760 in Großbritannien', 'Dampfkraft verwandelte Fertigung, Verkehr und Landwirtschaft', 'Die Urbanisierung schuf neue Klassen — Fabrikanten und Industriearbeiter', 'Um 1900 dominierten Industrienationen den Globus'], sectionHeadings: ['Die britischen Ursprünge', 'Eisenbahnen und die schrumpfende Welt', 'Soziale Folgen', 'Die zweite industrielle Revolution: Stahl, Elektrizität, Chemie', 'Imperium, Nationalismus und die Saat des Weltkriegs'] },
    fr: { title: 'La révolution industrielle', subtitle: 'Vapeur, acier et bouleversement social', keyFacts: ['La révolution industrielle commença en Grande-Bretagne vers 1760', "La vapeur transforma l'industrie, les transports et l'agriculture", "L'urbanisation créa de nouvelles classes — patrons d'usine et ouvriers", 'Vers 1900, les nations industrielles dominaient le globe'], sectionHeadings: ['Les origines britanniques', 'Les chemins de fer et le monde qui rétrécit', 'Conséquences sociales', 'La seconde révolution industrielle : acier, électricité, chimie', 'Empire, nationalisme et germes de la guerre mondiale'] },
  },
  'modern-02': {
    de: { title: 'Die Weltkriege', subtitle: 'Das Jahrhundert des totalen Krieges', keyFacts: ['Der Erste Weltkrieg (1914–1918) tötete 20 Millionen Menschen und zerstörte vier Reiche', 'Der Versailler Vertrag (1919) legte Deutschland harte Bedingungen auf', 'Der Zweite Weltkrieg (1939–1945) war mit 70–85 Millionen Toten der tödlichste Konflikt der Geschichte', 'Der Holocaust ermordete 6 Millionen Juden und Millionen weitere'], sectionHeadings: ['Der Große Krieg', 'Der Weg in den Zweiten Weltkrieg', 'Zweiter Weltkrieg und Holocaust', 'Zwischenkriegszeit: Depression und Totalitarismus', 'Die Nachkriegsordnung: UNO, NATO und Atomzeitalter'] },
    fr: { title: 'Les guerres mondiales', subtitle: 'Le siècle de la guerre totale', keyFacts: ['La Première Guerre mondiale (1914–1918) tua 20 millions de personnes et détruisit quatre empires', 'Le traité de Versailles (1919) imposa des conditions dures à l\'Allemagne', 'La Seconde Guerre mondiale (1939–1945) fut le conflit le plus meurtrier : 70–85 millions de morts', "La Shoah assassina 6 millions de Juifs et des millions d'autres"], sectionHeadings: ['La Grande Guerre', 'La route vers la Seconde Guerre mondiale', 'La Seconde Guerre mondiale et la Shoah', "L'entre-deux-guerres : dépression et totalitarismes", "L'ordre d'après-guerre : ONU, OTAN et ère atomique"] },
  },
  'modern-03': {
    de: { title: 'Kalter Krieg und Entkolonialisierung', subtitle: 'Zwei Supermächte, eine geteilte Welt', keyFacts: ['Der Kalte Krieg (1947–1991) war ein ideologischer Kampf zwischen USA und UdSSR', 'Beide Seiten entwickelten zivilisationsvernichtende Kernwaffen', 'Dutzende afrikanische und asiatische Nationen wurden in den 1950er–70ern unabhängig', 'Die Sowjetunion zerfiel 1991'], sectionHeadings: ['Der Kalte Krieg beginnt', 'Stellvertreterkriege und Wettbewerb', 'Entkolonialisierung und der Zusammenbruch der Sowjetunion', 'Die Kubakrise: Dreizehn Tage am Abgrund', 'Entspannung, Zusammenbruch und die neue Weltordnung'] },
    fr: { title: 'Guerre froide et décolonisation', subtitle: 'Deux superpuissances, un monde divisé', keyFacts: ['La guerre froide (1947–1991) opposa idéologiquement les États-Unis et l\'URSS', 'Les deux camps développèrent des arsenaux nucléaires capables de détruire la civilisation', "Des dizaines de nations d'Afrique et d'Asie devinrent indépendantes dans les années 1950–70", "L'Union soviétique s'effondra en 1991"], sectionHeadings: ['La guerre froide commence', 'Guerres par procuration et compétition', "Décolonisation et effondrement soviétique", 'La crise des missiles de Cuba : treize jours au bord du gouffre', 'Détente, effondrement et nouvel ordre mondial'] },
  },
  'modern-04': {
    de: { title: 'Globalisierung und Gegenwart', subtitle: 'Ein Planet, viele Herausforderungen', keyFacts: ['Das World Wide Web wurde 1989 von Tim Berners-Lee erfunden', 'Der Anteil des Welthandels am BIP verdoppelte sich zwischen 1960 und 2000', 'Der 11. September 2001 veränderte Weltpolitik und Sicherheit', 'Der Klimawandel ist die prägende Umweltfrage des 21. Jahrhunderts'], sectionHeadings: ['Die digitale Revolution', 'Wirtschaftliche Globalisierung', 'Das 21. Jahrhundert', 'Chinas Aufstieg und die multipolare Welt', 'Die KI-Revolution und die nächsten Herausforderungen'] },
    fr: { title: 'La mondialisation et le monde contemporain', subtitle: 'Une planète, mille défis', keyFacts: ['Le World Wide Web fut inventé par Tim Berners-Lee en 1989', 'La part du commerce mondial dans le PIB doubla entre 1960 et 2000', 'Le 11 septembre 2001 transforma la politique et la sécurité mondiales', 'Le changement climatique est le défi environnemental du XXIe siècle'], sectionHeadings: ['La révolution numérique', 'La mondialisation économique', 'Le XXIe siècle', "L'ascension de la Chine et le monde multipolaire", "La révolution de l'IA et les défis de demain"] },
  },
  'ancient-05': {
    de: { title: 'Das alte Ägypten: Götter, Pharaonen und das Jenseits', subtitle: 'Tod, Göttlichkeit und ewige Macht', keyFacts: ['Pharaonen galten als lebende Götter — Inkarnationen des Horus', 'Die Mumifizierung wurde über 2.000 Jahre praktiziert', 'Das Totenbuch geleitete die Seelen durch die Unterwelt', 'Die Große Pyramide war 3.800 Jahre das höchste Bauwerk der Welt', 'Kleopatra VII. war die letzte aktive Pharaonin Ägyptens'], sectionHeadings: ['Der Gottkönig: Die Macht des Pharaos', 'Mumifizierung und die Reise ins Jenseits', 'Die Pyramiden: Ingenieurskunst für die Ewigkeit', 'Ägyptische Götter und das kosmische Drama', 'Das Neue Reich und Ägyptens globale Reichweite'] },
    fr: { title: "L'Égypte antique : dieux, pharaons et au-delà", subtitle: 'Mort, divinité et pouvoir éternel', keyFacts: ['Les pharaons étaient des dieux vivants — incarnations d\'Horus', 'La momification fut pratiquée plus de 2 000 ans', 'Le Livre des morts guidait les âmes dans l\'au-delà', 'La Grande Pyramide resta 3 800 ans le plus haut édifice du monde', 'Cléopâtre VII fut la dernière pharaonne active d\'Égypte'], sectionHeadings: ['Le roi-dieu : le pouvoir du pharaon', "La momification et le voyage vers l'au-delà", "Les pyramides : bâtir l'éternel", 'Les dieux égyptiens et le drame cosmique', "Le Nouvel Empire et le rayonnement de l'Égypte"] },
  },
  'ancient-06': {
    de: { title: 'Die Phönizier: Meister des Meeres', subtitle: 'Alphabet, Handel und das Purpurreich', keyFacts: ['Die Phönizier erfanden um 1050 v. Chr. das erste Alphabet', 'Karthago — um 814 v. Chr. von Tyros gegründet — wurde Roms größter Rivale', 'Phönizischer Purpur war schwerer als Gold aufzuwiegen', 'Phönizische Seeleute umsegelten um 600 v. Chr. Afrika für Pharao Necho II.', 'Das Wort „Alphabet" stammt von den ersten zwei phönizischen Buchstaben: Aleph und Beth'], sectionHeadings: ['Das Purpurvolk der Levante', 'Das Geschenk des Alphabets', 'Händler des Mittelmeers', 'Karthago: Die Tochterstadt, die ihre Mutter überflügelte', 'Das Vermächtnis eines Seefahrervolks'] },
    fr: { title: 'Les Phéniciens : maîtres de la mer', subtitle: "Alphabet, commerce et l'empire de la pourpre", keyFacts: ["Les Phéniciens inventèrent le premier alphabet vers 1050 av. J.-C.", 'Carthage — fondée par Tyr vers 814 av. J.-C. — devint la grande rivale de Rome', 'La pourpre phénicienne valait plus que son poids en or', "Des marins phéniciens firent le tour de l'Afrique pour le pharaon Néchao II vers 600 av. J.-C.", "Le mot « alphabet » vient des deux premières lettres phéniciennes : aleph et beth"], sectionHeadings: ['Le peuple pourpre du Levant', "Le don de l'alphabet", 'Marchands de la Méditerranée', 'Carthage : la fille qui dépassa sa mère', "L'héritage d'un peuple de marins"] },
  },
  'ancient-07': {
    de: { title: 'Das antike Makedonien: Alexander der Große', subtitle: 'Von Pella bis ans Ende der Welt', keyFacts: ['Philipp II. baute das Heer um die 6-Meter-Sarissa und die Hetairenreiterei um', 'Alexander wurde mit 20 König und verlor in elf Feldzugsjahren keine Schlacht', 'Die Schlacht von Gaugamela (331 v. Chr.) zerstörte das Perserreich', 'Alexander gründete über zwanzig Städte namens Alexandria', 'Sein Tod mit 32 in Babylon (323 v. Chr.) spaltete das Reich und eröffnete das hellenistische Zeitalter'], sectionHeadings: ['Das Königreich am Rand der griechischen Welt', 'Philipp II.: Der Architekt des Imperiums', 'Die Eroberung Persiens', 'Bis ans Ende der Welt', 'Tod in Babylon und das hellenistische Erbe'] },
    fr: { title: "La Macédoine antique : Alexandre le Grand", subtitle: "De Pella aux confins du monde", keyFacts: ['Philippe II rebâtit l\'armée autour de la sarisse de 6 mètres et de la cavalerie des compagnons', 'Alexandre devint roi à 20 ans et ne perdit aucune bataille en onze ans', 'La bataille de Gaugamèles (331 av. J.-C.) détruisit l\'Empire perse', "Alexandre fonda plus de vingt villes nommées Alexandrie", 'Sa mort à 32 ans à Babylone (323 av. J.-C.) divisa l\'empire et ouvrit l\'âge hellénistique'], sectionHeadings: ['Le royaume aux marges du monde grec', "Philippe II : l'architecte de l'empire", 'La conquête de la Perse', 'Jusqu\'aux confins du monde', "Mort à Babylone et héritage hellénistique"] },
  },
  'medieval-04': {
    de: { title: 'Mittelalterliche Wirtschaft: Zünfte und der Aufstieg der Städte', subtitle: 'Handel, Handwerk und die Geburt des Bürgertums', keyFacts: ['Zünfte kontrollierten Qualität und Ausbildung der Handwerke', 'Die Hanse verband im 14. Jh. über 200 Handelsstädte', 'Der Schwarze Tod (1347–1351) tötete 30–60% der Bevölkerung Europas', 'Die Messen der Champagne zogen Händler aus ganz Eurasien an', 'Die Medici-Bank erfand doppelte Buchführung und Wechselbriefe'], sectionHeadings: ['Die Wiederbelebung des Handels', 'Die Zünfte: Meister der Handwerkswirtschaft', 'Die Hanse: mittelalterliche Globalisierung', 'Der Schwarze Tod: Katastrophe und Wandel', 'Banken, Kredit und die Anfänge des Kapitalismus'] },
    fr: { title: "L'économie médiévale : guildes et essor des villes", subtitle: 'Commerce, artisanat et naissance de la bourgeoisie', keyFacts: ['Les guildes contrôlaient la qualité et la formation des métiers', 'La Hanse reliait plus de 200 villes marchandes au XIVe siècle', 'La Peste noire (1347–1351) tua 30 à 60% de la population européenne', 'Les foires de Champagne attiraient des marchands de toute l\'Eurasie', 'Les Médicis inventèrent la comptabilité en partie double et la lettre de change'], sectionHeadings: ['Le renouveau du commerce', "Les guildes : maîtres de l'économie artisanale", 'La Hanse : une mondialisation médiévale', 'La Peste noire : catastrophe et transformation', 'Banque, crédit et aube du capitalisme'] },
  },
  'medieval-05': {
    de: { title: 'Das Mongolenreich', subtitle: 'Dschingis Khan und die Pax Mongolica', keyFacts: ['Dschingis Khan einte 1206 die mongolischen Stämme', 'Das Mongolenreich wurde das größte zusammenhängende Landreich der Geschichte', 'Die Pax Mongolica ermöglichte Handel von China bis Europa', 'Die Mongolen zerstörten 1258 Bagdad und beendeten das Abbasiden-Kalifat', 'Kublai Khan gründete 1271 die Yuan-Dynastie in China'], sectionHeadings: ['Der Aufstieg Dschingis Khans', 'Die Strategie der Eroberung', 'Das Reich auf dem Höhepunkt', 'Die Pax Mongolica: Handel und Kulturaustausch', 'Vermächtnis: Zerstörung und Schöpfung'] },
    fr: { title: "L'Empire mongol", subtitle: 'Gengis Khan et la Pax Mongolica', keyFacts: ['Gengis Khan unifia les tribus mongoles en 1206', "L'Empire mongol devint le plus grand empire terrestre contigu de l'histoire", 'La Pax Mongolica facilita le commerce de la Chine à l\'Europe', 'Les Mongols détruisirent Bagdad en 1258, mettant fin au califat abbasside', 'Kubilaï Khan fonda la dynastie Yuan en Chine en 1271'], sectionHeadings: ["L'ascension de Gengis Khan", 'La stratégie de conquête', "L'empire à son apogée", 'La Pax Mongolica : commerce et échanges', 'Héritage : destruction et création'] },
  },
  'medieval-06': {
    de: { title: 'Das mittelalterliche Japan: Samurai, Shogune und Bushidō', subtitle: 'Krieger, Ehre und der Weg des Schwertes', keyFacts: ['Die Samurai entstanden im 10. Jh. als Provinzkrieger', 'Der Genpei-Krieg (1180–1185) begründete das erste Shogunat', 'Der Zen-Buddhismus prägte Kultur und Ästhetik der Samurai', 'Die Mongoleninvasionen 1274 und 1281 scheiterten auch an den „Kamikaze"-Taifunen', 'Die Sengoku-Zeit („Streitende Reiche") dauerte von 1467 bis 1615'], sectionHeadings: ['Die Geburt der Samurai', 'Der Genpei-Krieg und der Aufstieg des Shogunats', 'Zen-Buddhismus und die Samurai-Ästhetik', 'Die Mongoleninvasionen und Japans Identität', 'Die Sengoku-Zeit und die Einigung'] },
    fr: { title: 'Le Japon médiéval : samouraïs, shoguns et bushidō', subtitle: "Guerriers, honneur et voie du sabre", keyFacts: ['La classe des samouraïs émergea au Xe siècle', 'La guerre de Genpei (1180–1185) établit le premier shogunat', 'Le bouddhisme zen imprégna la culture des samouraïs', 'Les invasions mongoles de 1274 et 1281 furent repoussées grâce aux typhons « kamikaze »', 'La période Sengoku (« provinces en guerre ») dura de 1467 à 1615'], sectionHeadings: ['La naissance des samouraïs', 'La guerre de Genpei et la montée du shogunat', 'Le zen et l\'esthétique samouraï', 'Les invasions mongoles et l\'identité japonaise', 'La période Sengoku et l\'unification'] },
  },
  'medieval-07': {
    de: { title: 'Die Wikingerzeit', subtitle: 'Räuber, Händler und Siedler des Nordens', keyFacts: ['Die Wikingerzeit reicht vom Überfall auf Lindisfarne (793) bis zur Schlacht von Stamford Bridge (1066)', 'Das Langschiff mit geringem Tiefgang erlaubte Flussraub wie Ozeanfahrt', 'Schwedische Waräger gründeten die Kiewer Rus und handelten bis Bagdad', 'Nordische Siedler erreichten Island (873), Grönland (985) und Nordamerika (um 1000)', '911 erhielt der Wikingerführer Rollo die Normandie — Stammvater der Normannen'], sectionHeadings: ['Der Sturm aus dem Norden', 'Das Langschiff: Ingenieurskunst der Epoche', 'Aus Räubern werden Herrscher', 'Die östlichen Flüsse und der Weg nach Byzanz', 'Der Rand der Welt und das Ende einer Ära'] },
    fr: { title: "L'âge viking", subtitle: 'Pillards, marchands et colons du Nord', keyFacts: ["L'âge viking va du raid de Lindisfarne (793) à la bataille de Stamford Bridge (1066)", 'Le langskip à faible tirant d\'eau permettait de remonter les fleuves comme de traverser l\'océan', 'Les Varègues suédois fondèrent la Rus de Kiev et commercèrent jusqu\'à Bagdad', "Les colons nordiques atteignirent l'Islande (873), le Groenland (985) et l'Amérique du Nord (v. 1000)", 'En 911, le chef viking Rollon reçut la Normandie — ancêtre des Normands'], sectionHeadings: ['La tempête venue du Nord', "Le langskip : le génie de l'époque", 'Les pillards deviennent souverains', 'Les fleuves de l\'Est et la route de Byzance', 'Le bout du monde et la fin d\'un âge'] },
  },
  'earlymod-04': {
    de: { title: 'Das Zeitalter des Absolutismus: Ludwig XIV. und Versailles', subtitle: 'Der Sonnenkönig und der Zenit königlicher Macht', keyFacts: ['Ludwig XIV. regierte Frankreich 72 Jahre — die längste Herrschaft eines großen Monarchen', 'Das Schloss Versailles beherbergte auf dem Höhepunkt über 20.000 Menschen', '„L\'état, c\'est moi" verkörpert die absolute Monarchie', 'Ludwig XIV. widerrief 1685 das Edikt von Nantes und vertrieb die Hugenotten', 'Der Spanische Erbfolgekrieg (1701–1714) ordnete Europas Machtgefüge neu'], sectionHeadings: ['Die Theorie der absoluten Monarchie', 'Der Sonnenkönig: Ludwig XIV.', 'Versailles: Der Palast als politisches Instrument', 'Religion, Widerruf und die Hugenotten', 'Grenzen und Vermächtnis des Absolutismus'] },
    fr: { title: "L'âge de l'absolutisme : Louis XIV et Versailles", subtitle: 'Le Roi-Soleil et le zénith du pouvoir royal', keyFacts: ['Louis XIV régna 72 ans sur la France — le plus long règne d\'un grand monarque', 'Le château de Versailles logea plus de 20 000 personnes à son apogée', "« L'État, c'est moi » résume la monarchie absolue", "Louis XIV révoqua l'édit de Nantes en 1685, chassant les protestants", "La guerre de Succession d'Espagne (1701–1714) redessina l'équilibre européen"], sectionHeadings: ['La théorie de la monarchie absolue', 'Le Roi-Soleil : Louis XIV', 'Versailles : le palais comme instrument politique', 'Religion, révocation et huguenots', "Limites et héritage de l'absolutisme"] },
  },
  'earlymod-05': {
    de: { title: 'Der transatlantische Sklavenhandel', subtitle: 'Gefangenschaft, Kommerz und die atlantische Welt', keyFacts: ['Schätzungsweise 12,5 Millionen Afrikaner wurden zwischen 1500 und 1900 über den Atlantik verschleppt', 'Die Mittelpassage tötete etwa 15–20% der Versklavten', 'Die Zuckerwirtschaft der Karibik beruhte völlig auf versklavter afrikanischer Arbeit', 'Olaudah Equianos Autobiografie (1789) stärkte die britische Abolitionsbewegung', 'Großbritannien verbot den Sklavenhandel 1807, die Sklaverei 1833'], sectionHeadings: ['Ursprünge: Zucker, Profit und Arbeitskräftebedarf', 'Der Sklavenhandel im Betrieb', 'Die Mittelpassage: Grauen auf See', 'Sklaverei in den Amerikas: Leben und Widerstand', 'Abolition und Vermächtnis'] },
    fr: { title: 'La traite négrière transatlantique', subtitle: "Captivité, commerce et fabrique du monde atlantique", keyFacts: ["Environ 12,5 millions d'Africains furent déportés à travers l'Atlantique entre 1500 et 1900", 'Le passage du milieu tua environ 15 à 20% des captifs', "L'économie sucrière des Caraïbes reposait entièrement sur le travail des esclaves africains", "L'autobiographie d'Olaudah Equiano (1789) nourrit le mouvement abolitionniste britannique", "La Grande-Bretagne abolit la traite en 1807, l'esclavage en 1833"], sectionHeadings: ['Origines : sucre, profit et demande de main-d\'œuvre', 'La traite en fonctionnement', 'Le passage du milieu : l\'horreur en mer', "L'esclavage dans les Amériques : vie et résistance", 'Abolition et héritage'] },
  },
  'earlymod-06': {
    de: { title: 'Das Osmanische Reich: Süleyman der Prächtige', subtitle: 'Islam, Recht und der Zenit osmanischer Macht', keyFacts: ['Das Osmanische Reich beherrschte drei Kontinente und 15–25 Millionen Menschen', 'Süleyman I. regierte 46 Jahre (1520–1566) — die längste osmanische Herrschaft', 'Die Belagerung Wiens 1529 markierte die westlichste Ausdehnung', 'Süleyman kodifizierte das osmanische Recht (kanun) — „der Gesetzgeber"', 'Die Seeschlacht von Lepanto (1571) war die erste große osmanische Niederlage zur See'], sectionHeadings: ['Der Aufstieg des osmanischen Staates', 'Süleyman der Prächtige: Der Gesetzgeber', 'Feldzüge und die Grenzen des Reiches', 'Osmanische Gesellschaft: Ein multireligiöses Reich', 'Osmanische Kultur und Vermächtnis'] },
    fr: { title: "L'Empire ottoman : Soliman le Magnifique", subtitle: "Islam, droit et zénith de la puissance ottomane", keyFacts: ["À son apogée, l'Empire ottoman contrôlait trois continents et 15 à 25 millions de personnes", 'Soliman Ier régna 46 ans (1520–1566), le plus long règne ottoman', 'Le siège de Vienne en 1529 marqua l\'extension maximale vers l\'ouest', 'Soliman codifia le droit ottoman (kanun) — « le Législateur »', 'La bataille de Lépante (1571) fut la première grande défaite navale ottomane'], sectionHeadings: ["L'essor de l'État ottoman", 'Soliman le Magnifique : le Législateur', "Campagnes militaires et limites de l'empire", 'La société ottomane : un empire multiconfessionnel', 'Culture et héritage ottomans'] },
  },
  'earlymod-07': {
    de: { title: 'Das Zeitalter der Revolutionen', subtitle: 'Amerika, Frankreich und die Geburt der modernen Demokratie', keyFacts: ['Die amerikanische Unabhängigkeitserklärung wurde am 4. Juli 1776 unterzeichnet', 'Die Französische Revolution begann 1789 mit dem Sturm auf die Bastille', 'Die Erklärung der Menschen- und Bürgerrechte (1789) verkündete Freiheit und Gleichheit', 'Die Schreckensherrschaft (1793–94) richtete über 17.000 Menschen hin', 'Napoleon kam 1799 an die Macht und trug revolutionäre Ideale durch Europa'], sectionHeadings: ['Die Amerikanische Revolution: Aufklärung in Aktion', 'Die Unabhängigkeit erringen', 'Die Französische Revolution: Liberté, Égalité, Fraternité', 'Die Schreckensherrschaft und ihre Folgen', 'Napoleon und das revolutionäre Erbe'] },
    fr: { title: "L'ère des révolutions", subtitle: "L'Amérique, la France et la naissance de la démocratie moderne", keyFacts: ["La Déclaration d'indépendance américaine fut signée le 4 juillet 1776", 'La Révolution française commença en 1789 avec la prise de la Bastille', "La Déclaration des droits de l'homme et du citoyen (1789) proclama liberté et égalité", 'La Terreur (1793–94) exécuta plus de 17 000 personnes, dont Marie-Antoinette', 'Napoléon Bonaparte prit le pouvoir en 1799, répandant les idéaux révolutionnaires'], sectionHeadings: ['La Révolution américaine : les Lumières en action', "Gagner l'indépendance", 'La Révolution française : Liberté, Égalité, Fraternité', 'La Terreur et ses suites', 'Napoléon et l\'héritage révolutionnaire'] },
  },
  'modern-05': {
    de: { title: 'Das Zeitalter des Imperialismus und der Wettlauf um Afrika', subtitle: 'Imperium, Ausbeutung und Widerstand', keyFacts: ['1914 kontrollierten europäische Mächte 84% der Landfläche der Erde', 'Die Berliner Konferenz 1884–85 teilte Afrika ohne afrikanische Beteiligung', 'Belgiens Kongo-Freistaat tötete schätzungsweise 10 Millionen Kongolesen', 'Die Zulu schlugen die Briten 1879 bei Isandlwana', 'Äthiopien blieb durch den Sieg von Adwa (1896) unabhängig'], sectionHeadings: ['Die Triebkräfte des Imperiums', 'Der Wettlauf um Afrika', 'Das Grauen im Kongo', 'Widerstand: Afrika schlägt zurück', 'Imperiales Erbe: Die Welt, die wir erbten'] },
    fr: { title: "L'âge de l'impérialisme et la course à l'Afrique", subtitle: 'Empire, exploitation et résistance', keyFacts: ['En 1914, les puissances européennes contrôlaient 84% des terres émergées', "La conférence de Berlin (1884–85) partagea l'Afrique sans aucun Africain", "L'État indépendant du Congo de Léopold II tua environ 10 millions de Congolais", 'Les Zoulous vainquirent les Britanniques à Isandlwana en 1879', "L'Éthiopie resta indépendante en battant l'Italie à Adoua en 1896"], sectionHeadings: ["Les moteurs de l'empire", "La course à l'Afrique", "L'horreur du Congo", "Résistances : l'Afrique riposte", 'Héritage impérial : le monde dont nous héritons'] },
  },
  'modern-06': {
    de: { title: 'Die Jugoslawienkriege', subtitle: 'Nationalismus, Völkermord und der Zerfall Jugoslawiens', keyFacts: ['Jugoslawien zerfiel zwischen 1991 und 2001 gewaltsam', 'Der Bosnienkrieg (1992–1995) umfasste das Massaker von Srebrenica — Europas schlimmsten Völkermord seit dem Zweiten Weltkrieg', 'Die NATO bombardierte Serbien 1999, um den Kosovokrieg zu beenden', 'Das ICTY verfolgte die Kriegsverbrechen', 'Slobodan Milošević war das erste amtierende Staatsoberhaupt unter Kriegsverbrecheranklage'], sectionHeadings: ['Die sozialistische Föderation und ihre Bruchlinien', 'Der Zerfall beginnt: Slowenien und Kroatien', 'Bosnien: Europas blutigster Krieg seit 1945', 'Srebrenica: „Nie wieder" geschah wieder', 'Kosovo, NATO-Intervention und die Folgen'] },
    fr: { title: 'Les guerres de Yougoslavie', subtitle: "Nationalisme, génocide et effondrement de la Yougoslavie", keyFacts: ['La Yougoslavie se disloqua violemment entre 1991 et 2001', 'La guerre de Bosnie (1992–1995) inclut le massacre de Srebrenica — pire génocide européen depuis 1945', "L'OTAN bombarda la Serbie en 1999 pour arrêter la guerre du Kosovo", 'Le TPIY poursuivit les crimes de guerre', 'Slobodan Milošević fut le premier chef d\'État en exercice inculpé de crimes de guerre'], sectionHeadings: ['La fédération socialiste et ses fractures', 'La dislocation commence : Slovénie et Croatie', "La Bosnie : la guerre la plus sanglante d'Europe depuis 1945", 'Srebrenica : « plus jamais ça » est arrivé encore', "Kosovo, intervention de l'OTAN et suites"] },
  },
  'modern-07': {
    de: { title: 'Der makedonische Kampf', subtitle: 'Der Kampf einer Nation um Identität im osmanischen Niedergang', keyFacts: ['Der makedonische Kampf (1904–1908) war ein bewaffneter Konflikt griechischer, bulgarischer und serbischer Kräfte um das osmanische Makedonien', 'Die IMRO startete 1903 den gescheiterten Ilinden-Aufstand', 'Griechische Banden (Andarten) kämpften gegen bulgarische Komitadschi', 'Die jungtürkische Revolution 1908 beendete den Kampf vorläufig', 'Makedonien wurde nach den Balkankriegen (1912–1913) zwischen Griechenland, Serbien und Bulgarien geteilt'], sectionHeadings: ['Makedonien: Der von allen umkämpfte Preis', 'IMRO und der Ilinden-Aufstand', 'Der Guerillakrieg: Griechische gegen bulgarische Banden', 'Der osmanische Kontext und die jungtürkische Revolution', 'Die Balkankriege und Makedoniens Teilung'] },
    fr: { title: 'La lutte macédonienne', subtitle: "Le combat d'une nation pour son identité dans le déclin ottoman", keyFacts: ['La lutte macédonienne (1904–1908) opposa forces grecques, bulgares et serbes pour la Macédoine ottomane', "L'ORIM lança en 1903 l'insurrection manquée d'Ilinden", 'Les bandes grecques (andartes) affrontèrent les comitadjis bulgares', 'La révolution jeune-turque de 1908 suspendit la lutte', 'La Macédoine fut partagée entre Grèce, Serbie et Bulgarie après les guerres balkaniques (1912–1913)'], sectionHeadings: ['La Macédoine : le prix disputé par tous', "L'ORIM et l'insurrection d'Ilinden", 'La guérilla : bandes grecques contre bulgares', 'Le contexte ottoman et la révolution jeune-turque', 'Les guerres balkaniques et la partition'] },
  },
  'ancient-08': {
    de: { title: 'Die hellenistische Welt', subtitle: 'Nachfolgereiche und das Zeitalter Alexandrias', keyFacts: ['Alexanders Reich zersplitterte nach 323 v. Chr. unter seinen Feldherren — den Diadochen', 'Ptolemäisches Ägypten, das Seleukidenreich und Antigonidisches Makedonien beherrschten drei Kontinente', 'Die Bibliothek von Alexandria wollte jedes Buch der Welt sammeln', 'Die hellenistische Wissenschaft brachte Euklid, Archimedes und Eratosthenes hervor'], sectionHeadings: ['Die Kriege der Nachfolger', 'Alexandria: Die universale Stadt', 'Wissenschaft auf ihrem antiken Höhepunkt', 'Verschmelzung und Vermächtnis', 'Die Attaliden von Pergamon'] },
    fr: { title: 'Le monde hellénistique', subtitle: "Royaumes successeurs et l'âge d'Alexandrie", keyFacts: ["L'empire d'Alexandre se fractura entre ses généraux — les diadoques — après 323 av. J.-C.", "L'Égypte lagide, l'Empire séleucide et la Macédoine antigonide dominèrent trois continents", "La bibliothèque d'Alexandrie visait à rassembler tous les livres du monde", 'La science hellénistique produisit Euclide, Archimède et Ératosthène'], sectionHeadings: ['Les guerres des successeurs', 'Alexandrie : la cité universelle', 'La science à son apogée antique', 'Fusion et héritage', 'Les Attalides de Pergame'] },
  },
  'ancient-09': {
    de: { title: 'Das Achämenidenreich', subtitle: 'Die erste Supermacht', keyFacts: ['Auf dem Höhepunkt beherrschte Persien vielleicht 44% der Weltbevölkerung — der höchste Anteil aller Reiche', 'Kyros\' des Großen Toleranzpolitik ließ unterworfenen Völkern ihre Götter und Sitten', 'Die Königsstraße war 2.700 km lang mit Relaisstationen für königliche Kuriere', 'Zwanzig Satrapien zahlten Tribut, verzeichnet an den Wänden von Persepolis'], sectionHeadings: ['Kyros und die Idee des Imperiums', 'Dareios der Organisator', 'Persepolis und die persische Kultur', 'Zusammenstoß mit Griechenland und Fall', 'Die Unsterblichen: Anatomie eines persischen Heeres'] },
    fr: { title: "L'Empire perse achéménide", subtitle: 'La première superpuissance', keyFacts: ["À son apogée, la Perse gouvernait peut-être 44% de la population mondiale — la plus forte part de tout empire", 'La tolérance de Cyrus le Grand laissa aux peuples conquis leurs dieux et coutumes', 'La Route royale s\'étendait sur 2 700 km avec des relais pour les courriers royaux', 'Vingt satrapies payaient tribut, gravé sur les murs de Persépolis'], sectionHeadings: ["Cyrus et l'idée d'empire", "Darius l'organisateur", 'Persépolis et la culture perse', 'Le choc avec la Grèce et la chute', "Les Immortels : anatomie d'une armée perse"] },
  },
  'medieval-08': {
    de: { title: 'Al-Andalus und die Reconquista', subtitle: 'Das islamische Iberien und die christliche Rückeroberung', keyFacts: ['Tariq ibn Ziyad setzte 711 nach Iberien über; binnen eines Jahrzehnts war der Großteil der Halbinsel muslimisch', 'Córdoba war im 10. Jh. eine der größten und gelehrtesten Städte Europas', 'Die Übersetzerbewegung von Toledo trug arabische und griechische Wissenschaft ins lateinische Europa', 'Granada, der letzte muslimische Staat Iberiens, fiel 1492 an Ferdinand und Isabella'], sectionHeadings: ['Die Eroberung von 711', 'Córdoba: Zierde der Welt', 'Die lange Reconquista', '1492 und die Bedeutung von al-Andalus', 'Averroes und Maimonides: Córdobas zwei Geister'] },
    fr: { title: 'Al-Andalus et la Reconquista', subtitle: "L'Ibérie islamique et la reconquête chrétienne", keyFacts: ["Tariq ibn Ziyad passa en Ibérie en 711 ; en une décennie, l'essentiel de la péninsule était musulman", 'Cordoue au Xe siècle était une des plus grandes et savantes villes d\'Europe', "Le mouvement de traduction de Tolède porta la science arabe et grecque vers l'Europe latine", 'Grenade, dernier État musulman d\'Ibérie, tomba devant Ferdinand et Isabelle en 1492'], sectionHeadings: ['La conquête de 711', 'Cordoue : ornement du monde', 'La longue Reconquista', '1492 et le sens d\'al-Andalus', 'Averroès et Maïmonide : les deux esprits de Cordoue'] },
  },
  'medieval-09': {
    de: { title: 'Der Hundertjährige Krieg', subtitle: 'England, Frankreich und die Geburt der Nationen', keyFacts: ['Der Krieg dauerte 116 Jahre (1337–1453) über fünf Königsgenerationen', 'Englische Langbogenschützen vernichteten das französische Rittertum bei Crécy, Poitiers und Azincourt', 'Jeanne d\'Arc, eine jugendliche Bauernvisionärin, wendete 1429 bei Orléans das Blatt', 'Pulverartillerie entschied die letzten Feldzüge — und beendete das Zeitalter der Burgen'], sectionHeadings: ['Aus einem Lehnsstreit wird ein nationaler Krieg', 'Die Stunde des Langbogens', 'Jeanne d\'Arc', 'Kanonen, Sieg und Nachwirkung', 'Die Bürger von Calais'] },
    fr: { title: 'La guerre de Cent Ans', subtitle: "L'Angleterre, la France et la naissance des nations", keyFacts: ['La guerre dura 116 ans (1337–1453) sur cinq générations de rois', "Les archers anglais anéantirent la chevalerie française à Crécy, Poitiers et Azincourt", 'Jeanne d\'Arc, jeune paysanne visionnaire, renversa le cours à Orléans en 1429', "L'artillerie à poudre décida les dernières campagnes — et mit fin à l'âge des châteaux"], sectionHeadings: ["Une querelle féodale devient guerre nationale", "L'heure de l'arc long", "Jeanne d'Arc", 'Canons, victoire et suites', 'Les bourgeois de Calais'] },
  },
  'earlymod-08': {
    de: { title: 'Das Mogulreich', subtitle: 'Indiens Zeitalter der Pracht', keyFacts: ['Babur gründete das Reich 1526 mit dem Sieg bei Panipat', 'Unter Akbar regierten die Moguln vielleicht 100 Millionen Menschen mit religiöser Toleranz', 'Shah Jahans Taj Mahal ist das höchste Denkmal indo-islamischer Architektur', 'Um 1700 stellte das Mogul-Indien etwa ein Viertel der Weltproduktion her'], sectionHeadings: ['Babur und die Gründung', 'Akbar der Große', 'Das Zeitalter des Marmors: Jahangir und Shah Jahan', 'Aurangzeb und der lange Zerfall', 'Der Pfauenthron und der Preis der Pracht'] },
    fr: { title: "L'Empire moghol", subtitle: "L'âge de splendeur de l'Inde", keyFacts: ["Babur fonda l'empire en 1526 par la victoire de Pânipat", 'Sous Akbar, les Moghols gouvernèrent quelque 100 millions de personnes avec tolérance religieuse', "Le Taj Mahal de Shah Jahan est le monument suprême de l'architecture indo-islamique", "Vers 1700, l'Inde moghole produisait environ un quart des manufactures du monde"], sectionHeadings: ['Babur et la fondation', 'Akbar le Grand', "L'âge du marbre : Jahangir et Shah Jahan", 'Aurangzeb et le long délitement', 'Le trône du Paon et le prix de la splendeur'] },
  },
  'earlymod-09': {
    de: { title: 'Das Tokugawa-Japan: Das geschlossene Land', subtitle: 'Zweieinhalb Jahrhunderte Frieden', keyFacts: ['Der Sieg bei Sekigahara (1600) machte Tokugawa Ieyasu zum Herrn Japans', 'Die Sakoku-Erlasse schlossen Japan ab den 1630ern nahezu vollständig ab', 'Edo (Tokio) wurde mit über einer Million Menschen zu einer der größten Städte der Welt', 'Ukiyo-e-Holzschnitte und Kabuki-Theater blühten in der friedlichen „fließenden Welt"'], sectionHeadings: ['Sekigahara und der Tokugawa-Frieden', 'Das geschlossene Land', 'Die fließende Welt', 'Risse im Siegel', 'Die siebenundvierzig Ronin'] },
    fr: { title: 'Le Japon Tokugawa : le pays fermé', subtitle: 'Deux siècles et demi de paix', keyFacts: ['La victoire de Sekigahara (1600) fit de Tokugawa Ieyasu le maître du Japon', 'Les édits sakoku fermèrent le Japon à presque tout contact étranger dès les années 1630', 'Edo (Tokyo) devint une des plus grandes villes du monde, plus d\'un million d\'habitants', "Les estampes ukiyo-e et le théâtre kabuki fleurirent dans le « monde flottant » pacifique"], sectionHeadings: ['Sekigahara et la paix Tokugawa', 'Le pays fermé', 'Le monde flottant', 'Fissures dans le sceau', 'Les quarante-sept rônins'] },
  },
  'modern-08': {
    de: { title: 'Die Russische Revolution und das sowjetische Jahrhundert', subtitle: 'Vom Winterpalast zum Eisernen Vorhang', keyFacts: ['Zwei Revolutionen 1917: Der Februar stürzte den Zaren, der Oktober brachte die Bolschewiki an die Macht', 'Der Bürgerkrieg (1918–1922) tötete Millionen und endete mit der Gründung der UdSSR', 'Stalins Fünfjahrespläne industrialisierten die UdSSR um katastrophalen Menschenpreis', 'Das sowjetische Experiment prägte — und spaltete — das ganze 20. Jahrhundert'], sectionHeadings: ['1917: Zwei Revolutionen', 'Bürgerkrieg und die Geburt der UdSSR', 'Stalin: Stahl und Terror', 'Supermacht und Zusammenbruch', 'Tschernobyl: Die Explosion, die das System aufriss'] },
    fr: { title: 'La révolution russe et le siècle soviétique', subtitle: "Du palais d'Hiver au rideau de fer", keyFacts: ['Deux révolutions en 1917 : Février renversa le tsar, Octobre porta les bolcheviks au pouvoir', "La guerre civile (1918–1922) tua des millions et s'acheva par la fondation de l'URSS", "Les plans quinquennaux de Staline industrialisèrent l'URSS à un coût humain catastrophique", "L'expérience soviétique façonna — et divisa — tout le XXe siècle"], sectionHeadings: ['1917 : deux révolutions', "Guerre civile et naissance de l'URSS", 'Staline : acier et terreur', 'Superpuissance et effondrement', "Tchernobyl : l'explosion qui fissura le système"] },
  },
  'modern-09': {
    de: { title: 'Gandhi und die Unabhängigkeit Indiens', subtitle: 'Gewaltlosigkeit, Freiheit und Teilung', keyFacts: ['Gandhis Satyagraha machte gewaltlosen Massenwiderstand zur weltverändernden politischen Waffe', 'Der Salzmarsch 1930 verwandelte eine Salzsteuer in eine Anklage gegen das Imperium', 'Die Unabhängigkeit kam um Mitternacht am 15. August 1947 — mit der Teilung des Subkontinents', 'Die Teilung vertrieb etwa 14 Millionen Menschen; Indien wurde die größte Demokratie der Welt'], sectionHeadings: ['Das Juwel in der Krone', 'Satyagraha: Die Kraft der Wahrheit', '„Quit India" und der Sprung zur Freiheit', 'Mitternachtsfreiheit, Mitternachtswunde', 'Ambedkar und die längste Verfassung der Welt'] },
    fr: { title: "Gandhi et l'indépendance de l'Inde", subtitle: 'Non-violence, liberté et Partition', keyFacts: ['La satyagraha de Gandhi fit de la résistance non violente de masse une arme politique décisive', "La marche du sel de 1930 transforma une taxe sur le sel en réquisitoire contre l'empire", "L'indépendance vint à minuit le 15 août 1947 — avec la partition du sous-continent", 'La Partition déplaça quelque 14 millions de personnes ; l\'Inde devint la plus grande démocratie du monde'], sectionHeadings: ['Le joyau de la couronne', 'Satyagraha : la force de la vérité', '« Quit India » et la course à la liberté', 'Liberté de minuit, blessure de minuit', "Ambedkar et la plus longue constitution du monde"] },
  },
};
