import type { Language } from './translations';
type ContentLang = Exclude<Language, 'en'>;

export const ANCIENT_MEDIEVAL_BODY_TRANS: Record<string, Partial<Record<ContentLang, string[]>>> = {
  'ancient-01': {
    es: [
      "Alrededor del 3500 a. C., los sumerios del sur de Mesopotamia —la tierra entre los ríos Tigris y Éufrates en el actual Irak— construyeron las primeras ciudades del mundo. Uruk, la más grande, pudo haber albergado a 50 000 personas. Para gestionar los excedentes de grano y las cuentas de los templos, los escribas sumerios inventaron la escritura cuneiforme alrededor del 3100 a. C., presionando marcas en forma de cuña sobre tablillas de arcilla.\n\nEste sistema de escritura se extendió por todo el Oriente Próximo y se convirtió en el guión dominante durante más de 3000 años. Las ciudades-estado mesopotámicas también desarrollaron herramientas de bronce, la rueda y sofisticados canales de riego que transformaron el desierto en tierras de cultivo.",
      "La civilización egipcia surgió a lo largo del Nilo aproximadamente al mismo tiempo que Súmer. La inundación anual del Nilo depositaba rico limo, convirtiendo a Egipto en una de las regiones más fértiles del mundo antiguo. Unificado bajo el faraón Narmer alrededor del 3100 a. C., Egipto desarrolló un sólido Estado centralizado gobernado por reyes-dioses.\n\nDurante el Imperio Antiguo (c. 2686–2181 a. C.), los faraones ordenaron la construcción de las grandes pirámides de Giza —hazañas de ingeniería que siguen siendo asombrosas hoy en día—. Los jeroglíficos egipcios, las matemáticas y la medicina se encontraban entre los más avanzados del mundo antiguo.",
      "El rey babilónico Hammurabi (r. 1792–1750 a. C.) unificó Mesopotamia y promulgó uno de los primeros códigos legales escritos del mundo. El Código de Hammurabi estableció castigos para los crímenes y reguló el comercio, reflejando una sociedad construida sobre el intercambio y el orden jurídico.\n\nTanto Egipto como Mesopotamia mantuvieron extensas redes comerciales. El oro y el grano egipcios fluían hacia el Levante; los mercaderes mesopotámicos comerciaban con el Valle del Indo. Estas primeras civilizaciones establecieron el modelo para el gobierno organizado, la religión, la agricultura y la vida urbana sobre el que todas las sociedades posteriores se construirían.",
      "La religión era inseparable del poder político en ambas civilizaciones. Los sumerios veneraban a un panteón de dioses que controlaban las fuerzas naturales —tormentas, inundaciones, fertilidad— y construyeron imponentes zigurats como templos para honrarlos. Los sacerdotes ejercían una enorme influencia, administrando las tierras de los templos y supervisando vastos almacenes de grano. La deidad más importante, Enlil, era considerada el rey de los dioses cuyo favor determinaba el destino de una ciudad.\n\nLa religión egipcia se centraba en la vida después de la muerte y el orden cósmico (Ma'at). Los faraones eran considerados dioses vivientes —manifestaciones de Horus en vida y de Osiris en la muerte—. El elaborado proceso de momificación y la construcción de tumbas piramidales tenían como objetivo preservar el cuerpo del faraón para la vida eterna. Estos sistemas religiosos daban sentido a las personas, legitimaban la autoridad política e impulsaban logros arquitectónicos de una ambición asombrosa.",
      "Bajo su visión del mundo religiosa, los eruditos mesopotámicos y egipcios lograron avances prácticos asombrosos. Los matemáticos babilónicos desarrollaron un sistema numérico de base 60 —el origen de nuestra hora de 60 minutos y el círculo de 360 grados—. Resolvieron ecuaciones cuadráticas y siguieron los movimientos planetarios durante siglos con una precisión meticulosa.\n\nLa medicina egipcia era igualmente impresionante. El Papiro Edwin Smith (c. 1600 a. C.) describe tratamientos quirúrgicos con observación clínica, reconociendo que las lesiones cerebrales causan parálisis específicas. Los médicos egipcios comprendían la anatomía gracias a la momificación y desarrollaron tratamientos para huesos rotos e infecciones. Este conjunto de conocimientos prácticos, aunque mezclado con remedios mágicos, sentó las bases para la medicina griega posterior y, en última instancia, para la ciencia moderna.",
    ],
    ru: [
      "Около 3500 г. до н. э. шумеры южной Месопотамии — земли между реками Тигр и Евфрат на территории современного Ирака — построили первые в мире города. Урук, крупнейший из них, мог насчитывать до 50 000 жителей. Для управления запасами зерна и храмовыми счетами шумерские писцы около 3100 г. до н. э. изобрели клинописное письмо, выдавливая клинообразные знаки на глиняных табличках.\n\nЭта система письма распространилась по всему Ближнему Востоку и оставалась господствующей письменностью на протяжении более 3000 лет. Месопотамские города-государства также разработали бронзовые орудия труда, колесо и сложные ирригационные каналы, превратившие пустыню в плодородные угодья.",
      "Египетская цивилизация возникла вдоль Нила примерно в то же время, что и шумерская. Ежегодные разливы Нила откладывали богатый ил, делая Египет одним из наиболее плодородных регионов древнего мира. Объединённый фараоном Нармером около 3100 г. до н. э., Египет выстроил сильное централизованное государство, которым правили цари-боги.\n\nВ эпоху Древнего царства (ок. 2686–2181 гг. до н. э.) фараоны повелели возвести великие пирамиды в Гизе — инженерные свершения, которые по сей день вызывают изумление. Египетские иероглифы, математика и медицина были в числе наиболее развитых в древнем мире.",
      "Вавилонский царь Хаммурапи (правл. 1792–1750 гг. до н. э.) объединил Месопотамию и издал один из древнейших письменных сводов законов. Кодекс Хаммурапи устанавливал наказания за преступления и регулировал торговлю, отражая общество, построенное на обмене и правовом порядке.\n\nИ Египет, и Месопотамия поддерживали обширные торговые сети. Египетские золото и зерно поступали на Левант; месопотамские купцы торговали с долиной Инда. Эти ранние цивилизации заложили образец организованного управления, религии, сельского хозяйства и городской жизни, на котором строились все последующие общества.",
      "Религия была неотделима от политической власти в обеих цивилизациях. Шумеры почитали пантеон богов, управлявших силами природы — бурями, наводнениями, плодородием, — и воздвигали величественные зиккураты как храмы в их честь. Жрецы обладали огромным влиянием, управляя храмовыми землями и надзирая за обширными зернохранилищами. Главное божество, Энлиль, почиталось как царь богов, чья благосклонность определяла судьбу города.\n\nЕгипетская религия сосредотачивалась на загробной жизни и космическом порядке (Маат). Фараоны считались живыми богами — воплощением Гора при жизни и Осириса после смерти. Сложный процесс мумификации и строительство пирамид-гробниц были призваны сохранить тело фараона для вечной жизни. Эти религиозные системы придавали людям смысл, легитимизировали политическую власть и вдохновляли на архитектурные свершения поразительного масштаба.",
      "За религиозным мировоззрением месопотамские и египетские учёные совершали поразительные практические открытия. Вавилонские математики разработали шестидесятеричную систему счисления — источник нашего шестидесятиминутного часа и трёхсот шестидесяти градусов окружности. Они решали квадратные уравнения и на протяжении столетий с тщательной точностью отслеживали движения планет.\n\nЕгипетская медицина была не менее впечатляющей. Папирус Эдвина Смита (ок. 1600 г. до н. э.) описывает хирургические методы лечения с клиническими наблюдениями, фиксируя, что травмы мозга вызывают определённые виды паралича. Египетские врачи понимали анатомию через мумификацию и разрабатывали методы лечения переломов и инфекций. Этот массив практических знаний, хотя и переплетённый с магическими средствами, заложил основу для последующей греческой медицины и в конечном счёте для современной науки.",
    ],
    mk: [
      "Околу 3500 г. пр. н. е., Сумерите од јужна Месопотамија — земјата меѓу реките Тигар и Еуфрат на просторот на денешен Ирак — ги изградиле првите градови на светот. Урук, најголемиот, можеби имал 50 000 жители. За да управуваат со вишоците жито и сметките на храмовите, сумерските писари ја измислиле клинестата писменост околу 3100 г. пр. н. е., притискајќи клинести знаци во глинени плочки.\n\nОвој систем на пишување се проширил низ Блискиот Исток и станал доминантна писменост повеќе од 3000 години. Месопотамските градови-држави развиле и бронзени алатки, тркалото и сложени канали за наводнување кои ја претвориле пустината во обработлива земја.",
      "Египетската цивилизација се pojавила долж Нил приближно во исто време кога и Сумер. Годишното поплавување на Нил таложело богат тиња, правејќи го Египет еден од најплодните региони на античкиот свет. Обединет под фараонот Нармер околу 3100 г. пр. н. е., Египет развил силна централизирана држава со владетели-богови.\n\nЗа време на Старото Кралство (ок. 2686–2181 г. пр. н. е.), фараоните наредиле изградба на големите пирамиди во Гиза — инженерски достигнувања кои и денес будат восхит. Египетските хиероглифи, математиката и медицината биле меѓу најнапредните во античкиот свет.",
      "Вавилонскиот крал Хамураби (вл. 1792–1750 г. пр. н. е.) ја обединил Месопотамија и издал еден од најраните писмени правни кодекси на светот. Законикот на Хамураби утврдил казни за злосторства и ја регулирал трговијата, одразувајќи општество изградено врз размена и правен поредок.\n\nИ Египет и Месопотамија одржувале широки трговски мрежи. Египетското злато и жито текло кон Левантот; месопотамските трговци тргувале со Долината на Инд. Овие рани цивилизации го поставиле образецот за организирана власт, религија, земјоделство и градски живот врз кој ќе се надградуваат сите подоцнежни општества.",
      "Религијата беше неодвоива од политичката власт во двете цивилизации. Сумерите се клањале на пантеон богови кои ги контролирале природните сили — бури, поплави, плодност — и градиле импозантни зигурати како храмови за да ги почитуваат. Свештениците имале огромно влијание, управувајќи со храмовните земји и надгледувајќи огромни складишта за жито. Најважното божество, Енлил, бил сметан за крал на боговите чија наклоност ја одредувала судбината на еден град.\n\nЕгипетската религија се фокусирала на задгробниот живот и космичкиот поредок (Ма'ат). Фараоните биле сметани за живи богови — манифестации на Хор во животот и на Озирис во смртта. Сложениот процес на мумифицирање и изградбата на пирамидални гробници имале за цел да го зачуваат телото на фараонот за вечен живот. Овие религиозни системи им давале смисла на луѓето, ја легитимизирале политичката власт и поттикнувале архитектонски достигнувања со изненадувачка амбиција.",
      "Под нивниот религиски поглед на светот, месопотамските и египетските учени правеле неверојатни практични напредоци. Вавилонските математичари развиле бројна систем со основа 60 — изворот на нашиот час од 60 минути и кругот од 360 степени. Решавале квадратни равенки и со педантна прецизност ги следеле движењата на планетите во текот на векови.\n\nЕгипетската медицина беше исто толку впечатлива. Папирусот Едвин Смит (ок. 1600 г. пр. н. е.) опишува хируршки третмани со клиничко набљудување, препознавајќи дека повредите на мозокот предизвикуваат специфична парализа. Египетските лекари ја разбирале анатомијата преку мумифицирање и развиле третмани за скршени коски и инфекции. Овој збир на практично знаење, иако измешан со магични лекови, ги поставил темелите за подоцнежната грчка медицина и, во крајна линија, за модерната наука.",
    ],
  },
  'ancient-02': {
    es: [
      "La antigua Grecia no era una nación unificada, sino una colección de ciudades-estado independientes (poleis), cada una con su propio gobierno y cultura. Atenas y Esparta eran las más poderosas. Esparta desarrolló una sociedad militarista; cada ciudadano varón se entrenaba como soldado desde los siete años. Atenas, por el contrario, se convirtió en un centro del arte, la filosofía y la innovación política.\n\nHacia el 508 a. C., el reformador ateniense Clístenes introdujo la demokratia —el gobierno del pueblo—, el primer gobierno democrático del mundo. Los ciudadanos (varones adultos libres) votaban directamente sobre leyes y políticas en la Asamblea, una idea revolucionaria que influiría en todas las democracias futuras.",
      "Cuando el Imperio Persa invadió Grecia en el 490 a. C., los atenienses los derrotaron en Maratón. Una segunda invasión persa en el 480 a. C. fue testigo de la legendaria resistencia espartana en las Termópilas antes de que los atenienses destruyeran la flota persa en Salamina.\n\nLa victoria sobre Persia llevó a Atenas a la cima de su poder. El líder ateniense Pericles utilizó el dinero de los tributos para construir el Partenón en la Acrópolis, una obra maestra de la arquitectura clásica. Pero la rivalidad entre Atenas y Esparta estalló en la devastadora Guerra del Peloponeso (431–404 a. C.), que agotó a ambas potencias.",
      "La Atenas clásica produjo algunos de los más grandes pensadores de la historia. Sócrates enseñaba mediante el cuestionamiento, desafiando a los atenienses a examinar sus creencias. Su método —el método socrático— sigue siendo fundamental en la educación hoy en día. Sócrates fue condenado a muerte en el 399 a. C. por 'corromper a la juventud'.\n\nSu discípulo Platón escribió diálogos que exploraban la justicia, la belleza y el Estado ideal. El alumno de Platón, Aristóteles, sistematizó la lógica, la biología, la ética y la política, y fue tutor del joven Alejandro de Macedonia. Alejandro Magno (r. 336–323 a. C.) conquistó un imperio que se extendía desde Grecia hasta Egipto e India, difundiendo la lengua y la cultura griegas —el helenismo— por todo el mundo antiguo.",
      "El arte y la arquitectura griegos reflejaban una búsqueda de la belleza y la proporción ideales. El Partenón en la Acrópolis de Atenas —construido entre el 447 y el 432 a. C. bajo la supervisión del escultor Fidias— ejemplifica esta búsqueda. Sus columnas se abomban sutilmente en el centro para corregir ilusiones ópticas, creando la impresión de perfecta rectitud. Escultores griegos como Mirón y Praxíteles representaron el cuerpo humano en poses idealizadas y naturalistas, superando con creces la rígida frontalidad de los estilos artísticos anteriores.\n\nLos Juegos Olímpicos, fundados en el 776 a. C. en Olimpia en honor a Zeus, reunían a atletas de todo el mundo griego cada cuatro años. Durante los juegos, las guerras se suspendían bajo una tregua sagrada. Las pruebas incluían carreras, lucha, lanzamiento de disco, carreras de carros y el pentatlón. Los vencedores olímpicos ganaban únicamente una corona de olivo —pero eran celebrados como héroes en sus ciudades de origen e inmortalizados en odas de victoria por poetas como Píndaro—. Los Juegos encarnaban el ideal griego de areté: excelencia, virtud y afán de superación.",
      "Las conquistas de Alejandro Magno difundieron la lengua, la cultura y las instituciones griegas por una vasta franja del mundo antiguo —desde Egipto hasta Bactriana (el actual Afganistán)—. Este mundo 'helenístico' albergó magníficas ciudades: Alejandría en Egipto, con su legendaria Biblioteca que guardaba quizás 500 000 rollos; Antioquía en Siria; Pérgamo en Anatolia. Estos cosmopolitas centros fusionaron las tradiciones griega, persa, egipcia e india.\n\nLos eruditos helenísticos lograron espectaculares avances. Eratóstenes calculó la circunferencia de la Tierra con notable exactitud usando sombras y geometría. Euclides sistematizó la geometría; Arquímedes calculó el número pi y descubrió los principios de la flotabilidad y la palanca. Aristarco incluso propuso que la Tierra orbitaba alrededor del Sol —diecisiete siglos antes que Copérnico—. Cuando Roma absorbió finalmente los reinos helenísticos, preservó y transmitió esta herencia intelectual, convirtiendo a la Grecia clásica en la fuente de la civilización occidental.",
    ],
    ru: [
      "Древняя Греция была не единым государством, а совокупностью независимых городов-государств (полисов), каждый со своим правительством и культурой. Афины и Спарта были наиболее могущественными. Спарта создала милитаристское общество; каждый гражданин мужского пола обучался военному делу с семи лет. Афины, напротив, стали центром искусства, философии и политических новаций.\n\nОколо 508 г. до н. э. афинский реформатор Клисфен ввёл демократию — власть народа — первое в мире демократическое правление. Граждане (свободные взрослые мужчины) непосредственно голосовали по законам и решениям на Народном собрании — революционная идея, повлиявшая на все будущие демократии.",
      "Когда Персидская империя вторглась в Грецию в 490 г. до н. э., афиняне разгромили её при Марафоне. Во время второго персидского вторжения в 480 г. до н. э. произошло легендарное Фермопильское сражение спартанцев, после чего афиняне уничтожили персидский флот при Саламине.\n\nПобеда над Персией вознесла Афины на вершину могущества. Афинский стратег Перикл использовал союзнические взносы для строительства Парфенона на Акрополе — шедевра классической архитектуры. Однако соперничество между Афинами и Спартой переросло в опустошительную Пелопоннесскую войну (431–404 гг. до н. э.), которая истощила обе державы.",
      "Классические Афины дали миру величайших мыслителей в истории. Сократ учил методом вопросов, побуждая афинян проверять свои убеждения. Его метод — сократовский диалог — по сей день остаётся основой образования. В 399 г. до н. э. Сократ был приговорён к смерти за «развращение юношества».\n\nЕго ученик Платон писал диалоги, исследующие справедливость, красоту и идеальное государство. Ученик Платона Аристотель систематизировал логику, биологию, этику и политику и был наставником юного Александра Македонского. Александр Великий (правл. 336–323 гг. до н. э.) завоевал империю, простиравшуюся от Греции до Египта и Индии, распространяя греческий язык и культуру — эллинизм — по всему античному миру.",
      "Греческое искусство и архитектура отражали стремление к идеальной красоте и пропорции. Парфенон на афинском Акрополе — построенный между 447 и 432 гг. до н. э. под руководством скульптора Фидия — воплощает это стремление. Его колонны слегка выпуклы посередине, чтобы исправить оптические иллюзии и создать впечатление совершенной прямолинейности. Греческие скульпторы — Мирон и Пракситель — изображали человеческое тело в идеализированных, натуралистических позах, далеко превзойдя жёсткую фронтальность более ранних художественных стилей.\n\nОлимпийские игры, основанные в 776 г. до н. э. в Олимпии в честь Зевса, собирали атлетов со всего греческого мира каждые четыре года. На время игр войны прекращались по условиям священного перемирия. Состязания включали бег, борьбу, метание диска, гонки на колесницах и пятиборье. Победители Олимпийских игр получали лишь оливковый венок — однако их чтили как героев в родных городах и увековечивали в победных одах такие поэты, как Пиндар. Игры воплощали греческий идеал арете: совершенства, добродетели и стремления к победе.",
      "Завоевания Александра Великого распространили греческий язык, культуру и институты на огромные просторы античного мира — от Египта до Бактрии (современного Афганистана). В этом «эллинистическом» мире процветали великолепные города: Александрия в Египте с легендарной Библиотекой, хранившей, возможно, 500 000 свитков; Антиохия в Сирии; Пергам в Анатолии. Эти космополитические центры смешивали греческие, персидские, египетские и индийские традиции.\n\nЭллинистические учёные совершили выдающиеся открытия. Эратосфен с замечательной точностью вычислил длину окружности Земли, используя тени и геометрию. Евклид систематизировал геометрию; Архимед вычислил число пи и открыл принципы плавучести и рычага. Аристарх даже предположил, что Земля вращается вокруг Солнца — за семнадцать веков до Коперника. Когда Рим в конечном счёте поглотил эллинистические царства, он сохранил и передал это интеллектуальное наследие, сделав Классическую Грецию колыбелью западной цивилизации.",
    ],
    mk: [
      "Античка Грција не беше обединета нација, туку збир на независни градови-држави (полиси), секој со своја влада и култура. Атина и Спарта беа најмоќните. Спарта развила милитаристичко општество; секој маж-граѓанин се обучувал за војник од седумгодишна возраст. Атина, напротив, станала центар на уметноста, филозофијата и политичките иновации.\n\nОколу 508 г. пр. н. е., атинскиот реформатор Клистен ја воведол демократијата — владеење на народот — прва демократска влада на светот. Граѓаните (слободни возрасни мажи) гласале директно за законите и политиките на Собранието — револуционерна идеја која ќе влијае на сите идни демократии.",
      "Кога Персиската Империја ја нападнала Грција во 490 г. пр. н. е., Атињаните ги поразиле кај Маратон. Второто персиско освојување во 480 г. пр. н. е. го донесло легендарното спартанско држење кај Термопили, по кое Атињаните ја уништиле персиската флота кај Саламина.\n\nПобедата над Персија ја издигнала Атина на врвот на моќта. Атинскиот водач Перикле ги искористил tribутните пари за изградба на Партенонот на Акрополот — ремек-дело на класичната архитектура. Но ривалството меѓу Атина и Спарта еруптирало во опустошувачката Пелопонеска Војна (431–404 г. пр. н. е.), која ги исцрпила двете сили.",
      "Класичната Атина произвела некои од највеликите мислители во историјата. Сократ поучувал преку прашања, предизвикувајќи ги Атињаните да ги испитаат своите верувања. Неговиот метод — сократскиот метод — останува централен во образованието и денес. Сократ бил осуден на смрт во 399 г. пр. н. е. за 'расипување на младите'.\n\nНеговиот ученик Платон пишувал дијалози кои истражуваат правда, убавина и идеалната држава. Платоновиот ученик Аристотел ги систематизирал логиката, биологијата, етиката и политиката, туторирајќи го младиот Александар Македонски. Александар Велики (вл. 336–323 г. пр. н. е.) освоил империја која се протегала од Грција до Египет и Индија, ширејќи го грчкиот јазик и култура — хеленизмот — низ античкиот свет.",
      "Грчката уметност и архитектура одразувале потрага по идеална убавина и пропорција. Партенонот врз атинскиот Акропол — изграден меѓу 447 и 432 г. пр. н. е. под надзор на вајарот Фидија — го претставува ова стремење. Неговите столбови суптилно се издуваат во средината за да ги исправат оптичките илузии, создавајќи впечаток на совршена правост. Грчки вајари како Мирон и Праксител го прикажувале човечкото тело во идеализирани, натуралистички пози, далеку надминувајќи ги цврстите фронтални стилови на поранешната уметност.\n\nОлимписките Игри, основани во 776 г. пр. н. е. во Олимпија во чест на Зевс, собирале атлети од целиот грчки свет на секои четири години. За време на игрите, војните биле суспендирани под свето примирје. Натпреварите вклучувале трчање, борење, фрлање диск, трки со коли и петобој. Олимписките победници освојувале само маслинов венец — но биле прославувани како херои во нивните домашни градови и овековечувани во победнички оди од поети како Пиндар. Игрите го отелотворувале грчкиот идеал на арете: извонредност, доблест и натпреварувачко тежнење.",
      "Освојувањата на Александар Велики го ширеле грчкиот јазик, културата и институциите низ огромен дел од античкиот свет — од Египет до Бактрија (денешен Авганистан). Овој 'хеленистички' свет поддржувал величествени градови: Александрија во Египет, со легендарната Библиотека која чувала можеби 500 000 свитоци; Антиохија во Сирија; Пергамон во Анатолија. Овие космополитски центри ги мешале грчките, персиските, египетските и индиските традиции.\n\nХеленистичките учени постигнале спектакуларен напредок. Ератостен ја пресметал обиколката на Земјата со забележителна точност користејќи сенки и геометрија. Евклид ја систематизирал геометријата; Архимед го пресметал пи и ги открил принципите на лебдење и потпора. Аристарх дури предложил дека Земјата орбитира околу Сонцето — седумнаесет века пред Коперник. Кога Рим конечно ги апсорбирал хеленистичките кралства, ја зачувал и пренел оваа интелектуална наследина, правејќи ја Класичната Грција извориштето на западната цивилизација.",
    ],
  },
  'ancient-03': {
    es: [
      "Según la tradición, Roma fue fundada en el 753 a. C. sobre siete colinas junto al río Tíber. Tras expulsar a sus reyes hacia el 509 a. C., Roma se convirtió en una república gobernada por cónsules elegidos y un Senado de aristócratas. Con el tiempo, los plebeyos obtuvieron mayores derechos a través de las Doce Tablas —el primer código legal escrito de Roma—.\n\nRoma se expandió de manera constante por toda Italia, venciendo a sus rivales mediante la disciplina militar y la hábil diplomacia. En el 264 a. C., Roma controlaba la península itálica y ponía sus miras en el vasto mundo mediterráneo.",
      "El choque de Roma con Cartago produjo las tres Guerras Púnicas (264–146 a. C.). El general cartaginés Aníbal cruzó famosamente los Alpes con elefantes de guerra y devastó a los ejércitos romanos en Cannas en el 216 a. C. Sin embargo, la resiliencia romana prevaleció; Cartago fue finalmente destruida en el 146 a. C.\n\nLa conquista romana trajo gran riqueza, pero también tensión social. Generales como Mario y Sila comandaban ejércitos personales leales a ellos antes que al Senado. El genio militar de Julio César en la Galia lo convirtió en el hombre más poderoso de Roma —hasta su asesinato en los Idus de Marzo del 44 a. C.",
      "El heredero de César, Octaviano, derrotó a sus rivales y se convirtió en el primer emperador de Roma como Augusto en el 27 a. C. La era augustana inauguró la Pax Romana —dos siglos de relativa estabilidad, prosperidad y logros culturales—. La red de calzadas romanas, los acueductos y el sistema jurídico unificaron un vasto imperio desde Britania hasta Mesopotamia.\n\nEn su apogeo bajo el emperador Trajano, el Imperio Romano cubría 5 millones de kilómetros cuadrados y albergaba quizás 70 millones de personas. Pero la sobreexpansión, la tensión económica y la presión militar de las tribus germánicas debilitaron gradualmente el imperio. En el 476 d. C., el último emperador romano de Occidente fue depuesto.",
      "La civilización romana fue tanto una hazaña de ingeniería como de política. Los romanos construyeron más de 80 000 km de calzadas pavimentadas con piedra tallada. Inventaron el hormigón, que permitió la construcción de la cúpula no reforzada del Panteón —aún la mayor del mundo después de 2000 años—, vastos acueductos que transportaban agua fresca cientos de kilómetros y el Coliseo con capacidad para 80 000 espectadores.\n\nLa vida cotidiana romana era sorprendentemente reconocible. Los romanos urbanos vivían en edificios de apartamentos de varios pisos (insulae), compraban en panaderías y tabernas, visitaban los baños públicos (thermae) para socializar y asistían a combates de gladiadores y carreras de carros. El derecho romano, sistematizado en el Corpus Juris Civilis del emperador Justiniano (529 d. C.), constituye el fundamento de los sistemas jurídicos de toda Europa y América Latina hasta hoy.",
      "Durante el reinado de Augusto, un maestro judío llamado Jesús de Nazaret nació en la Judea romana. Crucificado bajo el gobernador romano Poncio Pilato hacia el 30 d. C., sus seguidores creyeron que había resucitado de entre los muertos. El cristianismo se extendió rápidamente a lo largo de las calzadas romanas, atrayendo especialmente a esclavos, mujeres y pobres con su mensaje de igualdad y redención espiritual. Para el año 300 d. C., quizás el 10 % del imperio era cristiano.\n\nEn el 313 d. C., el emperador Constantino promulgó el Edicto de Milán, legalizando el cristianismo. En el 380 d. C., era la religión oficial. La adopción del cristianismo transformó el imperio y toda la historia occidental —moldeando la educación, el arte, la filosofía y el derecho—. Cuando el Imperio de Occidente cayó en el siglo V, la Iglesia sobrevivió como la principal continuidad institucional entre el mundo antiguo y el medieval, preservando la alfabetización latina y transmitiendo la sabiduría acumulada de Roma a las generaciones futuras.",
    ],
    ru: [
      "По преданию, Рим был основан в 753 г. до н. э. на семи холмах у реки Тибр. Изгнав царей около 509 г. до н. э., Рим превратился в республику, управляемую выборными консулами и Сенатом аристократов. Со временем плебеи добились бо́льших прав благодаря Законам двенадцати таблиц — первому письменному правовому кодексу Рима.\n\nРим неуклонно расширялся по всей Италии, побеждая соперников военной дисциплиной и искусной дипломатией. К 264 г. до н. э. Рим контролировал Апеннинский полуостров и обратил взоры на широкий средиземноморский мир.",
      "Столкновение Рима с Карфагеном породило три Пунические войны (264–146 гг. до н. э.). Карфагенский полководец Ганнибал прославился переходом через Альпы с боевыми слонами и разгромом римских армий при Каннах в 216 г. до н. э. Однако стойкость Рима взяла верх: Карфаген был окончательно разрушен в 146 г. до н. э.\n\nРимские завоевания принесли огромные богатства, но и социальную напряжённость. Полководцы Марий и Сулла командовали личными армиями, преданными им, а не Сенату. Военный гений Юлия Цезаря в Галлии сделал его могущественнейшим человеком в Риме — вплоть до его убийства на мартовские иды 44 г. до н. э.",
      "Наследник Цезаря Октавиан победил своих соперников и в 27 г. до н. э. стал первым императором Рима под именем Август. Эпоха Августа открыла Pax Romana — два века относительной стабильности, процветания и культурных достижений. Римская сеть дорог, акведуки и правовая система объединили огромную империю от Британии до Месопотамии.\n\nВ зените могущества при императоре Траяне Римская империя занимала 5 миллионов квадратных километров и насчитывала, возможно, 70 миллионов жителей. Но чрезмерное расширение, экономическое истощение и военное давление германских племён постепенно ослабляли империю. В 476 г. н. э. последний западноримский император был низложен.",
      "Римская цивилизация была столь же выдающимся инженерным свершением, как и политическим. Римляне проложили более 80 000 км дорог, вымощенных тёсаным камнем. Они изобрели бетон, что позволило возвести неармированный купол Пантеона — по сей день крупнейший в мире спустя 2000 лет, — огромные акведуки, несущие пресную воду на сотни километров, и Колизей вместимостью 80 000 зрителей.\n\nПовседневная жизнь римлян была поразительно узнаваема. Городские римляне жили в многоэтажных доходных домах (инсулах), закупались в пекарнях и тавернах, посещали общественные бани (термы) для общения и ходили на гладиаторские игры и гонки на колесницах. Римское право, систематизированное в Corpus Juris Civilis императора Юстиниана (529 г. н. э.), по сей день составляет основу правовых систем по всей Европе и Латинской Америке.",
      "В правление Августа в римской Иудее родился еврейский учитель по имени Иисус из Назарета. Распятый по приказу римского наместника Понтия Пилата около 30 г. н. э., он, по убеждению его последователей, воскрес из мёртвых. Христианство стремительно распространялось вдоль римских дорог, привлекая особенно рабов, женщин и бедняков своим посланием о равенстве и духовном искуплении. К 300 г. н. э. христианами были, возможно, 10% жителей империи.\n\nВ 313 г. н. э. император Константин издал Миланский эдикт, легализовавший христианство. К 380 г. н. э. оно стало официальной религией. Принятие христианства преобразило империю и всю западную историю — определив облик образования, искусства, философии и права. Когда в V веке пала Западная империя, Церковь выжила как главный институциональный мост между античным и средневековым мирами, сохраняя латинскую грамотность и передавая накопленную мудрость Рима будущим поколениям.",
    ],
    mk: [
      "Според преданието, Рим бил основан во 753 г. пр. н. е. на седум ридови покрај реката Тибар. По протерувањето на кралевите околу 509 г. пр. н. е., Рим станал република управувана од избрани конзули и Сенат на аристократи. Со текот на времето, плебејците добиле поголеми права преку Законите на дванаесетте таблици — првиот пишан правен законик на Рим.\n\nРим се ширел постепено низ цела Италија, победувајќи ги ривалите преку воена дисциплина и вешта дипломатија. До 264 г. пр. н. е., Рим го контролирал Апенинскиот Полуостров и ги насочил своите погледи кон поширокиот медитерански свет.",
      "Судирот на Рим со Картагина ги произвел трите Пунски Војни (264–146 г. пр. н. е.). Картагинскиот генерал Ханибал прочуено ги преминал Алпите со воени слонови и ги уништил римските армии кај Кана во 216 г. пр. н. е. Но отпорноста на Рим победила; Картагина конечно била уништена во 146 г. пр. н. е.\n\nРимското освојување донело големо богатство, но и социјална напнатост. Генерали како Мариј и Сула командувале лични армии лојални на нив, а не на Сенатот. Воениот гениј на Јулиј Цезар во Галија го направил најмоќниот човек во Рим — сè до неговото убиство на Мартовските иди, 44 г. пр. н. е.",
      "Наследникот на Цезар, Октавијан, ги поразил своите ривали и станал прв римски император како Август во 27 г. пр. н. е. Августовата ера ја поставила Pax Romana — два века на релативна стабилност, просперитет и културни достигнувања. Римската мрежа на патишта, акведуктите и правниот систем обединиле огромна империја од Британија до Месопотамија.\n\nНа врвот под царот Трајан, Римската Империја зафаќала 5 милиони квадратни километри и имала можеби 70 милиони луѓе. Но претераното ширење, економскиот притисок и воениот притисок од германските племиња постепено ја ослабиле империјата. Во 476 г. н. е., последниот западноримски цар бил соборен.",
      "Римската цивилизација беше исто толку инженерска колку и политичка достигнување. Римјаните изградиле повеќе од 80 000 km патишта поплочени со обработен камен. Го измислиле бетонот, овозможувајќи изградба на неармираната купола на Пантеонот — сè уште најголема во светот по 2000 години — огромни акведукти кои носат свежа вода стотици километри и Колосеумот со капацитет од 80 000 гледачи.\n\nСекојдневниот римски живот беше изненадувачки препознатлив. Урбаните Римјани живееле во повеќекатни станбени згради (инсули), купувале во пекари и крчми, посетувале јавни бањи (терми) за да социјализираат и присуствувале на гладијаторски борби и трки со коли. Римското право, систематизирано во Corpus Juris Civilis на царот Јустинијан (529 г. н. е.), ги формира темелите на правните системи низ цела Европа и Латинска Америка до денес.",
      "Во владеењето на Август, еврејски учител по име Исус од Назарет бил роден во римска Јудеа. Распнат под римскиот управник Понтиј Пилат околу 30 г. н. е., неговите следбеници верувале дека воскреснал од мртвите. Христијанството се ширело брзо долж римските патишта, привлекувајќи особено робови, жени и сиромашни со своето послание за еднаквост и духовен откуп. До 300 г. н. е., можеби 10% од империјата биле христијани.\n\nВо 313 г. н. е., царот Константин го издал Миланскиот Едикт, легализирајќи го христијанството. До 380 г. н. е., тоа станало официјална религија. Прифаќањето на христијанството ја трансформирало империјата и целата западна историја — обликувајќи го образованието, уметноста, филозофијата и правото. Кога Западната Империја паднала во 5 век, Црквата преживеала како главен институционален континуитет меѓу античкиот и средновековниот свет, зачувувајќи ја латинската писменост и пренесувајќи ја акумулираната мудрост на Рим на идните генерации.",
    ],
  },
};
