// ─── Prehistoric Ages: full content translations (es/ru/mk/de/fr) ────────────
// Single-file catalog for the Prehistoric era: era metadata, per-lesson meta
// (title, subtitle, keyFacts, sectionHeadings), and full section bodies. Merged
// into ERA_TRANS / LESSON_TRANS / BODY_TRANS by contentTranslations.ts. Content
// falls back to English when a language/key is missing.
import type { Language } from './translations';

type ContentLang = Exclude<Language, 'en'>;
interface EraContent { name: string; shortName: string; dateRange: string; description: string; }
interface LessonContent { title: string; subtitle: string; keyFacts: string[]; sectionHeadings: string[]; }

export const PREHISTORIC_ERA_TRANS: Partial<Record<ContentLang, EraContent>> = {
  es: { name: 'Edad Prehistórica', shortName: 'Prehistoria', dateRange: '~4.000.000 – 3000 a.C.', description: 'Antes de la escritura, antes de las ciudades — la historia humana profunda. Desde los primeros homínidos bípedos y el dominio del fuego hasta los cazadores de la Edad de Hielo, los pintores de cuevas y los agricultores cuya Revolución Neolítica inventó el mundo sedentario sobre el que se construyó todo lo demás.' },
  ru: { name: 'Доисторическая эпоха', shortName: 'Доистория', dateRange: '~4 000 000 – 3000 до н.э.', description: 'До письменности, до городов — глубинная история человека. От первых прямоходящих гоминин и покорения огня до охотников ледникового периода, художников пещер и земледельцев, чья неолитическая революция создала оседлый мир, на котором построено всё последующее.' },
  mk: { name: 'Праисториско Доба', shortName: 'Праисторија', dateRange: '~4.000.000 – 3000 п.н.е.', description: 'Пред писмото, пред градовите — длабоката човечка приказна. Од првите исправени хоминини и припитомувањето на огнот до ловците од Леденото Доба, пештерските сликари и земјоделците чија Неолитска револуција го измисли населениот свет врз кој се изгради сè што следеше.' },
  de: { name: 'Urgeschichte', shortName: 'Urzeit', dateRange: '~4.000.000 – 3000 v. Chr.', description: 'Vor der Schrift, vor den Städten — die tiefe Geschichte des Menschen. Von den ersten aufrecht gehenden Homininen und der Zähmung des Feuers bis zu den Jägern der Eiszeit, den Höhlenmalern und den Bauern, deren Neolithische Revolution die sesshafte Welt schuf, auf der alles Spätere aufbaute.' },
  fr: { name: 'Âge préhistorique', shortName: 'Préhistoire', dateRange: '~4 000 000 – 3000 av. J.-C.', description: "Avant l'écriture, avant les villes — la grande histoire de l'humanité. Des premiers hominidés bipèdes et de la maîtrise du feu aux chasseurs de l'ère glaciaire, aux peintres des cavernes et aux agriculteurs dont la révolution néolithique inventa le monde sédentaire sur lequel tout le reste s'est construit." },
};

export const PREHISTORIC_LESSON_TRANS: Record<string, Partial<Record<ContentLang, LessonContent>>> = {
  'prehistoric-01': {
    es: { title: 'Los Orígenes Humanos', subtitle: 'Los primeros homínidos y el surgimiento del bipedismo', keyFacts: ['Sahelanthropus (~7 millones de años) está entre los homínidos más antiguos conocidos', '"Lucy" (Australopithecus afarensis) vivió hace ~3,2 millones de años', 'El bipedismo liberó las manos y precedió al gran cerebro', 'Las huellas de Laetoli (~3,6 m.a.) prueban la marcha erguida'], sectionHeadings: ['Fuera de los árboles', 'Lucy y los australopitecos', 'Un árbol genealógico frondoso', 'Los primeros fabricantes de herramientas', 'Leer el pasado profundo'] },
    ru: { title: 'Происхождение человека', subtitle: 'Первые гоминины и появление прямохождения', keyFacts: ['Сахелантроп (~7 млн лет назад) — один из древнейших известных гоминин', '«Люси» (Australopithecus afarensis) жила ~3,2 млн лет назад', 'Прямохождение освободило руки и предшествовало большому мозгу', 'Следы в Лаэтоли (~3,6 млн лет) доказывают прямохождение'], sectionHeadings: ['Из деревьев', 'Люси и австралопитеки', 'Ветвистое родословное древо', 'Первые изготовители орудий', 'Читая глубокое прошлое'] },
    mk: { title: 'Потеклото на Човекот', subtitle: 'Првите хоминини и подемот на двоножноста', keyFacts: ['Сахелантроп (~7 милиони години) е меѓу најстарите познати хоминини', '„Луси“ (Australopithecus afarensis) живеела пред ~3,2 милиони години', 'Двоножноста ги ослободила рацете и претходела на големиот мозок', 'Отпечатоците од Лаетоли (~3,6 м.г.) го докажуваат исправеното одење'], sectionHeadings: ['Од дрвјата', 'Луси и австралопитеците', 'Разгрането семејно стебло', 'Првите изработувачи на алат', 'Читање на длабокото минато'] },
    de: { title: 'Die Ursprünge des Menschen', subtitle: 'Die ersten Homininen und der Aufstieg des aufrechten Gangs', keyFacts: ['Sahelanthropus (~7 Millionen Jahre) zählt zu den ältesten bekannten Homininen', '„Lucy“ (Australopithecus afarensis) lebte vor ~3,2 Millionen Jahren', 'Der aufrechte Gang befreite die Hände und ging dem großen Gehirn voraus', 'Die Fußspuren von Laetoli (~3,6 Mio. J.) beweisen den aufrechten Gang'], sectionHeadings: ['Aus den Bäumen', 'Lucy und die Australopithecinen', 'Ein verzweigter Stammbaum', 'Die ersten Werkzeugmacher', 'Die tiefe Vergangenheit lesen'] },
    fr: { title: 'Les origines humaines', subtitle: "Les premiers hominidés et l'essor de la bipédie", keyFacts: ["Sahélanthrope (~7 millions d'années) figure parmi les plus anciens hominidés connus", '« Lucy » (Australopithecus afarensis) vécut il y a ~3,2 millions d\'années', 'La bipédie libéra les mains et précéda le grand cerveau', 'Les empreintes de Laetoli (~3,6 M.a.) prouvent la marche debout'], sectionHeadings: ['Hors des arbres', 'Lucy et les australopithèques', 'Un arbre généalogique buissonnant', 'Les premiers tailleurs d\'outils', 'Lire le passé profond'] },
  },
  'prehistoric-02': {
    es: { title: 'El Dominio del Fuego', subtitle: 'Homo erectus y las primeras migraciones humanas', keyFacts: ['Homo erectus apareció hace ~1,9 millones de años', 'Fue el primer homínido en salir de África', 'El uso controlado del fuego se remonta al menos a 1 millón de años', 'Cocinar pudo haber impulsado el crecimiento del cerebro humano'], sectionHeadings: ['El primer viajero', 'Domar la llama', 'El simio cocinero', 'Cuerpos forjados por el fuego', 'El largo aprendizaje'] },
    ru: { title: 'Покорение огня', subtitle: 'Homo erectus и первые миграции человека', keyFacts: ['Homo erectus появился ~1,9 млн лет назад', 'Он первым из гоминин покинул Африку', 'Управляемое использование огня насчитывает не менее 1 млн лет', 'Приготовление пищи могло дать толчок росту мозга человека'], sectionHeadings: ['Первый странник', 'Укрощение пламени', 'Обезьяна, что готовит', 'Тела, созданные огнём', 'Долгое ученичество'] },
    mk: { title: 'Совладувањето на Огнот', subtitle: 'Homo erectus и првите човечки преселби', keyFacts: ['Homo erectus се појавил пред ~1,9 милиони години', 'Тој прв од хоминините ја напуштил Африка', 'Контролираната употреба на огнот датира најмалку 1 милион години', 'Готвењето можеби го поттикнало растот на човечкиот мозок'], sectionHeadings: ['Првиот патник', 'Припитомување на пламенот', 'Мајмунот што готви', 'Тела обликувани од огнот', 'Долгото чирачество'] },
    de: { title: 'Die Beherrschung des Feuers', subtitle: 'Homo erectus und die ersten Wanderungen des Menschen', keyFacts: ['Homo erectus erschien vor ~1,9 Millionen Jahren', 'Er war der erste Hominine, der Afrika verließ', 'Der kontrollierte Gebrauch des Feuers reicht mindestens 1 Million Jahre zurück', 'Das Kochen könnte das Wachstum des menschlichen Gehirns angetrieben haben'], sectionHeadings: ['Der erste Wanderer', 'Die Flamme zähmen', 'Der kochende Affe', 'Vom Feuer geformte Körper', 'Die lange Lehrzeit'] },
    fr: { title: 'La maîtrise du feu', subtitle: 'Homo erectus et les premières migrations humaines', keyFacts: ["Homo erectus apparut il y a ~1,9 million d'années", "Il fut le premier hominidé à quitter l'Afrique", "L'usage maîtrisé du feu remonte à au moins 1 million d'années", 'La cuisson a peut-être alimenté la croissance du cerveau humain'], sectionHeadings: ['Le premier voyageur', 'Apprivoiser la flamme', 'Le singe cuisinier', 'Des corps façonnés par le feu', 'Le long apprentissage'] },
  },
  'prehistoric-03': {
    es: { title: 'Los Neandertales y la Familia Humana', subtitle: 'Primos en el frío', keyFacts: ['Los neandertales vivieron en Europa y Asia occidental hace ~400.000–40.000 años', 'Enterraban a sus muertos y cuidaban a enfermos y heridos', 'Los humanos no africanos actuales portan ~1–2 % de ADN neandertal', 'Desaparecieron hace unos 40.000 años, tras encontrarse con Homo sapiens'], sectionHeadings: ['El pueblo del hielo', 'Mentes como las nuestras', 'Denisovanos y linajes fantasma', 'El gran encuentro', 'Por qué solo quedó uno'] },
    ru: { title: 'Неандертальцы и человеческая семья', subtitle: 'Двоюродные братья в холоде', keyFacts: ['Неандертальцы жили в Европе и Западной Азии ~400 000–40 000 лет назад', 'Они хоронили мёртвых и заботились о больных и раненых', 'Современные неафриканцы несут ~1–2 % неандертальской ДНК', 'Они исчезли около 40 000 лет назад, встретившись с Homo sapiens'], sectionHeadings: ['Народ льда', 'Разум, подобный нашему', 'Денисовцы и призрачные линии', 'Великая встреча', 'Почему остался лишь один'] },
    mk: { title: 'Неандерталците и Човечкото Семејство', subtitle: 'Братучеди во студот', keyFacts: ['Неандерталците живееле низ Европа и Западна Азија пред ~400.000–40.000 години', 'Ги погребувале мртвите и се грижеле за болните и повредените', 'Современите нежители на Африка носат ~1–2 % неандерталска ДНК', 'Исчезнале пред околу 40.000 години, откако се сретнале со Homo sapiens'], sectionHeadings: ['Народот на мразот', 'Умови како нашите', 'Денисовци и духовни лози', 'Големата средба', 'Зошто остана само еден'] },
    de: { title: 'Die Neandertaler und die Menschheitsfamilie', subtitle: 'Vettern in der Kälte', keyFacts: ['Neandertaler lebten in Europa und Westasien vor ~400.000–40.000 Jahren', 'Sie bestatteten ihre Toten und pflegten Kranke und Verletzte', 'Heutige Nicht-Afrikaner tragen ~1–2 % Neandertaler-DNA', 'Sie verschwanden vor etwa 40.000 Jahren, nach der Begegnung mit dem Homo sapiens'], sectionHeadings: ['Das Volk des Eises', 'Geister wie unsere', 'Denisova-Menschen und Geisterlinien', 'Die große Begegnung', 'Warum nur einer blieb'] },
    fr: { title: 'Les Néandertaliens et la famille humaine', subtitle: 'Cousins dans le froid', keyFacts: ["Les Néandertaliens vécurent en Europe et en Asie de l'Ouest il y a ~400 000–40 000 ans", 'Ils enterraient leurs morts et soignaient malades et blessés', "Les humains non africains actuels portent ~1–2 % d'ADN néandertalien", "Ils disparurent il y a environ 40 000 ans, après avoir rencontré Homo sapiens"], sectionHeadings: ['Le peuple de la glace', 'Des esprits comme les nôtres', 'Dénisoviens et lignées fantômes', 'La grande rencontre', 'Pourquoi un seul demeura'] },
  },
  'prehistoric-04': {
    es: { title: 'El Gran Viaje Humano', subtitle: 'Homo sapiens puebla la Tierra', keyFacts: ['Homo sapiens surgió en África hace ~300.000 años', 'La gran migración fuera de África comenzó hace ~60.000–70.000 años', 'Australia fue alcanzada hace ~50.000 años — cruzando mar abierto', 'Las Américas fueron pobladas hace ~15.000+ años vía Beringia'], sectionHeadings: ['Nacidos en África', 'El viaje comienza', 'Cruzar el mar hacia Australia', 'Hacia el Nuevo Mundo', 'Una especie, muchos mundos'] },
    ru: { title: 'Великое путешествие человека', subtitle: 'Homo sapiens заселяет Землю', keyFacts: ['Homo sapiens возник в Африке ~300 000 лет назад', 'Главное расселение из Африки началось ~60 000–70 000 лет назад', 'Австралия была достигнута ~50 000 лет назад — через открытое море', 'Америка была заселена ~15 000+ лет назад через Берингию'], sectionHeadings: ['Рождённые в Африке', 'Путешествие начинается', 'Через море в Австралию', 'В Новый Свет', 'Один вид, множество миров'] },
    mk: { title: 'Големото Човечко Патување', subtitle: 'Homo sapiens ја населува Земјата', keyFacts: ['Homo sapiens се појавил во Африка пред ~300.000 години', 'Големата преселба од Африка почнала пред ~60.000–70.000 години', 'Австралија била достигната пред ~50.000 години — преку отворено море', 'Америките биле населени пред ~15.000+ години преку Берингија'], sectionHeadings: ['Родени во Африка', 'Патувањето започнува', 'Преминување на морето до Австралија', 'Кон Новиот Свет', 'Еден вид, многу светови'] },
    de: { title: 'Die große Reise des Menschen', subtitle: 'Homo sapiens bevölkert die Erde', keyFacts: ['Homo sapiens entstand in Afrika vor ~300.000 Jahren', 'Die große Auswanderung aus Afrika begann vor ~60.000–70.000 Jahren', 'Australien wurde vor ~50.000 Jahren erreicht — über offene See', 'Amerika wurde vor ~15.000+ Jahren über Beringia besiedelt'], sectionHeadings: ['In Afrika geboren', 'Die Reise beginnt', 'Übers Meer nach Australien', 'In die Neue Welt', 'Eine Art, viele Welten'] },
    fr: { title: 'Le grand voyage humain', subtitle: 'Homo sapiens peuple la Terre', keyFacts: ["Homo sapiens apparut en Afrique il y a ~300 000 ans", "La grande migration hors d'Afrique commença il y a ~60 000–70 000 ans", "L'Australie fut atteinte il y a ~50 000 ans — en traversant la haute mer", "Les Amériques furent peuplées il y a ~15 000 ans et plus via la Béringie"], sectionHeadings: ['Nés en Afrique', 'Le voyage commence', 'Traverser la mer vers l\'Australie', 'Vers le Nouveau Monde', 'Une espèce, de nombreux mondes'] },
  },
  'prehistoric-05': {
    es: { title: 'El Instrumental de la Edad de Piedra', subtitle: 'Dos millones de años de tecnología', keyFacts: ['El instrumental olduvayense aparece hace ~2,6 millones de años', 'El bifaz achelense duró más de un millón de años', 'El Paleolítico Superior (~50.000 años) vio una explosión de tipos de herramientas', 'El arco y la flecha fue un arma revolucionaria del final de la Edad de Piedra'], sectionHeadings: ['La lógica de la piedra', 'Del canto tallado al bifaz', 'La mente preparada', 'El gran salto', 'El arma que cambió la caza'] },
    ru: { title: 'Инструментарий каменного века', subtitle: 'Два миллиона лет технологии', keyFacts: ['Олдувайские орудия появляются ~2,6 млн лет назад', 'Ашёльское рубило служило более миллиона лет', 'Верхний палеолит (~50 000 лет назад) — взрыв разнообразия орудий', 'Лук и стрелы стали революционным оружием позднего каменного века'], sectionHeadings: ['Логика камня', 'От чоппера к рубилу', 'Подготовленный ум', 'Великий скачок', 'Оружие, изменившее охоту'] },
    mk: { title: 'Приборот на Каменото Доба', subtitle: 'Два милиони години технологија', keyFacts: ['Олдувајскиот прибор се појавува пред ~2,6 милиони години', 'Ашелската рачна секира траела повеќе од милион години', 'Горниот Палеолит (~50.000 години) видел експлозија на видови алат', 'Лакот и стрелата биле револуционерно оружје од крајот на Каменото Доба'], sectionHeadings: ['Логиката на каменот', 'Од сечило до рачна секира', 'Подготвениот ум', 'Големиот скок', 'Оружјето што го смени ловот'] },
    de: { title: 'Das Werkzeug der Steinzeit', subtitle: 'Zwei Millionen Jahre Technik', keyFacts: ['Das Oldowan-Werkzeug erscheint vor ~2,6 Millionen Jahren', 'Der acheuléische Faustkeil hielt über eine Million Jahre', 'Das Jungpaläolithikum (~50.000 Jahre) brachte eine Explosion von Werkzeugtypen', 'Pfeil und Bogen waren eine revolutionäre Waffe der späten Steinzeit'], sectionHeadings: ['Die Logik des Steins', 'Vom Geröllgerät zum Faustkeil', 'Der vorbereitete Geist', 'Der große Sprung', 'Die Waffe, die die Jagd veränderte'] },
    fr: { title: "La panoplie de l'âge de pierre", subtitle: 'Deux millions d\'années de technologie', keyFacts: ["L'outillage oldowayen apparaît il y a ~2,6 millions d'années", "Le biface acheuléen dura plus d'un million d'années", 'Le Paléolithique supérieur (~50 000 ans) vit une explosion de types d\'outils', "L'arc et la flèche furent une arme révolutionnaire de la fin de l'âge de pierre"], sectionHeadings: ['La logique de la pierre', 'Du chopper au biface', "L'esprit préparé", 'Le grand bond', 'L\'arme qui changea la chasse'] },
  },
  'prehistoric-06': {
    es: { title: 'El Arte Rupestre y la Mente Simbólica', subtitle: 'El nacimiento de la imaginación', keyFacts: ['La cueva de Chauvet en Francia guarda pinturas de ~36.000 años', 'La Sala de los Toros de Lascaux data de hace ~17.000 años', 'Se tallaron figuras de Venus por toda la Europa glacial', 'El arte figurativo más antiguo es un jabalí verrugoso, pintado hace ~45.500 años en Indonesia'], sectionHeadings: ['En la oscuridad pintada', 'El significado en la oscuridad', 'Figuras en piedra y marfil', 'Sonido, ritmo y la primera música', 'Por qué importa'] },
    ru: { title: 'Пещерное искусство и символический разум', subtitle: 'Рождение воображения', keyFacts: ['Пещера Шове во Франции хранит рисунки возрастом ~36 000 лет', 'Зал быков в Ласко датируется ~17 000 лет назад', 'Фигурки Венеры вырезали по всей ледниковой Европе', 'Древнейшее фигуративное искусство — бородавчатая свинья, написанная ~45 500 лет назад в Индонезии'], sectionHeadings: ['В расписанной тьме', 'Смысл во тьме', 'Фигуры из камня и слоновой кости', 'Звук, ритм и первая музыка', 'Почему это важно'] },
    mk: { title: 'Пештерската Уметност и Симболичкиот Ум', subtitle: 'Раѓањето на имагинацијата', keyFacts: ['Пештерата Шове во Франција чува слики стари ~36.000 години', 'Салата на Биковите во Ласко датира од пред ~17.000 години', 'Фигурки на Венера биле изрежувани низ ледничка Европа', 'Најстарата фигуративна уметност е брадавичесто прасе, насликано пред ~45.500 години во Индонезија'], sectionHeadings: ['Во насликаниот мрак', 'Значењето во мракот', 'Фигури во камен и слонова коска', 'Звук, ритам и првата музика', 'Зошто е важно'] },
    de: { title: 'Höhlenkunst und der symbolische Geist', subtitle: 'Die Geburt der Vorstellungskraft', keyFacts: ['Die Chauvet-Höhle in Frankreich birgt ~36.000 Jahre alte Malereien', 'Der Saal der Stiere von Lascaux stammt aus der Zeit vor ~17.000 Jahren', 'Venusfigurinen wurden in ganz eiszeitlichen Europa geschnitzt', 'Die älteste figürliche Kunst ist ein Warzenschwein, vor ~45.500 Jahren in Indonesien gemalt'], sectionHeadings: ['In die bemalte Finsternis', 'Der Sinn im Dunkeln', 'Figuren aus Stein und Elfenbein', 'Klang, Rhythmus und die erste Musik', 'Warum es zählt'] },
    fr: { title: "L'art pariétal et l'esprit symbolique", subtitle: "La naissance de l'imagination", keyFacts: ['La grotte Chauvet en France abrite des peintures de ~36 000 ans', 'La Salle des Taureaux de Lascaux date d\'il y a ~17 000 ans', 'Des figurines de Vénus furent sculptées dans toute l\'Europe glaciaire', "L'art figuratif le plus ancien est un cochon verruqueux, peint il y a ~45 500 ans en Indonésie"], sectionHeadings: ['Dans les ténèbres peintes', 'Le sens dans le noir', 'Figures de pierre et d\'ivoire', 'Son, rythme et la première musique', 'Pourquoi cela compte'] },
  },
  'prehistoric-07': {
    es: { title: 'El Mundo de la Edad de Hielo', subtitle: 'Mamuts, glaciares y supervivencia', keyFacts: ['El último máximo glacial culminó hace ~20.000 años', 'Los mantos de hielo cubrieron gran parte del norte de Europa y Norteamérica', 'Mamuts, rinocerontes lanudos y osos de las cavernas recorrían la tundra', 'El descenso del nivel del mar expuso puentes de tierra que rehicieron las migraciones'], sectionHeadings: ['Un planeta de hielo', 'La estepa del mamut', 'Vivir al límite', 'Cuando cayeron los gigantes', 'El deshielo que nos hizo'] },
    ru: { title: 'Мир ледникового периода', subtitle: 'Мамонты, ледники и выживание', keyFacts: ['Последний ледниковый максимум достиг пика ~20 000 лет назад', 'Ледниковые щиты покрывали большую часть севера Европы и Северной Америки', 'Мамонты, шерстистые носороги и пещерные медведи бродили по тундре', 'Падение уровня моря обнажило перешейки, изменившие миграции'], sectionHeadings: ['Планета льда', 'Мамонтовая степь', 'Жизнь на грани', 'Когда пали гиганты', 'Оттепель, что создала нас'] },
    mk: { title: 'Светот на Леденото Доба', subtitle: 'Мамути, глечери и опстанок', keyFacts: ['Последниот леднички максимум го достигна врвот пред ~20.000 години', 'Ледените плочи покриваа голем дел од северна Европа и Северна Америка', 'Мамути, волнести носорози и пештерски мечки талкаа низ тундрата', 'Опаѓањето на морското ниво откри копнени мостови што ги преобликуваа преселбите'], sectionHeadings: ['Планета од мраз', 'Мамутската степа', 'Живот на работ', 'Кога паднаа џиновите', 'Топењето што нè создаде'] },
    de: { title: 'Die Welt der Eiszeit', subtitle: 'Mammuts, Gletscher und Überleben', keyFacts: ['Das letzte glaziale Maximum erreichte seinen Höhepunkt vor ~20.000 Jahren', 'Eisschilde bedeckten weite Teile Nordeuropas und Nordamerikas', 'Mammuts, Wollnashörner und Höhlenbären durchstreiften die Tundra', 'Sinkende Meeresspiegel legten Landbrücken frei, die Wanderungen umgestalteten'], sectionHeadings: ['Ein Planet aus Eis', 'Die Mammutsteppe', 'Am Rande leben', 'Als die Riesen fielen', 'Das Tauwetter, das uns schuf'] },
    fr: { title: "Le monde de l'ère glaciaire", subtitle: 'Mammouths, glaciers et survie', keyFacts: ['Le dernier maximum glaciaire culmina il y a ~20 000 ans', 'Les calottes glaciaires couvraient une grande partie du nord de l\'Europe et de l\'Amérique du Nord', 'Mammouths, rhinocéros laineux et ours des cavernes parcouraient la toundra', 'La baisse du niveau des mers dégagea des ponts terrestres qui refaçonnèrent les migrations'], sectionHeadings: ['Une planète de glace', 'La steppe à mammouths', 'Vivre à la limite', 'Quand les géants tombèrent', 'Le dégel qui nous fit'] },
  },
  'prehistoric-08': {
    es: { title: 'La Revolución Neolítica', subtitle: 'La invención de la agricultura', keyFacts: ['La agricultura comenzó de forma independiente hacia el 10.000 a.C. en el Creciente Fértil', 'Trigo, cebada, ovejas, cabras y ganado se domesticaron primero en el Suroeste Asiático', 'La agricultura surgió de forma independiente en China, las Américas y otros lugares', 'Permitió poblaciones densas pero a menudo empeoró la salud individual'], sectionHeadings: ['El cambio más importante', 'El Creciente Fértil', 'Un mundo de invenciones independientes', 'El pacto de los campos', 'Todo lo que siguió'] },
    ru: { title: 'Неолитическая революция', subtitle: 'Изобретение земледелия', keyFacts: ['Земледелие возникло независимо ~10 000 до н.э. на Плодородном полумесяце', 'Пшеницу, ячмень, овец, коз и скот впервые одомашнили в Юго-Западной Азии', 'Земледелие возникло независимо в Китае, Америке и других местах', 'Оно позволило плотное население, но часто ухудшало здоровье отдельного человека'], sectionHeadings: ['Важнейшая перемена', 'Плодородный полумесяц', 'Мир независимых изобретений', 'Сделка полей', 'Всё, что последовало'] },
    mk: { title: 'Неолитската револуција', subtitle: 'Изумот на земјоделството', keyFacts: ['Земјоделството започна независно околу 10.000 п.н.е. во Плодородниот Полумесец', 'Пченицата, јачменот, овците, козите и говедата првпат биле припитомени во Југозападна Азија', 'Земјоделството се појави независно во Кина, Америките и на други места', 'Овозможи густо население, но честопати го влошуваше индивидуалното здравје'], sectionHeadings: ['Најважната промена', 'Плодородниот Полумесец', 'Свет на независни изуми', 'Спогодбата на полињата', 'Сè што следеше'] },
    de: { title: 'Die Neolithische Revolution', subtitle: 'Die Erfindung des Ackerbaus', keyFacts: ['Der Ackerbau begann unabhängig um 10.000 v. Chr. im Fruchtbaren Halbmond', 'Weizen, Gerste, Schafe, Ziegen und Rinder wurden zuerst in Südwestasien gezähmt', 'Die Landwirtschaft entstand unabhängig in China, Amerika und anderswo', 'Sie ermöglichte dichte Bevölkerungen, verschlechterte aber oft die Gesundheit des Einzelnen'], sectionHeadings: ['Die wichtigste Veränderung', 'Der Fruchtbare Halbmond', 'Eine Welt unabhängiger Erfindungen', 'Der Handel der Felder', 'Alles, was folgte'] },
    fr: { title: 'La révolution néolithique', subtitle: "L'invention de l'agriculture", keyFacts: ["L'agriculture débuta de façon indépendante vers 10 000 av. J.-C. au Croissant fertile", 'Blé, orge, moutons, chèvres et bovins furent domestiqués d\'abord au Proche-Orient', "L'agriculture surgit indépendamment en Chine, dans les Amériques et ailleurs", 'Elle permit des populations denses mais dégrada souvent la santé individuelle'], sectionHeadings: ['Le changement le plus important', 'Le Croissant fertile', "Un monde d'inventions indépendantes", 'Le marché des champs', 'Tout ce qui suivit'] },
  },
  'prehistoric-09': {
    es: { title: 'Las Primeras Aldeas y Monumentos', subtitle: 'Göbekli Tepe, Çatalhöyük y el umbral de la historia', keyFacts: ['Göbekli Tepe (~9500 a.C.) es el sitio monumental más antiguo conocido', 'Çatalhöyük albergó a miles sin calles — se entraba por el tejado', 'La cerámica, el tejido y la metalurgia surgieron en el Neolítico tardío', 'Stonehenge fue construido y reconstruido desde ~3000 a.C.'], sectionHeadings: ['El templo antes del pueblo', 'La ciudad sin calles', 'La explosión artesanal', 'Levantar las grandes piedras', 'El umbral de la historia'] },
    ru: { title: 'Первые деревни и монументы', subtitle: 'Гёбекли-Тепе, Чатал-Хёюк и порог истории', keyFacts: ['Гёбекли-Тепе (~9500 до н.э.) — древнейший известный монументальный памятник', 'Чатал-Хёюк вмещал тысячи жителей без улиц — вход был через крышу', 'Гончарство, ткачество и металлообработка появились в позднем неолите', 'Стоунхендж строился и перестраивался с ~3000 до н.э.'], sectionHeadings: ['Храм прежде города', 'Город без улиц', 'Взрыв ремёсел', 'Поднять великие камни', 'Порог истории'] },
    mk: { title: 'Првите Села и Споменици', subtitle: 'Гебекли Тепе, Чаталхујук и прагот на историјата', keyFacts: ['Гебекли Тепе (~9500 п.н.е.) е најстариот познат монументален локалитет', 'Чаталхујук сместувал илјадници без улици — се влегувало преку кровот', 'Грнчарството, ткаењето и обработката на метал се појавија во доцниот неолит', 'Стоунхенџ бил граден и преградуван од ~3000 п.н.е.'], sectionHeadings: ['Храмот пред градот', 'Градот без улици', 'Занаетчиската експлозија', 'Кревање на големите камења', 'Прагот на историјата'] },
    de: { title: 'Die ersten Dörfer und Monumente', subtitle: 'Göbekli Tepe, Çatalhöyük und die Schwelle der Geschichte', keyFacts: ['Göbekli Tepe (~9500 v. Chr.) ist die älteste bekannte monumentale Stätte', 'Çatalhöyük beherbergte Tausende ohne Straßen — betreten durchs Dach', 'Töpferei, Weberei und Metallverarbeitung entstanden im späten Neolithikum', 'Stonehenge wurde ab ~3000 v. Chr. errichtet und umgebaut'], sectionHeadings: ['Der Tempel vor der Stadt', 'Die Stadt ohne Straßen', 'Die Explosion des Handwerks', 'Die großen Steine aufrichten', 'Die Schwelle der Geschichte'] },
    fr: { title: 'Les premiers villages et monuments', subtitle: "Göbekli Tepe, Çatalhöyük et le seuil de l'histoire", keyFacts: ['Göbekli Tepe (~9500 av. J.-C.) est le plus ancien site monumental connu', 'Çatalhöyük abritait des milliers de gens sans rues — on entrait par le toit', 'Poterie, tissage et métallurgie apparurent au Néolithique tardif', 'Stonehenge fut bâti et rebâti à partir de ~3000 av. J.-C.'], sectionHeadings: ['Le temple avant la ville', 'La ville sans rues', "L'explosion de l'artisanat", 'Dresser les grandes pierres', "Le seuil de l'histoire"] },
  },
};

// Section bodies are added in PREHISTORIC_BODY_TRANS (see prehistoricBodies.ts).
