import type { Era } from '@/types';

export const ERAS: Era[] = [
  { id: 'prehistoric', name: 'Prehistoric Ages', shortName: 'Prehistory', dateRange: '~4,000,000 – 3000 BCE', description: 'Before writing, before cities — the deep human story. From the first upright hominins and the taming of fire to Ice Age hunters, cave painters, and the farmers whose Neolithic Revolution invented the settled world that everything after was built upon.', icon: 'flame', color: 'text-orange-400', bgGradient: 'from-orange-950/30 to-background', lessonIds: ['prehistoric-01','prehistoric-02','prehistoric-03','prehistoric-04','prehistoric-05','prehistoric-06','prehistoric-07','prehistoric-08','prehistoric-09'], quizId: 'quiz-prehistoric' },
  { id: 'ancient', name: 'Ancient History', shortName: 'Ancient', dateRange: '~3000 BCE – 500 CE', description: 'From the first writing systems of Mesopotamia to the fall of the Western Roman Empire. Explore civilizations that laid the foundations of human culture, law, philosophy, and empire.', icon: 'scroll', color: 'text-amber-400', bgGradient: 'from-amber-950/30 to-background', lessonIds: ['ancient-01','ancient-02','ancient-03','ancient-04','ancient-05','ancient-06','ancient-07','ancient-08','ancient-09'], quizId: 'quiz-ancient' },
  { id: 'byzantine', name: 'The Byzantine World', shortName: 'Byzantium', dateRange: '330 – 1453 CE', description: 'The thousand-year Roman Empire of the East. From Constantine\'s New Rome to the fall of Constantinople: Justinian\'s laws, Hagia Sophia, Greek fire, the alphabet of Cyril and Methodius, and the rise of Orthodox Christianity that shaped half of Europe.', icon: 'church', color: 'text-violet-400', bgGradient: 'from-violet-950/30 to-background', lessonIds: ['byzantine-01','byzantine-02','byzantine-03','byzantine-04','byzantine-05','byzantine-06','byzantine-07','byzantine-08','byzantine-09'], quizId: 'quiz-byzantine' },
  { id: 'middle-ages', name: 'Middle Ages', shortName: 'Medieval', dateRange: '~500 – 1500 CE', description: 'A millennium of knights, cathedrals, plagues, and crusades. Discover how the medieval world shaped modern Europe, the rise of Islam, and the preservation of ancient knowledge.', icon: 'castle', color: 'text-blue-400', bgGradient: 'from-blue-950/30 to-background', lessonIds: ['medieval-01','medieval-02','medieval-03','medieval-04','medieval-05','medieval-06','medieval-07','medieval-08','medieval-09'], quizId: 'quiz-medieval' },
  { id: 'early-modern', name: 'Early Modern', shortName: 'Early Modern', dateRange: '~1500 – 1800 CE', description: 'The age of exploration, scientific revolution, and political upheaval. From Columbus to the American Revolution, this era reshaped the globe and our understanding of the universe.', icon: 'compass', color: 'text-emerald-400', bgGradient: 'from-emerald-950/30 to-background', lessonIds: ['earlymod-01','earlymod-02','earlymod-03','earlymod-04','earlymod-05','earlymod-06','earlymod-07','earlymod-08','earlymod-09'], quizId: 'quiz-earlymod' },
  { id: 'modern', name: 'Modern Era', shortName: 'Modern', dateRange: '~1800 CE – Present', description: 'Industrial revolution to the digital age. Two World Wars, decolonization, the Cold War, and the rise of globalization transformed every corner of the earth.', icon: 'industry', color: 'text-rose-400', bgGradient: 'from-rose-950/30 to-background', lessonIds: ['modern-01','modern-02','modern-03','modern-04','modern-05','modern-06','modern-07','modern-08','modern-09'], quizId: 'quiz-modern' },
];

export function getEraById(id: string) { return ERAS.find(e => e.id === id); }
export function getEraLessons(eraId: string) { return ERAS.find(e => e.id === eraId)?.lessonIds ?? []; }
