export type MapMarker = {
  lat: number;
  lon: number;
  label: string;
  description?: string;
};

export type LessonMapData = {
  lessonId: string;
  regionName: string;
  bounds: { north: number; south: number; east: number; west: number };
  markers: MapMarker[];
  description: string;
};

export const LESSON_MAPS: LessonMapData[] = [
  {
    lessonId: 'ancient-01',
    regionName: 'Mesopotamia & Ancient Egypt',
    bounds: { north: 34, south: 22, east: 50, west: 26 },
    markers: [
      { lat: 31.32, lon: 45.6, label: 'Uruk', description: "World's first city; birthplace of cuneiform writing (~3100 BCE)" },
      { lat: 32.54, lon: 44.42, label: 'Babylon', description: "Capital of Babylonian Empire; home of Hammurabi's Code (~1754 BCE)" },
      { lat: 30.96, lon: 46.1, label: 'Ur', description: 'Major Sumerian city-state; center of Mesopotamian trade' },
      { lat: 29.84, lon: 31.25, label: 'Memphis', description: 'Ancient Egyptian capital and religious center' },
      { lat: 29.97, lon: 31.13, label: 'Giza', description: 'Site of the Great Pyramids, built c.2560 BCE' },
      { lat: 25.72, lon: 32.66, label: 'Thebes', description: 'Major Egyptian city and center of Amun worship' },
    ],
    description: 'The Fertile Crescent — stretching from the Persian Gulf through Mesopotamia to Egypt — hosted the world\'s earliest civilizations. The Tigris and Euphrates rivers nourished Sumer, Akkad, and Babylon; the Nile sustained Egypt for over 3,000 years.',
  },
  {
    lessonId: 'ancient-02',
    regionName: 'Ancient Greece & the Aegean',
    bounds: { north: 42, south: 35, east: 30, west: 19 },
    markers: [
      { lat: 37.97, lon: 23.72, label: 'Athens', description: 'Birthplace of democracy; cultural center of the Greek world' },
      { lat: 37.07, lon: 22.43, label: 'Sparta', description: 'Militaristic city-state; rival of Athens' },
      { lat: 38.8, lon: 22.53, label: 'Thermopylae', description: 'Site of the legendary Spartan last stand (480 BCE)' },
      { lat: 37.9, lon: 23.5, label: 'Salamis', description: 'Greek naval victory over Persia (480 BCE)' },
      { lat: 37.6, lon: 21.63, label: 'Olympia', description: 'Site of the ancient Olympic Games (founded 776 BCE)' },
      { lat: 40.76, lon: 22.52, label: 'Pella', description: 'Capital of Macedonian Kingdom; birthplace of Alexander the Great' },
      { lat: 40.65, lon: 22.93, label: 'Thessaloniki', description: 'Major Macedonian port city' },
    ],
    description: 'Ancient Greece was a constellation of independent city-states clustered around the Aegean Sea. The mountainous terrain fostered diverse political experiments — from Athenian democracy to Spartan oligarchy. Alexander\'s Macedonian Empire later spread Greek culture from Egypt to the borders of India.',
  },
  {
    lessonId: 'ancient-03',
    regionName: 'The Roman World',
    bounds: { north: 58, south: 25, east: 45, west: -10 },
    markers: [
      { lat: 41.9, lon: 12.5, label: 'Rome', description: 'Capital of the Roman Republic, then Empire; founded c.753 BCE' },
      { lat: 36.85, lon: 10.32, label: 'Carthage', description: 'Great rival of Rome; destroyed in 146 BCE after the Punic Wars' },
      { lat: 37.97, lon: 23.72, label: 'Athens', description: 'Major Greek city absorbed into the Roman cultural sphere' },
      { lat: 31.2, lon: 29.9, label: 'Alexandria', description: "Egypt's capital under Rome; site of the ancient Library" },
      { lat: 31.77, lon: 35.2, label: 'Jerusalem', description: 'Roman province of Judaea; birthplace of Christianity' },
      { lat: 41.01, lon: 28.97, label: 'Constantinople', description: 'Eastern capital of the Empire; founded 330 CE by Constantine' },
      { lat: 51.51, lon: -0.12, label: 'Londinium', description: 'Roman settlement that became London' },
    ],
    description: 'At its height under Trajan, the Roman Empire covered 5 million km² — from Britain to Mesopotamia. Roman roads, aqueducts, and law unified a vast territory. The Western Empire fell in 476 CE; the Eastern (Byzantine) Empire survived until 1453.',
  },
  {
    lessonId: 'ancient-04',
    regionName: 'Persia, India & Han China',
    bounds: { north: 50, south: 8, east: 125, west: 28 },
    markers: [
      { lat: 29.94, lon: 52.89, label: 'Persepolis', description: 'Ceremonial capital of the Achaemenid Persian Empire' },
      { lat: 32.18, lon: 48.26, label: 'Susa', description: 'Administrative capital of the Persian Empire' },
      { lat: 25.6, lon: 85.1, label: 'Pataliputra', description: 'Capital of the Maurya Empire under Ashoka (268–232 BCE)' },
      { lat: 33.73, lon: 72.85, label: 'Taxila', description: 'Major Silk Road city; center of Buddhist learning in Gandhara' },
      { lat: 34.27, lon: 108.93, label: "Chang'an", description: "Capital of the Han Dynasty; western terminus of the Silk Road" },
      { lat: 34.65, lon: 112.47, label: 'Luoyang', description: 'Eastern Han capital; major center of Chinese culture' },
    ],
    description: 'Three great civilizations arose across the vast Eurasian continent: the Achaemenid Persian Empire (the largest of the ancient world), the Mauryan Empire in India, and the Han Dynasty in China. The Silk Road eventually linked them all, enabling exchange of goods, ideas, and religions.',
  },
  {
    lessonId: 'ancient-05',
    regionName: 'The Nile Valley & Ancient Egypt',
    bounds: { north: 32, south: 21, east: 37, west: 24 },
    markers: [
      { lat: 29.97, lon: 31.13, label: 'Giza', description: 'Site of the Great Pyramids; built c.2560–2490 BCE' },
      { lat: 29.84, lon: 31.25, label: 'Memphis', description: "Old Kingdom capital; center of Ptah's worship" },
      { lat: 25.72, lon: 32.66, label: 'Karnak / Thebes', description: 'New Kingdom capital; site of the Temple of Amun' },
      { lat: 27.65, lon: 30.9, label: 'Amarna', description: "Short-lived capital of Akhenaten's monotheistic revolution" },
      { lat: 31.2, lon: 29.9, label: 'Alexandria', description: 'Ptolemaic capital; site of the great ancient Library' },
      { lat: 22.37, lon: 31.63, label: 'Abu Simbel', description: "Ramesses II's great rock temples on the Nubian frontier" },
    ],
    description: 'Egyptian civilization flourished along the Nile for over 3,000 years, from the first Pharaoh Narmer (~3100 BCE) to Cleopatra VII (died 30 BCE). The annual Nile flood deposited rich silt, making Egypt one of the ancient world\'s most productive agricultural zones.',
  },
  {
    lessonId: 'ancient-06',
    regionName: 'The Phoenician Mediterranean',
    bounds: { north: 48, south: 24, east: 42, west: -7 },
    markers: [
      { lat: 33.27, lon: 35.2, label: 'Tyre', description: "Greatest Phoenician city; mother city of Carthage; invented the alphabet" },
      { lat: 33.56, lon: 35.37, label: 'Sidon', description: 'Major Phoenician city-state; famed for glass and purple dye production' },
      { lat: 34.12, lon: 35.64, label: 'Byblos', description: "Ancient port city; gave its name to 'Bible' (books from Byblos)" },
      { lat: 36.85, lon: 10.32, label: 'Carthage', description: "Phoenician colony founded c.814 BCE; became Rome's greatest rival" },
      { lat: 36.53, lon: -6.29, label: 'Gadir (Cádiz)', description: 'Westernmost Phoenician colony; gateway to the Atlantic' },
      { lat: 43.3, lon: 5.37, label: 'Massalia (Marseille)', description: 'Greek colony influenced by Phoenician Mediterranean trade' },
    ],
    description: 'From their narrow coastal homeland in modern Lebanon, the Phoenicians created a Mediterranean-wide trading network. Their most lasting gift was the alphabet — 22 consonants that the Greeks adopted and adapted, giving rise to every Western writing system in use today.',
  },

  // MIDDLE AGES
  {
    lessonId: 'medieval-01',
    regionName: 'Post-Roman Europe',
    bounds: { north: 62, south: 35, east: 45, west: -12 },
    markers: [
      { lat: 41.9, lon: 12.5, label: 'Rome', description: 'Seat of the Pope; center of Western Christianity after the Empire\'s fall' },
      { lat: 41.01, lon: 28.97, label: 'Constantinople', description: 'Capital of the Byzantine Empire; survived until 1453' },
      { lat: 50.77, lon: 6.09, label: 'Aachen', description: "Charlemagne's imperial capital; center of the Carolingian Renaissance" },
      { lat: 48.85, lon: 2.35, label: 'Paris', description: 'Capital of the Frankish kingdom; grew into a major medieval city' },
      { lat: 53.96, lon: -1.08, label: 'York', description: 'Major Viking and Anglo-Saxon center in northern England' },
      { lat: 59.95, lon: 30.32, label: 'Novgorod', description: 'Key city of the Norse-founded Rus\' state' },
    ],
    description: 'After Rome\'s fall in 476 CE, Germanic kingdoms carved up Western Europe. The Catholic Church preserved Latin literacy and provided social continuity. Charlemagne briefly reunited much of the West; the Byzantine Empire kept Roman traditions alive in the East for another millennium.',
  },
  {
    lessonId: 'medieval-02',
    regionName: 'The Crusading World & Islamic Civilization',
    bounds: { north: 52, south: 20, east: 58, west: -12 },
    markers: [
      { lat: 31.77, lon: 35.2, label: 'Jerusalem', description: 'Holy city contested by Christians and Muslims throughout the Crusades' },
      { lat: 33.34, lon: 44.4, label: 'Baghdad', description: "Abbasid Caliphate's capital; center of the Islamic Golden Age" },
      { lat: 21.42, lon: 39.82, label: 'Mecca', description: 'Holiest city of Islam; birthplace of the Prophet Muhammad' },
      { lat: 30.06, lon: 31.24, label: 'Cairo', description: "Fatimid and Ayyubid capital; Saladin's base for retaking Jerusalem" },
      { lat: 36.2, lon: 36.16, label: 'Antioch', description: 'First Crusader state; critical supply base for the Holy Land' },
      { lat: 45.44, lon: 12.33, label: 'Venice', description: 'Provided ships and logistics to the Crusades in exchange for trade rights' },
      { lat: 32.92, lon: 35.07, label: 'Acre', description: 'Last Crusader stronghold; fell to the Mamluks in 1291' },
    ],
    description: 'While Western Europe slowly recovered from Rome\'s fall, the Islamic world experienced a brilliant Golden Age of science, philosophy, and culture. The Crusades (1095–1291) were a series of religiously motivated wars that intensified contact — and conflict — between Christian Europe and the Islamic world.',
  },
  {
    lessonId: 'medieval-03',
    regionName: 'Plague-Stricken Europe',
    bounds: { north: 62, south: 35, east: 38, west: -12 },
    markers: [
      { lat: 44.94, lon: 34.1, label: 'Caffa', description: 'Genoese port on the Black Sea where the Black Death entered Europe (1346)' },
      { lat: 37.49, lon: 15.07, label: 'Messina', description: 'First Italian city struck by the plague (October 1347)' },
      { lat: 43.77, lon: 11.25, label: 'Florence', description: 'Lost 60% of its population; Boccaccio wrote the Decameron here' },
      { lat: 48.85, lon: 2.35, label: 'Paris', description: 'The University of Paris issued a report blaming the plague on astrological causes' },
      { lat: 51.51, lon: -0.12, label: 'London', description: 'Lost perhaps half its population to the plague' },
      { lat: 43.95, lon: 4.81, label: 'Avignon', description: "Papal residence during the plague; Pope Clement VI sat between fires to prevent infection" },
    ],
    description: 'The Black Death (1347–1353) killed between one-third and one-half of Europe\'s population — perhaps 25 million people. Originating in Central Asia and spreading along trade routes, it transformed European society: empowering survivors, weakening the Church, and accelerating social changes that led toward the Renaissance.',
  },
  {
    lessonId: 'medieval-04',
    regionName: 'Medieval Trade Networks',
    bounds: { north: 62, south: 42, east: 32, west: -6 },
    markers: [
      { lat: 53.87, lon: 10.68, label: 'Lübeck', description: "Informal capital of the Hanseatic League; dominated Baltic trade" },
      { lat: 53.55, lon: 10.0, label: 'Hamburg', description: 'Major Hanseatic port; gateway between Baltic and North Sea' },
      { lat: 45.44, lon: 12.33, label: 'Venice', description: 'Mediterranean trading power; pioneered banking and double-entry bookkeeping' },
      { lat: 43.77, lon: 11.25, label: 'Florence', description: "Home of the Medici banking dynasty; cradle of Renaissance finance" },
      { lat: 51.2, lon: 3.22, label: 'Bruges', description: "Northwestern Europe's greatest trading city in the 13th–14th centuries" },
      { lat: 51.51, lon: -0.12, label: 'London', description: 'Had a Hanseatic trading post (Kontor) called the Steelyard' },
      { lat: 58.52, lon: 31.27, label: 'Novgorod', description: 'Eastern terminus of Hanseatic trade; linked Europe to Russia and Persia' },
      { lat: 48.72, lon: 4.5, label: 'Champagne Fairs', description: 'Annual fairs that became the commercial hub of medieval Europe' },
    ],
    description: 'From around 1000 CE, a commercial revolution transformed medieval Europe. Weekly markets, annual fairs, merchant guilds, and the Hanseatic League created trade networks that stretched from England to Russia. Italian bankers invented double-entry bookkeeping, bills of exchange, and the foundations of modern finance.',
  },
  {
    lessonId: 'medieval-05',
    regionName: 'The Mongol Empire',
    bounds: { north: 66, south: 22, east: 135, west: 25 },
    markers: [
      { lat: 47.2, lon: 102.83, label: 'Karakorum', description: "Genghis Khan's imperial capital on the Mongolian steppe" },
      { lat: 39.9, lon: 116.4, label: 'Zhongdu / Beijing', description: 'Jin Dynasty capital captured by the Mongols in 1215; later Yuan capital' },
      { lat: 33.34, lon: 44.4, label: 'Baghdad', description: 'Abbasid capital sacked by Hülegü Khan in 1258; ended Islamic Golden Age' },
      { lat: 39.65, lon: 66.96, label: 'Samarkand', description: 'Silk Road hub; devastated by Genghis Khan, later rebuilt by Timur' },
      { lat: 50.45, lon: 30.52, label: 'Kiev', description: 'Major Russian city devastated by Batu Khan\'s westward campaign (1240)' },
      { lat: 30.06, lon: 31.24, label: 'Cairo', description: 'Mamluk capital; defeated Mongols at Ain Jalut (1260), halting westward expansion' },
    ],
    description: 'Founded by Genghis Khan in 1206, the Mongol Empire became the largest contiguous land empire in history — 24 million km², spanning from China to Eastern Europe. The Pax Mongolica (c.1260–1350) united Eurasian trade routes, enabling Marco Polo\'s journey and accelerating the exchange of goods, diseases, and ideas.',
  },
  {
    lessonId: 'medieval-06',
    regionName: 'Medieval Japan',
    bounds: { north: 46, south: 30, east: 150, west: 128 },
    markers: [
      { lat: 35.02, lon: 135.75, label: 'Kyoto', description: "Imperial capital (Heian-kyō); center of aristocratic culture and later Zen Buddhism" },
      { lat: 35.32, lon: 139.55, label: 'Kamakura', description: "Japan's first shogunate capital (1185); center of Zen and samurai culture" },
      { lat: 34.68, lon: 135.83, label: 'Nara', description: 'Earlier imperial capital; site of great Buddhist temples' },
      { lat: 33.6, lon: 130.4, label: 'Hakata Bay', description: 'Site of both Mongol invasion attempts (1274, 1281); where the kamikaze struck' },
      { lat: 35.68, lon: 139.69, label: 'Edo (Tokyo)', description: 'Later rose to prominence under Tokugawa rule' },
      { lat: 34.69, lon: 135.5, label: 'Osaka', description: 'Commercial center; site of Hideyoshi\'s great castle' },
    ],
    description: "Japan's medieval period (roughly 1185–1600) was defined by the rise of the samurai class, the establishment of military governments (shogunates), and a profound cultural synthesis of warrior ethics and Zen Buddhist aesthetics. Two Mongol invasion attempts were repelled — partly by typhoons that Japanese called kamikaze ('divine wind').",
  },

  // EARLY MODERN
  {
    lessonId: 'earlymod-01',
    regionName: 'Renaissance Europe & the New World',
    bounds: { north: 58, south: 15, east: 32, west: -100 },
    markers: [
      { lat: 43.77, lon: 11.25, label: 'Florence', description: 'Cradle of the Renaissance; home of Leonardo, Michelangelo, and the Medici' },
      { lat: 45.44, lon: 12.33, label: 'Venice', description: 'Wealthy trading republic; gateway between East and West' },
      { lat: 38.72, lon: -9.14, label: 'Lisbon', description: "Portugal's capital; launched the Age of Exploration" },
      { lat: 19.43, lon: -99.13, label: 'Tenochtitlan', description: 'Aztec capital on a lake island; population ~200,000; conquered by Cortés 1521' },
      { lat: 11.0, lon: -74.8, label: 'Caribbean', description: 'Columbus landed in 1492; starting point of the Columbian Exchange' },
      { lat: 13.5, lon: -72.0, label: 'Cuzco', description: 'Inca capital in the Andes; conquered by Pizarro 1533' },
    ],
    description: 'The Renaissance (14th–17th c.) began in the wealthy Italian city-states as a rebirth of classical learning and artistic achievement. Simultaneously, Portuguese and Spanish explorers opened sea routes to Asia and the Americas — connecting the world\'s hemispheres for the first time and triggering the Columbian Exchange.',
  },
  {
    lessonId: 'earlymod-02',
    regionName: 'Reformation Europe',
    bounds: { north: 60, south: 40, east: 30, west: -6 },
    markers: [
      { lat: 51.86, lon: 12.64, label: 'Wittenberg', description: "Where Luther nailed his 95 Theses in 1517; epicenter of the Reformation" },
      { lat: 46.2, lon: 6.15, label: 'Geneva', description: "Calvin's city; center of Reformed Protestantism" },
      { lat: 47.38, lon: 8.54, label: 'Zurich', description: "Zwingli's city; early center of the Swiss Reformation" },
      { lat: 41.9, lon: 12.5, label: 'Rome', description: 'Seat of the Pope; launched the Counter-Reformation at the Council of Trent' },
      { lat: 51.51, lon: -0.12, label: 'London', description: "Henry VIII broke with Rome in 1534; created the Church of England" },
      { lat: 55.95, lon: -3.19, label: 'Edinburgh', description: 'Capital of Presbyterian Scotland; John Knox brought Calvinism here' },
    ],
    description: "Luther's challenge to the Church in 1517 shattered Western Christianity's unity. By 1560, Northern Europe was predominantly Protestant while the South remained Catholic. The resulting religious wars, culminating in the Thirty Years' War (1618–1648), killed millions and ultimately established the principle of state sovereignty.",
  },
  {
    lessonId: 'earlymod-03',
    regionName: 'The Scientific Revolution & Enlightenment',
    bounds: { north: 62, south: 38, east: 30, west: -12 },
    markers: [
      { lat: 43.72, lon: 10.4, label: 'Pisa', description: "Galileo's birthplace; where he studied motion by dropping objects from the tower" },
      { lat: 45.41, lon: 11.88, label: 'Padua', description: "Galileo taught here; Europe's leading university for natural philosophy" },
      { lat: 51.51, lon: -0.12, label: 'London', description: "Newton's Royal Society; center of English empiricism and the new science" },
      { lat: 52.37, lon: 4.9, label: 'Amsterdam', description: 'Publishing hub; Descartes wrote here; center of Enlightenment book trade' },
      { lat: 48.85, lon: 2.35, label: 'Paris', description: 'Home of the philosophes — Voltaire, Rousseau, Diderot, Montesquieu' },
      { lat: 52.22, lon: 21.0, label: 'Warsaw', description: "Near Toruń, birthplace of Copernicus, who proposed heliocentrism in 1543" },
    ],
    description: "The Scientific Revolution (1543–1687) overturned a millennium of ancient astronomy and philosophy. Copernicus, Galileo, and Newton established that nature operates according to mathematical laws. The Enlightenment applied this rational method to politics and society, inspiring the American and French Revolutions.",
  },
  {
    lessonId: 'earlymod-04',
    regionName: 'Absolutist Europe',
    bounds: { north: 60, south: 40, east: 24, west: -12 },
    markers: [
      { lat: 48.8, lon: 2.13, label: 'Versailles', description: "Louis XIV's palace; housed 20,000 people; symbol of absolute monarchy" },
      { lat: 48.85, lon: 2.35, label: 'Paris', description: 'Capital of France; center of Enlightenment thought and royal power' },
      { lat: 48.2, lon: 16.37, label: 'Vienna', description: 'Habsburg capital; seat of the Holy Roman Empire' },
      { lat: 40.42, lon: -3.7, label: 'Madrid', description: 'Spanish royal capital; center of a global empire' },
      { lat: 52.52, lon: 13.4, label: 'Berlin', description: 'Prussian capital; grew under the Hohenzollern dynasty' },
      { lat: 59.95, lon: 30.32, label: 'St. Petersburg', description: "Peter the Great's new capital; modeled on Versailles; window to the West" },
    ],
    description: "In 17th-century Europe, absolute monarchs centralized power, built standing armies, and created bureaucratic states. Louis XIV of France was the supreme model — his Palace of Versailles was both a marvel of art and a machine for political control. His revocation of the Edict of Nantes (1685) drove 200,000 skilled Protestants to France's rivals.",
  },
  {
    lessonId: 'earlymod-05',
    regionName: 'The Transatlantic Slave Trade Triangle',
    bounds: { north: 58, south: -15, east: 25, west: -85 },
    markers: [
      { lat: 51.51, lon: -0.12, label: 'London', description: 'Center of British slave trade; abolitionism also arose here (1807)' },
      { lat: 38.72, lon: -9.14, label: 'Lisbon', description: 'Portugal pioneered the slave trade to Brazil from the 1530s' },
      { lat: 14.7, lon: -17.47, label: 'Dakar / Gorée', description: "West African 'departure point'; Gorée Island was a major slave depot" },
      { lat: -8.84, lon: 13.23, label: 'Luanda', description: 'Main port for Angolan slave trade; millions embarked here' },
      { lat: 17.9, lon: -76.8, label: 'Kingston, Jamaica', description: "Britain's most profitable sugar colony; ran on enslaved African labor" },
      { lat: -12.97, lon: -38.5, label: 'Salvador da Bahia', description: "Brazil's first capital; received more enslaved Africans than any other city" },
      { lat: 23.13, lon: -82.38, label: 'Havana', description: "Cuba's sugar economy depended on enslaved labor until 1886" },
    ],
    description: 'The transatlantic slave trade forcibly transported ~12.5 million Africans to the Americas between 1500 and 1900. The triangular trade — European goods to Africa, enslaved Africans to the Americas, colonial goods back to Europe — built the wealth of Atlantic economies while inflicting incalculable human suffering.',
  },
  {
    lessonId: 'earlymod-06',
    regionName: 'The Ottoman Empire',
    bounds: { north: 52, south: 20, east: 60, west: 10 },
    markers: [
      { lat: 41.01, lon: 28.97, label: 'Istanbul', description: "Ottoman capital (conquered 1453); Topkapı Palace housed 30,000 people" },
      { lat: 30.06, lon: 31.24, label: 'Cairo', description: 'Major Ottoman provincial capital; controlled Egypt and Arabia' },
      { lat: 33.34, lon: 44.4, label: 'Baghdad', description: 'Taken by Suleiman in 1534; controlled access to Persian Gulf' },
      { lat: 21.42, lon: 39.82, label: 'Mecca', description: "Under Ottoman protection; Suleiman was 'Servant of the Two Holy Mosques'" },
      { lat: 44.82, lon: 20.46, label: 'Belgrade', description: 'Captured by Suleiman in 1521; gateway to Central Europe' },
      { lat: 48.2, lon: 16.37, label: 'Vienna', description: "Westernmost limit of Ottoman expansion; besieged in 1529 and 1683" },
      { lat: 36.44, lon: 28.22, label: 'Rhodes', description: 'Knights Hospitaller fortress expelled by Suleiman in 1522' },
      { lat: 36.73, lon: 3.08, label: 'Algiers', description: 'Ottoman corsair base controlling western Mediterranean' },
    ],
    description: "At its height under Suleiman the Magnificent (1520–1566), the Ottoman Empire spanned three continents — from Algeria to Azerbaijan, from Hungary to Yemen — governing a diverse population of Christians, Jews, and Muslims through the millet system of semi-autonomous communities.",
  },
  {
    lessonId: 'earlymod-07',
    regionName: 'The Age of Revolution',
    bounds: { north: 56, south: 18, east: 32, west: -105 },
    markers: [
      { lat: 39.95, lon: -75.17, label: 'Philadelphia', description: 'Where the Declaration of Independence (1776) and Constitution (1787) were signed' },
      { lat: 42.46, lon: -71.36, label: 'Concord & Lexington', description: 'First battles of the American Revolutionary War (April 1775)' },
      { lat: 37.24, lon: -76.51, label: 'Yorktown', description: 'Site of Cornwallis\'s surrender (1781); effectively ended the American war' },
      { lat: 48.85, lon: 2.35, label: 'Paris', description: 'Center of the French Revolution; the Bastille fell here on 14 July 1789' },
      { lat: 48.8, lon: 2.13, label: 'Versailles', description: 'Where Louis XVI called the Estates-General in May 1789' },
      { lat: 43.84, lon: -0.5, label: 'Waterloo region', description: 'Napoleon finally defeated here in June 1815' },
    ],
    description: "The American Revolution (1776) and French Revolution (1789) translated Enlightenment ideals into political reality. The Declaration of Independence and Declaration of the Rights of Man established the vocabulary of modern democracy — liberty, equality, and popular sovereignty — that would inspire revolutions worldwide.",
  },

  // MODERN ERA
  {
    lessonId: 'modern-01',
    regionName: 'Industrial Britain & Europe',
    bounds: { north: 60, south: 40, east: 28, west: -10 },
    markers: [
      { lat: 53.48, lon: -2.24, label: 'Manchester', description: "The 'Cottonopolis'; center of Britain's textile industry" },
      { lat: 52.48, lon: -1.9, label: 'Birmingham', description: "The 'City of a Thousand Trades'; iron, steel, and manufacturing hub" },
      { lat: 53.41, lon: -2.98, label: 'Liverpool', description: 'Major port for transatlantic trade; linked industrial goods to global markets' },
      { lat: 55.86, lon: -4.26, label: 'Glasgow', description: 'Watt improved the steam engine here; Scotland\'s industrial powerhouse' },
      { lat: 51.51, lon: -0.12, label: 'London', description: "World's largest city by 1800; center of finance and global trade" },
      { lat: 52.52, lon: 13.4, label: 'Berlin', description: 'Center of Germany\'s rapid industrialization after 1871' },
      { lat: 40.44, lon: -79.99, label: 'Pittsburgh', description: "America's 'Steel City'; Carnegie Steel dominated global production" },
    ],
    description: 'The Industrial Revolution began in Britain around 1760 and spread across Europe and North America by the 1870s. Steam power, mechanized textile production, railways, and steel transformed economies and societies — urbanizing populations, creating new social classes, and fueling European imperial expansion.',
  },
  {
    lessonId: 'modern-02',
    regionName: 'The Two World Wars',
    bounds: { north: 65, south: 25, east: 52, west: -10 },
    markers: [
      { lat: 44.82, lon: 20.46, label: 'Sarajevo', description: 'Assassination of Franz Ferdinand (June 28, 1914) triggered WWI' },
      { lat: 49.16, lon: 5.38, label: 'Verdun', description: "WWI's longest battle (1916); ~700,000 casualties" },
      { lat: 49.37, lon: -0.74, label: 'Normandy', description: 'D-Day Allied landings (June 6, 1944); turned the tide in Western Europe' },
      { lat: 48.7, lon: 44.5, label: 'Stalingrad', description: "WWII's decisive Eastern Front battle (1942–43); ~2 million casualties" },
      { lat: 50.03, lon: 19.2, label: 'Auschwitz', description: 'Nazi death camp; site of the systematic murder of 1.1 million Jews' },
      { lat: 52.52, lon: 13.4, label: 'Berlin', description: 'Germany\'s capital; divided after WWII into East and West sectors' },
      { lat: 34.39, lon: 132.45, label: 'Hiroshima', description: 'First city destroyed by an atomic bomb (August 6, 1945)' },
    ],
    description: 'The two World Wars (1914–1918 and 1939–1945) together killed over 100 million people and reshaped the world order. WWI destroyed four empires; WWII produced the Holocaust, the United Nations, and the atomic age. The post-WWII order — NATO, the UN, the Marshall Plan — shaped global politics for decades.',
  },
  {
    lessonId: 'modern-03',
    regionName: 'The Cold War World',
    bounds: { north: 78, south: -15, east: 180, west: -180 },
    markers: [
      { lat: 38.9, lon: -77.04, label: 'Washington D.C.', description: 'Capital of the Western alliance; headquarters of NATO policy' },
      { lat: 55.75, lon: 37.62, label: 'Moscow', description: 'Capital of the Soviet Union; center of the Eastern bloc' },
      { lat: 52.52, lon: 13.4, label: 'Berlin', description: 'Divided city on the Iron Curtain; the Berlin Wall (1961–1989) symbolized the Cold War' },
      { lat: 23.13, lon: -82.38, label: 'Havana', description: 'Soviet-backed Cuba; site of the 1962 Missile Crisis' },
      { lat: 39.02, lon: 125.74, label: 'Pyongyang', description: "North Korea; divided after the 1950–53 Korean War along the 38th parallel" },
      { lat: 10.82, lon: 106.63, label: 'Saigon (Ho Chi Minh City)', description: 'South Vietnamese capital; fell to North Vietnam in 1975' },
      { lat: 34.52, lon: 69.18, label: 'Kabul', description: 'Soviet invasion of Afghanistan (1979) reignited Cold War tensions' },
    ],
    description: "The Cold War (1947–1991) was an ideological contest between US-led liberal democracy and Soviet communism. Both superpowers built nuclear arsenals capable of destroying civilization; they competed through proxy wars, space races, and economic aid. The Soviet Union's collapse in 1991 ended the Cold War.",
  },
  {
    lessonId: 'modern-04',
    regionName: 'The Globalized World',
    bounds: { north: 75, south: -45, east: 180, west: -180 },
    markers: [
      { lat: 40.71, lon: -74.0, label: 'New York', description: 'Global financial center; site of the 9/11 attacks (2001)' },
      { lat: 51.51, lon: -0.12, label: 'London', description: 'Major global financial hub; home of the World Wide Web inventor (Tim Berners-Lee)' },
      { lat: 31.23, lon: 121.47, label: 'Shanghai', description: "Symbol of China's economic rise; fastest-growing megacity of the 21st century" },
      { lat: 1.35, lon: 103.82, label: 'Singapore', description: 'Hub of global trade in Southeast Asia; model of development economics' },
      { lat: 25.2, lon: 55.27, label: 'Dubai', description: 'Transformed from desert to global hub within decades; symbol of Gulf modernization' },
      { lat: 19.08, lon: 72.88, label: 'Mumbai', description: "India's financial capital; anchor of the world's largest democracy's rise" },
      { lat: -23.55, lon: -46.64, label: 'São Paulo', description: "South America's largest city; Brazil's economic powerhouse" },
    ],
    description: 'The internet, containerized shipping, and the fall of trade barriers created a globalized world economy after 1990. Hundreds of millions were lifted out of poverty — especially in China and India. Yet globalization also intensified inequality within nations, and the 2008 financial crisis revealed how interconnected and fragile the global system had become.',
  },
  {
    lessonId: 'modern-05',
    regionName: 'Colonial Africa',
    bounds: { north: 40, south: -36, east: 52, west: -20 },
    markers: [
      { lat: 30.06, lon: 31.24, label: 'Cairo', description: 'Capital of Egypt; under British control from 1882' },
      { lat: 6.45, lon: 3.39, label: 'Lagos', description: 'Major British colonial port in Nigeria' },
      { lat: -4.32, lon: 15.32, label: 'Leopoldville (Kinshasa)', description: "Capital of Leopold II's Congo Free State; center of rubber terror" },
      { lat: -1.29, lon: 36.82, label: 'Nairobi', description: 'Founded as a British railway camp; became capital of British East Africa' },
      { lat: 9.03, lon: 38.74, label: 'Addis Ababa', description: "Ethiopian capital; Menelik II's base for the victory at Adwa (1896)" },
      { lat: -33.92, lon: 18.42, label: 'Cape Town', description: 'Site of the Berlin Conference\'s legacy; where Rhodes dreamed of Cape-to-Cairo' },
      { lat: -26.2, lon: 28.04, label: 'Johannesburg', description: 'Founded 1886 after gold discovery; center of South African industrialization' },
    ],
    description: 'The Scramble for Africa (1880–1914) saw European powers divide the entire continent among themselves — without consulting a single African leader. The Berlin Conference of 1884–85 drew the borders. By 1914, only Ethiopia and Liberia remained independent. The colonial legacy shapes Africa\'s political geography to this day.',
  },
  {
    lessonId: 'modern-06',
    regionName: 'The Former Yugoslavia',
    bounds: { north: 50, south: 39, east: 28, west: 12 },
    markers: [
      { lat: 45.81, lon: 15.98, label: 'Zagreb', description: 'Capital of Croatia; declared independence June 1991' },
      { lat: 46.05, lon: 14.51, label: 'Ljubljana', description: "Capital of Slovenia; won independence after a 10-day war in 1991" },
      { lat: 43.84, lon: 18.36, label: 'Sarajevo', description: 'Capital of Bosnia; besieged for 44 months (longest siege of a capital in modern history)' },
      { lat: 44.82, lon: 20.46, label: 'Belgrade', description: 'Serbian capital; seat of Milošević\'s government' },
      { lat: 44.1, lon: 19.3, label: 'Srebrenica', description: 'Site of the 1995 genocide: 8,000+ Bosniak men and boys murdered' },
      { lat: 45.35, lon: 18.99, label: 'Vukovar', description: 'Croatian city shelled for 87 days in 1991; symbol of the war\'s brutality' },
      { lat: 42.67, lon: 21.17, label: 'Pristina', description: "Kosovo's capital; NATO intervened to stop ethnic cleansing in 1999" },
    ],
    description: "Yugoslavia's violent dissolution (1991–2001) produced the worst atrocities in Europe since WWII. Ethnic nationalism unleashed by communism's collapse drove wars in Slovenia, Croatia, Bosnia, and Kosovo. The Srebrenica massacre (1995) — 8,000 Bosniaks murdered in a UN 'safe area' — was ruled genocide by the International Court of Justice.",
  },
  {
    lessonId: 'modern-07',
    regionName: 'Macedonia & the Balkans (1900–1913)',
    bounds: { north: 44, south: 39, east: 26, west: 19 },
    markers: [
      { lat: 40.64, lon: 22.94, label: 'Thessaloniki', description: 'Ottoman-controlled city; center of the Macedonian Struggle and Young Turk revolution' },
      { lat: 42.0, lon: 21.43, label: 'Skopje', description: 'Major Macedonian city under Ottoman rule; became Serbian after 1912' },
      { lat: 41.37, lon: 21.25, label: 'Krushevo', description: 'Site of the short-lived Krushevo Republic (10 days in August 1903)' },
      { lat: 41.12, lon: 20.8, label: 'Ohrid', description: 'Ancient city; seat of the Archbishopric of Ohrid with contested Greek/Bulgarian allegiance' },
      { lat: 41.03, lon: 21.35, label: 'Bitola (Monastir)', description: 'Major city contested by all three powers; where young Atatürk served as officer' },
      { lat: 42.7, lon: 23.32, label: 'Sofia', description: "Bulgarian capital; Bulgaria's IMRO organized from here" },
      { lat: 40.94, lon: 24.4, label: 'Kavala', description: 'Aegean port city; became Greek after the Balkan Wars' },
    ],
    description: 'The Macedonian Struggle (1904–1908) was a covert guerrilla war between Greek, Bulgarian, and Serbian armed bands fighting for control of Ottoman Macedonia — and for the identity of its mixed Orthodox population. It ended not with Macedonian autonomy but with partition after the Balkan Wars of 1912–1913.',
  },
];

export function getLessonMapData(lessonId: string): LessonMapData | undefined {
  return LESSON_MAPS.find(m => m.lessonId === lessonId);
}
