import type { Lesson } from '@/types';

// ─── Curriculum Expansion II — the road to 132 lessons (22 per era) ───────────
// Two further lessons per era, deepening the deep-time, world-history, and
// history-of-science coverage: the age of the dinosaurs and the Ice Ages before
// humanity; early sub-Saharan Africa, Mesoamerica, the Khmer, Great Zimbabwe,
// the Swahili coast, Songhai, and the Pacific; and the modern conquest of space
// and disease. Each lesson runs the full six sections. English is authoritative;
// every non-English language is localized at runtime (dynamicLessonTranslation).

export const LESSONS_EXPANSION_2: Lesson[] = [
  // ══════════════════════ PREHISTORIC (21–22) ══════════════════════
  { id: 'prehistoric-21', eraId: 'prehistoric', order: 21, title: 'The Age of Dinosaurs', subtitle: 'Deep Time and the Reign of the Reptiles', estimatedMinutes: 16, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tyrannosaurus_Rex_Holotype.jpg',
    keyFacts: ['Dinosaurs ruled the Earth for about 165 million years', 'They first appeared in the Triassic, ~230 million years ago', 'A giant asteroid impact ended their reign ~66 million years ago', 'Birds are living dinosaurs — the lineage never fully died out'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Meaning of Deep Time', body: 'Long before the first human being — before mammals, before flowers, before the continents took their modern shapes — the Earth belonged to the dinosaurs. To understand prehistory in its fullest sense is to confront "deep time," the almost unimaginable vastness of the planet\'s 4.5-billion-year history. All of human existence, from the first stone tools to the present, occupies only the last thin sliver of that story.\n\nThe age of dinosaurs is a powerful way to grasp this scale. These animals dominated the land for some 165 million years — roughly a thousand times longer than our own species has existed. When we speak of the "prehistoric," we usually mean the human past before writing; but the same rock layers that preserve ancient tools also preserve, far deeper down, the bones of creatures from a world with no people in it at all.' },
      { heading: 'The Rise of the Dinosaurs', body: 'Dinosaurs emerged during the Triassic period, around 230 million years ago, in the aftermath of the greatest mass extinction in Earth\'s history — the "Great Dying," which had wiped out most life on the planet. Into the emptied world stepped a new group of reptiles, walking upright on legs positioned beneath their bodies rather than sprawling to the sides. That posture gave them speed, endurance, and an edge over their rivals.\n\nAt first dinosaurs were modest in size, sharing the land with other reptiles. But as the supercontinent Pangaea slowly broke apart and climates shifted, they diversified and grew. By the Jurassic period they had become the dominant land animals on Earth, filling nearly every role — hunters and grazers, giants and sprinters — in ecosystems utterly unlike anything alive today.' },
      { heading: 'Giants of the Jurassic', body: 'The Jurassic period, from about 200 to 145 million years ago, was the golden age of the great long-necked sauropods — creatures like Brachiosaurus and Diplodocus that rank among the largest animals ever to walk the Earth. Some stretched longer than a tennis court and weighed as much as a dozen elephants, browsing the tops of tall conifers with necks that swung like living cranes.\n\nAround them moved a rich cast: plated Stegosaurus with its spiked tail, swift predators, and in the skies the pterosaurs — flying reptiles, not dinosaurs, but rulers of the air. In the seas swam ichthyosaurs and plesiosaurs. It was a world of ferns and cycads and towering evergreens, warm and green from pole to pole, with no grass, no flowers as we know them, and no familiar birdsong — only the alien calls of the reptile age.' },
      { heading: 'The Cretaceous World', body: 'In the Cretaceous period, the last great chapter of the dinosaur age, the world grew more familiar. Flowering plants appeared and spread, transforming landscapes and co-evolving with the first pollinating insects. The continents drifted toward their modern positions, and dinosaur life reached its greatest variety — horned Triceratops, armored Ankylosaurus, duck-billed herds, and the crested and clawed hunters of many lands.\n\nThis was the age of the most famous dinosaur of all: Tyrannosaurus rex, a predator up to twelve metres long with a bone-crushing bite unmatched in the animal kingdom. Yet for all its power, T. rex lived at the very end of the dinosaurs\' reign. The world it ruled, teeming and ancient, was about to end in a single catastrophic instant.' },
      { heading: 'The Day the Sky Fell', body: 'About 66 million years ago, an asteroid perhaps ten kilometres across slammed into what is now the Yucatán Peninsula of Mexico, striking with the force of billions of atomic bombs. The impact threw enormous quantities of rock and dust into the atmosphere, triggered wildfires and tsunamis, and shrouded the planet in a darkness that lasted for years. Photosynthesis faltered, food chains collapsed, and a long, cold winter descended.\n\nIn this catastrophe, the non-bird dinosaurs — along with the flying pterosaurs, the great marine reptiles, and countless other species — vanished forever. It was one of the five great mass extinctions in Earth\'s history. The buried layer of iridium-rich clay that marks this moment can be found in rocks around the world: a thin dark line separating the age of dinosaurs from the age of mammals, and ultimately, of us.' },
      { heading: 'Reading the Bones', body: 'Everything we know of this vanished world comes from fossils — bones, teeth, eggs, footprints, and even skin impressions turned to stone over millions of years. Paleontology, the science of ancient life, reconstructs these lost creatures the way archaeology reconstructs the human past: as detective work, reading clues the deep past never meant to leave. Each new fossil rewrites and refines the story.\n\nOne of its greatest discoveries is that the dinosaurs never entirely died. A lineage of small, feathered, meat-eating dinosaurs survived the catastrophe and became the birds — so every sparrow and eagle alive today is a living dinosaur, the last heir of the Mesozoic. In this way the age of dinosaurs connects directly to our own world, a reminder that the history of life, like human history, is one long unbroken chain reaching back through the depths of time.' },
    ] },

  { id: 'prehistoric-22', eraId: 'prehistoric', order: 22, title: 'The Ice Ages', subtitle: 'Frozen Worlds and the Human Crucible', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Woolly_mammoth_model_Royal_BC_Museum_in_Victoria.jpg',
    keyFacts: ['The last Ice Age peaked about 20,000 years ago', 'Vast ice sheets covered much of North America and Europe', 'Lower sea levels opened land bridges that reshaped human migration', 'Ice Age climate swings drove human adaptation and invention'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Planet of Ice', body: 'For much of the last two and a half million years — the geological epoch called the Pleistocene — the Earth was gripped by recurring ice ages. Great sheets of ice, kilometres thick, advanced and retreated across the northern continents dozens of times, sculpting the land, gouging out lakes and valleys, and locking up so much of the world\'s water that the oceans fell far below their present levels.\n\nThis frozen world was the crucible in which humanity was forged. Our species and its close relatives evolved, spread, and survived amid these dramatic climate swings. To be human is, in a sense, to be a child of the Ice Age — shaped by cold, scarcity, and the constant need to adapt to a world that would not hold still.' },
      { heading: 'The Rhythm of Ice', body: 'Ice ages are not random. They follow slow, regular cycles driven by subtle variations in the Earth\'s orbit and the tilt of its axis — the Milankovitch cycles — which change how much sunlight reaches the northern latitudes over tens of thousands of years. When summers grow cool enough that winter snow no longer fully melts, ice begins to accumulate, and over millennia it builds into continental glaciers.\n\nWithin the long glacial periods came warmer spells, and the deep cold was punctuated by abrupt swings that could transform the climate within a human lifetime. This restless, unpredictable world demanded flexibility. Human groups had to track shifting herds, changing coastlines, and vanishing forests — and those best able to innovate, cooperate, and plan ahead were the ones who endured.' },
      { heading: 'The Mammoth Steppe', body: 'At the height of the last glaciation, a vast, cold grassland stretched across the northern hemisphere from Europe deep into Asia and beyond — the "mammoth steppe," the largest biome on Earth at the time. It teemed with great Ice Age beasts: woolly mammoths and woolly rhinoceroses, giant deer, bison, wild horses, and the cave lions and bears that hunted them.\n\nHumans lived among these giants and hunted them, wringing survival from a frozen land. From mammoths they took meat, hides, fat for fuel, and great curved tusks and bones — even building shelters from mammoth bone where no wood grew. This intimate, dangerous partnership with the megafauna of the steppe shaped Ice Age cultures across two continents and filled the imaginations of the cave painters.' },
      { heading: 'Bridges of Land and Ice', body: 'Because so much water was locked in the ice sheets, sea levels during the last glacial maximum stood more than 120 metres lower than today. Shallow seas became dry plains, and new land bridges connected regions now divided by water. Britain was joined to Europe; Southeast Asian islands merged into a single peninsula; and, most consequentially, Siberia was linked to Alaska across the grasslands of Beringia.\n\nThese exposed corridors reshaped the human map. Across Beringia came the first peoples of the Americas; across other lowlands humans and animals moved into lands they could never otherwise have reached. When the ice melted and the seas rose again, these bridges drowned — stranding populations, flooding ancient coastlines, and severing the connections that Ice Age geography had briefly opened.' },
      { heading: 'Invented in the Cold', body: 'The pressures of Ice Age life drove some of humanity\'s most important innovations. To survive bitter winters, people mastered fire, tailored fitted clothing with bone needles, and built durable shelters. They developed new hunting technologies — the spear-thrower and eventually the bow — and complex strategies of cooperation to bring down large and dangerous game.\n\nThe cold also seems to have concentrated the mind and the spirit. It was during the last Ice Age that humans created the great cave paintings, carved figurines, and personal ornaments that mark the flowering of symbolic thought. Scarcity and hardship did not crush our ancestors; they sharpened them, fostering the planning, artistry, and social bonds that are hallmarks of the human mind.' },
      { heading: 'The Great Thaw', body: 'Around 11,700 years ago, the last glacial period ended and the world entered the warm, stable epoch we still live in: the Holocene. The ice sheets retreated, forests spread north, seas rose to their modern levels, and the mammoth steppe and its giants faded into extinction. Into this gentler, more predictable world, human beings began the experiment that would change everything — agriculture.\n\nIt is almost certainly no coincidence that farming, permanent villages, and eventually civilization all arose in the warm, steady climate that followed the Ice Age. The end of the great cold opened the door to the Neolithic Revolution and everything after it. Our entire recorded history has unfolded within this single warm interval — a brief, benign pause in the long, cold rhythm of the ice.' },
    ] },

  // ══════════════════════ ANCIENT (21–22) ══════════════════════
  { id: 'ancient-21', eraId: 'ancient', order: 21, title: 'Africa Before Rome', subtitle: 'Nok, Bantu, and the Iron Frontier', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Nok_sculpture_Louvre_70-1998-11-1.jpg',
    keyFacts: ['The Nok culture of Nigeria made terracotta art by ~1000 BCE', 'Sub-Saharan Africa developed ironworking early and independently', 'The Bantu migrations spread languages and farming across a continent', 'Aksum in Ethiopia became a major trading empire and early Christian state'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Continent of Its Own Story', body: 'While Greece and Rome rose around the Mediterranean, sub-Saharan Africa followed its own rich and independent path — one long neglected in traditional histories that treated the continent below the Sahara as timeless and changeless. In truth, ancient Africa was a place of innovation: of accomplished artists, ironworkers, farmers, and traders who built cultures and kingdoms across an immense and varied land.\n\nRecovering this history means looking beyond written records, for many African societies passed their knowledge orally rather than in texts. Archaeology, linguistics, and oral tradition together reveal a continent alive with movement and creativity in the centuries when the classical Mediterranean world was taking shape.' },
      { heading: 'The Nok and Their Sculptures', body: 'In what is now central Nigeria, from around 1000 BCE, the Nok culture produced some of the oldest known sculpture in sub-Saharan Africa: striking terracotta heads and figures with elaborate hairstyles, expressive features, and pierced eyes. These works, rediscovered by chance in the twentieth century, reveal a sophisticated artistic tradition flourishing more than two and a half thousand years ago.\n\nThe Nok were also early ironworkers, smelting metal in furnaces at a time when much of the world still relied on bronze or stone. Their culture, which lasted for centuries, hints at organized communities with specialized crafts and shared artistic conventions — a vivid reminder that monumental creativity in Africa long predates any outside contact.' },
      { heading: 'The Mastery of Iron', body: 'Ironworking was one of ancient Africa\'s defining technologies. In many parts of the continent, iron smelting appeared early and, unusually, without a preceding bronze age — a sign of independent invention rather than borrowing. African smiths built tall furnaces, fed them with charcoal, and produced iron for tools and weapons that transformed farming and warfare.\n\nIron gave communities the means to clear dense forest, till heavy soils, and expand into new lands. The smith, master of fire and transformation, held a place of power and mystery in many African societies, his craft wrapped in ritual. The spread of ironworking helped fuel one of the greatest population movements in human history.' },
      { heading: 'The Bantu Migrations', body: 'Beginning several thousand years ago in the region of modern Cameroon and Nigeria, groups speaking early Bantu languages began to migrate outward — a slow, centuries-long expansion that eventually carried their languages, farming, and iron technology across much of central, eastern, and southern Africa. It was one of the largest and most consequential migrations in the human story.\n\nThe Bantu-speaking peoples brought crops, cattle, and metallurgy into new lands, mingling with and sometimes displacing earlier hunter-gatherer populations. Today hundreds of related Bantu languages are spoken by a third of Africa\'s people — a living testament to this vast diffusion. The map of modern Africa is in large part the legacy of these ancient farmers on the move.' },
      { heading: 'Kush and Aksum', body: 'Along the Nile south of Egypt, the kingdom of Kush built pyramids of its own and, for a time, its kings ruled Egypt itself as pharaohs. From its capital at Meroë, Kush grew wealthy on iron and trade, developing its own script and a distinctive civilization that endured for centuries as a bridge between the Mediterranean and the African interior.\n\nFarther east, in the highlands of what is now Ethiopia and Eritrea, the empire of Aksum rose as a great trading power, its ports linking Africa to Arabia, India, and Rome. Aksum minted its own coins, raised towering stone stelae, and in the fourth century CE adopted Christianity — becoming one of the earliest Christian states in the world, whose church endures to this day.' },
      { heading: 'The Roots of Later Empires', body: 'The achievements of ancient Africa laid foundations for the celebrated empires that would follow. The ironworking, farming, and trade networks established in these early centuries made possible the later rise of Ghana, Mali, and Songhai in the west, and Great Zimbabwe and the Swahili city-states in the east and south.\n\nTo study Africa before Rome is to correct an old and damaging silence. Far from standing outside history, the peoples of ancient sub-Saharan Africa were active makers of it — sculpting, smelting, migrating, trading, and building states — during the very centuries when the classical world we more often celebrate was itself coming into being.' },
    ] },

  { id: 'ancient-22', eraId: 'ancient', order: 22, title: 'The Olmec and Early Mesoamerica', subtitle: 'The Mother Culture of the Americas', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Olmec_Head_No._3.jpg',
    keyFacts: ['The Olmec flourished in Mexico from ~1200 BCE', 'They carved colossal basalt heads weighing many tonnes', 'Mesoamericans domesticated maize, the staple of the Americas', 'The Olmec influenced later Maya and Aztec civilizations'],
    relatedTimeline: [],
    sections: [
      { heading: 'Civilization in the New World', body: 'The peoples of the Americas, isolated from the Old World for thousands of years, built their own civilizations entirely independently — inventing cities, monumental art, calendars, and writing without any contact with Mesopotamia, Egypt, or China. The heartland of this achievement was Mesoamerica, the region stretching across central and southern Mexico into Central America.\n\nHere, in the humid lowlands along the Gulf of Mexico, arose the first great civilization of the Americas: the Olmec. Often called the "mother culture" of Mesoamerica, the Olmec established patterns of art, religion, and society that later peoples — the Maya, the Zapotec, and ultimately the Aztec — would inherit and build upon over the following two thousand years.' },
      { heading: 'The Gift of Maize', body: 'At the root of Mesoamerican civilization lay a single, remarkable achievement: the domestication of maize. Over many generations, ancient farmers transformed a wild grass called teosinte, with its tiny hard kernels, into corn — a nourishing, storable staple that could feed dense populations. It was one of the most important feats of plant breeding in human history.\n\nMaize became far more than food. It was woven into religion and myth, revered as a divine gift and, in some traditions, as the very substance from which humans were made. The reliable surpluses that maize agriculture provided freed people from constant foraging and made possible the villages, cities, priests, and rulers on which civilization depended.' },
      { heading: 'The Colossal Heads', body: 'The most famous creations of the Olmec are their colossal stone heads: massive portraits carved from single blocks of basalt, some standing three metres tall and weighing many tonnes. Each face is distinct, with individual features and a helmet-like headdress, suggesting they portray specific rulers — powerful individuals commemorated in enduring stone.\n\nThe achievement is staggering. The basalt was quarried in distant mountains and somehow transported dozens of kilometres, without draft animals or the wheel, to the Olmec centers where it was carved with stone tools. That such effort was devoted to portraying rulers speaks of a society with strong central authority, organized labour, and the capacity to mobilize resources across a wide territory.' },
      { heading: 'Cities of the Gulf', body: 'The Olmec built the first true ceremonial centers in the Americas, at sites like San Lorenzo and La Venta. These were not cities in the modern sense but planned complexes of earthen mounds, plazas, and monuments, arranged with care and serving as hubs of religion, trade, and power. At La Venta, a great clay pyramid rose above the surrounding wetlands.\n\nFrom these centers the Olmec traded far and wide, exchanging jade, obsidian, and other precious materials across Mesoamerica. Their distinctive art — jaguar imagery, were-creatures, and finely carved jade — spread with these networks, carrying Olmec ideas and beliefs to distant peoples and seeding a shared cultural world that would outlast the Olmec themselves.' },
      { heading: 'Counting Time and the Cosmos', body: 'The Mesoamericans became extraordinary observers of the heavens and keepers of time. Building on foundations that reach back to the Olmec, they developed sophisticated calendars, tracked the movements of the sun, moon, and Venus, and grasped the mathematical concept of zero — an idea that eluded many Old World civilizations.\n\nThey also developed early writing and record-keeping, using glyphs to note dates, rulers, and events. Religion pervaded this intellectual life: the calendar governed rituals, agriculture, and warfare, and the cosmos was seen as a delicate balance requiring human offerings to sustain it. These traditions, first stirring in the Olmec world, would reach their fullest flowering among the Maya.' },
      { heading: 'An Enduring Inheritance', body: 'The Olmec civilization faded by around 400 BCE, its great centers abandoned for reasons still debated. But its legacy did not die. The gods, the ballgame, the calendar, the art of monumental sculpture, and the very idea of the ceremonial city passed down to the civilizations that followed, forming the deep bedrock of Mesoamerican culture.\n\nWhen the Maya raised their temples, when the Aztec built their capital in a lake, they were heirs of a tradition first shaped in the Olmec lowlands more than a thousand years before. The story of the Olmec is a powerful reminder that civilization arose more than once, in more than one hemisphere — and that the Americas hold a heritage of achievement as ancient and profound as any on Earth.' },
    ] },

  // ══════════════════════ BYZANTINE (21–22) ══════════════════════
  { id: 'byzantine-21', eraId: 'byzantine', order: 21, title: 'The Macedonian Renaissance', subtitle: 'Byzantium\'s Golden Age of Learning', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Paris_psaulter_gr139_fol1v.jpg',
    keyFacts: ['The Macedonian dynasty ruled Byzantium from 867 to 1056', 'It sparked a revival of classical learning and art', 'Byzantine scholars preserved ancient Greek texts for the world', 'The empire reached a new height of wealth and culture'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Revival in the East', body: 'While western Europe passed through what was once called its "dark ages," the Byzantine Empire — the surviving eastern half of the Roman world — experienced a brilliant cultural revival under the Macedonian dynasty, which came to power in 867. This "Macedonian Renaissance" saw a renewed love of the classical past, a flowering of art and scholarship, and a confident, prosperous empire at the height of its powers.\n\nCenturies before the Italian Renaissance, Byzantine scholars turned back to the literature, philosophy, and science of ancient Greece and Rome. In the libraries and workshops of Constantinople, the achievements of antiquity were studied, copied, and treasured — a conscious effort to reconnect with a glorious heritage and to prove Byzantium the true heir of the classical world.' },
      { heading: 'Guardians of Ancient Wisdom', body: 'One of Byzantium\'s greatest gifts to civilization was its preservation of ancient Greek literature. Most of the classical Greek texts we possess today — Homer and Plato, Aristotle and Euclid, the tragedians and historians — survived because Byzantine scribes patiently copied them by hand, generation after generation, in the empire\'s monasteries and schools.\n\nThe Macedonian era gave this work new energy. Scholars like the patriarch Photios compiled and summarized vast bodies of ancient writing; a new, clearer style of handwriting made texts easier to reproduce. Without this centuries-long labor of preservation, much of the wisdom of antiquity would have been lost forever. When these texts later reached the West, they would help ignite the European Renaissance itself.' },
      { heading: 'Beauty in Gold and Ivory', body: 'The Macedonian Renaissance produced some of the finest Byzantine art. Freed from the earlier bans of the iconoclast controversy, artists filled churches with radiant mosaics and painted icons, and created exquisite small treasures in ivory, enamel, and precious metal. A renewed appreciation of classical forms brought a new grace and naturalism to the human figure.\n\nManuscripts were adorned with luminous illustrations, some deliberately echoing ancient models. The famous Paris Psalter, with its scenes painted almost in the manner of classical antiquity, embodies the era\'s marriage of Christian devotion and classical beauty. Byzantine art of this age set standards of splendor admired and imitated across the medieval world, from the Slavic lands to Italy.' },
      { heading: 'An Empire Restored', body: 'The Macedonian emperors were not only patrons of culture but formidable soldiers and statesmen. Under rulers like Basil II, Byzantium went on the offensive, recovering lost territory, securing its frontiers, and dominating its neighbors. The empire\'s wealth, drawn from trade and a well-run administration, funded both its armies and its arts.\n\nConstantinople in this age was the greatest city of the Christian world — vast, rich, and dazzling to visitors from humbler lands. Its markets overflowed with goods from three continents; its court dazzled with ceremony; its walls seemed impregnable. The confidence of the Macedonian Renaissance flowed from this restored strength: a civilization sure of its place as the enduring center of the Roman and Christian world.' },
      { heading: 'Learning and the Law', body: 'The revival extended to education and government. Constantinople\'s schools trained officials in rhetoric, philosophy, and law; a reorganized university nurtured advanced learning. The great legal inheritance of Justinian was restated and updated, keeping Roman law alive as a living system and a model that would influence legal thought far beyond Byzantium\'s borders.\n\nThis marriage of scholarship and statecraft gave the empire a highly educated elite and a sophisticated bureaucracy that were the envy of the age. Byzantine diplomacy, informed by deep learning and long memory, managed a complex world of rivals through cunning as much as force — one reason the empire, though often beset, endured for so many centuries.' },
      { heading: 'A Light That Reached the World', body: 'The Macedonian Renaissance radiated far beyond the empire\'s frontiers. Byzantine missionaries, art, and learning shaped the emerging Slavic world, carrying the Orthodox faith, the Cyrillic alphabet, and Byzantine models of kingship to the Rus, the Bulgarians, and the Serbs. The cultural DNA of eastern Europe was profoundly marked by this golden age.\n\nAnd when, centuries later, Byzantine scholars fleeing a shrinking empire carried their precious Greek manuscripts westward to Italy, they helped set alight the Renaissance that transformed Europe. The classical learning that Byzantium had guarded through long centuries became a gift to all humanity — a golden thread running from ancient Athens, through Constantinople, into the modern world.' },
    ] },

  { id: 'byzantine-22', eraId: 'byzantine', order: 22, title: 'Heirs of Constantinople', subtitle: 'The Long Byzantine Legacy', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Saint_Basil%27s_Cathedral_in_Moscow.jpg',
    keyFacts: ['Constantinople fell to the Ottomans in 1453', 'Russia claimed to be the "Third Rome" after Byzantium', 'Byzantine art and faith shaped Orthodox Christianity forever', 'Greek learning fleeing east helped spark the Western Renaissance'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Fall and What Survived', body: 'In 1453, after more than eleven centuries, the Byzantine Empire finally fell as Ottoman armies breached the walls of Constantinople. The last Roman emperor died in the fighting, and the great Christian capital of the East became the Ottoman city of Istanbul. It was the end of an empire that had preserved the name and law of Rome for a thousand years after Rome itself had fallen.\n\nYet an empire\'s death is not the death of its civilization. Byzantium had shaped the faith, art, law, and identity of a vast swath of the world, and these legacies long outlived the political state. In churches, alphabets, laws, and ideas of kingship, the influence of Constantinople continued to echo across Europe and the Middle East for centuries after its fall.' },
      { heading: 'The Soul of Orthodoxy', body: 'Byzantium\'s most enduring legacy is Orthodox Christianity. The theology, liturgy, and spiritual traditions developed in the Byzantine world remain the living heart of the Orthodox churches followed today by hundreds of millions across Russia, the Balkans, the Middle East, and beyond. The soaring chant, the golden icons, the domed churches — all bear the unmistakable stamp of Constantinople.\n\nThe icon, in particular, remains central to Orthodox devotion, its style and meaning fixed by Byzantine tradition. The great debates that Byzantium fought over the nature of Christ and the use of images shaped Orthodox belief permanently. To worship in an Orthodox church today is to stand within a spiritual world that Byzantium built and bequeathed.' },
      { heading: 'The Third Rome', body: 'As Byzantium declined, a new power in the north claimed its inheritance. Moscow, having adopted Orthodox Christianity from Byzantium centuries earlier, came to see itself as the successor to the fallen empire. After 1453, Russian churchmen and rulers proclaimed Moscow the "Third Rome" — the last true guardian of Orthodox Christianity and imperial authority after Rome and Constantinople.\n\nThe grand princes of Moscow took the title "tsar," derived from "Caesar," and adopted the double-headed eagle of Byzantium as their emblem. Byzantine ideas of a sacred monarchy, ruling in partnership with the church, deeply shaped the Russian state for centuries. In the onion domes and golden icons of Russia, the spiritual and political vision of Byzantium found a powerful new home.' },
      { heading: 'A Gift to the West', body: 'In the empire\'s final century, as danger closed in, Byzantine scholars increasingly traveled to Italy, carrying with them their knowledge of ancient Greek and precious manuscripts unknown in the West. Italian humanists, hungry to recover the classical past, eagerly learned Greek at their feet and gained access to works of Plato, Aristotle, and other ancients long lost to western Europe.\n\nThis transfer of learning helped fuel the Italian Renaissance. The rediscovery of Greek philosophy and science, mediated by Byzantine teachers and texts, enriched European thought at a decisive moment. In a profound irony, the dying empire of the East helped give birth to the intellectual rebirth of the West — one civilization\'s twilight kindling another\'s dawn.' },
      { heading: 'Law, Art, and Statecraft', body: 'Byzantium\'s influence ran through the practical foundations of later societies as well. Its codification of Roman law, above all the great work of Justinian, preserved a legal tradition that would be rediscovered in medieval Europe and become the basis of legal systems across much of the world. The idea of a written, systematic body of law owes an immense debt to Constantinople.\n\nIn art and architecture, Byzantine models — the domed church, the mosaic, the icon, the ceremonial court — were imitated from Italy to Russia. Byzantine diplomacy, with its blend of ceremony, intelligence, and patience, offered a template for statecraft. The machinery of civilized government that Byzantium refined across a thousand years seeded institutions far beyond its borders.' },
      { heading: 'The Empire That Would Not Die', body: 'Historians once dismissed Byzantium as a stagnant, declining relic. That judgment has been overturned. We now see it as one of history\'s most resilient and creative civilizations — a state that survived crisis after crisis for over a millennium, preserved the heritage of antiquity, spread a great faith, and shaped the identities of nations still with us today.\n\nThe legacy of Constantinople endures wherever an Orthodox liturgy is sung, wherever Roman law underlies a legal code, wherever the classical learning it guarded is read. The empire fell in 1453, but its civilization never truly ended. It lives on, transformed and diffused, in the faith, culture, and institutions of a great part of the modern world — the deathless afterlife of the empire that called itself Rome.' },
    ] },

  // ══════════════════════ MIDDLE AGES (21–22) ══════════════════════
  { id: 'medieval-21', eraId: 'middle-ages', order: 21, title: 'Great Zimbabwe and the Swahili Coast', subtitle: 'Gold, Stone, and the Indian Ocean World', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Great_Zimbabwe_2.jpg',
    keyFacts: ['Great Zimbabwe was a stone-built city that peaked around 1300 CE', 'Its walls were raised without mortar from millions of granite blocks', 'The Swahili city-states linked Africa to India, Arabia, and China', 'Gold, ivory, and slaves flowed through a vast Indian Ocean trade'],
    relatedTimeline: [],
    sections: [
      { heading: 'A City of Stone in the South', body: 'In the interior of southern Africa, between the Zambezi and Limpopo rivers, rose one of medieval Africa\'s most impressive achievements: Great Zimbabwe. At its height around 1300, it was a thriving city of perhaps eighteen thousand people, its rulers commanding a wealthy kingdom built on cattle, gold, and trade. Its name, from a local word for "houses of stone," fits it well.\n\nThe city\'s great stone enclosures, with walls up to eleven metres high and five metres thick, were built entirely without mortar from millions of precisely fitted granite blocks. For centuries, prejudiced outsiders refused to believe Africans had built them, inventing fanciful foreign origins. Archaeology has decisively proven otherwise: Great Zimbabwe was the work of the ancestors of the region\'s Shona people, a monument to indigenous African genius.' },
      { heading: 'Gold and Cattle', body: 'The wealth of Great Zimbabwe flowed from two sources: vast herds of cattle, which measured status and stored wealth, and gold, mined across the surrounding plateau and traded to the coast. From there it entered the great commerce of the Indian Ocean, carrying the kingdom\'s riches to distant lands and bringing exotic goods back in return.\n\nArchaeologists have found at the site glass beads from India, porcelain from China, and coins from the Swahili coast — proof of a kingdom plugged into a trading world that spanned continents. Gold from the African interior adorned the courts of Asia, and the rulers of Great Zimbabwe grew rich as the crucial link between the mines of the south and the merchants of the sea.' },
      { heading: 'The Swahili City-States', body: 'Along the East African coast, from Somalia to Mozambique, a chain of prosperous trading cities arose — Kilwa, Mombasa, Zanzibar, and dozens more. These Swahili city-states blended African roots with influences from Arab and Persian traders who settled among them, creating a distinctive culture and the Swahili language, an African tongue enriched with Arabic words.\n\nThe Swahili cities were cosmopolitan and Muslim, their merchants sailing the monsoon winds to trade across the Indian Ocean. They built mosques and palaces of coral stone, imported luxuries from across Asia, and grew immensely wealthy. Kilwa, which controlled the gold trade from Great Zimbabwe\'s hinterland, was described by one Arab traveler as among the most beautiful cities he had ever seen.' },
      { heading: 'Riding the Monsoon', body: 'The engine of this world was the Indian Ocean monsoon, whose winds blow reliably in one direction for half the year and reverse for the other. Sailors learned to time their voyages to these seasonal rhythms, sailing from Africa to Arabia, India, and beyond, then waiting for the winds to turn before returning home. The monsoon knit the shores of the ocean into a single commercial system.\n\nAcross this network flowed an astonishing variety of goods: African gold, ivory, and timber; Indian cloth; Arabian horses; Chinese porcelain and silk; and, darkly, enslaved people. Ideas and religion traveled too, above all Islam, which spread along the trade routes to become the faith of the coastal cities. The Swahili coast was Africa\'s vibrant gateway to the wider medieval world.' },
      { heading: 'A Connected Medieval World', body: 'The story of Great Zimbabwe and the Swahili coast shatters the myth of a medieval Africa cut off and unchanging. Here was a continent deeply engaged with the wider world, its gold gilding Asian courts, its ports welcoming ships from a dozen lands, its cultures blending African and Indian Ocean influences into something new and sophisticated.\n\nChinese fleets under the admiral Zheng He even visited the Swahili coast in the early 1400s, taking an African giraffe back to the emperor as a wonder. Long before European ships arrived, East Africa was a full participant in one of the great commercial worlds of the age — proof that the medieval globe was far more interconnected than we often imagine.' },
      { heading: 'Echoes in the Ruins', body: 'Great Zimbabwe declined in the fifteenth century, perhaps as trade routes shifted or the land tired, and its people moved on to found successor kingdoms. But its stone towers still stand, and its soapstone bird carvings became a national emblem — so cherished that the modern nation of Zimbabwe took its very name from the ancient city.\n\nThe Swahili coast, too, was eventually disrupted, its cities battered when Portuguese fleets forced their way into the Indian Ocean around 1500. Yet Swahili culture and language endure, spoken today by many millions across East Africa. Together, these civilizations stand as enduring witnesses to the wealth, artistry, and global reach of medieval Africa.' },
    ] },

  { id: 'medieval-22', eraId: 'middle-ages', order: 22, title: 'The Khmer Empire and Angkor', subtitle: 'Temples, Water, and Power in Southeast Asia', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Angkor_Wat.jpg',
    keyFacts: ['The Khmer Empire dominated Southeast Asia from the 9th to 15th centuries', 'Angkor was the largest pre-industrial city in the world', 'Angkor Wat is the largest religious monument ever built', 'A vast system of canals and reservoirs sustained the empire'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Great Empire of the Khmer', body: 'In the tropical lands of mainland Southeast Asia, in what is now Cambodia and beyond, one of the medieval world\'s most powerful and creative civilizations flourished: the Khmer Empire. From the ninth to the fifteenth centuries, its god-kings ruled a vast realm, commanding immense wealth and labor and raising some of the most extraordinary monuments ever built by human hands.\n\nAt the heart of this empire lay Angkor, its sprawling capital. Recent surveys using laser mapping have revealed that Angkor was the largest city in the pre-industrial world — a low-density metropolis of temples, palaces, canals, and rice fields sprawling across an area comparable to a modern city, home to perhaps three-quarters of a million people at its height.' },
      { heading: 'Angkor Wat', body: 'The crowning glory of the Khmer is Angkor Wat, the largest religious monument on Earth. Built in the early twelfth century by King Suryavarman II, it was originally dedicated to the Hindu god Vishnu, its five great towers representing the sacred peaks of Mount Meru, home of the gods. Its scale is breathtaking: a temple-mountain surrounded by a moat so wide it resembles an inland sea.\n\nEvery surface tells a story. Nearly two kilometres of intricate stone reliefs wind around the temple, depicting Hindu epics, celestial dancers, and the king\'s own armies on the march. The precision of its construction, the harmony of its proportions, and the sheer ambition of its design make Angkor Wat one of humanity\'s supreme architectural achievements — a mountain of carved stone raised to bridge earth and heaven.' },
      { heading: 'Masters of Water', body: 'The true foundation of Khmer greatness was not stone but water. In a land of drenching monsoons and long dry seasons, the Khmer became master hydraulic engineers, building an enormous network of canals, moats, and vast reservoirs called barays. These captured the monsoon rains and distributed water across the landscape, allowing farmers to grow multiple rice crops each year.\n\nThis control of water underpinned everything. The rice surpluses it produced fed the great population of Angkor, freed labor to build the temples, and sustained the armies that expanded the empire. The Khmer kings presented themselves as the guarantors of this life-giving water, their power bound up with the flow that made civilization possible in the tropical plains.' },
      { heading: 'God-Kings and Faith', body: 'Khmer kings ruled as devaraja — "god-kings" — divine or semi-divine figures who linked their realms to the cosmic order. Their temples were not only places of worship but statements of royal power and instruments for securing the favor of the gods. To build a great temple was to earn spiritual merit and to proclaim one\'s glory for the ages.\n\nThe empire\'s religion shifted over time between Hinduism and Buddhism. Angkor Wat began as a Hindu temple; later, the extraordinary king Jayavarman VII embraced Buddhism and built the walled city of Angkor Thom, with its famous Bayon temple, whose towers bear dozens of enormous serene stone faces gazing out in every direction. Faith and kingship were forever intertwined in the Khmer world.' },
      { heading: 'The Decline of Angkor', body: 'By the fifteenth century, the great age of Angkor was ending. Historians debate the causes: strain on the vast water system, perhaps worsened by climate swings of severe droughts and floods; the rising cost of maintaining the empire; shifting trade routes; and pressure from neighboring kingdoms, especially the growing power of the Thai to the west, who sacked the capital.\n\nGradually the court moved away toward the region of modern Phnom Penh, and the mighty city of Angkor was largely abandoned to the encroaching forest. The elaborate waterworks fell into disrepair, and the jungle slowly wrapped its roots around the temples. The empire that had dominated Southeast Asia for six centuries faded, though the Khmer people and their culture endured.' },
      { heading: 'The Temples in the Jungle', body: 'For centuries the ruins of Angkor slumbered beneath the forest, never wholly forgotten by the Cambodian people but unknown to the wider world. When their scale was fully revealed to outside eyes in the nineteenth century, they astonished all who saw them, and today Angkor is recognized as one of the great wonders of human civilization and Cambodia\'s national symbol.\n\nAngkor Wat appears on the Cambodian flag — one of the only national flags to feature a building — a source of enduring pride and identity. The achievement of the Khmer stands as a reminder that some of history\'s greatest civilizations flourished far from the more familiar centers of Europe and the Middle East, in the tropical heart of Southeast Asia.' },
    ] },

  // ══════════════════════ EARLY MODERN (21–22) ══════════════════════
  { id: 'earlymod-21', eraId: 'early-modern', order: 21, title: 'The Songhai Empire', subtitle: 'Timbuktu and the Last Great Empire of the Sahel', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/University_of_Sankore_2.jpg',
    keyFacts: ['Songhai was the largest empire in West African history', 'It controlled the trans-Saharan gold and salt trade', 'Timbuktu was a renowned center of Islamic learning', 'A Moroccan invasion with firearms ended the empire in 1591'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Greatest of the Sahel Empires', body: 'Along the great bend of the Niger River, in the grasslands of West Africa known as the Sahel, a succession of powerful empires rose on the wealth of trade. First Ghana, then Mali, and finally Songhai — the largest of them all — dominated the region for centuries. At its height in the sixteenth century, the Songhai Empire stretched across a domain larger than western Europe.\n\nThese were not marginal states but wealthy, organized empires that commanded the respect of the wider world. Their power rested on control of the trans-Saharan trade, the flow of goods across the great desert that linked sub-Saharan Africa to the Mediterranean and the Islamic world. Whoever mastered this trade grew rich, and Songhai mastered it magnificently.' },
      { heading: 'Gold for Salt', body: 'The trans-Saharan trade was built on a deceptively simple exchange: gold for salt. West Africa possessed some of the richest goldfields in the medieval world, while the Sahara held vast deposits of salt, a substance essential for life and preservation that was scarce in the tropics. Camel caravans carried salt south and gold north, and both were sometimes valued nearly equally.\n\nAlong these routes moved far more than gold and salt: copper, cloth, books, enslaved people, and above all ideas and religion. Islam spread along the trade roads, becoming the faith of the empire\'s rulers and cities. The taxes Songhai levied on this immense commerce filled its treasury and funded its armies, its cities, and its famed centers of learning.' },
      { heading: 'Timbuktu, City of Books', body: 'The jewel of the Songhai Empire was Timbuktu, a fabled city on the edge of the desert that became one of the great intellectual centers of the Islamic world. Its markets traded in gold and salt, but its true glory was scholarship. The University of Sankore and the city\'s many schools drew students and teachers from across Africa and beyond to study law, theology, mathematics, astronomy, and medicine.\n\nTimbuktu was a city of books, home to a vast trade in manuscripts and to libraries holding hundreds of thousands of volumes. "In Timbuktu," one visitor recorded, books sold for more profit than any other goods. Tens of thousands of these manuscripts survive today, a precious written record that refutes forever the myth that Africa had no literate, learned civilizations of its own.' },
      { heading: 'Askia the Great', body: 'The Songhai Empire reached its zenith under Askia Muhammad, who seized power in 1493 and ruled for decades as one of Africa\'s most capable statesmen. He reorganized the sprawling empire into provinces with appointed governors, standardized taxation and trade, built a professional army, and established a system of justice rooted in Islamic law.\n\nA devout Muslim, Askia made a famous pilgrimage to Mecca with a great caravan, strengthening Songhai\'s ties to the wider Islamic world and its reputation for wealth and piety. Under his rule Timbuktu and other cities flourished as never before. His reign showed the sophistication of West African statecraft — a well-governed empire, its administration and learning the equal of any in the world at the time.' },
      { heading: 'The Fall to Firearms', body: 'For all its wealth and organization, Songhai met a sudden and brutal end. In 1591, the Sultan of Morocco, coveting the empire\'s gold, sent an army across the Sahara — a daring march of thousands of kilometres through the desert. The Songhai forces were far larger, but the Moroccans carried a decisive advantage: firearms and cannon, weapons the empire had never faced.\n\nAt the Battle of Tondibi, gunpowder shattered the massed Songhai army. The great empire collapsed with startling speed, its cities plundered and its unity broken. The fall of Songhai marked a turning point: the old trans-Saharan trade began to decline as European ships increasingly carried West African commerce by sea, and the golden age of the Sahel empires drew to a close.' },
      { heading: 'A Legacy Reclaimed', body: 'The memory of Songhai, Mali, and Timbuktu endured as a source of pride and a rebuke to those who denied Africa a history. The empire\'s scale, wealth, and learning stand among the great achievements of the early modern world, and the surviving manuscripts of Timbuktu — painstakingly preserved and studied today — offer an irreplaceable window into that world.\n\nIn recent times these treasures have faced new dangers, and heroic efforts have been made to rescue and protect the ancient libraries. Each saved manuscript is a victory for history itself. The story of Songhai reminds us that West Africa was home to empires as grand, as governed, and as learned as any of their age — a heritage now being reclaimed and celebrated.' },
    ] },

  { id: 'earlymod-22', eraId: 'early-modern', order: 22, title: 'Voyagers of the Pacific', subtitle: 'Polynesian Navigation and the Last Frontier', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Hokulea.jpg',
    keyFacts: ['Polynesians settled the vast Pacific using only the stars and waves', 'They reached islands from Hawaii to New Zealand to Easter Island', 'Voyaging canoes crossed thousands of kilometres of open ocean', 'It was the last great human colonization of the Earth'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Last Lands Settled', body: 'The islands scattered across the vast Pacific Ocean were the last habitable places on Earth to be reached by human beings. Long after people had spread across Africa, Asia, Europe, Australia, and the Americas, the remote islands of the open Pacific remained empty — until an extraordinary seafaring people, the Polynesians, set out to conquer the largest ocean on the planet.\n\nThe scale of their achievement is staggering. Across the "Polynesian Triangle," with its corners at Hawaii, New Zealand, and Easter Island, the Polynesians settled thousands of islands separated by immense stretches of open water. They accomplished this without metal, without writing, and without any of the navigational instruments of European sailors — a feat of exploration unmatched in human history.' },
      { heading: 'Reading the Ocean', body: 'How did they do it? Polynesian navigators developed a profound science of "wayfinding," reading the natural world with a precision that astonished later European explorers. They memorized the rising and setting points of hundreds of stars, using them as a compass across the night sky. They read the direction and pattern of ocean swells, feeling the subtle motion of the canoe to hold a course.\n\nThey watched the flight of seabirds that fly out to fish and return to land at dusk; noted the clouds that gather over unseen islands; observed the color of the water and the drift of debris. All this knowledge, held entirely in memory and passed down through generations of master navigators, allowed them to find tiny specks of land across thousands of kilometres of featureless sea.' },
      { heading: 'The Great Canoes', body: 'Polynesian voyages were made in remarkable vessels: large double-hulled canoes, lashed together with a platform between them, capable of carrying dozens of people along with the plants, animals, and supplies needed to found a new colony. Swift, seaworthy, and able to sail against the wind, these canoes were among the finest oceangoing craft of their era.\n\nSettling a new island was a deliberate act of colonization. Voyagers carried with them the "canoe plants" — taro, breadfruit, coconut, banana — and animals like pigs, dogs, and chickens, everything needed to transplant their way of life. That they sailed with such cargo shows these were not accidental drifts but planned expeditions, launched by a confident maritime culture reaching purposefully into the unknown.' },
      { heading: 'From Hawaii to Aotearoa', body: 'Over centuries, Polynesian voyagers reached and settled an astonishing array of lands. They found the Hawaiian Islands in the far north, thousands of kilometres from any other inhabited land. They reached remote Easter Island in the southeast, where their descendants would raise the famous giant stone statues. And around 1300, they made the long southern voyage to New Zealand — Aotearoa — the largest and last major landmass they settled, becoming the ancestors of the Māori.\n\nEach island world developed its own distinct culture while retaining deep common roots — related languages, shared myths, and a common heritage of voyaging. From the frozen edges of New Zealand to tropical atolls, the Polynesians adapted to wildly different environments, a single far-flung people bound together by the ocean their ancestors had mastered.' },
      { heading: 'Encounter and Disruption', body: 'When European explorers finally entered the Pacific in the age of sail, they were astonished to find nearly every habitable island already inhabited by peoples who shared related languages across an ocean-spanning distance. Navigators like the Tahitian priest Tupaia, who sailed with Captain Cook, amazed Europeans by drawing charts of dozens of islands from memory and guiding ships across the sea.\n\nBut contact brought disruption and tragedy. European diseases, to which the islanders had no immunity, swept through Pacific populations with devastating effect. Traders, missionaries, and eventually colonial powers transformed island societies, often violently. The proud voyaging traditions declined, and much precious navigational knowledge was lost as the old world of the Pacific was overturned.' },
      { heading: 'The Voyage Reborn', body: 'In modern times, the ancient art of Polynesian wayfinding has been triumphantly revived. In the 1970s, the voyaging canoe Hōkūleʻa sailed from Hawaii to Tahiti using only traditional navigation, guided by a master wayfinder from the last islands where the knowledge survived — proving that the great voyages could indeed have been made deliberately, as the ancestors always said.\n\nThis revival has become a powerful source of pride and cultural renewal across the Pacific, reconnecting island peoples with the genius of their forebears. The story of the Polynesian voyagers stands as one of the supreme achievements of the human spirit: ordinary people, armed with knowledge alone, who dared to cross the greatest ocean on Earth and made its scattered islands their home.' },
    ] },

  // ══════════════════════ MODERN (21–22) ══════════════════════
  { id: 'modern-21', eraId: 'modern', order: 21, title: 'The Space Age', subtitle: 'The Race to the Moon and Beyond', estimatedMinutes: 16, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aldrin_Apollo_11_original.jpg',
    keyFacts: ['Sputnik, the first satellite, launched in 1957', 'Yuri Gagarin became the first human in space in 1961', 'Apollo 11 landed humans on the Moon in 1969', 'Space exploration grew from Cold War rivalry into global science'],
    relatedTimeline: [],
    sections: [
      { heading: 'Humanity Leaves the Earth', body: 'For all of history, human beings had been bound to the surface of a single planet. Then, within a single astonishing decade, they broke free. The Space Age opened the greatest frontier ever crossed, as humanity sent machines and then people beyond the atmosphere into the void — an achievement that transformed science, technology, and our very sense of our place in the cosmos.\n\nThis leap grew out of an intense rivalry. The two superpowers of the Cold War, the United States and the Soviet Union, competed fiercely for prestige and strategic advantage, and the heavens became their arena. What began as a contest of missiles and propaganda became, almost in spite of itself, one of the noblest adventures in the human story.' },
      { heading: 'Sputnik and the Shock', body: 'The Space Age began on October 4, 1957, when the Soviet Union launched Sputnik, the first artificial satellite, into orbit. This small metal sphere, beeping as it circled the Earth every ninety minutes, stunned the world. That the Soviets had achieved it first shocked the United States and set off a frantic drive to catch up.\n\nSputnik reshaped politics, education, and science. Fearing they had fallen behind, Americans poured resources into science and technology and created a new space agency, NASA. The rockets that lifted satellites were cousins of those that carried nuclear weapons, so the race had a hard strategic edge. But it also fired the imagination of millions, opening an age of possibility that had until then belonged only to dreamers.' },
      { heading: 'The First Humans in Space', body: 'The Soviets struck again on April 12, 1961, when cosmonaut Yuri Gagarin became the first human being to journey into space, orbiting the Earth once and returning safely. His flight made him a global hero and confirmed Soviet leadership in the young Space Age. Weeks later the United States sent its own astronaut aloft, and the contest intensified.\n\nIn response, President John F. Kennedy set an audacious goal: to land a man on the Moon and return him safely before the decade was out. It was a staggering ambition, demanding technologies that did not yet exist. Yet it galvanized a national effort of extraordinary scale, mobilizing hundreds of thousands of engineers, scientists, and workers toward a single, seemingly impossible objective.' },
      { heading: 'One Giant Leap', body: 'On July 20, 1969, the goal was achieved. The Apollo 11 mission carried three astronauts to the Moon, and Neil Armstrong and Buzz Aldrin descended to its surface while Michael Collins orbited above. As Armstrong stepped onto the lunar dust, his words — "one small step for man, one giant leap for mankind" — were heard by an estimated 600 million people, the largest audience in history to that point.\n\nThe Moon landing was one of the supreme achievements of the twentieth century, a demonstration of what focused human effort could accomplish. Six Apollo missions ultimately landed twelve people on the Moon, who conducted experiments and returned with rocks that revealed the Moon\'s history. For a brief, shining moment, humanity had walked on another world.' },
      { heading: 'The View from Space', body: 'The Space Age gave humanity a profound new perspective: the sight of our own planet from beyond. Photographs like "Earthrise" and the "Blue Marble," showing the Earth as a small, fragile, beautiful sphere in the blackness of space, moved millions and helped inspire the modern environmental movement. Seen from the Moon, the planet\'s borders vanished and its unity became visible.\n\nBeyond inspiration, space technology transformed daily life in ways few anticipated. Satellites now carry our communications, forecast our weather, guide our navigation, and monitor the health of the planet. The drive to reach the Moon spun off countless innovations. The frontier opened in rivalry delivered practical benefits that touch nearly every person on Earth today.' },
      { heading: 'Beyond the Moon', body: 'After Apollo, human spaceflight turned to building a lasting presence in orbit — space stations where astronauts from many nations live and work for months, and where former rivals learned to cooperate. Meanwhile robotic explorers fanned out across the solar system, landing on Mars, visiting every planet, and even leaving the solar system entirely, extending human senses across billions of kilometres.\n\nToday the adventure continues in new forms, as private companies join national agencies, as nations old and new reach for the Moon and Mars, and as telescopes peer toward the very beginnings of the universe. The Space Age, born of Cold War fear, has matured into a shared human endeavor — the ongoing story of a species that, having mastered its own planet, has begun, tentatively, to reach for the stars.' },
    ] },

  { id: 'modern-22', eraId: 'modern', order: 22, title: 'The Conquest of Disease', subtitle: 'Medicine, Public Health, and Modern Life', estimatedMinutes: 15, xpReward: 130,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Penicillin_Past_Present_and_Future-_the_Development_and_Production_of_Penicillin%2C_England%2C_1943_D17203.jpg',
    keyFacts: ['Vaccination began with smallpox in the late 18th century', 'Germ theory transformed medicine in the 19th century', 'Antibiotics like penicillin arrived in the 20th century', 'Smallpox was eradicated worldwide by 1980'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Oldest Enemy', body: 'For nearly all of human history, disease was the great, inescapable killer. Plagues emptied cities, childhood illnesses carried off vast numbers of the young, and a simple infected wound could mean death. Average life expectancy remained low not because people could not grow old, but because so many died young of causes we now consider preventable or curable.\n\nThe modern conquest of disease is one of the most important and least celebrated revolutions in human history. Over the past few centuries, and especially the past hundred and fifty years, medicine and public health transformed the human condition, adding decades to the average lifespan and freeing billions from ancient terrors. It is a story of science, sanitation, and slow, hard-won understanding.' },
      { heading: 'The Birth of Vaccination', body: 'One of the first great victories came against smallpox, a disease that killed and disfigured millions. In the late eighteenth century, the English physician Edward Jenner noticed that milkmaids who had caught mild cowpox seemed immune to smallpox. In 1796 he tested the idea by deliberately exposing a boy to cowpox, then to smallpox — and the boy did not sicken. Vaccination was born.\n\nThe principle — training the body\'s defenses by exposing it to a harmless form of a germ — would become one of medicine\'s most powerful tools. Though it took a century more to understand why it worked, vaccination spread around the world, saving countless lives. It was an early demonstration that disease was not simply fate, but an enemy that human ingenuity could fight and defeat.' },
      { heading: 'The Germ Theory', body: 'The decisive breakthrough came in the nineteenth century with the germ theory of disease. Scientists like Louis Pasteur and Robert Koch proved that many illnesses were caused by tiny living microorganisms — bacteria and other microbes — invisible to the naked eye. This overturned centuries of belief that disease came from bad air or imbalances of the body\'s "humors."\n\nThe implications were revolutionary. If germs caused disease, then killing or blocking germs could prevent it. The surgeon Joseph Lister introduced antiseptic methods that made operations survivable; doctors and nurses began to wash their hands and sterilize instruments. Understanding the true, microscopic enemy gave medicine, for the first time, a rational foundation on which real cures and prevention could be built.' },
      { heading: 'Clean Water and Public Health', body: 'Some of the greatest gains against disease came not from doctors treating individuals but from governments protecting whole populations. As industrial cities grew crowded and filthy, deadly epidemics of cholera and typhoid spread through contaminated water. The physician John Snow traced a London cholera outbreak to a single tainted water pump — pioneering evidence that clean water was a matter of life and death.\n\nIn response, cities built sewers, filtered and treated their water, cleared slums, and organized public health. These unglamorous measures — clean water, safe food, proper sanitation — saved more lives than almost any medicine, quietly slashing death rates. The recognition that health was a public responsibility, not merely a private misfortune, reshaped modern society and government.' },
      { heading: 'The Age of Antibiotics', body: 'In 1928, the Scottish scientist Alexander Fleming noticed that a mold contaminating one of his dishes killed the bacteria around it. That mold produced penicillin, the first antibiotic — a drug that could cure bacterial infections that had killed for millennia. Developed for mass production during the Second World War, penicillin and the antibiotics that followed saved millions of lives.\n\nSuddenly, infections that had been death sentences — pneumonia, blood poisoning, infected wounds — could be cured with a course of pills. Combined with new vaccines against diseases like polio and measles, antibiotics helped drive death rates to historic lows across much of the world in the mid-twentieth century. It was the golden age of the fight against infectious disease.' },
      { heading: 'Triumph and New Challenges', body: 'The greatest triumph came in 1980, when the World Health Organization declared smallpox — a disease that had killed hundreds of millions across history — completely eradicated from the wild through a global vaccination campaign. It was the first time humanity had deliberately wiped out a disease, a stunning proof of what coordinated science and cooperation could achieve.\n\nYet the war is not won. Bacteria evolve resistance to antibiotics; new diseases emerge and, as recent pandemics have shown, can spread across a connected world with frightening speed. The conquest of disease remains an ongoing struggle, demanding constant vigilance and innovation. But its achievements — longer, healthier lives for billions — stand among the noblest accomplishments of the modern age.' },
    ] },
  // ══════════════════════ MODERN (23) ══════════════════════
  // "The World Wars" gives the overview; this follows the second war on its
  // own terms — a different conflict in scale, technology and moral weight,
  // not a sequel to the first.
  { id: 'modern-23', eraId: 'modern', order: 23, title: 'The World Wars, Part II', subtitle: 'The Second World War, 1939\u20131945', estimatedMinutes: 20, xpReward: 170,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/The_Big_Three_at_the_Yalta_Conference.jpg',
    keyFacts: ['Germany invaded Poland on 1 September 1939, and Britain and France declared war two days later', 'It killed an estimated 70\u201385 million people \u2014 most of them civilians', 'The Holocaust murdered six million Jews alongside millions of Roma, Poles, Soviet prisoners, disabled people and others', 'It was the first and so far only war in which nuclear weapons were used', 'It ended Europe\u2019s dominance and left the United States and the Soviet Union as the two world powers'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Peace That Could Not Hold', body: 'The settlement that ended the First World War carried the seeds of the second. Germany was stripped of territory, saddled with reparations and blamed for the whole catastrophe, and the resentment that followed became the fuel of a politics of grievance. The Great Depression turned resentment into desperation. Adolf Hitler came to power in 1933 promising to tear up the settlement, and through the 1930s he did exactly that \u2014 rearming, remilitarising the Rhineland, absorbing Austria, dismembering Czechoslovakia \u2014 while Britain and France, remembering the slaughter of the last war, chose appeasement over confrontation. When Hitler signed a pact with Stalin in August 1939 dividing eastern Europe between them, the last restraint fell away.' },
      { heading: 'Blitzkrieg and the Fall of Europe', body: 'Germany invaded Poland on 1 September 1939. What followed was not the static trench warfare of 1914 but its opposite: fast armoured columns supported by aircraft and radio, striking deep behind the front. Poland fell in five weeks. In the spring of 1940 the same method took Denmark, Norway, the Netherlands, Belgium and \u2014 in six astonishing weeks \u2014 France, a country that had held out for four years the last time. Britain, alone and expecting invasion, survived the summer of 1940 because the Royal Air Force denied the Luftwaffe control of the air over the Channel.' },
      { heading: 'A World at War', body: 'Two decisions in 1941 turned a European war into a global one. In June, Hitler invaded the Soviet Union in the largest land operation in history, opening a front that would consume the bulk of German strength for the rest of the war. In December, Japan attacked the American fleet at Pearl Harbor, bringing the United States into a conflict already raging across China, southeast Asia and the Pacific. From that point the war was fought on every inhabited continent and every ocean.' },
      { heading: 'The Holocaust', body: 'The Second World War was also the setting for a crime without precedent. The Nazi regime set out to murder every Jew in Europe, and killed roughly six million \u2014 first by mass shooting behind the eastern front, then in purpose-built extermination camps. Millions more were murdered alongside them: Roma and Sinti, Soviet prisoners of war, Polish civilians, disabled people, political prisoners and gay men. This was not a byproduct of the fighting. It was organised by a modern state using railways, census records and industrial method, and it is the reason the war cannot be told as a story of strategy alone.' },
      { heading: 'The Turn of the Tide', body: 'The war turned in the winter of 1942\u201343 and turned in several places at once. At Stalingrad, a German army was encircled and destroyed. At El Alamein, the Axis advance in North Africa was broken. At Midway, American carriers sank four Japanese carriers in a single day. Behind the fronts, the decisive factor was production: the United States and the Soviet Union out-built the Axis so comprehensively that by 1944 the outcome was a question of time and cost rather than of doubt.' },
      { heading: 'Victory and the Bomb', body: 'The Allies landed in Normandy in June 1944 and closed on Germany from west and east; Berlin fell to the Red Army in May 1945 and Hitler killed himself in a bunker beneath it. The Pacific war ended differently. In August 1945 the United States dropped atomic bombs on Hiroshima and Nagasaki, killing well over a hundred thousand people, most of them civilians, and Japan surrendered days later. The decision remains among the most argued-over in modern history \u2014 and it opened an age in which the weapons existed to end the argument permanently.' },
      { heading: 'The World the War Left', body: 'Between 70 and 85 million people were dead, the majority of them civilians, and the centre of world power had moved off the European continent for good. Out of the wreckage came the United Nations, the Universal Declaration of Human Rights, the Nuremberg trials and the very idea of a crime against humanity. It also came with a fault line: the alliance that won the war split almost immediately into the two blocs of the Cold War, and the empires that had fought it no longer had the strength to hold their colonies.' },
    ] },
  { id: 'modern-24', eraId: 'modern', order: 24, title: 'Second World War, Part II', subtitle: 'The Eastern Front, the Pacific, and the War Behind the Lines', estimatedMinutes: 20, xpReward: 170,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Into_the_Jaws_of_Death_23-0455M_edit.jpg',
    keyFacts: ['The Eastern Front accounted for roughly three-quarters of German military losses; the Soviet Union lost some 27 million people', 'The war in Asia began in 1937, two years before Europe\u2019s, when Japan invaded China \u2014 China\u2019s dead are estimated at 15 to 20 million', 'Strategic bombing killed several hundred thousand civilians in Germany and Japan and remains among the most argued-over decisions of the war', 'Almost every occupied country produced resistance and collaboration at the same time, and the line between them was rarely clean', 'The Tehran, Yalta and Potsdam conferences drew the borders and spheres of influence that became the Cold War'],
    relatedTimeline: [],
    sections: [
      { heading: 'The War Behind the Headlines', body: 'The short version of the Second World War runs from Poland to blitzkrieg to Pearl Harbor to D-Day to the bomb, and almost every step of it happens in western Europe or the Pacific. That version is not wrong, but it is badly out of proportion. The overwhelming majority of the fighting, and of the dying, happened somewhere else: on a front line that ran for nearly three thousand kilometres from the Arctic to the Black Sea, and in a war in China that had already been going on for two years when Germany invaded Poland. This lesson is about the parts the summary compresses \u2014 where the war was actually decided, how it was paid for, and what it did to the people who never held a rifle.' },
      { heading: 'The Eastern Front', body: 'On 22 June 1941 Germany invaded the Soviet Union with roughly three million men along a front stretching from the Baltic to the Black Sea. Nothing on that scale had been attempted before, and nothing since has come close. Leningrad was encircled for 872 days and something like 800,000 of its civilians starved to death. At Stalingrad an entire German army was surrounded and destroyed. At Kursk in July 1943 the two sides put several thousand tanks into a single battle, and the German army never mounted a major offensive in the east again. In the summer of 1944, Operation Bagration destroyed German Army Group Centre so completely that the Soviet advance did not stop until it reached the outskirts of Warsaw. Roughly three-quarters of all German military losses in the war were suffered here. The Soviet Union lost about 27 million people, the majority of them civilians \u2014 a figure so large that it is easier to state than to grasp.' },
      { heading: 'The War That Started in 1937', body: 'For China the Second World War began in July 1937, and by the time Europe joined in, the Japanese army had already taken Shanghai and Nanjing, where it massacred somewhere between 100,000 and 300,000 people over several weeks. China fought on for eight years, mostly alone, losing an estimated 15 to 20 million people and tying down more than a million Japanese troops who were consequently not available anywhere else. The Pacific war that Americans remember \u2014 Guadalcanal, Tarawa, Iwo Jima, Okinawa \u2014 was fought across islands most people could not find on a map, and its logic was brutal arithmetic: take the airfields, move the bombers closer, repeat. Meanwhile Japanese forces reached the borders of India, and a famine in Bengal in 1943, made far worse by wartime policy, killed around three million people who never saw a Japanese soldier.' },
      { heading: 'Occupation, Collaboration and Resistance', body: 'By 1942 Germany governed most of Europe, and every occupied country had to work out how to live under it. Some collaborated openly: Vidkun Quisling gave his name to the whole idea, and Vichy France ran its own police, its own laws, and deported its own Jewish citizens. Others resisted, and paid for it. Yugoslavia\u2019s partisans tied down entire German divisions in a mountain war that was also a civil war. The Warsaw Rising of August 1944 held out for 63 days and cost roughly 200,000 Polish lives while the Red Army waited on the far bank of the Vistula. What makes this history hard is that the categories blur: the same village could hide a resistance cell and denounce its neighbours, and after liberation the settling of accounts was often as political as it was moral.' },
      { heading: 'The War of Factories', body: 'The Allies did not out-fight the Axis so much as out-produce it. American industry built roughly 300,000 aircraft, 100,000 tanks and enough shipping to replace losses faster than submarines could inflict them, and shipped a substantial share of it to Britain and the Soviet Union under Lend-Lease \u2014 including the trucks that gave the Red Army the mobility to reach Berlin. The Soviets did something even stranger: in the months after the invasion they dismantled well over a thousand factories and moved them east of the Urals by rail, and had many of them producing again within a year. Germany, by contrast, relied on some 12 million forced and slave labourers, a system that extracted work by terror and was correspondingly wasteful. Women entered heavy industry in every combatant country, which is one reason the post-war world could not simply be put back the way it was.' },
      { heading: 'Bombing the Cities', body: 'Air power in this war moved by stages from the battlefield to the population, and it did so on every side. Guernica and the destruction of Rotterdam came first; the Blitz killed some 40,000 British civilians; then the RAF and USAAF turned area bombing into an industry. Hamburg burned in a firestorm in July 1943 that killed around 37,000 people in a few nights. Dresden in February 1945 killed perhaps 25,000 and has been argued about ever since, largely because by then the war was plainly won. The single deadliest air raid in history was not a nuclear one: on the night of 9 March 1945, incendiaries dropped on Tokyo killed roughly 100,000 people and burned out sixteen square miles of the city. Whether any of this shortened the war is still disputed by historians; that it was aimed at civilians is not.' },
      { heading: 'The Peace That Became the Cold War', body: 'The shape of the post-war world was settled while the fighting was still going on, in three conferences. At Tehran in November 1943 the Allies agreed to open a second front in France and, in effect, that the Soviet Union would be the power that liberated eastern Europe. At Yalta in February 1945 they moved Poland bodily westward, taking its eastern half for the Soviet Union and compensating it with German land, and agreed on occupation zones for Germany. At Potsdam in July, with Roosevelt dead and the atomic bomb newly tested, the mood had already cooled. The alliance held just long enough to finish the war and then dissolved: within two years Europe had a line drawn across it that would last until 1989. The Second World War ended, in other words, by arranging the next one \u2014 which is worth holding in mind when the story is told as a clean victory.' },
    ] },
];
