import type { Lesson } from '@/types';

// ─── Curriculum Expansion — the road to 120 lessons (20 per era) ─────────────
// These lessons extend each era from 9 to 20, deliberately filling the world-
// history gaps the core set skipped: the Americas, Africa, Oceania, South and
// East Asia, the history of science, and — in every era — literature and the
// life of women. New lessons run one section longer than the pre-expansion
// average (six sections) per the brief. They are merged into LESSONS in
// lessonsData.ts; the English text is authoritative and every translation
// layer falls back to it safely.

export const LESSONS_EXPANSION: Lesson[] = [
  // ══════════════════════ PREHISTORIC (10–20) ══════════════════════
  { id: 'prehistoric-10', eraId: 'prehistoric', order: 10, title: 'The Peopling of the Americas', subtitle: 'The Last Great Migration', estimatedMinutes: 16, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Clovis_Rummells_Maske.jpg',
    keyFacts: ['Humans crossed from Siberia into the Americas by at least 16,000 years ago', 'Beringia was a grassland "land bridge" exposed by low Ice Age sea levels', 'Monte Verde in Chile shows people were far south by ~14,500 years ago', 'The Clovis toolmakers spread across North America within a few centuries'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Empty Continents', body: 'For most of the human story, two entire continents lay untouched by our species. The Americas — nearly a third of the planet\'s land — held no people at all while Homo sapiens spread across Africa, Asia, Europe, and Australia. Their peopling was the last great chapter of the original human diaspora, and the fastest: within a few thousand years, migrants would travel from the Arctic to the southern tip of Patagonia, adapting to deserts, rainforests, high plains, and glaciers along the way.\n\nHow and when they came has been argued for a century, and the dates keep moving earlier. What is certain is that the ancestors of Native Americans were Ice Age hunter-gatherers from northeast Asia, carrying stone-tipped spears, tailored clothing, and the fire and language of a mature human culture. They did not "discover" an empty land so much as inherit it, and everything that followed — from the Maya to the Inca to the nations of the plains — descended from these first travelers.' },
      { heading: 'Beringia: The Vanished Land', body: 'During the last glacial maximum, so much water was locked in ice sheets that global sea levels fell by more than 120 metres. Where the shallow Bering Strait now separates Siberia from Alaska, a broad plain of grassland and tundra emerged — Beringia, a land the size of a subcontinent. It was no mere bridge to be crossed in a hurry but a homeland in its own right, grazed by mammoth, horse, and bison and hunted by the people who would become the first Americans.\n\nGenetic evidence suggests these populations were isolated in or near Beringia for thousands of years — a "standstill" during which they became genetically distinct from other Asians — before the thaw let them move south. When the ice sheets finally parted, two doors opened: an interior "ice-free corridor" down the spine of North America, and a coastal route along the Pacific shore, rich in fish, seals, and kelp. Both were probably used.' },
      { heading: 'Monte Verde and the Shattered Consensus', body: 'For decades archaeologists held to the "Clovis first" model: that the makers of distinctive fluted Clovis spearpoints, appearing around 13,000 years ago, were the earliest Americans. Then a waterlogged site in southern Chile — Monte Verde — overturned it. Preserved in a peat bog were the remains of a small settlement: wooden tent-frames, hearths, chewed medicinal plants, even a child\'s footprint, all dated to about 14,500 years ago.\n\nMonte Verde sat thousands of kilometres south of the ice, meaning people had reached the far end of South America before Clovis even began. Newer sites push human presence back further still, some controversially beyond 20,000 years. The tidy picture dissolved into a richer one: multiple routes, multiple waves, and a human arrival far older and more complex than a single stone-tool tradition could explain.' },
      { heading: 'The Clovis World and Its Hunters', body: 'Whoever came first, the Clovis culture remains one of prehistory\'s most striking phenomena. Around 13,000 years ago, a technology of beautifully worked, fluted stone points spread across North America with astonishing speed — from the Rockies to the Atlantic in perhaps a few centuries. Clovis points have been found lodged in the bones of mammoths and mastodons, evidence of hunters bold enough to take the largest land animals of the age.\n\nThe Clovis toolkit was a portable, adaptable system suited to people constantly on the move through unfamiliar country. Its rapid spread suggests small bands in loose contact across enormous distances, sharing ideas and perhaps mates. Then, almost as suddenly, Clovis vanished — replaced by a proliferation of regional cultures as populations settled into and specialized for the continent\'s many environments.' },
      { heading: 'Giants Fall: The Great Extinction', body: 'The Americas that greeted the first people teemed with megafauna: mammoths and mastodons, giant ground sloths the size of elephants, sabre-toothed cats, dire wolves, camels, horses, and a beaver as large as a bear. Within a few thousand years of human arrival, most of these giants were gone — dozens of large species extinct in a geological instant.\n\nWhat killed them is one of prehistory\'s great debates. Some blame human hunting pressure on animals with no evolved fear of people; others point to the abrupt climate swings at the end of the Ice Age; most suspect a lethal combination. The disappearance reshaped the hemisphere\'s ecology and its human future: the loss of the horse, native to the Americas, meant that when it returned with Europeans millennia later it seemed an alien wonder — even though its ancestors had first evolved on American plains.' },
      { heading: 'A New World Made Human', body: 'By around 10,000 years ago, humans occupied every major environment in the Americas, from Arctic coasts to Amazonian forests to Andean heights above 4,000 metres. Cut off from the rest of humanity by rising seas that drowned Beringia, these populations then developed in near-total isolation for ten millennia, inventing agriculture, cities, writing, and states entirely independently of the Old World.\n\nThat independent parallel is one of history\'s great natural experiments. Maize, potatoes, tomatoes, chocolate, and countless other crops were domesticated here; monumental civilizations rose without contact with Mesopotamia or China. When the two halves of humanity finally met again in 1492, they had been separated so long that even their diseases were mutually unfamiliar — a separation born on the vanished grasslands of Beringia, at the close of the Ice Age.' },
    ] },

  { id: 'prehistoric-11', eraId: 'prehistoric', order: 11, title: 'The First Australians', subtitle: 'Sixty Thousand Years of the Dreaming', estimatedMinutes: 16, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Aboriginal_Art_Australia.jpg',
    keyFacts: ['Aboriginal Australians have lived on the continent for at least 60,000 years', 'Reaching Sahul required the earliest known open-sea voyages', 'The "Dreaming" preserves one of humanity\'s oldest continuous oral traditions', 'Some Aboriginal stories appear to encode real events from 10,000+ years ago'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Oldest Living Cultures', body: 'While the Americas were the last continents peopled, Australia was among the first beyond Africa. Aboriginal Australians represent one of the oldest continuous human cultures on Earth, with an unbroken presence stretching back at least 60,000 years — perhaps more. When the pyramids were built, that presence was already tens of thousands of years old; when the first cave paintings were made in Europe, people had already lived in Australia for millennia.\n\nThis staggering antiquity is not a museum fact but a living inheritance. Hundreds of distinct Aboriginal nations, each with its own language and Country, carried forward customs, laws, art, and stories across a span of time that dwarfs all of written history combined. To study prehistoric Australia is to glimpse how human societies can endure — and remember — across almost unimaginable stretches of time.' },
      { heading: 'Crossing to Sahul', body: 'During the Ice Age, lower sea levels joined Australia, Tasmania, and New Guinea into a single landmass geographers call Sahul. But Sahul was never connected to Asia; between them lay a chain of deep-water straits that even at the lowest sea levels required crossing open ocean — stretches of dozens of kilometres where the far shore was invisible over the horizon.\n\nTo reach Sahul, then, the ancestors of Aboriginal Australians had to build watercraft and deliberately voyage across the sea, generations before any comparable feat elsewhere. These were the earliest mariners in human history, and their achievement demanded planning, boats, and enough people to found a viable population. That first landfall, perhaps 65,000 years ago, ranks among the boldest journeys our species has ever made.' },
      { heading: 'Mastering a Continent', body: 'The land the first Australians inherited was vast and varied: tropical north, temperate southeast, and an immense arid heart. Over tens of thousands of years they mastered all of it, developing an intimate ecological knowledge encoded in language, song, and law. They reshaped the land itself with "firestick farming" — deliberate, patterned burning that cleared undergrowth, encouraged new growth, and drove game, managing whole landscapes across generations.\n\nThey engineered too: the stone fish traps at Budj Bim in Victoria, built to channel and harvest eels, are among the oldest aquaculture systems known, older than Stonehenge. Far from being simple wanderers, Aboriginal societies were sophisticated land managers who sustained themselves on the driest inhabited continent for longer than any other human population has occupied anywhere.' },
      { heading: 'The Dreaming', body: 'At the heart of Aboriginal culture is the Dreaming (or Dreamtime) — a rich framework that is at once creation story, moral law, map, and history. In the Dreaming, ancestral beings travelled across a formless land, shaping mountains, rivers, and waterholes, and laying down the rules by which people must live. These beings did not simply act in a distant past; the Dreaming is a continuous reality, woven into the living landscape and renewed in ceremony.\n\nThe Dreaming is transmitted through one of humanity\'s greatest oral literatures: story cycles, songs, and "songlines" — sung routes that thread across the continent, encoding directions, water sources, and law in verse that can be followed like a map. Without writing, Aboriginal peoples built a vast library held in memory and performance, passed with remarkable fidelity from generation to generation.' },
      { heading: 'Memory Across Ten Thousand Years', body: 'Astonishingly, some Aboriginal oral traditions appear to preserve the memory of real geological events from the deep past. Stories from coastal peoples describe a time when the shoreline lay far out to sea, when now-drowned lands were dry — memories that match the post-Ice-Age sea-level rise that flooded those coasts more than 7,000 years ago. Other tales describe volcanic eruptions and the forms of extinct megafauna.\n\nIf these interpretations hold, they represent the longest accurately transmitted oral memories known to science — knowledge carried across three hundred generations by voice alone. It is a profound demonstration that "prehistory," the age before writing, was never a time without records. It was a time whose records were kept in the human mind, and in some places kept astonishingly well.' },
      { heading: 'Art on the Rock', body: 'Australia holds one of the world\'s richest bodies of rock art, spanning tens of thousands of years — from ancient hand stencils and depictions of long-extinct animals to the intricate "X-ray" style showing the bones and organs of fish and game. Sites like those of Arnhem Land and the Kimberley form open-air galleries where layer upon layer of painting records changing worlds, changing animals, and changing beliefs.\n\nThis art was never merely decorative. It marked sacred sites, taught law and Dreaming stories, and tied people to Country. Much of it remains living tradition, its meanings still known to the communities whose ancestors made it. In the rock art of Australia, prehistory speaks not as a silent riddle but in a voice its heirs can still, in part, understand — a continuity unmatched anywhere else on Earth.' },
    ] },

  { id: 'prehistoric-12', eraId: 'prehistoric', order: 12, title: 'Metal from Stone', subtitle: 'The Dawn of Copper and Bronze', estimatedMinutes: 16, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bronze_age_axe_heads.jpg',
    keyFacts: ['Copper was first worked over 9,000 years ago in the Near East', 'Smelting freed metal from ore using controlled high-temperature fire', 'Bronze — copper alloyed with tin — is far harder than either metal alone', 'The demand for tin created some of the first long-distance trade networks'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Age of Stone Ends', body: 'For more than three million years, the cutting edge of technology was literally stone. Then, in the millennia after farming began, human beings learned to command a new kind of material — metal — and the change was so profound that we name whole ages after it. The transition was not sudden; stone tools remained in use for a long time. But the mastery of metal set human societies on a path toward specialization, trade, and inequality that stone never could.\n\nMetalworking demanded fire hotter than any cooking hearth, knowledge of rare ores, and skills that took a lifetime to learn. It produced the first true specialists — smiths whose craft seemed almost magical — and the first goods worth carrying across continents. The Metal Ages were as much a social revolution as a technological one.' },
      { heading: 'Native Copper and the First Metalsmiths', body: 'The story began with copper, which occasionally occurs in pure "native" form — nuggets of red metal lying in the ground. The earliest metalworkers, over 9,000 years ago in Anatolia and the Near East, treated these nuggets as a peculiar kind of stone, hammering them into beads and small tools. Copper had an alluring advantage over stone: it did not shatter when struck. It bent, and could be hammered back into shape.\n\nThis cold-hammering was the humble beginning. But native copper was rare, and its uses limited. The real breakthrough came when people discovered that far more copper was locked invisibly inside certain colorful rocks — ores like malachite and azurite — and that intense heat could set it free. That discovery, smelting, transformed metal from a curiosity into an industry.' },
      { heading: 'The Secret of Smelting', body: 'Smelting is the art of chemically freeing metal from its ore using heat and a controlled, oxygen-starved fire. It required temperatures above 1,000°C — achievable only in specially built furnaces fed by bellows or blowpipes — and an understanding, however intuitive, of the transformations happening in the flames. When mastered, it turned drab greenish rock into gleaming molten metal that could be poured into moulds.\n\nCasting was the second great skill. Molten copper poured into a shaped mould hardened into any form the smith desired — axes, blades, ornaments — in quantities and shapes impossible to achieve by chipping stone. For the first time, humans were not merely shaping natural materials but chemically remaking them. The smith, master of fire and secret knowledge, became a figure of power and mystery in many early societies.' },
      { heading: 'Bronze: The Perfect Alloy', body: 'Pure copper is soft, and blunts quickly. The decisive advance came when metalworkers learned to melt tin together with copper to make bronze — an alloy far harder, tougher, and easier to cast than copper alone. A bronze axe held its edge; a bronze sword could be a fearsome weapon; bronze tools could work wood and stone with new efficiency. By around 3300 BCE, bronze was reshaping the civilizations of the Near East.\n\nBronze gave its name to an age and its edge to armies. Bronze weapons and armour helped equip the first professional soldiers and the states that fielded them. Its manufacture required organization, skilled labour, and above all raw materials — and there lay a problem, for the two ingredients of bronze were rarely found together.' },
      { heading: 'The Tin Trade and the First Networks', body: 'Copper was widespread, but tin was scarce and concentrated in only a few regions — Cornwall in Britain, parts of Central Asia, the mountains of Anatolia. To make bronze, societies had to obtain tin from far away, and so metallurgy did what few forces before it had: it stitched distant lands together with trade. Ingots of tin and copper travelled hundreds of kilometres by pack animal and ship.\n\nThese were among the world\'s first long-distance commercial networks, and they carried more than metal. Along the tin routes moved ideas, styles, languages, and people. A shipwreck off the Turkish coast at Uluburun, sunk around 1300 BCE, held tin and copper ingots, along with goods from a dozen cultures — a snapshot of a connected Bronze Age world already dependent on international trade to arm and adorn itself.' },
      { heading: 'A World Remade in Metal', body: 'The coming of metal accelerated the trends farming had begun. Metal tools raised agricultural output; metal weapons concentrated military power; metal ornaments displayed wealth and rank. Societies grew more stratified, with smiths, warriors, traders, and rulers standing above ordinary farmers. Control of ore sources and trade routes became a source of political power in itself.\n\nThe Bronze Age would eventually give way to iron — a metal harder to work but far more abundant, which democratized access to metal tools and weapons. But the pattern was set in bronze: technology, trade, specialization, and inequality advancing together. The mastery of metal, born from the patient study of fire and stone, had carried humanity to the threshold of the great literate civilizations — and, in doing so, closed the long age of prehistory.' },
    ] },

  { id: 'prehistoric-13', eraId: 'prehistoric', order: 13, title: 'Temples Before Cities', subtitle: 'Göbekli Tepe and the Megalith Builders', estimatedMinutes: 16, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/G%C3%B6bekli_Tepe%2C_Urfa.jpg',
    keyFacts: ['Göbekli Tepe in Turkey was built ~11,600 years ago — before pottery or farming', 'Its builders raised multi-tonne carved stone pillars as hunter-gatherers', 'Stonehenge was built over many centuries beginning ~5,000 years ago', 'Megalithic monuments appear independently across prehistoric Europe and beyond'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Monument That Rewrote the Story', body: 'On a barren hilltop in southeastern Turkey stands a discovery that upended a century of theory. Göbekli Tepe is a complex of great stone enclosures, ringed by T-shaped limestone pillars up to five metres tall and weighing many tonnes, carved with foxes, snakes, vultures, and scorpions. It is roughly 11,600 years old — older than Stonehenge by six thousand years, older than the pyramids by seven.\n\nThe shock lies in who built it. The old model held that monumental architecture required cities, farming, and states to organize the necessary labour. But Göbekli Tepe was raised by hunter-gatherers who had not yet domesticated a single plant or animal, who had no pottery, no metal, and no writing. Somehow, foragers coordinated the quarrying, carving, and raising of colossal stones — for reasons that had nothing to do with survival and everything to do with belief.' },
      { heading: 'Did Faith Build the First Order?', body: 'Göbekli Tepe suggests a startling reversal of cause and effect. Perhaps it was not agriculture that made monuments possible, but the desire to gather and build monuments that helped drive people toward agriculture. Feeding the crowds who assembled to raise these stones may have created pressure to produce food more reliably — and it is no coincidence that some of the earliest domesticated wheat comes from the hills within sight of the site.\n\nWhatever its purpose — temple, gathering place, or both — the site shows that the human impulse toward the sacred and the communal is very old, older than the settled world we assume it required. Ritual, art, and shared belief may have been not luxuries that civilization afforded, but forces that helped call civilization into being. Then, mysteriously, the builders deliberately buried their own creation, sealing it beneath tonnes of earth.' },
      { heading: 'The Megalithic Impulse', body: 'Göbekli Tepe was extraordinary, but the urge to build in great stone — megalithic architecture, from the Greek for "large stone" — appeared again and again across prehistoric Europe and beyond. From the passage tombs of Ireland to the temples of Malta, from the standing stones of Brittany to the dolmens scattered across the continent, Neolithic peoples raised enduring monuments of rock, often aligned to the movements of the sun and moon.\n\nThese were among the first structures built to outlast their makers, and many still stand after five thousand years. The temples of Malta, older than the pyramids, are among the oldest freestanding buildings on Earth. Newgrange in Ireland was engineered so that at dawn on the winter solstice, a beam of sunlight pierces its inner chamber — a feat of astronomy and construction achieved by farmers with stone tools.' },
      { heading: 'Stonehenge', body: 'The most famous megalith of all rose on Salisbury Plain in Britain over many centuries, beginning around 5,000 years ago. Stonehenge was not built at once but reshaped by generations: first an earthwork and timber structure, later the great ring of sarsen stones capped with lintels, and the smaller "bluestones" hauled — astonishingly — some 240 kilometres from the mountains of Wales.\n\nStonehenge was aligned to the solstices, framing the rising midsummer and setting midwinter sun, and it drew people from across Britain and beyond; isotope analysis of bodies buried nearby shows some came from as far as the Alps. It served as temple, calendar, cemetery, and gathering place. That a society without writing or metal could conceive, transport, and raise it speaks to a sophistication we are only beginning to credit.' },
      { heading: 'Reading the Sky', body: 'Again and again, megalithic monuments encode astronomical knowledge: solstice alignments, lunar cycles, the risings and settings of stars. Prehistoric peoples watched the heavens with care, for the sky was their calendar — telling them when to plant, when to expect the return of the light, when to hold their feasts. To align a monument to the solstice required years of patient observation and a precise understanding of the sun\'s wandering path.\n\nThis marriage of sky-watching and stone-building reveals minds engaged with abstract, mathematical questions long before writing could record them. The builders were not merely superstitious; they were empirical observers of nature, translating what they learned into architecture that still keeps time today. In these silent stones we see the deep roots of both religion and science, tangled together at their common origin.' },
      { heading: 'Monuments and Memory', body: 'Why did prehistoric peoples pour such enormous effort into the immovable and the eternal? Part of the answer is memory. A monument is a claim upon the land and upon time — a way of saying "we were here, this place is ours, our ancestors lie beneath these stones." Megaliths often mark burials, binding the living to the dead and a people to their territory across generations.\n\nThey also demanded and displayed cooperation. Raising a great stone required many hands working together toward a purpose beyond any single lifetime, forging the bonds of a community and the authority of those who could organize it. In building for eternity, these societies were also building themselves — creating shared identity, shared labour, and shared meaning. The monuments outlasted their makers\' names, but they still transmit, wordlessly, the human hunger to endure.' },
    ] },

  { id: 'prehistoric-14', eraId: 'prehistoric', order: 14, title: 'Beasts of Burden', subtitle: 'The Taming of Animals and a Second Revolution', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cattle_in_Bunyala.jpg',
    keyFacts: ['Dogs were the first domesticated animal, thousands of years before farming', 'Sheep, goats, cattle, and pigs were tamed in the Near East by ~8,000 BCE', 'The "Secondary Products Revolution" harnessed milk, wool, and animal traction', 'The horse, domesticated on the Eurasian steppe, transformed transport and war'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Partnership of Species', body: 'Farming was never only about plants. Alongside the domestication of wheat and barley came the taming of animals — a transformation just as profound, and in some ways stranger, for it meant forging lasting partnerships with other species. Domesticated animals gave prehistoric people a mobile store of food, a source of materials, and, eventually, muscle power that multiplied what a human body could do.\n\nDomestication reshaped the animals as much as the people. Over generations of selective breeding, wild aurochs became docile cattle, wild boar became pigs, and wary wolves became dogs. The animals grew tamer, smaller-brained, and dependent; the humans grew wealthier, more settled, and bound to the daily labour of herding and care. It was a bargain that remade both sides.' },
      { heading: 'The First Friend', body: 'Long before any crop was planted, humans had already befriended one species: the dog. Grey wolves began associating with human groups perhaps 20,000 or more years ago, drawn to the scraps of the hunt, and over time the boldest and least fearful were tolerated, fed, and bred. The result was the dog — the first domesticated animal, and for thousands of years the only one.\n\nThe partnership was mutual. Dogs helped humans hunt, guarded camps, and gave warning of danger; humans provided food and shelter. This deep alliance, forged in the Ice Age between two social predators, is the oldest interspecies friendship in history. By the time farming began, the dog was already an ancient companion — proof that domestication grew out of relationships, not just economics.' },
      { heading: 'Herds and Flocks', body: 'With the Neolithic came the great livestock animals. In the Near East, by around 8,000 BCE, people had domesticated sheep and goats for meat, then cattle and pigs. These herd animals were suited to domestication: social by nature, willing to follow a leader, and able to eat grass and scraps humans could not. A flock was walking wealth — a reserve of food that could be moved, traded, and inherited.\n\nOwning animals changed society. Herds could be accumulated far beyond immediate need, making some families richer than others and giving rise to new forms of property and inequality. In many regions, whole ways of life grew up around the herd: pastoral nomads who followed their animals across grasslands and deserts, mobile and often warlike, forever shaping the settled world at their edges.' },
      { heading: 'The Secondary Products Revolution', body: 'At first, animals were valued mainly dead — for meat and hides. But sometime after their initial domestication, people made a series of discoveries that multiplied an animal\'s worth many times over: the "secondary products" that a living beast provides again and again. They learned to milk sheep, goats, and cattle, turning grass into a renewable food supply of milk, cheese, and yogurt.\n\nThey learned to shear sheep for wool and spin it into cloth; to harness oxen to pull ploughs and carts, unlocking soils and loads no human could manage; to use dung as fuel and fertilizer. This "Secondary Products Revolution" transformed the economy of the Neolithic world, allowing far more food and goods to be wrung from the same land and animals — and reshaping labour, trade, and diet across the Old World.' },
      { heading: 'The Horse and the Wheel', body: 'The most world-changing domestication of all came on the open grasslands of the Eurasian steppe, where, around 5,500 years ago, people first tamed the wild horse. At first horses were kept for meat and milk, but their true power lay in speed. Ridden or harnessed to vehicles, the horse shrank distances that had always seemed vast and gave its masters an overwhelming advantage in trade, migration, and war.\n\nPaired with another steppe-linked invention — the wheel and the wheeled cart — the horse set peoples in motion across continents. Mounted, mobile herders spread their languages (including, many linguists argue, the ancestors of a huge family of tongues from India to Ireland), their goods, and their armies far and wide. The taming of the horse was among the last acts of prehistory and among the most consequential, launching a mobile, interconnected age.' },
      { heading: 'Living With Animals, Living With Disease', body: 'The intimacy of human and animal life carried a hidden cost that would echo through all later history. Crowded together with their herds, drinking their milk and breathing their air, farming peoples became the hosts of diseases that jumped from animals to humans. Measles, smallpox, influenza, tuberculosis — many of humanity\'s great killers originated in the livestock of the Neolithic.\n\nOver generations, farming populations paid a terrible toll but also built up partial immunities to these "crowd diseases." That grim inheritance would one day become a weapon: when densely populated, animal-rich Old World societies met peoples who had domesticated few such animals — as in the Americas — the diseases they carried proved more devastating than any army. The bargain struck with animals in prehistory shaped not only diet and labour but the deadly balance of encounters thousands of years later.' },
    ] },

  { id: 'prehistoric-15', eraId: 'prehistoric', order: 15, title: 'The Green Sahara', subtitle: 'Africa\'s Forgotten Prehistoric Worlds', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Tassili_ligne_de_femmes.jpg',
    keyFacts: ['The Sahara was a green, lake-dotted grassland for thousands of years', 'Its rock art shows cattle herders, hippos, and swimmers where desert now lies', 'Nabta Playa in Egypt holds a stone circle older than Stonehenge', 'Africa\'s prehistory extends far beyond the origin of humankind'],
    relatedTimeline: [],
    sections: [
      { heading: 'Beyond the Cradle', body: 'Africa is rightly known as the birthplace of humanity, but its prehistory is far richer than that single, defining fact. Long after the first humans spread out of Africa, the continent remained a stage of extraordinary developments — of herders, artists, and monument-builders whose worlds are only now being recovered. Much of this story unfolded in a place that today seems the least likely of all: the Sahara.\n\nWe picture the Sahara as timeless, lifeless desert. But this is a recent condition. For long stretches of prehistory, the greatest desert on Earth was a well-watered land of lakes, rivers, and grassland teeming with life and people. The story of the "Green Sahara" is one of prehistory\'s most dramatic reminders that the world our ancestors knew was profoundly different from our own.' },
      { heading: 'When the Desert Bloomed', body: 'Driven by slow cycles in the Earth\'s orbit that shifted the African monsoon, the Sahara has swung between desert and grassland many times. During the "African Humid Period," from roughly 11,000 to 5,000 years ago, rains soaked the region, filling vast lakes — Lake Chad swelled to the size of a sea — and clothing the land in savannah. Hippos wallowed, crocodiles basked, and giraffes and elephants grazed where only sand now stretches.\n\nInto this green world came people: hunters, fishers, and — in time — herders driving cattle across the grass. They left their villages, their tools, and their harpoons for fishing the ancient lakes scattered across what is now bone-dry desert. For thousands of years the Sahara was not a barrier but a homeland, one of the more fertile and populated parts of the continent.' },
      { heading: 'Galleries in the Sand', body: 'The people of the Green Sahara left behind one of the world\'s greatest treasuries of rock art. On cliffs and in caves across the central Sahara — at Tassili n\'Ajjer in Algeria and countless other sites — they painted and engraved thousands of images across millennia: herds of cattle, wild animals now vanished from the region, hunters, dancers, and mysterious robed figures.\n\nOne famous scene at Wadi Sura in Egypt shows tiny human figures who appear to be swimming — painted on a rock face in what is now one of the driest places on Earth, a haunting testimony to the lost lakes and rivers. The art records a whole way of life: the shift from hunting to cattle-herding, the ceremonies, the animals, and eventually the desiccation that would drive people out. It is prehistory\'s vivid diary of a green world lost.' },
      { heading: 'Nabta Playa: An African Stonehenge', body: 'In the desert of southern Egypt, at a site called Nabta Playa, cattle-herding peoples built something remarkable around 7,000 years ago: arrangements of standing stones, including a small circle aligned to the heavens, older than Stonehenge. They dug deep wells, built shelters, and buried cattle with ceremony, hinting at a religion in which the herd was sacred.\n\nNabta Playa suggests that some of the ideas we associate with Egyptian civilization — astronomical alignment, monumental stone, cattle cult, and organized ritual — may have roots among the herders of the Sahara who, as the desert returned, migrated toward the Nile. The prehistoric peoples of Africa were not passive recipients of civilization from elsewhere; they were, in places, its pioneers.' },
      { heading: 'The Great Drying', body: 'Around 5,000 years ago, the orbital cycle turned again, the monsoon rains withdrew southward, and the Sahara dried out — over centuries in some places, more abruptly in others. Lakes shrank and vanished; grassland gave way to sand; the great desert returned. Its inhabitants had to leave, migrating toward the few places where water remained: the shores of Lake Chad, the highlands, and above all the valley of the Nile.\n\nMany scholars see in this exodus a driving force behind the rise of Egyptian civilization, as displaced herders concentrated along the last great river. The drying of the Sahara also raised a formidable barrier across Africa, separating the Mediterranean north from sub-Saharan Africa and shaping the continent\'s history ever after. A climate shift remade the human map, as it had done and would do again.' },
      { heading: 'A Continent of Deep Histories', body: 'The Green Sahara is only one chapter of Africa\'s vast prehistory. Elsewhere on the continent, peoples independently developed distinctive tool traditions, pottery among the world\'s oldest, and, later, ironworking that in parts of Africa appeared without a preceding bronze age. The story of prehistoric Africa is one of diversity and innovation across an enormous range of environments, from rainforest to savannah to desert.\n\nRecovering these histories corrects a long-standing distortion that treated Africa as merely the place humanity began and then, supposedly, stood still. In truth the continent hosted dynamic prehistoric worlds — herding societies, artistic traditions, and monumental sites — that unfolded over tens of thousands of years. Africa was not only humanity\'s cradle but the setting for some of prehistory\'s most fascinating and least-known achievements.' },
    ] },

  { id: 'prehistoric-16', eraId: 'prehistoric', order: 16, title: 'Before Writing, the Word', subtitle: 'Language, Myth, and the First Literature', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Lascaux_2.jpg',
    keyFacts: ['Human language may be tens of thousands of years old or more', 'Oral traditions preserved knowledge, law, and story for countless generations', 'Myths and epics existed as living performance long before they were written', 'The first written literature captured tales already ancient in the telling'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Invisible Invention', body: 'Of all human creations, the most powerful leaves no fossil: language. Spoken words vanish the instant they are uttered, so we cannot excavate the birth of speech as we can a stone tool. Yet language is arguably the invention that made all others possible — the medium of thought, cooperation, teaching, and memory that set our species apart. Every hand-axe, cave painting, and myth passed down through the ages depended on the ability to speak and be understood.\n\nWhen fully modern language emerged is fiercely debated. Some link it to the burst of symbolic behaviour — art, ornament, ritual — that flowered tens of thousands of years ago; others push it much earlier. What is clear is that by the time our ancestors were painting caves and burying their dead with grave goods, they possessed language rich enough to tell stories, teach skills, and speak of things unseen.' },
      { heading: 'The Library in the Mind', body: 'Prehistoric peoples had no books, yet they were not without literature. In societies without writing, everything worth remembering — history, genealogy, law, ritual, practical knowledge, and story — had to be held in living memory and passed from voice to voice. To make such knowledge memorable and durable, people wrapped it in the arts of oral tradition: rhythm, rhyme, repetition, song, and narrative.\n\nThese were not crude substitutes for writing but sophisticated systems in their own right. A well-trained memory, disciplined by poetic form, could store and transmit vast bodies of knowledge with remarkable accuracy across generations. Aboriginal songlines, the genealogies of oral cultures worldwide, and the epic reciters of many traditions all attest to the astonishing capacity of the human mind, trained from childhood, to serve as a living library.' },
      { heading: 'Why We Tell Stories', body: 'Storytelling appears to be a human universal, found in every culture ever studied, which suggests it runs very deep in our nature. Around the fires of the Ice Age, our ancestors almost certainly told stories — of hunts and heroes, of the origins of the world, of the beings that dwelt in the dark beyond the firelight. Studies of modern hunter-gatherers find that a great share of night-time talk is storytelling, and that the best storytellers are esteemed and even reproductively favoured.\n\nStories did real work. They taught the young how to behave and how to survive; they bound the group with shared beliefs and shared identity; they explained the frightening and the unknown. Myth gave order to a chaotic world, placing human life within a larger story of gods, ancestors, and origins. The impulse to make meaning through narrative is among the oldest and most defining of human traits.' },
      { heading: 'The Shape of Myth', body: 'Though the myths of prehistoric peoples are lost to us in their original form, their descendants survive in the earliest recorded traditions, and certain themes recur across the world with striking persistence: the creation of the world and of humankind, a great flood, a trickster figure, a hero\'s journey, the origin of death. Some of these shared patterns may descend from very ancient stories carried by migrating peoples across tens of thousands of years.\n\nMyth was inseparable from ritual, art, and the rhythms of life. The painted caves, the carved figurines, the aligned monuments all likely enacted or referred to stories now beyond recovery. In myth, prehistoric humans grappled with the deepest questions — Where do we come from? Why do we die? What powers rule the world? — and their answers, preserved in performance, formed the spiritual and intellectual bedrock on which written religion and literature would later rise.' },
      { heading: 'From Voice to Verse', body: 'When writing finally appeared, the first literature it captured was not new but old — tales, hymns, and epics that had lived for ages on human lips. The Epic of Gilgamesh, written down in Mesopotamia, drew on far older oral traditions; the hymns of the Rigveda in India were composed and memorized orally for centuries before being committed to text; Homer\'s Iliad and Odyssey grew from generations of oral bardic performance before they were ever set in letters.\n\nThus the boundary between "prehistory" and "history" is not the boundary between silence and literature. It is the boundary between literature we can only infer and literature we can read. The written masterpieces of the first civilizations are, in a real sense, the earliest surviving snapshots of a storytelling tradition already immensely old — the moment when the endless spoken word first left its shadow on clay and stone.' },
      { heading: 'The Deepest Inheritance', body: 'Language and story are the true bridge across the vast gulf of prehistory. Genes carry our bodies forward; language carries our minds. Through it, the accumulated knowledge, values, and imagination of countless generations could be handed down, refined, and built upon — the great engine of cumulative culture that no other species possesses. Everything we call civilization is, at bottom, a structure built of words.\n\nWhen we read the oldest myths, or listen to the oral traditions still living today, we are hearing the faint echo of firesides tens of thousands of years gone. The specific words are lost, but the human need that shaped them — to explain, to remember, to belong, to be moved — is exactly our own. In that continuity of the storytelling mind lies perhaps the most intimate connection we can feel with the nameless millions who lived and dreamed before history began to write their names.' },
    ] },

  { id: 'prehistoric-17', eraId: 'prehistoric', order: 17, title: 'The Iceman\'s Secrets', subtitle: 'How We Read the Prehistoric Past', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Oetzi-Quinson.jpg',
    keyFacts: ['Ötzi the Iceman, found frozen in the Alps, died about 5,300 years ago', 'His body, clothes, and tools survived intact, a snapshot of Copper Age life', 'Modern science — DNA, isotopes, imaging — reveals his diet, health, and death', 'Archaeology reconstructs prehistory from clues the past never meant to leave'],
    relatedTimeline: [],
    sections: [
      { heading: 'A Body Out of Time', body: 'In 1991, hikers in the Alps on the border of Italy and Austria stumbled upon a corpse melting out of a glacier. They took it for a recent accident victim. It was, in fact, a man who had died some 5,300 years ago and been frozen ever since — the oldest well-preserved human body in Europe. Nicknamed Ötzi, he arrived from the Copper Age not as bones or artifacts but as a whole person: skin, organs, clothing, weapons, and last meal intact.\n\nÖtzi is a miracle of preservation and a marvel of what science can now recover from prehistory. Where most of the ancient dead leave only a scatter of stone and bone, the Iceman offers an almost complete snapshot of an individual life — and, through him, a vivid window onto a world that existed before writing, at the very edge of history.' },
      { heading: 'Dressed for the Mountains', body: 'Ötzi died fully equipped for the high Alps, and his gear reveals a technological sophistication easy to underestimate in "Stone Age" people. He wore a coat, leggings, and loincloth of stitched animal hides, a bearskin cap, a woven grass cape, and shoes of leather and bast stuffed with grass for insulation. His clothing used the hides of at least five species, chosen for their particular qualities.\n\nHe carried a remarkable kit: a copper axe of high purity, a flint dagger, a longbow and a quiver of arrows, a fire-starting set, and a birch-bark container. Among his belongings were lumps of birch fungus, likely used as medicine. Every item speaks of deep practical knowledge — of tanning, weaving, toolmaking, metallurgy, and mountain survival — carried by an ordinary man five thousand years ago.' },
      { heading: 'The Story in the Body', body: 'Modern science has interrogated Ötzi\'s body in extraordinary detail. Analysis of his stomach and intestines revealed his final meals: ibex and red deer meat, einkorn wheat, and even traces of toxic bracken fern. Isotopes in his teeth and bones, which reflect the water and food of his childhood and adult life, showed where he grew up and how he moved through the Alpine valleys.\n\nHis DNA was sequenced, revealing his brown eyes, his blood type, his lactose intolerance, and a genetic predisposition to heart disease — confirmed by hardened arteries visible in scans. He carried the eggs of intestinal parasites and the bacterium behind stomach ulcers. Sixty-one tattoos, mostly over joints, may mark an early form of pain therapy. From a single frozen body, science reconstructed a detailed medical and life history across five millennia.' },
      { heading: 'A Prehistoric Murder', body: 'For years Ötzi was thought to have died of exposure. Then, a decade after his discovery, an X-ray revealed an arrowhead lodged in his left shoulder, having severed a major artery. Ötzi had been shot from behind and had bled to death — a murder victim from the Copper Age. Further study found a deep cut on his hand, suggesting he had fought hand-to-hand shortly before, and traces of blood from four other people on his gear.\n\nThe evidence paints a tense final drama: a violent encounter, a chase or flight into the high mountains, and a killing from ambush. The murderer left Ötzi\'s valuable copper axe behind, deepening the mystery. Five thousand years later, science had reopened and partly solved a prehistoric homicide — a striking demonstration that even the intimate events of a single ancient life can, with the right clues, be recovered.' },
      { heading: 'The Detective Science', body: 'Ötzi embodies what archaeology has become: a forensic science that reads the past from traces it never meant to leave. Prehistoric peoples wrote nothing down, so everything we know of them is inferred from physical evidence — the shape of a tool, the layers of a dig, the chemistry of a bone, the pollen in ancient mud. Archaeologists are detectives working the oldest cold cases of all.\n\nThe toolkit is astonishing. Radiocarbon dating fixes the age of once-living things; DNA reveals ancestry, migration, and disease; isotope analysis traces diet and movement; microscopic wear on tools shows how they were used; residues betray ancient meals and medicines. Each advance lets prehistory speak a little more clearly, turning mute objects into testimony about how real people lived, ate, moved, healed, and died.' },
      { heading: 'Recovering the Silent Millennia', body: 'The deep human past is not truly silent — it is only written in an unfamiliar language that science is slowly learning to read. Bit by bit, the "prehistoric" is becoming historic, as new methods extract ever more meaning from ancient remains. A single tooth can now yield a genome; a scrap of sediment can reveal the DNA of people who left no bones at all. Our picture of prehistory grows sharper each year.\n\nÖtzi stands as both a symbol and a promise: proof of how much can be recovered from the past when preservation and technology align. Behind every stone tool and painted cave lie real human beings with real lives, and the great project of prehistoric science is to give them back their story. In doing so, it reminds us that the people of the deep past were not "primitives" but fully human — as skilled, as vulnerable, and as complex as ourselves.' },
    ] },

  { id: 'prehistoric-18', eraId: 'prehistoric', order: 18, title: 'The Hidden Half', subtitle: 'Women in the Prehistoric World', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Venus_von_Willendorf_01.jpg',
    keyFacts: ['Gathering by women likely supplied most calories in foraging societies', '"Venus" figurines are among the oldest known sculptures of the human form', 'Some Ice Age painted hands and burials appear to be those of women', 'New science is overturning old assumptions about prehistoric gender roles'],
    relatedTimeline: [],
    sections: [
      { heading: 'Half the Human Story', body: 'For most of the time we have studied prehistory, its women were nearly invisible. Popular images fixed on "man the hunter" — the spear-wielding male as the driver of human evolution — while women appeared, if at all, as passive figures in the background. But roughly half of all prehistoric humans were women, and their labour, knowledge, and choices shaped the human story as profoundly as any hunt. Recovering their role is one of the most important corrections in the modern study of the past.\n\nThe difficulty is that prehistory rarely labels its evidence by sex, and past assumptions filled the gaps with the biases of the present. New scientific methods and a more critical eye are now revealing a prehistoric world in which women were central actors — providers, innovators, artists, and leaders — not the shadowy dependents of an outdated story.' },
      { heading: 'The Providers', body: 'In many foraging societies studied by anthropologists, it is the gathering of plant foods — traditionally women\'s work — that supplies the majority of the diet, day in and day out, while hunting yields prized but unpredictable windfalls. If prehistoric societies were similar, then women\'s steady gathering was the true foundation of survival, feeding families far more reliably than the hunt.\n\nGathering was no simple task but a knowledge-intensive skill: identifying hundreds of plants, knowing their seasons and locations, distinguishing food from poison, and processing tough or toxic materials into nourishment. This botanical expertise, passed from mother to daughter, was arguably the deepest ecological knowledge in any society — and it was women who, in learning which seeds grew where, likely took the first steps toward the invention of agriculture itself.' },
      { heading: 'The Venus Figurines', body: 'Among the oldest sculptures of the human body are the so-called "Venus" figurines — small carvings of women, some over 30,000 years old, found across Ice Age Europe and beyond. Many emphasize the breasts, belly, and hips, and their meaning has been endlessly debated: fertility symbols, goddesses, self-portraits by the women who carved them, or something else entirely. The famous Venus of Willendorf is among the most celebrated artworks of the deep past.\n\nWhatever their purpose, these figurines put the female form at the very center of the earliest known sculpture, thousands of years before writing. They suggest that womanhood, fertility, and the body held profound significance in Ice Age thought. Some researchers argue the figurines were made by women themselves, giving us a rare possible glimpse of how prehistoric women saw and represented their own bodies.' },
      { heading: 'Rethinking Who Hunted', body: 'The neat division of "men hunt, women gather" is crumbling under new evidence. In the Andes, archaeologists found a 9,000-year-old burial of a young woman interred with a full big-game hunting toolkit; a survey of similar burials suggested that female hunters may have been far from rare in the early Americas. Studies of the pigment-blown hand stencils in Ice Age caves have argued, from their proportions, that many were made by women.\n\nSuch findings do not simply swap one rigid story for another; they reveal that prehistoric gender roles were more varied and flexible than the modern assumptions projected onto them. Different societies, in different times and places, divided labour in different ways. The lesson is humility: the deep past did not necessarily share our categories, and we must let the evidence, not our expectations, describe how prehistoric people actually lived.' },
      { heading: 'Bearers of Culture', body: 'Women\'s contributions to prehistoric life extended far beyond food. In most known societies, women are central to the transmission of culture — teaching children language, skills, story, and values, and thus carrying tradition from one generation to the next. In a world without writing, this role as educator and keeper of knowledge was foundational to the survival of everything a people knew.\n\nWomen were also likely pioneers of key technologies: the making of cordage, baskets, nets, and cloth; the processing and preservation of food; the crafting of clothing that let humans survive harsh climates and settle new lands. Many of these perishable crafts leave little archaeological trace, which has caused their importance — and their makers — to be badly underestimated. The "invisible" technologies of prehistory were often women\'s work, and they were essential to human success.' },
      { heading: 'Restoring the Whole Picture', body: 'The study of women in prehistory is not about inventing a flattering past but about seeing the past whole. For too long, a partial view mistook half of humanity for the whole and cast the other half as mere backdrop. Correcting this makes our picture of prehistoric life not only fairer but more accurate — and often more interesting, revealing a human world of shared and shifting roles rather than a rigid caricature.\n\nAs science grows more able to determine the sex of ancient remains and to detect the traces of perishable crafts, the hidden half of prehistory is steadily coming into view. What emerges is a portrait of women as full participants in the human adventure — providers and inventors, artists and teachers, and quite possibly hunters and leaders too. Their story, recovered at last, completes our understanding of the long age before history began.' },
    ] },

  { id: 'prehistoric-19', eraId: 'prehistoric', order: 19, title: 'The First Villages of the East', subtitle: 'Neolithic China and the Indus Threshold', estimatedMinutes: 15, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Banpo_matriarchal_clan_community.jpg',
    keyFacts: ['Rice was domesticated in the Yangtze valley thousands of years ago', 'Millet farming built early village societies along China\'s Yellow River', 'Jiahu in China yields some of the world\'s earliest music and possible signs', 'Mehrgarh in South Asia shows farming long before the Indus cities'],
    relatedTimeline: [],
    sections: [
      { heading: 'Farming\'s Many Cradles', body: 'The Neolithic Revolution was not a single event that spread outward from one place. Farming was invented independently several times, in different corners of the world, using different plants and animals. While wheat and barley were being domesticated in the Near East, entirely separate agricultural revolutions were unfolding in East and South Asia — and their descendants would feed some of the largest populations on Earth. To understand prehistory whole, we must look east.\n\nIn the great river valleys of China and the plains bordering the Indus, prehistoric peoples domesticated rice, millet, and other crops, built enduring villages, and laid the deep foundations of civilizations that would flourish for thousands of years. These eastern Neolithic worlds were as inventive and important as any in the west, though they remain far less known outside the regions where they occurred.' },
      { heading: 'Rice and Millet', body: 'China gave the world two great grain traditions. In the warm, wet south, along the Yangtze River, peoples domesticated rice from wild grasses many thousands of years ago, developing the flooded-field cultivation that would one day support enormous populations. In the cooler, drier north, along the Yellow River, farmers domesticated millet, a hardy grain suited to the loess soils of the region.\n\nThese two agricultural systems — rice in the south, millet in the north — anchored distinct but connected Neolithic worlds. Around them grew settled villages, pottery traditions, and rising populations. The domestication of rice in particular ranks among the most consequential events in human history, for it underpins the food supply of much of humanity to this day. China\'s prehistoric farmers were pioneers whose innovations still nourish billions.' },
      { heading: 'The Village of Banpo', body: 'Among the best-known windows onto Neolithic China is Banpo, a village near modern Xi\'an inhabited some 6,000 years ago by millet farmers of the Yangshao culture. Excavations revealed a planned settlement: round and square houses with sunken floors and thatched roofs, a surrounding ditch for defense, communal storage pits, kilns for firing pottery, and a cemetery set apart from the living.\n\nBanpo\'s people made distinctive painted pottery decorated with fish, faces, and geometric designs — among the finest ceramic art of the prehistoric world. Their village reveals a settled, organized community with craft specialists, shared facilities, and clear customs surrounding death. It is a vivid picture of Neolithic life in the East: farmers rooted to the land, building the enduring village societies from which Chinese civilization would grow.' },
      { heading: 'Music and Marks at Jiahu', body: 'At the site of Jiahu in central China, dating back some 9,000 years, archaeologists uncovered extraordinary finds. Among them were flutes carved from the wing bones of cranes — playable instruments, some with seven holes, that produce a musical scale. They are among the oldest known playable musical instruments in the world, proof that prehistoric people made and enjoyed music according to ordered systems of tone.\n\nJiahu also yielded markings incised on tortoise shells and bone that some scholars have suggested might be among the earliest precursors to writing, though their meaning is uncertain and hotly debated. Whether or not they are true signs, they attest to a rich symbolic life. Between its flutes, its careful burials, and its early rice, Jiahu reveals a prehistoric society of surprising sophistication at the very dawn of the Chinese Neolithic.' },
      { heading: 'Mehrgarh and the Road to the Indus', body: 'Far to the west, on the plains bordering the Indus River in what is now Pakistan, the site of Mehrgarh reveals farming taking root in South Asia thousands of years before the great Indus cities arose. Beginning around 7,000 BCE, the people of Mehrgarh cultivated wheat and barley, herded cattle, sheep, and goats, built mud-brick houses and granaries, and made pottery and ornaments.\n\nMehrgarh even yields evidence of remarkable skill: teeth drilled with fine flint tools, the earliest known dentistry, performed some 9,000 years ago. Over millennia, the descendants of such farming communities grew in number and complexity, until the plains of the Indus supported one of the ancient world\'s greatest urban civilizations — the Harappan cities, with their planned streets and drains. Mehrgarh is the deep prehistoric root of that civilization, the long Neolithic prelude to the cities of the Indus.' },
      { heading: 'The Eastern Threshold', body: 'By the close of prehistory, the Neolithic villages of East and South Asia stood on the threshold of civilization, just as those of the Near East did. Rising populations, surplus grain, craft specialization, trade, and increasingly complex societies were pushing toward the emergence of cities, writing, and states. Along China\'s rivers, cultures grew ever more elaborate, building toward the first Chinese dynasties; on the Indus plains, villages swelled toward the Harappan cities.\n\nThese eastern developments were not echoes of the west but parallel achievements, born of separate discoveries and distinctive crops. Recognizing them corrects a lingering bias that placed the origins of civilization solely in the Fertile Crescent. In truth, humanity crossed the threshold from prehistory to history in several places at once — and some of the most populous and enduring civilizations the world would ever know grew from the Neolithic villages of the East.' },
    ] },

  { id: 'prehistoric-20', eraId: 'prehistoric', order: 20, title: 'On the Edge of History', subtitle: 'The World the First Cities Inherited', estimatedMinutes: 16, xpReward: 120,
    imageUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/%C3%87atalh%C3%B6y%C3%BCk_after_the_first_excavations_by_James_Mellaart_and_his_team..jpg',
    keyFacts: ['Çatalhöyük in Anatolia was a dense town of thousands, 9,000 years ago', 'Surplus food allowed some people to specialize away from farming', 'Trade, religion, and social rank grew more complex in the late Neolithic', 'Writing arose to manage the wealth and organization of the first cities'],
    relatedTimeline: [],
    sections: [
      { heading: 'The Threshold Approached', body: 'By the end of prehistory, the settled world the Neolithic had created was straining toward something new. Farming villages had grown into towns; populations had multiplied; societies had grown richer, more organized, and more unequal. The last stretch of prehistory was a time of gathering momentum, as the innovations of thousands of years — agriculture, herding, pottery, metal, trade — combined and compounded toward the great transformation we call civilization.\n\nThis was the world the first cities inherited: not a blank slate but the accumulated achievement of countless generations of prehistoric people. When writing finally appeared and history "began," it did so atop a foundation entirely built in the ages before — a foundation of domesticated crops, technologies, beliefs, and social forms without which no city could have stood.' },
      { heading: 'Çatalhöyük: The Town Without Streets', body: 'One of the most remarkable late-Neolithic settlements was Çatalhöyük, in what is now Turkey, a dense town of perhaps several thousand people around 9,000 years ago. It had no streets: its mud-brick houses were packed tightly together, entered through the roof by ladder, so that the rooftops formed a kind of elevated pathway across the settlement. Inside, homes were plastered, decorated with paintings and cattle-horn installations, and often held the buried dead beneath their floors.\n\nÇatalhöyük startles us with its scale and its strangeness. It was a town-sized community that nonetheless lacked the palaces, temples, and obvious rulers we expect of cities — a large, egalitarian-seeming settlement of farmers living cheek by jowl. It shows the Neolithic pushing right up to the edge of urban life while retaining its own distinctive character, a bridge between the village and the city.' },
      { heading: 'The Power of Surplus', body: 'The engine of change was surplus. When farmers could grow more food than they immediately needed, that surplus could feed people who did not farm at all — potters, weavers, smiths, priests, chiefs, and warriors. For the first time, human societies could support full-time specialists, and specialization drove innovation, as skilled hands perfected crafts and knowledge.\n\nBut surplus also concentrated power. Whoever controlled the stored grain, the herds, the trade goods, and the labour of others gained wealth and authority over them. The rough equality of small foraging bands gave way to societies of ranks and classes, of leaders and led, of rich and poor. The seeds of kingship, priesthood, and the state were sown in the granaries of the late Neolithic, as surplus food became surplus power.' },
      { heading: 'Gods, Goods, and Rank', body: 'Late prehistoric societies grew richer in religion, trade, and hierarchy alike. Shrines and ritual objects multiplied; the dead were increasingly buried with grave goods that displayed their status, marking some individuals as more important than others. Elaborate burials of a few well-furnished graves amid many plain ones reveal societies where rank had become real and heritable.\n\nTrade networks lengthened and thickened, carrying obsidian, shells, metals, and fine goods across great distances and binding distant communities together. Prestige objects — rare, beautiful, and hard to obtain — became markers of wealth and power. Religion, meanwhile, grew more organized, with special places, specialists, and rituals that helped bind communities and legitimize their emerging leaders. The simple world of the first farmers was giving way to something far more complex and stratified.' },
      { heading: 'Writing: The Final Threshold', body: 'The last piece of the puzzle was writing, and it arose from the practical needs of the complex societies the Neolithic had produced. In Mesopotamia, as cities grew and their economies swelled, people needed to keep track of goods — how much grain was stored, who owed what, what had been traded. From systems of clay tokens and simple marks, around 3300 BCE, emerged the first true writing: cuneiform, pressed into clay tablets.\n\nWriting was, at first, mostly accounting — the bookkeeping of temples and rulers managing wealth beyond what memory could hold. But once invented, it could record anything: laws, letters, prayers, and stories. With writing, human beings gained the power to preserve their words across time and space, and the age of prehistory — the age before writing — came to an end. History, in the literal sense of the written record, could now begin.' },
      { heading: 'The Debt to the Deep Past', body: 'Everything that came after — every empire, religion, artwork, and idea of recorded history — rested on foundations laid in prehistory. The domestication of plants and animals, the mastery of fire and metal, the building of villages and monuments, the invention of language, art, music, and story: all of these were the achievements of nameless prehistoric people, worked out over tens of thousands of years before a single word was written down.\n\nWe often imagine history beginning with the first cities and scripts, as if the human story truly started there. But that is only the moment the record begins, not the moment humanity did. The vast, silent ages before were when we became fully human and built the world the first cities inherited. To honour prehistory is to recognize that the debt of civilization is owed, above all, to the countless generations who lived and learned and passed down their hard-won knowledge in the long dawn before history.' },
    ] },
];
