import type { Lesson } from '@/types';

export const LESSONS: Lesson[] = [
  { id: 'ancient-01', eraId: 'ancient', order: 1, title: 'The First Civilizations', subtitle: 'Mesopotamia and Egypt', estimatedMinutes: 8, xpReward: 100,
    keyFacts: ['Sumer invented writing (cuneiform) around 3100 BCE', 'The Egyptian Old Kingdom built the pyramids c.2686–2181 BCE', 'Hammurabi\'s Code (c.1754 BCE) is one of history\'s earliest legal codes', 'Both civilizations depended on river systems for agriculture'],
    relatedTimeline: ['t-cuneiform','t-pyramid','t-hammurabi'],
    sections: [
      { heading: 'The Cradle of Civilization', body: 'Around 3500 BCE, the Sumerians of southern Mesopotamia—the land between the Tigris and Euphrates rivers in modern Iraq—built the world\'s first cities. Uruk, the largest, may have housed 50,000 people. To manage grain surpluses and temple accounts, Sumerian scribes invented cuneiform writing around 3100 BCE, pressing wedge-shaped marks into clay tablets.\n\nThis writing system spread across the Near East and became the dominant script for over 3,000 years. Mesopotamian city-states also developed bronze tools, the wheel, and sophisticated irrigation canals that turned desert into farmland.' },
      { heading: 'Ancient Egypt: Gift of the Nile', body: 'Egypt\'s civilization emerged along the Nile around the same time as Sumer. The annual Nile flood deposited rich silt, making Egypt one of the ancient world\'s most fertile regions. Unified under Pharaoh Narmer around 3100 BCE, Egypt developed a strong centralized state ruled by god-kings.\n\nDuring the Old Kingdom (c.2686–2181 BCE), Pharaohs commanded the construction of the great pyramids at Giza—feats of engineering that remain awe-inspiring today. Egyptian hieroglyphics, mathematics, and medicine were among the most advanced of the ancient world.' },
      { heading: 'Laws, Trade, and Legacy', body: 'The Babylonian king Hammurabi (r.1792–1750 BCE) united Mesopotamia and issued one of the world\'s earliest written legal codes. The Code of Hammurabi established punishments for crimes and regulated commerce, reflecting a society built on trade and legal order.\n\nBoth Egypt and Mesopotamia maintained extensive trade networks. Egyptian gold and grain flowed to the Levant; Mesopotamian merchants traded with the Indus Valley. These early civilizations established the blueprint for organized government, religion, agriculture, and urban life that all later societies would build upon.' },
    ] },

  { id: 'ancient-02', eraId: 'ancient', order: 2, title: 'Classical Greece', subtitle: 'Democracy, Philosophy, and War', estimatedMinutes: 10, xpReward: 100,
    keyFacts: ['Athens established the world\'s first democracy around 508 BCE', 'The Persian Wars (499–449 BCE) united the Greek city-states', 'Socrates, Plato, and Aristotle founded Western philosophy', 'Alexander the Great spread Greek culture from Egypt to India'],
    relatedTimeline: ['t-democracy','t-persian-wars','t-alexander'],
    sections: [
      { heading: 'The Greek City-States', body: 'Ancient Greece was not a unified nation but a collection of independent city-states (poleis), each with its own government and culture. Athens and Sparta were the most powerful. Sparta developed a militaristic society; every male citizen trained as a soldier from age seven. Athens, by contrast, became a center of art, philosophy, and political innovation.\n\nAround 508 BCE, the Athenian reformer Cleisthenes introduced demokratia—rule by the people—the world\'s first democratic government. Citizens (free adult males) voted directly on laws and policies in the Assembly, a revolutionary idea that would influence all future democracies.' },
      { heading: 'War and Conflict', body: 'When the Persian Empire invaded Greece in 490 BCE, the Athenians defeated them at Marathon—a run of 26 miles reportedly made by a messenger to Athens announced the victory, giving the marathon race its name. A second Persian invasion in 480 BCE saw the legendary Spartan stand at Thermopylae before the Athenians destroyed the Persian fleet at Salamis.\n\nVictory over Persia brought Athens to the height of its power. The Athenian leader Pericles used tribute money to build the Parthenon on the Acropolis, a masterpiece of classical architecture. But rivalry between Athens and Sparta erupted in the devastating Peloponnesian War (431–404 BCE), which exhausted both powers.' },
      { heading: 'The Philosophers', body: 'Classical Athens produced some of history\'s greatest thinkers. Socrates taught through questioning, challenging Athenians to examine their beliefs. His method—the Socratic method—remains central to education today. Socrates was sentenced to death in 399 BCE for "corrupting the youth."\n\nHis student Plato wrote dialogues exploring justice, beauty, and the ideal state. Plato\'s student Aristotle systematized logic, biology, ethics, and politics, tutoring the young Alexander of Macedon. Alexander the Great (r.336–323 BCE) conquered an empire stretching from Greece to Egypt and India, spreading Greek language and culture—Hellenism—across the ancient world.' },
    ] },

  { id: 'ancient-03', eraId: 'ancient', order: 3, title: 'The Roman Republic and Empire', subtitle: 'From Seven Hills to World Dominion', estimatedMinutes: 12, xpReward: 100,
    keyFacts: ['Rome was founded as a republic around 509 BCE', 'Julius Caesar was assassinated on 15 March 44 BCE', 'At its height, the Roman Empire covered 5 million km²', 'The Western Roman Empire fell in 476 CE'],
    relatedTimeline: ['t-roman-republic','t-caesar','t-pax-romana','t-rome-fall'],
    sections: [
      { heading: 'The Roman Republic', body: 'According to tradition, Rome was founded in 753 BCE on seven hills beside the Tiber River. After expelling its kings around 509 BCE, Rome became a republic governed by elected consuls and a Senate of aristocrats (patricians). Over time, plebeians (commoners) won greater rights through the Twelve Tables—Rome\'s first written law code.\n\nRome expanded steadily across Italy, defeating rivals through military discipline and clever diplomacy. By 264 BCE, Rome controlled the Italian peninsula and set its sights on the wider Mediterranean world.' },
      { heading: 'Conquest and the Punic Wars', body: 'Rome\'s clash with Carthage—a powerful North African city-state—produced the three Punic Wars (264–146 BCE). The Carthaginian general Hannibal famously crossed the Alps with war elephants and devastated Roman armies at Cannae in 216 BCE. Yet Rome\'s resilience prevailed; Carthage was ultimately destroyed in 146 BCE.\n\nRoman conquest brought great wealth but also social tension. Generals like Marius and Sulla commanded personal armies loyal to them rather than the Senate, setting the stage for civil war. Julius Caesar\'s military genius in Gaul (58–50 BCE) made him the most powerful man in Rome—until his assassination on the Ides of March, 44 BCE.' },
      { heading: 'Empire and the Pax Romana', body: 'Caesar\'s heir Octavian defeated his rivals and became Rome\'s first emperor as Augustus in 27 BCE. The Augustan age inaugurated the Pax Romana ("Roman Peace")—two centuries of relative stability, prosperity, and cultural achievement. The Roman road network, aqueducts, and legal system unified a vast empire from Britain to Mesopotamia.\n\nAt its height under Emperor Trajan (r.98–117 CE), Rome\'s empire covered 5 million square kilometers and held perhaps 70 million people. But overexpansion, economic strain, and military pressure from Germanic tribes and the Huns gradually weakened the empire. In 476 CE, the last Western Roman emperor was deposed, though the Eastern Roman (Byzantine) Empire survived for another thousand years.' },
    ] },

  { id: 'ancient-04', eraId: 'ancient', order: 4, title: 'The Ancient East', subtitle: 'Persia, India, and China', estimatedMinutes: 9, xpReward: 100,
    keyFacts: ['The Achaemenid Persian Empire was the largest empire of the ancient world', 'Emperor Ashoka of India promoted Buddhist ethics across Asia', 'The Han Dynasty unified China and established the civil service exam', 'The Silk Road connected China to the Mediterranean by 100 BCE'],
    relatedTimeline: ['t-persia','t-ashoka','t-han','t-silk-road'],
    sections: [
      { heading: 'The Persian Empire', body: 'Under Cyrus the Great (r.550–530 BCE), the Achaemenid Persians built the ancient world\'s largest empire, stretching from Anatolia to the Indus Valley. Unlike many ancient conquerors, Cyrus was known for religious tolerance—he allowed the Jewish exiles in Babylon to return to their homeland, an act celebrated in the Hebrew Bible.\n\nDarius I organized the empire into provinces (satrapies) and built the Royal Road stretching 2,700 km from Sardis to Susa, enabling rapid communication. Persian culture—Zoroastrian religion, monumental architecture at Persepolis, and sophisticated administration—deeply influenced all later Near Eastern civilizations.' },
      { heading: 'India: The Maurya Empire and Ashoka', body: 'India\'s Maurya Empire (322–185 BCE), founded by Chandragupta Maurya, was the first to unify most of the Indian subcontinent. His grandson Ashoka (r.268–232 BCE) became one of history\'s most remarkable rulers. After the brutal conquest of Kalinga, Ashoka converted to Buddhism, renounced further conquest, and governed according to dharma (ethical duty).\n\nAshoka\'s rock edicts—inscriptions carved across his empire—promoted tolerance, non-violence, and welfare. He sent Buddhist missionaries to Sri Lanka, Central Asia, and Greece, helping spread Buddhism across Asia. Indian mathematics, particularly the concept of zero and the decimal system, would later transform the world through Arab scholars.' },
      { heading: 'China and the Silk Road', body: 'China\'s Han Dynasty (206 BCE–220 CE) ruled one of the ancient world\'s most sophisticated civilizations. Emperor Wu (r.141–87 BCE) expanded the empire into Central Asia and established the Silk Road—a network of trade routes linking China to Rome. Silk, spices, and ideas flowed both ways along these routes.\n\nHan China developed paper, the seismograph, and cast iron. Confucian ethics shaped governance; the civil service examination system—admitting officials based on merit—was a revolutionary concept. When the Han Dynasty fell in 220 CE, China fragmented into rival kingdoms, but the Han model of unified imperial rule remained the ideal for all subsequent Chinese dynasties.' },
    ] },

  { id: 'medieval-01', eraId: 'middle-ages', order: 1, title: 'The Fall of Rome and Early Middle Ages', subtitle: 'From Empire to Feudal Europe', estimatedMinutes: 8, xpReward: 100,
    keyFacts: ['The Western Roman Empire fell in 476 CE', 'Charlemagne was crowned Holy Roman Emperor in 800 CE', 'Feudalism organized medieval society into lords and serfs', 'The Catholic Church preserved literacy and learning after Rome\'s fall'],
    relatedTimeline: ['t-rome-fall','t-charlemagne','t-feudalism'],
    sections: [
      { heading: 'The Collapse of Rome', body: 'By the 5th century CE, the Western Roman Empire was crumbling under pressure from Germanic tribes, economic collapse, and political instability. In 410 CE, the Visigoths sacked Rome—an event that shocked the ancient world. In 476 CE, the Germanic chieftain Odoacer deposed the last Western emperor, Romulus Augustulus, marking the traditional end of Rome.\n\nWhat followed was not simply "dark ages" but a complex transformation. Germanic kingdoms—Franks, Visigoths, Ostrogoths—replaced Roman provinces. The Catholic Church, however, maintained continuity, preserving Latin literacy and providing social services across the former empire.' },
      { heading: 'Charlemagne and the Carolingian Renaissance', body: 'The Frankish king Charlemagne (r.768–814 CE) reunited much of Western Europe through conquest and diplomacy. On Christmas Day 800, Pope Leo III crowned him "Emperor of the Romans"—a symbolic assertion that Christian Europe had a new secular ruler. Charlemagne promoted education, standardized weights and measures, and brought scholars to his court at Aachen.\n\nThe Carolingian Renaissance—a revival of learning under Charlemagne\'s patronage—helped preserve classical texts. After Charlemagne\'s death, his empire was divided among his grandsons under the Treaty of Verdun (843), creating the rough outlines of modern France and Germany.' },
      { heading: 'Feudalism and Medieval Society', body: 'Medieval European society organized itself around feudalism—a hierarchical system of land ownership and military obligation. Kings granted land (fiefs) to nobles in exchange for military service. Nobles sublet land to knights; peasants (serfs) worked the land in exchange for protection. The manor—a self-sufficient estate—was the basic economic unit.\n\nThe Catholic Church stood apart from—and often above—this secular hierarchy. The Pope could excommunicate kings and interdict entire kingdoms. Monasteries preserved manuscripts, ran schools, and provided hospitals. This interweaving of religious and secular power defined medieval European civilization.' },
    ] },

  { id: 'medieval-02', eraId: 'middle-ages', order: 2, title: 'The Crusades and the Islamic Golden Age', subtitle: 'Faith, Knowledge, and Conflict', estimatedMinutes: 10, xpReward: 100,
    keyFacts: ['Islam spread from Arabia across the Middle East and North Africa within 100 years of Muhammad\'s death', 'The Islamic Golden Age (8th–13th centuries) preserved and advanced Greek science', 'The First Crusade captured Jerusalem in 1099', 'The Crusades increased trade and cultural exchange between Europe and the East'],
    relatedTimeline: ['t-islam','t-golden-age','t-crusades','t-saladin'],
    sections: [
      { heading: 'The Rise of Islam', body: 'In 610 CE, the merchant Muhammad received his first revelation in a cave near Mecca, beginning the religion of Islam. By his death in 632 CE, most of Arabia was united under Islam. Within a century, Arab armies had conquered the Persian Empire, Egypt, North Africa, and Spain—one of history\'s most rapid imperial expansions.\n\nThe Umayyad and Abbasid caliphates created a vast, cosmopolitan Islamic world stretching from the Atlantic to Central Asia. Arabic became the language of scholarship, trade, and religion, binding together diverse peoples from Spain to Persia.' },
      { heading: 'The Islamic Golden Age', body: 'While Western Europe recovered slowly from Rome\'s fall, the Islamic world experienced a golden age of intellectual achievement (8th–13th centuries). The Abbasid court in Baghdad—"the City of Peace"—became the world\'s greatest center of learning. Scholars translated Greek texts by Aristotle, Euclid, and Galen, preserving them from loss.\n\nIslamic scholars made original contributions across mathematics (algebra was developed by al-Khwarizmi), astronomy, medicine (Ibn Sina\'s Canon of Medicine was used in European universities for centuries), and optics. This knowledge later flowed back to Europe, igniting the Scientific Revolution.' },
      { heading: 'The Crusades', body: 'In 1095, Pope Urban II called for a holy war to recapture Jerusalem from the Seljuk Turks. The First Crusade succeeded spectacularly—Jerusalem fell to Crusader forces in 1099 in a bloody massacre. Four Crusader states were established in the Holy Land. But Christian control proved fragile; Saladin, the Kurdish sultan of Egypt, retook Jerusalem in 1187.\n\nSeven major Crusades followed over two centuries. Though the Crusades ultimately failed militarily, they profoundly shaped both European and Islamic civilizations. They intensified trade with the East, introduced Europeans to Islamic scholarship and goods, and left deep, lasting religious hatreds that echoed for centuries.' },
    ] },

  { id: 'medieval-03', eraId: 'middle-ages', order: 3, title: 'The Black Death and Late Medieval Crisis', subtitle: 'Plague, Revolt, and Cultural Change', estimatedMinutes: 8, xpReward: 100,
    keyFacts: ['The Black Death killed 30–60% of Europe\'s population (1347–1353)', 'The plague originated in Central Asia and spread via trade routes', 'Labor shortages after the plague empowered surviving peasants', 'The crisis accelerated the end of feudalism and the rise of the Renaissance'],
    relatedTimeline: ['t-black-death','t-peasants-revolt'],
    sections: [
      { heading: 'Origins and Spread of the Plague', body: 'The Black Death—caused by the bacterium Yersinia pestis, carried by fleas on rats—originated in Central Asia around 1340. Spreading along trade routes, it reached the Black Sea ports in 1346 and entered Europe through Sicily in October 1347. Within five years, it had swept from Portugal to Poland.\n\nThe disease took three forms: bubonic plague (swollen lymph nodes), pneumonic plague (lung infection), and septicemic plague (blood infection). Contemporary medicine was powerless; bleeding and herbal remedies did nothing. Cities were hardest hit—London lost perhaps half its population; Florence lost 60%.' },
      { heading: 'Death, Chaos, and Resilience', body: 'At its peak, the Black Death killed thousands per day in major cities. Bodies piled up faster than they could be buried. Social order broke down; priests refused to administer last rites, doctors fled. Some turned to flagellant movements—publicly whipping themselves as penance. Paranoid communities massacred Jewish populations, falsely blaming them for poisoning wells.\n\nBy the time the worst waves passed in the 1350s, Europe had lost between one-third and one-half of its population—perhaps 25 million people. The psychological trauma was immense. Art and literature became saturated with death imagery; the "dance of death" (danse macabre) became a popular motif.' },
      { heading: 'Social and Cultural Consequences', body: 'The plague\'s aftermath transformed European society. With so many peasants dead, those who survived could demand higher wages and better conditions. Serfdom declined rapidly in Western Europe. The English Peasants\' Revolt of 1381 showed that the lower classes were no longer willing to accept their traditional station.\n\nThe Church, which had failed to explain or stop the catastrophe, lost prestige. Questioning of Church authority helped lay the groundwork for the Renaissance and later the Protestant Reformation. Perversely, the labor shortage accelerated technological innovation—labor-saving devices became more economically valuable, including the printing press.' },
    ] },

  { id: 'earlymod-01', eraId: 'early-modern', order: 1, title: 'The Renaissance and Age of Exploration', subtitle: 'Rebirth of Ideas, Discovery of Worlds', estimatedMinutes: 10, xpReward: 100,
    keyFacts: ['The Renaissance began in Italian city-states in the 14th century', 'Humanism placed mankind, not God, at the center of intellectual inquiry', 'Columbus reached the Americas in 1492', 'The Columbian Exchange transformed both hemispheres'],
    relatedTimeline: ['t-renaissance','t-columbus','t-columbian-exchange'],
    sections: [
      { heading: 'The Italian Renaissance', body: 'The Renaissance ("rebirth") began in the wealthy city-states of northern Italy—Florence, Venice, Milan—in the 14th century. Wealthy patrons like the Medici family of Florence funded artists, architects, and scholars, triggering an explosion of creativity. Artists studied classical Greek and Roman works to understand perspective, proportion, and the human form.\n\nLeonardo da Vinci (1452–1519) embodied the "Renaissance man"—painter, sculptor, scientist, engineer, and anatomist. Michelangelo\'s Sistine Chapel ceiling and his statue of David remain pinnacles of Western art. Architects like Brunelleschi designed the Florence Cathedral dome using forgotten Roman techniques.' },
      { heading: 'Humanism and the Printing Press', body: 'Renaissance humanism placed human experience and reason at the center of intellectual life—a shift from the medieval focus on God and theology. Scholars studied classical texts in their original Greek and Latin, recovering lost knowledge and questioning Church interpretations. Erasmus\'s wit and Thomas More\'s Utopia explored human nature and ideal society.\n\nJohannes Gutenberg\'s invention of the movable-type printing press around 1440 was transformative. Books that had taken monks months to copy could now be printed in days. By 1500, over 20 million books circulated in Europe, spreading new ideas with unprecedented speed—and making the Reformation possible.' },
      { heading: 'The Age of Exploration', body: 'Portuguese sailors, seeking a sea route to Asia\'s spice trade, crept down the African coast through the 15th century. Vasco da Gama reached India in 1498. Meanwhile, Christopher Columbus, sailing for Spain, reached the Caribbean in 1492—believing he had found Asia. The "New World" he discovered would reshape global history.\n\nThe Columbian Exchange that followed transformed both hemispheres. Europeans brought horses, cattle, wheat, and devastating diseases (smallpox, measles) to the Americas; they returned with potatoes, tomatoes, maize, and tobacco. Indigenous American populations, lacking immunity to European diseases, collapsed by up to 90% within a century—one of history\'s greatest demographic catastrophes.' },
    ] },

  { id: 'earlymod-02', eraId: 'early-modern', order: 2, title: 'The Protestant Reformation', subtitle: 'Religious Revolution and Wars of Faith', estimatedMinutes: 9, xpReward: 100,
    keyFacts: ['Martin Luther posted his 95 Theses in 1517', 'The Reformation split Western Christianity into Catholic and Protestant branches', 'The Thirty Years\' War (1618–1648) killed 8 million people', 'The Peace of Westphalia established the principle of national sovereignty'],
    relatedTimeline: ['t-luther','t-thirty-years-war','t-westphalia'],
    sections: [
      { heading: 'Crisis in the Church', body: 'By 1500, the Catholic Church faced widespread criticism for corruption, worldliness, and the selling of "indulgences"—certificates supposedly reducing time in purgatory. The papal court in Rome lived in enormous luxury, funded by taxes on ordinary Christians. Many clergy were ignorant, absentee, or openly immoral. Yet the Church tolerated no dissent; earlier reformers like Jan Hus had been burned as heretics.' },
      { heading: 'Luther and the Reformation', body: 'On October 31, 1517, the German monk Martin Luther nailed his 95 Theses to the door of Wittenberg\'s Castle Church—a list of arguments against indulgences and Church corruption. Printed and circulated across Germany within weeks, Luther\'s challenge ignited a firestorm. Summoned before the Diet of Worms in 1521, Luther refused to recant: "Here I stand; I can do no other."\n\nExcommunicated by the Pope, Luther launched the Protestant Reformation, arguing that salvation came through faith alone (sola fide), not Church rituals. Other reformers followed—Zwingli in Zurich, Calvin in Geneva. By 1560, Northern Europe was predominantly Protestant, shattering Western Christianity\'s thousand-year unity.' },
      { heading: 'Wars of Religion and the Peace of Westphalia', body: 'The Reformation triggered generations of religious war. The Thirty Years\' War (1618–1648), which began as a religious conflict in the Holy Roman Empire, became a general European war that killed 8 million people and depopulated parts of Germany by a third. Armies devastated the countryside; famine and plague followed.\n\nThe Peace of Westphalia (1648) ended the war and established new principles: rulers could determine the religion of their territories, and states should not interfere in each other\'s internal affairs. These principles of sovereignty and non-interference became the foundation of the modern international state system.' },
    ] },

  { id: 'earlymod-03', eraId: 'early-modern', order: 3, title: 'Scientific Revolution and Enlightenment', subtitle: 'Reason Reshapes the World', estimatedMinutes: 11, xpReward: 100,
    keyFacts: ['Copernicus proposed heliocentrism in 1543', 'Newton\'s Principia (1687) established classical mechanics', 'Enlightenment thinkers challenged monarchies and the Church', 'The American and French Revolutions applied Enlightenment ideals'],
    relatedTimeline: ['t-copernicus','t-newton','t-enlightenment','t-french-revolution'],
    sections: [
      { heading: 'Overturning the Cosmos', body: 'For over a thousand years, Europeans believed the Earth stood motionless at the center of the universe—the Ptolemaic model endorsed by Aristotle and the Church. In 1543, the Polish astronomer Nicolaus Copernicus published On the Revolutions of the Celestial Spheres, arguing the Earth revolved around the Sun.\n\nGalileo Galilei used the newly invented telescope in 1609 to observe mountains on the Moon, moons around Jupiter, and phases of Venus—all supporting the Copernican model. The Church condemned Galileo in 1633, forcing him to recant. But the evidence was overwhelming, and the old cosmology could not survive.' },
      { heading: 'Newton and the New Science', body: 'Isaac Newton (1642–1727) synthesized a century of astronomical discoveries into a unified mathematical framework. His Principia Mathematica (1687) described the laws of motion and universal gravitation—the same force that caused an apple to fall kept the Moon in orbit. Newton showed that nature operated according to mathematical laws that human reason could discover.\n\nThe "Scientific Revolution" transformed how Europeans understood knowledge itself. Francis Bacon championed empiricism—knowledge gained through observation and experiment. René Descartes contributed analytical geometry and the principle of systematic doubt. Science became a method, not just a set of facts, and that method began reshaping every field.' },
      { heading: 'The Enlightenment', body: 'The Scientific Revolution\'s success inspired intellectuals to apply reason to society, government, and religion. French philosophes—Voltaire, Montesquieu, Rousseau, Diderot—questioned traditional authority, religious dogma, and absolute monarchy. Montesquieu\'s The Spirit of the Laws argued for separation of powers; Rousseau\'s Social Contract posited government legitimacy resting on popular consent.\n\nThese ideas traveled across the Atlantic. American founders like Jefferson drew directly on Enlightenment thought when writing the Declaration of Independence (1776). In France, Enlightenment ideas fueled revolutionary anger. When the French Revolution exploded in 1789, it swept away the monarchy, the aristocracy, and the Church\'s special privileges—remaking French society on Enlightenment principles.' },
    ] },

  { id: 'modern-01', eraId: 'modern', order: 1, title: 'The Industrial Revolution', subtitle: 'Steam, Steel, and Social Change', estimatedMinutes: 10, xpReward: 100,
    keyFacts: ['The Industrial Revolution began in Britain around 1760', 'Steam power transformed manufacturing, transport, and agriculture', 'Urbanization created new social classes—the factory owner and the industrial worker', 'By 1900, industrial nations dominated the globe'],
    relatedTimeline: ['t-steam-engine','t-railways','t-industrialization'],
    sections: [
      { heading: 'The British Origins', body: 'The Industrial Revolution began in Britain around 1760, driven by a unique combination of factors: abundant coal and iron, a stable government, secure property rights, a growing empire providing markets and raw materials, and a culture that valued practical invention. James Watt\'s improved steam engine (1769) became its symbol—a machine that could turn heat into mechanical work.\n\nTextile mills in Lancashire, iron foundries in Birmingham, and coal mines in Wales transformed Britain\'s economy. By 1800, Britain produced more iron and steel than the rest of the world combined. Child labor was common; workers toiled 14-hour days in dangerous conditions for meager wages.' },
      { heading: 'Railroads and the Shrinking World', body: 'The steam locomotive revolutionized transportation. George Stephenson\'s Rocket (1829) inaugurated the railway age. By 1850, Britain had 10,000 km of railways; by 1900, the world had 790,000 km. Railways moved goods and people at unprecedented speed—cutting travel times from days to hours.\n\nThe telegraph, patented in the 1830s and 1840s, enabled near-instant long-distance communication. For the first time in human history, information could travel faster than a human being. These technologies together created the first truly integrated national—and eventually global—markets.' },
      { heading: 'Social Consequences', body: 'Industrialization uprooted millions. Peasants migrated to industrial cities; by 1851, Britain was the world\'s first majority-urban nation. These cities were often overcrowded, polluted, and disease-ridden—cholera epidemics killed thousands. Yet industrialization also created wealth, lowered prices, and eventually raised living standards.\n\nNew social classes emerged: the industrial bourgeoisie (factory owners) and the proletariat (wage laborers). Karl Marx and Friedrich Engels, observing Manchester\'s squalor, wrote The Communist Manifesto (1848), arguing class struggle was history\'s engine. Trade unions organized; workers eventually won shorter hours, better pay, and political rights. By 1900, industrialization had spread across Europe, North America, and Japan—creating the modern world.' },
    ] },

  { id: 'modern-02', eraId: 'modern', order: 2, title: 'The World Wars', subtitle: 'The Century of Total War', estimatedMinutes: 14, xpReward: 100,
    keyFacts: ['WWI (1914–1918) killed 20 million people and destroyed four empires', 'The Treaty of Versailles (1919) imposed harsh terms on Germany', 'WWII (1939–1945) was history\'s deadliest conflict, with 70–85 million dead', 'The Holocaust murdered 6 million Jews and millions of others'],
    relatedTimeline: ['t-wwi','t-versailles','t-wwii','t-holocaust'],
    sections: [
      { heading: 'The Great War', body: 'World War I began in August 1914, triggered by the assassination of Austro-Hungarian Archduke Franz Ferdinand in Sarajevo. The underlying causes were deeper: rigid alliance systems, imperial rivalry, an arms race, and aggressive nationalism. Within weeks, the great powers of Europe were at war.\n\nThe Western Front quickly became a nightmare of trench warfare. Millions of soldiers faced each other across no-man\'s land, separated by barbed wire and machine guns. The Battle of the Somme (1916) alone produced over 1 million casualties. New weapons—poison gas, tanks, airplanes—made the war uniquely terrible. By 1918, 20 million were dead, and four great empires—Ottoman, Austro-Hungarian, Russian, and German—had collapsed.' },
      { heading: 'The Road to World War II', body: 'The Treaty of Versailles (1919) humiliated Germany with war guilt, reparations, and territorial losses. The Great Depression (1929–1939) devastated economies worldwide, creating fertile ground for extremism. Adolf Hitler\'s Nazi Party rose to power in Germany in 1933 on promises of national revival, blaming Jews and communists for Germany\'s woes.\n\nHitler remilitarized the Rhineland, annexed Austria, and seized Czechoslovakia while Britain and France, traumatized by WWI, pursued appeasement. When Germany invaded Poland on September 1, 1939, Britain and France finally declared war. WWII had begun.' },
      { heading: 'World War II and the Holocaust', body: 'WWII was the most destructive conflict in human history. Germany conquered most of Europe by 1941; Japan seized vast swaths of Asia and the Pacific. Germany\'s invasion of the Soviet Union in June 1941 opened the largest land campaign in history. America entered the war after Japan\'s attack on Pearl Harbor in December 1941.\n\nThe Nazi regime systematically murdered 6 million Jews, along with Roma, disabled people, homosexuals, and political opponents—the Holocaust. Allied forces liberated the death camps in 1945. Germany surrendered in May 1945; Japan surrendered in August after the United States dropped atomic bombs on Hiroshima and Nagasaki. Between 70 and 85 million people had died—the bloodiest conflict in human history.' },
    ] },

  { id: 'modern-03', eraId: 'modern', order: 3, title: 'The Cold War and Decolonization', subtitle: 'Two Superpowers, One Divided World', estimatedMinutes: 12, xpReward: 100,
    keyFacts: ['The Cold War (1947–1991) was an ideological struggle between the USA and USSR', 'Both sides developed nuclear weapons capable of destroying civilization', 'Dozens of African and Asian nations gained independence in the 1950s–70s', 'The Soviet Union collapsed in 1991'],
    relatedTimeline: ['t-cold-war','t-korean-war','t-vietnam','t-decolonization','t-berlin-wall'],
    sections: [
      { heading: 'The Cold War Begins', body: 'As WWII ended, the alliance between the democratic West (led by the USA) and communist East (led by the USSR) fractured. By 1947, Winston Churchill described an "Iron Curtain" dividing Europe. The USA responded with the Truman Doctrine and the Marshall Plan—billions of dollars to rebuild Western Europe and contain communism.\n\nThe Soviet Union developed its own atomic bomb in 1949; China became communist the same year. Both superpowers built vast nuclear arsenals capable of destroying civilization. The Cuban Missile Crisis of 1962—when Soviet missiles were discovered in Cuba—brought the world within hours of nuclear war before a tense diplomatic resolution.' },
      { heading: 'Proxy Wars and Competition', body: 'The Cold War was fought indirectly through proxy wars and competition for influence in the developing world. The Korean War (1950–53) ended in stalemate at roughly the 38th parallel—where it had started. The Vietnam War (1955–75) drew massive American involvement; the US eventually withdrew after losing 58,000 soldiers, and Vietnam was reunified under communist rule.\n\nBoth superpowers competed in space—the "Space Race." The USSR launched Sputnik in 1957 and put Yuri Gagarin in orbit in 1961; the USA responded by landing on the Moon in 1969. Scientific and technological competition drove unprecedented advances.' },
      { heading: 'Decolonization and the Soviet Collapse', body: 'While the superpowers competed, the European empires collapsed. India gained independence in 1947; dozens of African nations gained independence in the 1950s and 1960s. The process was often violent—France fought brutal wars in Vietnam and Algeria. Cold War competition complicated decolonization, as each superpower backed favored factions in newly independent nations.\n\nBy the 1980s, the Soviet economy was stagnating. Mikhail Gorbachev\'s reforms (glasnost and perestroika) unleashed forces he could not control. Eastern European nations broke free in 1989—the Berlin Wall fell on November 9. In 1991, the Soviet Union itself dissolved into 15 independent states. The Cold War was over.' },
    ] },

  { id: 'modern-04', eraId: 'modern', order: 4, title: 'Globalization and the Contemporary World', subtitle: 'One Planet, Many Challenges', estimatedMinutes: 8, xpReward: 100,
    keyFacts: ['The World Wide Web was invented by Tim Berners-Lee in 1989', 'Global trade as a share of GDP doubled between 1960 and 2000', 'September 11, 2001 transformed global politics and security', 'Climate change is the defining environmental challenge of the 21st century'],
    relatedTimeline: ['t-internet','t-9-11','t-climate'],
    sections: [
      { heading: 'The Digital Revolution', body: 'The invention of the personal computer (1970s), the World Wide Web (1989), and the smartphone (2007) transformed human society as profoundly as the printing press or the steam engine. By 2023, over 5 billion people had internet access. Information, culture, and commerce now flow globally in real time.\n\nSocial media platforms—Facebook, Twitter, Instagram—gave individuals unprecedented ability to communicate and organize, fueling political movements from the Arab Spring to global climate strikes. But the digital revolution also enabled misinformation, mass surveillance, and the concentration of power in a handful of technology corporations.' },
      { heading: 'Economic Globalization', body: 'The fall of the Soviet Union and China\'s opening to markets triggered the greatest economic globalization in history. Trade barriers fell; supply chains stretched across continents. Hundreds of millions escaped poverty—especially in China and India. The World Trade Organization (1995) created rules for global commerce.\n\nBut globalization\'s benefits were unevenly distributed. Manufacturing jobs moved from wealthy nations to lower-wage countries. Inequality rose within many nations even as it fell between them. The 2008 financial crisis—originating in American mortgage markets—cascaded into a global recession, demonstrating how interconnected and fragile the world economy had become.' },
      { heading: 'The 21st Century', body: 'The September 11, 2001 attacks by al-Qaeda killed 3,000 people in New York, Washington, and Pennsylvania—and triggered two decades of American military involvement in Afghanistan and Iraq. Terrorism became a defining security concern of the early 21st century.\n\nClimate change—driven by the greenhouse gas emissions of industrial civilization—is the defining challenge of our era. Global temperatures are rising, sea levels are climbing, and extreme weather events are intensifying. The scientific consensus is unequivocal, yet political action has been halting. How humanity responds to climate change will shape the history of the coming centuries more than any other decision.' },
    ] },
];

export function getLessonById(id: string) { return LESSONS.find(l => l.id === id); }
export function getEraLessons(eraId: string) { return LESSONS.filter(l => l.eraId === eraId).sort((a,b) => a.order - b.order); }
