// ─── Real historical territory geometry loader ──────────────────────────────
// Loads the verified boundary polygons generated by
// `scripts/fetch_territory_polygons.py` (sourced from aourednik/historical-
// basemaps) from `public/data/map-territories/{topicId}.json`. When a topic has
// real geometry it replaces the curated in-app rings on the Territory Map, so
// borders are professional and historically accurate. Everything is cached and
// degrades to null (→ curated geometry) if an asset is missing or offline.

const BASE = '/data/map-territories';

export interface TerritoryFeatureProps {
  lesson_id?: number | null;
  topic_id: string;
  entity_name: string;
  year_start: number;
  year_end: number;
  fill_color: string;
  stroke_color: string;
  stroke_width?: number;
  opacity?: number;
  source?: string;
  source_snapshot?: string;
}

export interface TerritoryFeatureCollection {
  type: 'FeatureCollection';
  features: {
    type: 'Feature';
    properties: TerritoryFeatureProps;
    geometry: { type: 'MultiPolygon' | 'Polygon'; coordinates: number[][][] | number[][][][] };
  }[];
}

/** One outer ring in the app's [lat,lng] convention, plus its fill colour. */
export interface RealPolygon {
  coords: [number, number][];
  color: string;
  label?: string;
}

const fcCache = new Map<string, TerritoryFeatureCollection | null>();
let indexPromise: Promise<Set<string>> | null = null;

/** The set of topic_ids that have generated real geometry (from _index.json). */
export function loadRealGeometryIndex(): Promise<Set<string>> {
  if (!indexPromise) {
    indexPromise = fetch(`${BASE}/_index.json`)
      .then(r => (r.ok ? r.json() : []))
      .then((ids: unknown) => new Set(Array.isArray(ids) ? (ids as string[]) : []))
      .catch(() => new Set<string>());
  }
  return indexPromise;
}

/** Fetch a topic's FeatureCollection, or null when it has no real geometry. */
export async function loadTerritoryGeoJson(topicId: string): Promise<TerritoryFeatureCollection | null> {
  if (fcCache.has(topicId)) return fcCache.get(topicId)!;
  const index = await loadRealGeometryIndex();
  if (!index.has(topicId)) {
    fcCache.set(topicId, null);
    return null;
  }
  try {
    const res = await fetch(`${BASE}/${topicId}.json`);
    const fc = res.ok ? ((await res.json()) as TerritoryFeatureCollection) : null;
    fcCache.set(topicId, fc);
    return fc;
  } catch {
    fcCache.set(topicId, null);
    return null;
  }
}

/**
 * Convert a FeatureCollection into the app's polygon rings ([lat,lng] outer
 * rings, holes dropped for the simple renderer). One RealPolygon per outer ring.
 */
export function toRealPolygons(fc: TerritoryFeatureCollection): RealPolygon[] {
  const out: RealPolygon[] = [];
  for (const f of fc.features) {
    const color = f.properties.fill_color ?? '#f59e0b';
    const label = f.properties.entity_name;
    const g = f.geometry;
    const polys = (g.type === 'MultiPolygon' ? g.coordinates : [g.coordinates]) as number[][][][];
    for (const poly of polys) {
      const outer = poly[0]; // [ [lng,lat], ... ]
      if (!outer || outer.length < 4) continue;
      out.push({ coords: outer.map(([lng, lat]) => [lat, lng] as [number, number]), color, label });
    }
  }
  return out;
}

/** Convenience: load + convert in one call. */
export async function loadRealPolygons(topicId: string): Promise<RealPolygon[] | null> {
  const fc = await loadTerritoryGeoJson(topicId);
  return fc ? toRealPolygons(fc) : null;
}
