import type { Language } from '@/i18n/translations';

export interface TerritoryMarker {
  name: string;
  lat: number;
  lng: number;
  note?: string;
}

export interface TerritoryTopic {
  id: string;
  era: 'ancient' | 'medieval' | 'early-modern' | 'modern';
  period: string;
  center: [number, number];
  zoom: number;
  title: string;
  titleI18n: Partial<Record<Exclude<Language, 'en'>, string>>;
  description: string;
  markers: TerritoryMarker[];
}

export const TERRITORY_TOPICS: TerritoryTopic[] = [
  // ── ANCIENT ──────────────────────────────────────────────────────────────
  {
    id: 'mesopotamia',
    era: 'ancient',
    period: '3100–500 BCE',
    center: [30, 42],
    zoom: 5,
    title: 'Mesopotamia & Ancient Egypt',
    titleI18n: { es: 'Mesopotamia y Antiguo Egipto', ru: 'Месопотамия и Древний Египет', mk: 'Месопотамија и Античко Египет' },
    description: 'The Fertile Crescent — from Mesopotamia\'s Tigris-Euphrates to the Nile Valley — hosted humanity\'s first cities, writing, and empires.',
    markers: [
      { name: 'Uruk', lat: 31.32, lng: 45.6, note: 'World\'s first city & cuneiform writing (~3100 BCE)' },
      { name: 'Babylon', lat: 32.54, lng: 44.42, note: 'Hammurabi\'s Code, Hanging Gardens' },
      { name: 'Ur', lat: 30.96, lng: 46.1, note: 'Major Sumerian city-state' },
      { name: 'Memphis', lat: 29.84, lng: 31.25, note: 'Ancient Egyptian capital' },
      { name: 'Giza', lat: 29.97, lng: 31.13, note: 'Great Pyramids (~2560 BCE)' },
      { name: 'Thebes', lat: 25.72, lng: 32.66, note: 'Egyptian religious capital, Valley of the Kings' },
    ],
  },
  {
    id: 'classical-greece',
    era: 'ancient',
    period: '800–323 BCE',
    center: [38.5, 24],
    zoom: 6,
    title: 'Classical Greece',
    titleI18n: { es: 'Grecia Clásica', ru: 'Классическая Греция', mk: 'Класична Грција' },
    description: 'Ancient Greek city-states forged democracy, philosophy, and science — foundations of Western civilisation.',
    markers: [
      { name: 'Athens', lat: 37.97, lng: 23.72, note: 'Birthplace of democracy and philosophy' },
      { name: 'Sparta', lat: 37.07, lng: 22.43, note: 'Militaristic rival of Athens' },
      { name: 'Olympia', lat: 37.6, lng: 21.63, note: 'Ancient Olympic Games (776 BCE)' },
      { name: 'Delphi', lat: 38.48, lng: 22.5, note: 'Oracle of Apollo' },
      { name: 'Thermopylae', lat: 38.8, lng: 22.53, note: '300 Spartans vs Persia (480 BCE)' },
      { name: 'Pella', lat: 40.76, lng: 22.52, note: 'Birthplace of Alexander the Great' },
    ],
  },
  {
    id: 'persian-empire',
    era: 'ancient',
    period: '550–330 BCE',
    center: [33, 52],
    zoom: 4,
    title: 'The Persian Empire',
    titleI18n: { es: 'El Imperio Persa', ru: 'Персидская Империя', mk: 'Персиската Империја' },
    description: 'The Achaemenid Empire stretched from Egypt to India — the largest empire the world had yet seen, united by the Royal Road.',
    markers: [
      { name: 'Persepolis', lat: 29.93, lng: 52.89, note: 'Ceremonial capital of Achaemenid Empire' },
      { name: 'Pasargadae', lat: 30.19, lng: 53.17, note: 'Tomb of Cyrus the Great' },
      { name: 'Susa', lat: 32.19, lng: 48.26, note: 'Administrative capital' },
      { name: 'Ecbatana', lat: 34.8, lng: 48.5, note: 'Median capital, summer residence of kings' },
    ],
  },
  {
    id: 'roman-empire',
    era: 'ancient',
    period: '27 BCE–476 CE',
    center: [42, 14],
    zoom: 4,
    title: 'The Roman Empire',
    titleI18n: { es: 'El Imperio Romano', ru: 'Римская Империя', mk: 'Римската Империја' },
    description: 'At its peak under Trajan (117 CE), Rome unified the Mediterranean world — from Britain to Mesopotamia — with roads, law, and Latin.',
    markers: [
      { name: 'Rome', lat: 41.9, lng: 12.5, note: 'Eternal City and capital of the Empire' },
      { name: 'Carthage', lat: 36.86, lng: 10.32, note: 'Destroyed after three Punic Wars (146 BCE)' },
      { name: 'Alexandria', lat: 31.2, lng: 29.92, note: 'Centre of Hellenistic learning' },
      { name: 'Constantinople', lat: 41.01, lng: 28.98, note: 'Eastern capital (founded 330 CE)' },
      { name: 'Londinium', lat: 51.51, lng: -0.12, note: 'Roman London, founded ~43 CE' },
      { name: 'Jerusalem', lat: 31.77, lng: 35.22, note: 'Jewish-Roman conflict, destroyed 70 CE' },
    ],
  },
  {
    id: 'ancient-china',
    era: 'ancient',
    period: '221 BCE–220 CE',
    center: [35, 110],
    zoom: 4,
    title: 'Ancient China — Han Dynasty',
    titleI18n: { es: 'China Antigua — Dinastía Han', ru: 'Древний Китай — Династия Хань', mk: 'Античка Кина — Хан Династија' },
    description: 'The Han Dynasty unified China under Confucian bureaucracy, extended the Silk Road, and established cultural patterns lasting millennia.',
    markers: [
      { name: "Chang'an", lat: 34.27, lng: 108.95, note: "Han capital (modern Xi'an)" },
      { name: 'Luoyang', lat: 34.62, lng: 112.45, note: 'Eastern Han capital' },
      { name: 'Dunhuang', lat: 40.14, lng: 94.66, note: 'Silk Road gateway and Buddhist caves' },
      { name: 'Great Wall', lat: 40.43, lng: 116.57, note: 'Northern defence against nomads' },
    ],
  },

  // ── MEDIEVAL ─────────────────────────────────────────────────────────────
  {
    id: 'byzantine-empire',
    era: 'medieval',
    period: '476–1453 CE',
    center: [40, 33],
    zoom: 5,
    title: 'Byzantine Empire',
    titleI18n: { es: 'Imperio Bizantino', ru: 'Византийская Империя', mk: 'Византиската Империја' },
    description: 'The Eastern Roman Empire survived the fall of the West by nearly a millennium, preserving Greek-Roman culture and Orthodox Christianity.',
    markers: [
      { name: 'Constantinople', lat: 41.01, lng: 28.98, note: 'Capital — fell 1453 CE to the Ottomans' },
      { name: 'Nicaea', lat: 40.42, lng: 29.72, note: 'Council of Nicaea (325 CE)' },
      { name: 'Antioch', lat: 36.2, lng: 36.16, note: 'Major city of the eastern empire' },
      { name: 'Thessaloniki', lat: 40.64, lng: 22.94, note: 'Second city of the Byzantine Empire' },
    ],
  },
  {
    id: 'islamic-caliphates',
    era: 'medieval',
    period: '632–1258 CE',
    center: [28, 42],
    zoom: 4,
    title: 'Islamic Caliphates',
    titleI18n: { es: 'Califatos Islámicos', ru: 'Исламские Халифаты', mk: 'Исламски Калифати' },
    description: 'From Arabia, Islam spread across the Middle East, North Africa, Central Asia, and Spain — creating a vast civilisation of science and trade.',
    markers: [
      { name: 'Mecca', lat: 21.42, lng: 39.83, note: 'Birthplace of Islam, holiest city' },
      { name: 'Medina', lat: 24.47, lng: 39.61, note: "Prophet Muhammad's capital" },
      { name: 'Baghdad', lat: 33.34, lng: 44.4, note: 'Abbasid capital — House of Wisdom' },
      { name: 'Damascus', lat: 33.51, lng: 36.29, note: 'Umayyad capital' },
      { name: 'Córdoba', lat: 37.89, lng: -4.78, note: 'Islamic Spain — centre of medieval learning' },
    ],
  },
  {
    id: 'mongol-empire',
    era: 'medieval',
    period: '1206–1368 CE',
    center: [48, 95],
    zoom: 3,
    title: 'The Mongol Empire',
    titleI18n: { es: 'El Imperio Mongol', ru: 'Монгольская Империя', mk: 'Монголската Империја' },
    description: "Genghis Khan's descendants forged the largest contiguous land empire in history, connecting Europe to China and reshaping Eurasia.",
    markers: [
      { name: 'Karakorum', lat: 47.2, lng: 102.84, note: "Genghis Khan's Mongolian capital" },
      { name: 'Beijing', lat: 39.9, lng: 116.4, note: "Kublai Khan's Yuan China capital" },
      { name: 'Samarkand', lat: 39.65, lng: 66.97, note: 'Silk Road hub, conquered 1220' },
      { name: 'Baghdad', lat: 33.34, lng: 44.4, note: 'Sacked 1258 — end of Abbasid Caliphate' },
      { name: 'Krakow', lat: 50.06, lng: 19.94, note: 'Western limit of Mongol invasion (1241)' },
    ],
  },
  {
    id: 'crusader-states',
    era: 'medieval',
    period: '1096–1291 CE',
    center: [32, 36],
    zoom: 6,
    title: 'Crusades & the Holy Land',
    titleI18n: { es: 'Cruzadas y Tierra Santa', ru: 'Крестовые Походы и Святая Земля', mk: 'Крстоносните Походи и Светата Земја' },
    description: 'Nine major Crusades attempted to secure Christian control of Jerusalem, transforming medieval European politics and culture.',
    markers: [
      { name: 'Jerusalem', lat: 31.77, lng: 35.22, note: 'Holy city — conquered 1099, lost 1187' },
      { name: 'Acre', lat: 32.92, lng: 35.07, note: 'Final Crusader stronghold (fell 1291)' },
      { name: 'Antioch', lat: 36.2, lng: 36.16, note: 'First major Crusader city-state' },
      { name: 'Constantinople', lat: 41.01, lng: 28.98, note: 'Sacked by Crusaders — 4th Crusade (1204)' },
    ],
  },
  {
    id: 'medieval-japan',
    era: 'medieval',
    period: '1185–1600 CE',
    center: [36, 137],
    zoom: 5,
    title: 'Medieval Japan',
    titleI18n: { es: 'Japón Medieval', ru: 'Средневековая Япония', mk: 'Средновековна Јапонија' },
    description: "Japan's feudal age saw samurai clans struggle for supremacy — forging the code of Bushido and the aesthetic of Zen Buddhism.",
    markers: [
      { name: 'Kyoto', lat: 35.01, lng: 135.77, note: 'Imperial capital (794–1868 CE)' },
      { name: 'Kamakura', lat: 35.32, lng: 139.55, note: 'First shogunate capital (1185 CE)' },
      { name: 'Osaka', lat: 34.69, lng: 135.5, note: "Toyotomi Hideyoshi's fortress-city" },
      { name: 'Edo', lat: 35.69, lng: 139.69, note: 'Tokugawa capital (modern Tokyo)' },
    ],
  },

  // ── EARLY MODERN ─────────────────────────────────────────────────────────
  {
    id: 'ottoman-empire',
    era: 'early-modern',
    period: '1453–1683 CE',
    center: [39, 35],
    zoom: 4,
    title: 'Ottoman Empire at its Peak',
    titleI18n: { es: 'Imperio Otomano en su Apogeo', ru: 'Османская Империя на Пике Могущества', mk: 'Отоманската Империја на Врвот' },
    description: "Under Suleiman the Magnificent (1520–66), the Ottomans controlled three continents — from Vienna's gates to the Persian Gulf.",
    markers: [
      { name: 'Constantinople', lat: 41.01, lng: 28.98, note: 'Capital, fell to Mehmed II (1453)' },
      { name: 'Mecca', lat: 21.42, lng: 39.83, note: 'Holy city under Ottoman protection' },
      { name: 'Cairo', lat: 30.04, lng: 31.24, note: 'Mamluk capital conquered 1517' },
      { name: 'Baghdad', lat: 33.34, lng: 44.4, note: 'Taken from Safavids (1534)' },
      { name: 'Vienna', lat: 48.2, lng: 16.37, note: 'Failed Ottoman sieges (1529, 1683)' },
    ],
  },
  {
    id: 'renaissance-italy',
    era: 'early-modern',
    period: '1400–1600 CE',
    center: [43, 12],
    zoom: 6,
    title: 'Renaissance Italy',
    titleI18n: { es: 'Italia del Renacimiento', ru: 'Италия эпохи Ренессанса', mk: 'Ренесансна Италија' },
    description: 'The Italian city-states became the epicentre of the Renaissance — a rebirth of classical learning, art, and humanism funded by merchant wealth.',
    markers: [
      { name: 'Florence', lat: 43.77, lng: 11.25, note: 'Medici patronage — Botticelli, da Vinci, Brunelleschi' },
      { name: 'Rome', lat: 41.9, lng: 12.5, note: 'Vatican — Michelangelo, Raphael, St. Peter\'s' },
      { name: 'Venice', lat: 45.44, lng: 12.33, note: 'Trading republic and printing press hub' },
      { name: 'Milan', lat: 45.46, lng: 9.19, note: "Leonardo da Vinci's workshop" },
    ],
  },
  {
    id: 'age-of-exploration',
    era: 'early-modern',
    period: '1415–1600 CE',
    center: [20, -20],
    zoom: 2,
    title: 'Age of Exploration',
    titleI18n: { es: 'La Época de la Exploración', ru: 'Эпоха Великих Географических Открытий', mk: 'Доба на Географски Откритија' },
    description: 'Portuguese and Spanish explorers mapped the coasts of Africa, crossed the Atlantic, and circumnavigated the globe — transforming world trade.',
    markers: [
      { name: 'Lisbon', lat: 38.72, lng: -9.14, note: "Portugal's hub of maritime exploration" },
      { name: 'Tenochtitlan', lat: 19.43, lng: -99.13, note: 'Aztec capital (modern Mexico City), conquered 1521' },
      { name: 'Cusco', lat: -13.53, lng: -71.97, note: 'Inca capital, conquered by Pizarro (1533)' },
      { name: 'Calicut', lat: 11.25, lng: 75.78, note: "Vasco da Gama's India landing (1498)" },
      { name: 'Cape of Good Hope', lat: -34.36, lng: 18.47, note: "Bartholomeu Dias's landmark (1488)" },
    ],
  },
  {
    id: 'protestant-reformation',
    era: 'early-modern',
    period: '1517–1648 CE',
    center: [51, 12],
    zoom: 5,
    title: 'Protestant Reformation',
    titleI18n: { es: 'La Reforma Protestante', ru: 'Протестантская Реформация', mk: 'Протестантска Реформација' },
    description: "Luther's 95 Theses (1517) fractured Western Christianity, unleashing a century of religious wars that redrawn Europe's political map.",
    markers: [
      { name: 'Wittenberg', lat: 51.87, lng: 12.65, note: 'Luther posted his 95 Theses here (1517)' },
      { name: 'Geneva', lat: 46.2, lng: 6.15, note: "Calvin's theocratic republic" },
      { name: 'Zurich', lat: 47.38, lng: 8.54, note: "Zwingli's reformed city" },
      { name: 'Augsburg', lat: 48.37, lng: 10.9, note: 'Peace of Augsburg (1555)' },
      { name: 'London', lat: 51.51, lng: -0.12, note: 'Henry VIII breaks with Rome — Anglican Church' },
    ],
  },
  {
    id: 'american-revolution',
    era: 'early-modern',
    period: '1763–1789 CE',
    center: [38, -80],
    zoom: 5,
    title: 'American Revolution',
    titleI18n: { es: 'La Revolución Americana', ru: 'Американская Революция', mk: 'Американска Револуција' },
    description: "The thirteen British colonies declared independence (1776) and defeated the British Empire, establishing the world's first modern democratic republic.",
    markers: [
      { name: 'Philadelphia', lat: 39.95, lng: -75.17, note: 'Continental Congress and Declaration of Independence' },
      { name: 'Boston', lat: 42.36, lng: -71.06, note: 'Boston Tea Party — "shot heard round the world"' },
      { name: 'Valley Forge', lat: 40.1, lng: -75.45, note: "Washington's winter encampment (1777–78)" },
      { name: 'Yorktown', lat: 37.24, lng: -76.51, note: 'Final battle — British surrender (1781)' },
    ],
  },
  {
    id: 'french-revolution',
    era: 'early-modern',
    period: '1789–1815 CE',
    center: [47, 3],
    zoom: 5,
    title: 'French Revolution & Napoleon',
    titleI18n: { es: 'Revolución Francesa y Napoleón', ru: 'Французская Революция и Наполеон', mk: 'Француска Револуција и Наполеон' },
    description: "The French Revolution dismantled the ancien régime; Napoleon's conquests spread revolutionary ideals across Europe before final defeat.",
    markers: [
      { name: 'Paris', lat: 48.86, lng: 2.35, note: 'Storming of the Bastille (1789)' },
      { name: 'Versailles', lat: 48.8, lng: 2.12, note: 'Palace of Louis XVI' },
      { name: 'Waterloo', lat: 50.68, lng: 4.41, note: "Napoleon's final defeat (1815)" },
      { name: 'Moscow', lat: 55.75, lng: 37.62, note: 'Failed Napoleonic campaign (1812)' },
      { name: 'Trafalgar', lat: 36.02, lng: -6.03, note: "Nelson defeats Napoleon's fleet (1805)" },
    ],
  },

  // ── MODERN ───────────────────────────────────────────────────────────────
  {
    id: 'industrial-revolution',
    era: 'modern',
    period: '1760–1850 CE',
    center: [53, -2],
    zoom: 6,
    title: 'Industrial Revolution',
    titleI18n: { es: 'La Revolución Industrial', ru: 'Промышленная Революция', mk: 'Индустриска Револуција' },
    description: "Britain's transformation from agrarian to industrial economy — steam power, factories, railways — changed human life more than any prior development.",
    markers: [
      { name: 'Manchester', lat: 53.48, lng: -2.24, note: 'First industrial city — "Cottonopolis"' },
      { name: 'Birmingham', lat: 52.48, lng: -1.89, note: "Ironworking and Watt's steam engine" },
      { name: 'London', lat: 51.51, lng: -0.12, note: 'Financial centre and Great Exhibition 1851' },
      { name: 'Liverpool', lat: 53.4, lng: -2.99, note: 'Port linking industry to global trade' },
      { name: 'Glasgow', lat: 55.86, lng: -4.25, note: 'Shipbuilding capital of the Empire' },
    ],
  },
  {
    id: 'wwi',
    era: 'modern',
    period: '1914–1918 CE',
    center: [49, 12],
    zoom: 4,
    title: 'World War I',
    titleI18n: { es: 'Primera Guerra Mundial', ru: 'Первая Мировая Война', mk: 'Прва Светска Војна' },
    description: "The 'war to end all wars' consumed Europe — trench warfare, industrial weapons, and the collapse of four empires (Austro-Hungarian, Ottoman, Russian, German).",
    markers: [
      { name: 'Sarajevo', lat: 43.85, lng: 18.36, note: 'Assassination of Franz Ferdinand (28 Jun 1914)' },
      { name: 'Verdun', lat: 49.16, lng: 5.39, note: 'Longest WWI battle — 300,000+ killed' },
      { name: 'The Somme', lat: 50.0, lng: 2.7, note: '1 million casualties in 141 days (1916)' },
      { name: 'Gallipoli', lat: 40.35, lng: 26.58, note: 'Allied disaster against Ottoman forces (1915)' },
      { name: 'Berlin', lat: 52.52, lng: 13.4, note: 'German capital — armistice 11 Nov 1918' },
    ],
  },
  {
    id: 'wwii',
    era: 'modern',
    period: '1939–1945 CE',
    center: [50, 20],
    zoom: 3,
    title: 'World War II',
    titleI18n: { es: 'Segunda Guerra Mundial', ru: 'Вторая Мировая Война', mk: 'Втора Светска Војна' },
    description: "The deadliest conflict in history — 70–85 million lives. Nazi conquest of Europe, the Holocaust, Pacific war, and Allied victory reshaped the world order.",
    markers: [
      { name: 'Berlin', lat: 52.52, lng: 13.4, note: 'Nazi capital — fell 2 May 1945' },
      { name: 'Stalingrad', lat: 48.71, lng: 44.51, note: 'Turning point on the Eastern Front (1943)' },
      { name: 'Normandy', lat: 49.37, lng: -0.85, note: 'D-Day landings — 6 June 1944' },
      { name: 'Hiroshima', lat: 34.39, lng: 132.45, note: 'First atomic bomb — 6 August 1945' },
      { name: 'Auschwitz', lat: 50.03, lng: 19.2, note: 'Largest Nazi extermination camp' },
      { name: 'Pearl Harbor', lat: 21.36, lng: -157.98, note: 'Japanese surprise attack — 7 Dec 1941' },
    ],
  },
  {
    id: 'cold-war',
    era: 'modern',
    period: '1947–1991 CE',
    center: [50, 20],
    zoom: 2,
    title: 'Cold War',
    titleI18n: { es: 'La Guerra Fría', ru: 'Холодная Война', mk: 'Студена Војна' },
    description: 'The US and USSR faced off in a global ideological struggle — proxy wars, the space race, nuclear brinkmanship, and the Berlin Wall — until Soviet collapse in 1991.',
    markers: [
      { name: 'Washington D.C.', lat: 38.9, lng: -77.04, note: 'US capital and NATO leader' },
      { name: 'Moscow', lat: 55.75, lng: 37.62, note: 'Soviet capital — Warsaw Pact leader' },
      { name: 'Berlin', lat: 52.52, lng: 13.4, note: 'Divided city — Wall built 1961, fell 1989' },
      { name: 'Havana', lat: 23.14, lng: -82.36, note: 'Cuban Missile Crisis (1962)' },
      { name: 'Hanoi', lat: 21.03, lng: 105.85, note: 'Vietnam War — major proxy conflict' },
    ],
  },
  {
    id: 'yugoslav-wars',
    era: 'modern',
    period: '1991–2001 CE',
    center: [44, 18],
    zoom: 6,
    title: 'The Yugoslav Wars',
    titleI18n: { es: 'Las Guerras Yugoslavas', ru: 'Югославские Войны', mk: 'Југословенските Војни' },
    description: "The dissolution of Yugoslavia triggered brutal ethnic conflicts in the Balkans — the worst European atrocities since WWII — leading to NATO intervention.",
    markers: [
      { name: 'Sarajevo', lat: 43.85, lng: 18.36, note: 'Besieged for 1,425 days (1992–95)' },
      { name: 'Srebrenica', lat: 44.1, lng: 19.3, note: 'Massacre of 8,000 Bosniaks (1995)' },
      { name: 'Vukovar', lat: 45.35, lng: 19.0, note: 'Croatian city destroyed in 1991' },
      { name: 'Belgrade', lat: 44.82, lng: 20.46, note: 'Yugoslav/Serbian capital' },
      { name: 'Pristina', lat: 42.67, lng: 21.17, note: 'Kosovo capital — NATO air campaign 1999' },
    ],
  },
  {
    id: 'macedonian-struggle',
    era: 'modern',
    period: '1893–1913 CE',
    center: [41.5, 22],
    zoom: 7,
    title: 'The Macedonian Struggle',
    titleI18n: { es: 'La Lucha Macedonia', ru: 'Македонская Борьба', mk: 'Македонската Борба' },
    description: "The struggle for Macedonia's liberation from Ottoman rule — armed uprisings, the Ilinden Revolt (1903), and the Balkan Wars — defined modern Macedonian identity.",
    markers: [
      { name: 'Bitola', lat: 41.03, lng: 21.33, note: 'VMRO headquarters and centre of resistance' },
      { name: 'Skopje', lat: 41.99, lng: 21.43, note: 'Capital of Ottoman-era Macedonia' },
      { name: 'Ohrid', lat: 41.12, lng: 20.8, note: 'Cultural and religious centre of Macedonia' },
      { name: 'Kruševo', lat: 41.37, lng: 21.25, note: 'Ilinden Uprising capital (August 1903)' },
      { name: 'Thessaloniki', lat: 40.64, lng: 22.94, note: 'Major Ottoman city, VMRO activity centre' },
    ],
  },
];
