// ─── Clio sample dialogues · translated bodies ────────────────────────────────
// The chip labels were translated (`topicI18n`) but the exchange behind them was
// not, so a learner reading the app in Macedonian clicked "Колапсот на
// бронзеното доба" and got four paragraphs of English.
//
// These are curated examples of Clio's voice, loaded into an empty chat before
// the student has typed anything, so they are shipped as data rather than
// translated at runtime: an empty state should be instant, it should not spend
// the learner's AI allowance, and a scripted demonstration should read the same
// way every time.
//
// Each array is index-aligned with that dialogue's `turns`. Dates, figures and
// proper names are carried across unchanged — a translation that rounds 132
// billion gold marks or moves Ugarit is a worse failure than an English one.

import type { SampleDialogue } from './clioSampleDialogues';

export type SampleLang = keyof SampleDialogue['topicI18n'];

export const SAMPLE_LANGS: SampleLang[] = ['es', 'ru', 'mk', 'de', 'fr'];

export const SAMPLE_TURNS_I18N: Record<string, Record<SampleLang, string[]>> = {
  'sample-bronze-collapse': {
    es: [
      "¿Por qué se derrumbaron tantas civilizaciones a la vez hacia el 1200 a. C.?",
      "Entre 1200 y 1150 a. C. casi todas las grandes potencias del Mediterráneo oriental cayeron en el espacio de una sola vida humana: el Imperio hitita se desvaneció, los palacios micénicos ardieron desde Pilos hasta Micenas, Ugarit fue destruida tan de repente que quedaron cartas sin enviar cociéndose en sus hornos, y Egipto, bajo Ramsés III, apenas logró rechazar a los Pueblos del Mar en 1177 a. C. Lo fascinante de este colapso es que ninguna causa aislada lo explica. La lectura más sólida hoy lo entiende como un fallo sistémico: la sequía (confirmada por los sondeos de polen del mar de Galilea), los terremotos, las migraciones y las incursiones tensaron cada uno por su lado una red de economías palaciales que dependían entre sí incluso para obtener el bronce: cobre de Chipre y estaño llegado desde tan lejos como Afganistán. Cuando el comercio se rompió, se rompió también todo reino que vivía de él. Aquí va una pregunta que merece rumiarse: si aquellos reinos hubieran estado menos conectados, ¿crees que habrían sobrevivido, o esa misma interdependencia era también la fuente de su riqueza?",
      "Supongo que la interdependencia los hizo ricos Y frágiles al mismo tiempo, ¿no?",
      "Exactamente, y acabas de formular lo que los historiadores llaman la paradoja de la complejidad. La interdependencia permitió que un rey micénico tuviera ámbar báltico y oro egipcio en la misma tumba, pero también significaba que una sequía en Anatolia podía dejar sin estaño a un herrero de Grecia. Fíjate en que el patrón se repite después: la red cerealista romana en el siglo V d. C., o incluso el sistema financiero global de 2008; la eficiencia y la fragilidad crecieron juntas. Una civilización, sin embargo, resistió el 1177 a. C. mejor que sus vecinas: Egipto sobrevivió, mermado pero entero, en parte porque el Nilo le daba un suministro interno de alimentos que ningún saqueador del mar podía cortar. Así que piénsalo: ¿qué necesitaría mantener «en casa» una civilización para resistir el colapso: alimento, energía, conocimiento? ¿Y es eso siquiera posible sin renunciar a la riqueza que trae el comercio?",
    ],
    ru: [
      "Почему около 1200 года до н. э. столько цивилизаций рухнуло разом?",
      "Между 1200 и 1150 годами до н. э. почти все крупные державы Восточного Средиземноморья пали на протяжении одной человеческой жизни: Хеттское царство исчезло, микенские дворцы от Пилоса до Микен сгорели, Угарит был разрушен так внезапно, что неотправленные письма остались запекаться в его печах, а Египет при Рамсесе III едва отбил народы моря в 1177 году до н. э. Самое любопытное в этом крахе то, что ни одна отдельная причина его не объясняет. Наиболее убедительное объяснение сегодня — системный сбой: засуха (подтверждённая пыльцевыми колонками из Галилейского моря), землетрясения, переселения и набеги, каждое по-своему, давили на сеть дворцовых хозяйств, которые зависели друг от друга даже ради самой бронзы: медь шла с Кипра, олово — из мест столь далёких, как Афганистан. Когда торговля оборвалась, оборвалось и каждое царство, что на неё опиралось. Вот вопрос, над которым стоит подумать: если бы эти царства были связаны слабее, уцелели бы они — или взаимозависимость и была источником их богатства?",
      "Наверное, взаимозависимость сделала их одновременно и богатыми, И хрупкими?",
      "Именно так, и ты только что сформулировал то, что историки называют парадоксом сложности. Взаимозависимость позволяла микенскому царю положить в одну гробницу балтийский янтарь и египетское золото, но она же означала, что засуха в Анатолии могла оставить кузнеца в Греции без олова. Обрати внимание, как этот рисунок повторяется позже: римская хлебная сеть в V веке н. э. или даже мировая финансовая система 2008 года — эффективность и хрупкость росли вместе. Впрочем, одна цивилизация пережила 1177 год до н. э. лучше соседей: Египет уцелел, ослабленный, но целый, отчасти потому, что Нил давал ему внутренний источник продовольствия, который не мог перерезать ни один морской налётчик. Так что подумай: что цивилизации нужно держать «у себя дома», чтобы устоять перед крахом, — еду, энергию, знание? И возможно ли это вообще, не отказавшись от богатства, которое приносит торговля?",
    ],
    mk: [
      "Зошто толку многу цивилизации пропаднале одеднаш околу 1200 година пр. н. е.?",
      "Меѓу 1200 и 1150 година пр. н. е. речиси сите големи сили на источниот Медитеран паднале во рамките на еден човечки век: Хетитското царство исчезнало, микенските палати од Пилос до Микена изгореле, Угарит бил уништен толку ненадејно што неиспратените писма останале да се печат во неговите печки, а Египет под Рамзес III едвај ги одбил Народите на морето во 1177 година пр. н. е. Она што го прави овој колапс толку интересен е тоа што ниту една единствена причина не го објаснува. Најубедливото денешно толкување го гледа како системски пад: сушата (потврдена со поленските јадра од Галилејското Море), земјотресите, преселбите и упадите, секој од нив, притискале врз мрежа од палатски стопанства што зависеле едно од друго дури и за самата бронза: бакар од Кипар, калај од места далечни како Авганистан. Кога трговијата пукнала, пукнало и секое царство што се потпирало на неа. Еве прашање вредно за размисла: ако тие царства биле помалку поврзани, мислиш ли дека ќе преживееја — или таа меѓузависност била и изворот на нивното богатство?",
      "Веројатно меѓузависноста ги направила и богати И кревки во исто време?",
      "Точно така, и штотуку го искажа она што историчарите го нарекуваат парадокс на сложеноста. Меѓузависноста му овозможила на еден микенски крал да има балтички килибар и египетско злато во истата гробница, но истовремено значела дека суша во Анадолија може да остави ковач во Грција без калај. Забележи како истиот образец се повторува подоцна: римската житна мрежа во V век н. е., па дури и светскиот финансиски систем во 2008 година — ефикасноста и кревкоста растеле заедно. Сепак, една цивилизација ја издржала 1177 година пр. н. е. подобро од соседите: Египет преживеал, намален но цел, делум затоа што Нил му давал внатрешен извор на храна што ниту еден морски напаѓач не можел да го пресече. Затоа размисли: што би морала една цивилизација да задржи „кај себе“ за да биде отпорна на колапс — храна, енергија, знаење? И дали тоа воопшто е можно без да се откаже од богатството што го носи трговијата?",
    ],
    de: [
      "Warum sind um 1200 v. Chr. so viele Zivilisationen gleichzeitig zusammengebrochen?",
      "Zwischen 1200 und 1150 v. Chr. fiel fast jede größere Macht des östlichen Mittelmeers innerhalb eines einzigen Menschenlebens: Das Hethiterreich verschwand, die mykenischen Paläste von Pylos bis Mykene brannten, Ugarit wurde so plötzlich zerstört, dass unversandte Briefe in seinen Brennöfen zurückblieben, und Ägypten wehrte unter Ramses III. 1177 v. Chr. die Seevölker nur mit Mühe ab. Das Faszinierende an diesem Zusammenbruch ist, dass keine einzelne Ursache ihn erklärt. Die überzeugendste heutige Deutung sieht darin ein Systemversagen: Dürre (bestätigt durch Pollenbohrkerne aus dem See Genezareth), Erdbeben, Wanderungen und Raubzüge belasteten jeweils ein Netz von Palastwirtschaften, die selbst für die Bronze voneinander abhingen — Kupfer aus Zypern, Zinn aus Gegenden so fern wie Afghanistan. Als der Handel riss, riss auch jedes Königreich, das auf ihm beruhte. Hier eine Frage, über die sich nachdenken lässt: Hätten diese Königreiche überlebt, wären sie weniger eng verflochten gewesen — oder war die Verflechtung zugleich die Quelle ihres Reichtums?",
      "Wahrscheinlich hat die Verflechtung sie zugleich reich UND anfällig gemacht?",
      "Genau, und damit hast du gerade das ausgesprochen, was Historiker das Paradox der Komplexität nennen. Die Verflechtung erlaubte einem mykenischen König, baltischen Bernstein und ägyptisches Gold in dasselbe Grab zu legen, aber sie bedeutete auch, dass eine Dürre in Anatolien einem Schmied in Griechenland das Zinn nehmen konnte. Beachte, wie sich das Muster später wiederholt: das römische Getreidenetz im 5. Jahrhundert n. Chr. oder auch das globale Finanzsystem von 2008 — Effizienz und Anfälligkeit wuchsen gemeinsam. Eine Zivilisation überstand 1177 v. Chr. allerdings besser als ihre Nachbarn: Ägypten überlebte, geschwächt, aber intakt, auch weil der Nil ihm eine innere Nahrungsquelle gab, die kein Seeräuber durchtrennen konnte. Denk also weiter: Was müsste eine Zivilisation „im eigenen Haus“ behalten, um kollapsfest zu sein — Nahrung, Energie, Wissen? Und ist das überhaupt möglich, ohne den Reichtum aufzugeben, den der Handel bringt?",
    ],
    fr: [
      "Pourquoi tant de civilisations se sont-elles effondrées d’un coup vers 1200 av. J.-C. ?",
      "Entre 1200 et 1150 av. J.-C., presque toutes les grandes puissances de la Méditerranée orientale sont tombées en l’espace d’une seule vie humaine : l’Empire hittite s’est évanoui, les palais mycéniens ont brûlé de Pylos à Mycènes, Ougarit a été détruite si soudainement que des lettres jamais envoyées sont restées à cuire dans ses fours, et l’Égypte de Ramsès III a repoussé de justesse les Peuples de la mer en 1177 av. J.-C. Ce qui rend cet effondrement si fascinant, c’est qu’aucune cause unique ne l’explique. La lecture la plus solide aujourd’hui y voit une défaillance systémique : la sécheresse (confirmée par les carottes polliniques de la mer de Galilée), les séismes, les migrations et les raids ont chacun pesé sur un réseau d’économies palatiales qui dépendaient les unes des autres jusque pour le bronze lui-même — le cuivre de Chypre, l’étain venu d’aussi loin que l’Afghanistan. Quand le commerce a rompu, chaque royaume qui en vivait a rompu aussi. Voici une question qui mérite réflexion : si ces royaumes avaient été moins interconnectés, penses-tu qu’ils auraient survécu — ou cette interdépendance était-elle aussi la source de leur richesse ?",
      "Sans doute que l’interdépendance les a rendus riches ET fragiles en même temps ?",
      "Exactement, et tu viens de formuler ce que les historiens appellent le paradoxe de la complexité. L’interdépendance permettait à un roi mycénien de réunir dans la même tombe l’ambre de la Baltique et l’or d’Égypte, mais elle signifiait aussi qu’une sécheresse en Anatolie pouvait priver d’étain un forgeron de Grèce. Remarque que le schéma se répète ensuite : le réseau céréalier romain au Ve siècle apr. J.-C., ou même le système financier mondial de 2008 — l’efficacité et la fragilité ont grandi ensemble. Une civilisation a pourtant mieux encaissé 1177 av. J.-C. que ses voisines : l’Égypte a survécu, diminuée mais entière, en partie parce que le Nil lui offrait une réserve alimentaire intérieure qu’aucun pillard venu de la mer ne pouvait couper. Alors pousse l’idée : que faudrait-il qu’une civilisation garde « chez elle » pour résister à l’effondrement — la nourriture, l’énergie, le savoir ? Et est-ce seulement possible sans renoncer à la richesse qu’apporte le commerce ?",
    ],
  },

  'sample-printing-press': {
    es: [
      "¿La imprenta fue realmente tan revolucionaria, o se exagera?",
      "Las cifras dicen que fue genuinamente revolucionaria. Antes de que Gutenberg imprimiera su Biblia de 42 líneas hacia 1455, una sola Biblia copiada a mano ocupaba a un escriba unos tres años; hacia 1500, apenas dos generaciones después, las prensas europeas habían producido entre 8 y 10 millones de libros, más que todos los escribas del milenio anterior juntos. Pero la revolución más profunda no fue solo el volumen: fue la fiabilidad y la velocidad. Cuando Martín Lutero fijó sus noventa y cinco tesis en Wittenberg en 1517, las copias impresas alcanzaron la mayor parte de las tierras alemanas en un mes; el propio Lutero llamó a la imprenta «el acto supremo de gracia de Dios». La Iglesia ya se había enfrentado a herejes antes: Jan Hus sostuvo argumentos parecidos en 1415 y fue quemado en Constanza. Lutero los sostuvo CON una imprenta detrás y no se le pudo contener. Así que aquí va el filo socrático: ¿la diferencia entre la muerte de Hus y el éxito de Lutero estuvo en las ideas mismas, o en la tecnología de la información que las transportó?",
      "Suena a que fue la tecnología. ¿Internet está haciendo hoy lo mismo?",
      "Esa comparación la toman en serio los historiadores, y los paralelismos son llamativos: ambas tecnologías hundieron el coste de copiar, ambas rompieron el monopolio de un guardián (el scriptorium latino de la Iglesia entonces, los medios de difusión ahora) y ambas desataron décadas de convulsión antes de que las sociedades se adaptaran. La imprenta no solo le dio a Europa la Reforma: alimentó un siglo de guerras de religión que terminó en Westfalia en 1648, pero también hizo posible la Revolución Científica, porque Copérnico, Vesalio y más tarde Newton pudieron apoyarse en copias exactas e idénticas de los datos de los demás. La imprenta premió a quien dominara antes el nuevo medio: Lutero escribía panfletos contundentes en alemán mientras sus adversarios escribían tratados en latín. ¿Quién crees que es el «Lutero» de la era de internet, y quién está escribiendo tratados en latín sin darse cuenta?",
    ],
    ru: [
      "Книгопечатание правда было настолько революционным, или это преувеличение?",
      "Цифры говорят, что оно было революционным по-настоящему. До того как Гутенберг около 1455 года напечатал свою 42-строчную Библию, одна переписанная от руки Библия отнимала у писца примерно три года; к 1500 году, всего через два поколения, европейские печатные станки выпустили, по оценкам, от 8 до 10 миллионов книг — больше, чем все писцы предыдущего тысячелетия вместе взятые. Но более глубокая революция состояла не в объёме, а в надёжности и скорости. Когда Мартин Лютер в 1517 году обнародовал в Виттенберге девяносто пять тезисов, печатные копии за месяц разошлись почти по всем немецким землям; сам Лютер называл книгопечатание «высшим актом Божьей милости». С еретиками Церковь сталкивалась и раньше: Ян Гус выдвигал схожие доводы в 1415 году и был сожжён в Констанце. Лютер выдвинул их, имея за спиной печатный станок, и остановить его не удалось. Вот сократовское лезвие: разница между гибелью Гуса и успехом Лютера была в самих идеях — или в информационной технологии, которая их несла?",
      "Похоже, дело в технологии. Интернет сегодня делает то же самое?",
      "Это сравнение историки принимают всерьёз, и совпадения поразительны: обе технологии обрушили стоимость копирования, обе сломали монополию привратника (латинский скрипторий Церкви тогда, вещательные медиа теперь) и обе вызвали десятилетия потрясений, прежде чем общества к ним приспособились. Книгопечатание дало Европе не только Реформацию — оно подпитывало столетие религиозных войн, закончившихся Вестфальским миром 1648 года, но оно же сделало возможной научную революцию, потому что Коперник, Везалий, а позже Ньютон могли опираться на точные, тождественные копии данных друг друга. Печать вознаграждала того, кто первым освоил новую среду: Лютер писал хлёсткие немецкие памфлеты, пока его противники писали латинские трактаты. Как ты думаешь, кто сегодня «Лютер» интернет-эпохи — и кто, сам того не замечая, пишет латинские трактаты?",
    ],
    mk: [
      "Дали печатарската преса навистина била толку револуционерна, или тоа е претерување?",
      "Бројките зборуваат дека била вистински револуционерна. Пред Гутенберг да ја отпечати својата Библија со 42 реда околу 1455 година, една рачно препишана Библија му одземала на препишувачот околу три години; до 1500 година, едвај две генерации подоцна, европските преси произвеле проценети 8 до 10 милиони книги — повеќе отколку сите препишувачи од претходниот милениум заедно. Но подлабоката револуција не била само во обемот, туку во сигурноста и брзината. Кога Мартин Лутер ги објавил своите деведесет и пет тези во Витенберг во 1517 година, отпечатените примероци стигнале до најголемиот дел од германските земји за еден месец; самиот Лутер го нарекол печатењето „највисокиот чин на Божја милост“. Црквата и порано се соочувала со еретици: Јан Хус изнесол слични тврдења во 1415 година и бил изгорен во Констанц. Лутер ги изнесол СО преса зад себе и не можел да биде запрен. Еве го сократовскиот нож: дали разликата меѓу смртта на Хус и успехот на Лутер лежела во самите идеи, или во информациската технологија што ги пренела?",
      "Изгледа дека е технологијата. Дали интернетот го прави истото денес?",
      "Таа споредба историчарите ја сфаќаат сериозно, а паралелите се впечатливи: и двете технологии ја урнале цената на копирањето, и двете го скршиле монополот на чуварот на портата (латинскиот скрипториум на Црквата тогаш, медиумите за емитување сега) и двете предизвикале децении потреси пред општествата да се прилагодат. Печатарската преса не ѝ ја дала на Европа само Реформацијата — таа поттикнала век религиозни војни што завршиле со Вестфалија во 1648 година, но исто така ја овозможила и Научната револуција, зашто Коперник, Везалиј и подоцна Њутн можеле да се потпрат на точни, идентични копии од податоците еден на друг. Печатењето го наградувало оној што прв ќе го совлада новиот медиум: Лутер пишувал остри германски памфлети додека неговите противници пишувале латински трактати. Кој мислиш дека е „Лутер“ на интернет-ерата — и кој пишува латински трактати без да го забележи тоа?",
    ],
    de: [
      "War der Buchdruck wirklich so revolutionär, oder ist das übertrieben?",
      "Die Zahlen sprechen dafür, dass er wirklich revolutionär war. Bevor Gutenberg um 1455 seine 42-zeilige Bibel druckte, beschäftigte eine einzige handgeschriebene Bibel einen Schreiber rund drei Jahre; bis 1500, kaum zwei Generationen später, hatten europäische Pressen schätzungsweise 8 bis 10 Millionen Bücher hergestellt — mehr als alle Schreiber des vorangegangenen Jahrtausends zusammen. Die tiefere Revolution lag aber nicht im Umfang, sondern in Verlässlichkeit und Tempo. Als Martin Luther 1517 in Wittenberg seine fünfundneunzig Thesen veröffentlichte, erreichten gedruckte Exemplare binnen eines Monats den größten Teil der deutschen Lande; Luther selbst nannte den Druck „Gottes höchste Gnadentat“. Ketzer hatte die Kirche schon zuvor erlebt: Jan Hus vertrat 1415 ähnliche Argumente und wurde in Konstanz verbrannt. Luther vertrat sie MIT einer Presse im Rücken und war nicht mehr einzudämmen. Hier also das sokratische Messer: Lag der Unterschied zwischen Hus’ Tod und Luthers Erfolg in den Ideen selbst — oder in der Informationstechnik, die sie trug?",
      "Klingt nach der Technik. Macht das Internet heute dasselbe?",
      "Diesen Vergleich nehmen Historiker ernst, und die Parallelen sind auffällig: Beide Techniken ließen die Kosten des Kopierens einstürzen, beide brachen das Monopol eines Torwächters (damals das lateinische Skriptorium der Kirche, heute die Rundfunkmedien), und beide lösten Jahrzehnte der Umwälzung aus, bevor die Gesellschaften sich anpassten. Der Buchdruck gab Europa nicht nur die Reformation — er befeuerte ein Jahrhundert der Religionskriege, das 1648 in Westfalen endete, machte aber auch die wissenschaftliche Revolution möglich, weil Kopernikus, Vesalius und später Newton auf exakte, identische Kopien der Daten der anderen aufbauen konnten. Der Druck belohnte, wer das neue Medium zuerst beherrschte: Luther schrieb schlagkräftige deutsche Flugschriften, während seine Gegner lateinische Traktate verfassten. Wer ist deiner Meinung nach der „Luther“ des Internetzeitalters — und wer schreibt lateinische Traktate, ohne es zu merken?",
    ],
    fr: [
      "L’imprimerie a-t-elle vraiment été si révolutionnaire, ou est-ce exagéré ?",
      "Les chiffres plaident pour une révolution bien réelle. Avant que Gutenberg n’imprime sa Bible à 42 lignes vers 1455, une seule Bible copiée à la main occupait un scribe environ trois ans ; vers 1500, à peine deux générations plus tard, les presses européennes avaient produit entre 8 et 10 millions de livres — plus que tous les scribes du millénaire précédent réunis. Mais la révolution profonde tenait à la fiabilité et à la vitesse, pas seulement au volume. Lorsque Martin Luther afficha ses quatre-vingt-quinze thèses à Wittenberg en 1517, les exemplaires imprimés atteignirent la plupart des terres allemandes en un mois ; Luther lui-même appelait l’imprimerie « le plus haut acte de grâce de Dieu ». L’Église avait déjà affronté des hérétiques : Jan Hus avait soutenu des arguments semblables en 1415 et fut brûlé à Constance. Luther les soutint AVEC une presse derrière lui, et on ne put le contenir. Voici donc la lame socratique : la différence entre la mort de Hus et le succès de Luther tenait-elle aux idées elles-mêmes, ou à la technologie de l’information qui les portait ?",
      "On dirait que c’est la technologie. Internet fait-il la même chose aujourd’hui ?",
      "Les historiens prennent cette comparaison au sérieux, et les parallèles sont frappants : les deux technologies ont effondré le coût de la copie, toutes deux ont brisé le monopole d’un gardien (le scriptorium latin de l’Église hier, les médias de masse aujourd’hui), et toutes deux ont déclenché des décennies de bouleversements avant que les sociétés ne s’adaptent. L’imprimerie n’a pas seulement donné la Réforme à l’Europe — elle a nourri un siècle de guerres de religion qui s’acheva en Westphalie en 1648, mais elle a aussi rendu possible la révolution scientifique, car Copernic, Vésale puis Newton pouvaient s’appuyer sur des copies exactes et identiques des données les uns des autres. L’imprimé récompensait celui qui maîtrisait le premier le nouveau média : Luther écrivait des pamphlets allemands percutants pendant que ses adversaires rédigeaient des traités latins. Selon toi, qui est le « Luther » de l’ère d’Internet — et qui rédige des traités latins sans s’en rendre compte ?",
    ],
  },

  'sample-cold-war': {
    es: [
      "¿Cuán cerca estuvo realmente la crisis de los misiles de Cuba de una guerra nuclear?",
      "Más cerca de lo que ninguno de los dos gobiernos supo entonces, y más cerca de lo que el público conoció durante décadas. Los trece días de octubre de 1962 tuvieron al menos tres detonantes a punto de saltar. Primero, el 27 de octubre un U-2 pilotado por Rudolf Anderson fue derribado sobre Cuba, la única muerte en combate de la crisis, y las órdenes vigentes implicaban represalia, algo que Kennedy anuló personalmente. Segundo, ese mismo día, el submarino soviético B-59, sin contacto por radio y bajo cargas de práctica estadounidenses, estuvo a punto de lanzar un torpedo nuclear; el lanzamiento exigía tres oficiales, y uno de ellos, Vasili Arjípov, se negó. Tercero, sin que Washington lo supiera, las fuerzas soviéticas en Cuba ya disponían de unas 100 ojivas nucleares tácticas, de modo que la invasión que urgían los jefes del Estado Mayor probablemente habría sido nuclear desde el primer día. La salida fue una retirada soviética pública a cambio de un compromiso público estadounidense de no invadir y de una retirada SECRETA de los misiles Júpiter de Turquía. Una pregunta para ti: se elogió a Kennedy por mantenerse firme, pero el acuerdo funcionó porque dejó que Jrushchov salvara la cara en público mientras cedía en privado. Dejar que el adversario salve la cara, ¿es una debilidad o un arma?",
      "Un arma, supongo: Jrushchov pudo retroceder sin quedar humillado.",
      "Precisamente, y la historia ofrece un sombrío grupo de control para esa hipótesis. Compara Versalles en 1919: los vencedores maximizaron la humillación pública de Alemania, con la cláusula de «culpabilidad de guerra» y reparaciones fijadas en 132.000 millones de marcos oro, y en veinte años esa humillación se había convertido ella misma en un arma para Hitler. Tucídides vio la misma dinámica 2.400 años antes, cuando Atenas dijo a los melios que «los fuertes hacen lo que pueden y los débiles sufren lo que deben»: una victoria a corto plazo que ayudó a volver implacables a los enemigos de Atenas. Después de 1962, ambas superpotencias construyeron discretamente mecanismos para salvar la cara dentro del sistema: el teléfono rojo entre Moscú y Washington en 1963, y luego tratados de control de armas que permitían a cada bando llamar «verificación» a la contención, en vez de retirada. Ahora lleva la idea un paso más allá: ¿se te ocurre algún enfrentamiento actual en el que lo que falta no sea fuerza, sino una salida honrosa? ¿Y quién tendría que construirla?",
    ],
    ru: [
      "Насколько близко Карибский кризис на самом деле подошёл к ядерной войне?",
      "Ближе, чем в тот момент знали оба правительства, и ближе, чем публика узнала за последующие десятилетия. В тринадцати днях октября 1962 года было по меньшей мере три несработавших спусковых крючка. Во-первых, 27 октября над Кубой сбили U-2 под управлением Рудольфа Андерсона — единственная боевая смерть кризиса, — и действующие приказы предполагали ответный удар, который Кеннеди отменил лично. Во-вторых, в тот же день советская подводная лодка Б-59, потерявшая радиосвязь и забрасываемая американскими учебными глубинными бомбами, едва не выпустила ядерную торпеду; для пуска требовалось согласие трёх офицеров, и один из них, Василий Архипов, отказался. В-третьих, Вашингтон не знал, что советские силы на Кубе уже располагали примерно 100 тактическими ядерными боезарядами, так что вторжение, к которому подталкивал Объединённый комитет начальников штабов, скорее всего стало бы ядерным в первый же день. Развязкой стал публичный вывод советских ракет в обмен на публичное американское обязательство не вторгаться — и на ТАЙНЫЙ вывод американских ракет «Юпитер» из Турции. Вопрос к тебе: Кеннеди хвалили за твёрдость, но сделка сработала потому, что он дал Хрущёву сохранить лицо публично, уступив при этом втайне. Позволить противнику сохранить лицо — это слабость или оружие?",
      "Наверное, оружие: Хрущёв смог отступить, не будучи униженным.",
      "Именно, и история предлагает мрачную контрольную группу для этой гипотезы. Сравни с Версалем 1919 года: победители довели публичное унижение Германии до предела — статья о «виновности в войне», репарации, назначенные в 132 миллиарда золотых марок, — и за двадцать лет само это унижение стало оружием в руках Гитлера. Фукидид видел ту же механику за 2400 лет до того, когда Афины сказали мелосцам, что «сильные делают, что могут, а слабые терпят, что должны», — краткосрочная победа, которая помогла сделать врагов Афин непримиримыми. После 1962 года обе сверхдержавы тихо встроили в систему механизмы сохранения лица: линию прямой связи Москва — Вашингтон в 1963 году, а затем договоры о контроле над вооружениями, позволявшие каждой стороне называть сдержанность «проверкой», а не отступлением. Теперь продвинь мысль дальше: приходит ли тебе на ум сегодняшнее противостояние, в котором не хватает не силы, а достойного выхода? И кто должен был бы его построить?",
    ],
    mk: [
      "Колку блиску навистина беше Кубанската ракетна криза до нуклеарна војна?",
      "Поблиску отколку што знаеја двете влади тогаш, и поблиску отколку што јавноста дозна со децении. Тринаесетте дена во октомври 1962 година имаа најмалку три речиси повлечени чкрапала. Прво, на 27 октомври беше соборен U-2 пилотиран од Рудолф Андерсон над Куба — единствената борбена смрт во кризата — а важечките наредби подразбираа одмазда, што Кенеди лично ја поништи. Второ, истиот ден советската подморница Б-59, без радио-врска и напаѓана со американски вежбовни длабински бомби, замалку не испука нуклеарно торпедо; за лансирање беа потребни тројца офицери, а еден од нив, Василиј Архипов, одби. Трето, без Вашингтон да знае, советските сили на Куба веќе имаа околу 100 тактички нуклеарни боеви глави, па инвазијата на која инсистираше Здружениот штаб веројатно ќе станеше нуклеарна уште првиот ден. Решението беше јавно советско повлекување разменето за јавен американски залог за неинвазија и за ТАЈНО повлекување на американските ракети „Јупитер“ од Турција. Прашање за тебе: Кенеди беше пофален што остана цврст, но договорот успеа зашто му дозволи на Хрушчов да го зачува образот јавно додека попушташе тајно. Дали да му дозволиш на противникот да го зачува образот е слабост или оружје?",
      "Оружје, претпоставувам — Хрушчов можеше да отстапи без да биде понижен.",
      "Токму така, и историјата нуди мрачна контролна група за таа хипотеза. Спореди со Версај во 1919 година: победниците го доведоа јавното понижување на Германија до крајност — клаузулата за „воена вина“, репарации утврдени на 132 милијарди златни марки — и за дваесет години самото понижување стана оружје за Хитлер. Тукидид ја видел истата динамика 2.400 години порано, кога Атина им рекла на Мелјаните дека „силните прават што можат, а слабите трпат што мораат“ — краткорочна победа што помогнала непријателите на Атина да станат непомирливи. По 1962 година, двете суперсили тивко вградија механизми за зачувување на образот во системот: линијата Москва — Вашингтон во 1963 година, а потоа договорите за контрола на вооружувањето што им дозволуваа на двете страни воздржаноста да ја наречат „проверка“ наместо повлекување. Сега поттурни ја идејата чекор понатаму: се сеќаваш ли на денешен судир каде што недостига не сила, туку излез со зачуван образ? И кој би морал да го изгради?",
    ],
    de: [
      "Wie nah kam die Kubakrise tatsächlich an einen Atomkrieg heran?",
      "Näher, als beide Regierungen damals wussten, und näher, als die Öffentlichkeit jahrzehntelang erfuhr. Die dreizehn Tage im Oktober 1962 hatten mindestens drei Beinahe-Auslöser. Erstens wurde am 27. Oktober eine von Rudolf Anderson geflogene U-2 über Kuba abgeschossen — der einzige Gefechtstod der Krise —, und die geltenden Befehle sahen eine Vergeltung vor, die Kennedy persönlich aufhob. Zweitens hätte am selben Tag das sowjetische U-Boot B-59, ohne Funkkontakt und mit amerikanischen Übungswasserbomben belegt, beinahe einen Nukleartorpedo abgefeuert; der Start erforderte drei Offiziere, und einer von ihnen, Wassili Archipow, verweigerte sich. Drittens verfügten die sowjetischen Truppen auf Kuba, für Washington unbemerkt, bereits über rund 100 taktische Atomsprengköpfe, sodass die von den Vereinigten Stabschefs geforderte Invasion vermutlich am ersten Tag nuklear geworden wäre. Die Lösung war ein öffentlicher sowjetischer Rückzug im Tausch gegen ein öffentliches amerikanisches Nichtangriffsversprechen und einen GEHEIMEN Abzug der amerikanischen Jupiter-Raketen aus der Türkei. Eine Frage an dich: Kennedy wurde für seine Festigkeit gelobt, aber der Handel gelang, weil er Chruschtschow öffentlich das Gesicht wahren ließ, während er im Geheimen nachgab. Ist es eine Schwäche oder eine Waffe, dem Gegner das Gesicht zu lassen?",
      "Eine Waffe, würde ich sagen — Chruschtschow konnte zurückweichen, ohne gedemütigt zu werden.",
      "Genau, und die Geschichte liefert dafür eine düstere Kontrollgruppe. Vergleiche Versailles 1919: Die Sieger trieben Deutschlands öffentliche Demütigung auf die Spitze — der „Kriegsschuld“-Artikel, Reparationen von 132 Milliarden Goldmark —, und binnen zwanzig Jahren war die Demütigung selbst zu einer Waffe für Hitler geworden. Thukydides sah dieselbe Dynamik 2400 Jahre früher, als Athen den Meliern sagte, „die Starken tun, was sie können, und die Schwachen erleiden, was sie müssen“ — ein kurzfristiger Sieg, der Athens Feinde unversöhnlich werden ließ. Nach 1962 bauten beide Supermächte still eine Mechanik des Gesichtswahrens in das System ein: den heißen Draht Moskau–Washington 1963, danach Rüstungskontrollverträge, die es jeder Seite erlaubten, Zurückhaltung „Verifikation“ zu nennen statt Rückzug. Nun treib den Gedanken weiter: Fällt dir eine heutige Konfrontation ein, in der nicht Stärke fehlt, sondern ein gesichtswahrender Ausweg? Und wer müsste ihn bauen?",
    ],
    fr: [
      "À quel point la crise des missiles de Cuba a-t-elle vraiment frôlé la guerre nucléaire ?",
      "Plus près que ne le savaient alors les deux gouvernements, et plus près que le public ne l’a appris pendant des décennies. Les treize jours d’octobre 1962 comptent au moins trois détentes presque pressées. D’abord, le 27 octobre, un U-2 piloté par Rudolf Anderson fut abattu au-dessus de Cuba — la seule mort au combat de la crise — et les ordres en vigueur impliquaient des représailles, que Kennedy annula personnellement. Ensuite, le même jour, le sous-marin soviétique B-59, privé de liaison radio et grenadé par des charges d’exercice américaines, faillit lancer une torpille nucléaire ; le tir exigeait trois officiers, et l’un d’eux, Vassili Arkhipov, refusa. Enfin, à l’insu de Washington, les forces soviétiques à Cuba disposaient déjà d’environ 100 ogives nucléaires tactiques : l’invasion que réclamaient les chefs d’état-major serait donc probablement devenue nucléaire dès le premier jour. Le dénouement fut un retrait soviétique public échangé contre un engagement américain public de non-invasion et un retrait SECRET des missiles Jupiter américains de Turquie. Une question pour toi : on a loué la fermeté de Kennedy, mais l’accord a fonctionné parce qu’il a laissé Khrouchtchev sauver la face en public tout en cédant en privé. Laisser son adversaire sauver la face, est-ce une faiblesse ou une arme ?",
      "Une arme, je dirais — Khrouchtchev pouvait reculer sans être humilié.",
      "Exactement, et l’histoire offre à cette hypothèse un sinistre groupe témoin. Compare avec Versailles en 1919 : les vainqueurs ont poussé à son comble l’humiliation publique de l’Allemagne — la clause de « culpabilité de guerre », des réparations fixées à 132 milliards de marks-or — et en vingt ans cette humiliation était elle-même devenue une arme pour Hitler. Thucydide observait la même dynamique 2 400 ans plus tôt, quand Athènes déclarait aux Méliens que « les forts font ce qu’ils peuvent et les faibles subissent ce qu’ils doivent » — une victoire à court terme qui contribua à rendre implacables les ennemis d’Athènes. Après 1962, les deux superpuissances ont discrètement intégré au système une mécanique du sauvetage de la face : le téléphone rouge Moscou-Washington en 1963, puis des traités de maîtrise des armements qui permettaient à chaque camp d’appeler la retenue « vérification » plutôt que recul. Pousse maintenant l’idée d’un cran : vois-tu un affrontement actuel où ce qui manque n’est pas la force, mais une sortie honorable ? Et qui devrait la construire ?",
    ],
  },
};
