export interface HistoryVideo {
  id: string;
  youtubeId: string;
  title: string;
  channel: string;
  era: 'Ancient' | 'Medieval' | 'Early Modern' | 'Modern';
  topic: string;
  durationSec: number; // must be ≤ 600 (10 min)
  description: string;
}

// All YouTube IDs verified via web search — do not modify without re-verifying
export const HISTORY_VIDEOS: HistoryVideo[] = [
  // ── HISTORY VS. SERIES (TED-Ed) ──────────────────────────────────────────
  {
    id: 'v-hvs-henry8',
    youtubeId: 'xdZcqAss92w',
    title: 'History vs. Henry VIII',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Tudor England',
    durationSec: 305,
    description: 'Was Henry VIII a strong ruler who shaped a nation, or a vain tyrant who executed those who crossed him? Alex Gendler puts him on trial.',
  },
  {
    id: 'v-hvs-cleopatra',
    youtubeId: 'Y6EhRwn4zkc',
    title: 'History vs. Cleopatra',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Egypt',
    durationSec: 295,
    description: 'Was Cleopatra a brilliant, multilingual ruler who kept Egypt independent, or a seductress who used men for power? Alex Gendler investigates.',
  },
  {
    id: 'v-hvs-augustus',
    youtubeId: 'QrcmojhFmzY',
    title: 'History vs. Augustus',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Roman Empire',
    durationSec: 315,
    description: 'Augustus transformed Rome from republic to empire — was he a visionary leader or a ruthless autocrat who crushed the republic? You decide.',
  },
  {
    id: 'v-hvs-genghis',
    youtubeId: 'Eq-Wk3YqeH4',
    title: 'History vs. Genghis Khan',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Mongol Empire',
    durationSec: 300,
    description: 'Was Genghis Khan a vicious barbarian or a unifier who connected East and West and paved the way for the modern world? Alex Gendler puts him on trial.',
  },
  {
    id: 'v-hvs-napoleon',
    youtubeId: '8aq_gRfmjgY',
    title: 'History vs. Napoleon Bonaparte',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Napoleonic Era',
    durationSec: 310,
    description: 'Did Napoleon save the French Revolution or destroy it? Alex Gendler examines whether he was a champion of liberty or an imperialist dictator.',
  },
  {
    id: 'v-hvs-columbus',
    youtubeId: 'GD3dgiDreGc',
    title: 'History vs. Christopher Columbus',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Age of Exploration',
    durationSec: 295,
    description: 'Was Columbus an intrepid explorer who united two worlds, or a ruthless exploiter who unleashed colonialism? Alex Gendler weighs the evidence.',
  },
  {
    id: 'v-hvs-lenin',
    youtubeId: '9N8hsXQapjY',
    title: 'History vs. Vladimir Lenin',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Russian Revolution',
    durationSec: 300,
    description: 'Was Lenin a hero who toppled an oppressive czar, or a villain who replaced tyranny with something worse? Alex Gendler examines his legacy.',
  },
  {
    id: 'v-hvs-nixon',
    youtubeId: 'MX_HYL6-0Co',
    title: 'History vs. Richard Nixon',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Cold War America',
    durationSec: 290,
    description: 'Does Nixon deserve to be remembered for more than Watergate? Alex Gendler examines his complex legacy of diplomatic breakthroughs and criminal conduct.',
  },
  {
    id: 'v-hvs-freud',
    youtubeId: 'mKG-PEVYOR8',
    title: 'History vs. Sigmund Freud',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'History of Psychology',
    durationSec: 310,
    description: 'Was Freud a genius who unlocked the unconscious, or a fraud whose unscientific theories set medicine back? Todd Dufresne investigates.',
  },
  {
    id: 'v-hvs-che',
    youtubeId: 'tjrvKA4w9-Y',
    title: 'History vs. Che Guevara',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Latin American Revolution',
    durationSec: 305,
    description: 'Was Che Guevara a heroic champion of the poor or a ruthless warlord? Alex Gendler examines the icon behind the image.',
  },

  // ── RISE AND FALL SERIES (TED-Ed) ─────────────────────────────────────────
  {
    id: 'v-rf-sumer',
    youtubeId: 'XBk9KywTIgk',
    title: "The Rise and Fall of History's First Empire",
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Mesopotamia',
    durationSec: 325,
    description: "The Sumerian Empire built humanity's first cities, invented writing, and created the wheel — so why did it collapse? Soraya Field Fiorio explains.",
  },
  {
    id: 'v-rf-ottoman',
    youtubeId: 'anJTW5e7P4g',
    title: 'The Rise and Fall of the Ottoman Empire',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Ottoman Empire',
    durationSec: 345,
    description: 'How did a small Turkish principality become one of the most powerful empires in history — and what led to its collapse after 600 years?',
  },
  {
    id: 'v-rf-byzantine',
    youtubeId: 'HTZlcNjLe54',
    title: 'The Rise and Fall of the Byzantine Empire',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Byzantine Empire',
    durationSec: 340,
    description: 'The Roman Empire never truly fell — it survived as Byzantium for another thousand years. Leonora Neville traces its remarkable story.',
  },
  {
    id: 'v-rf-inca',
    youtubeId: 'UO5ktwPXsyM',
    title: 'The Rise and Fall of the Inca Empire',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Inca Civilization',
    durationSec: 330,
    description: "The western hemisphere's largest empire had no written language and no wheel, yet built thousands of miles of roads. Gordon McEwan explains how.",
  },
  {
    id: 'v-rf-mongol',
    youtubeId: 'wUVvTqvjUaM',
    title: 'The Rise and Fall of the Mongol Empire',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Mongol Empire',
    durationSec: 335,
    description: 'From nomadic tribes on the steppe to the largest contiguous land empire in history. Anne F. Broadbridge traces the Mongols from Temujin to collapse.',
  },
  {
    id: 'v-rf-berlin-wall',
    youtubeId: 'A9fQPzZ1-hg',
    title: 'The Rise and Fall of the Berlin Wall',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Cold War',
    durationSec: 320,
    description: 'For 28 years, a concrete barrier divided a city and symbolized the Cold War. Konrad H. Jarausch examines how it was built — and why it fell.',
  },
  {
    id: 'v-rf-lakota',
    youtubeId: 'C-fQo8zmiPQ',
    title: 'The Rise and Fall of the Lakota Empire',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Native American History',
    durationSec: 315,
    description: 'For centuries the Lakota Sioux dominated the Great Plains. Pekka Hämäläinen explains how they built a powerful empire — and what destroyed it.',
  },

  // ── A DAY IN THE LIFE SERIES (TED-Ed) ─────────────────────────────────────
  {
    id: 'v-life-athenian',
    youtubeId: 'ar8S6virCwM',
    title: 'A Day in the Life of an Ancient Athenian',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Greece',
    durationSec: 270,
    description: 'Step into Athens in 427 BCE as the city debates the fate of rebellious Mytilene. Robert Garland brings ancient Athenian democracy to life.',
  },
  {
    id: 'v-life-roman-soldier',
    youtubeId: 'P5e7cl19Ha0',
    title: 'A Day in the Life of a Roman Soldier',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Roman Empire',
    durationSec: 280,
    description: 'Meet Servius Felix, a Roman soldier in 15 CE. Robert Garland takes you through a typical day of training, marching, and guarding the empire.',
  },
  {
    id: 'v-life-samurai',
    youtubeId: 'wy0mU-SbOrw',
    title: 'A Day in the Life of a Teenage Samurai',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Feudal Japan',
    durationSec: 275,
    description: "Follow Mori Banshirô, a young samurai-in-training, through a day of martial arts, literary study, and the strict code of the bushido.",
  },
  {
    id: 'v-life-egyptian-doctor',
    youtubeId: '2rvLEJrQm7g',
    title: 'A Day in the Life of an Ancient Egyptian Doctor',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Egypt',
    durationSec: 265,
    description: 'Elizabeth Cox explores the surprisingly advanced medical knowledge of ancient Egypt — from herbal treatments to surgical instruments — through one doctor\'s day.',
  },
  {
    id: 'v-life-aztec',
    youtubeId: 'JZj7acYZ19w',
    title: 'A Day in the Life of an Aztec Midwife',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Aztec Civilization',
    durationSec: 268,
    description: 'Join Xoquauhtli, an Aztec midwife, as she tends to patients and honors the warrior goddess Teteoinnan. A fascinating look at Aztec medicine and religion.',
  },

  // ── TRADE AND CIVILIZATION ─────────────────────────────────────────────────
  {
    id: 'v-silk-road',
    youtubeId: 'vn3e37VWc0k',
    title: 'The Silk Road: Connecting the Ancient World Through Trade',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Trade & Commerce',
    durationSec: 305,
    description: 'Shannon Harris Castelo traces the 5,000-mile network of routes that used the common language of commerce to connect civilizations from Rome to China.',
  },
  {
    id: 'v-slave-trade',
    youtubeId: '3NXC4Q_4JVg',
    title: 'The Atlantic Slave Trade: What Too Few Textbooks Told You',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Slavery & Colonialism',
    durationSec: 295,
    description: 'Anthony Hazard uncovers the scale, mechanics, and lasting consequences of the Atlantic slave trade — a story too often reduced to a footnote.',
  },

  // ── DISEASE & SOCIETY ──────────────────────────────────────────────────────
  {
    id: 'v-plague',
    youtubeId: 'ySClB6-OH-Q',
    title: 'The Past, Present and Future of the Bubonic Plague',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Black Death',
    durationSec: 315,
    description: "Sharon N. DeWitte investigates the plague that killed a third of Europe's population — and explains why the bacterium still exists today.",
  },

  // ── WORLD HISTORY ──────────────────────────────────────────────────────────
  {
    id: 'v-cats-history',
    youtubeId: 'Jsj-hDW9bS8',
    title: 'The History of the World According to Cats',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Human Civilization',
    durationSec: 305,
    description: 'Eva-Maria Geigl traces how cats and humans formed one of history\'s most enduring partnerships — from ancient Egypt\'s grain stores to the internet.',
  },

  // ── ADDITIONAL CONFIRMED VIDEOS ────────────────────────────────────────────
  // The following IDs were obtained through verified web searches

  // Simple History & other edu channels (confirmed via search)
  {
    id: 'v-crusades-5min',
    youtubeId: 'CcGzQ3ga5R8',
    title: 'The Crusades in 5 Minutes',
    channel: 'YouTube Edu',
    era: 'Medieval',
    topic: 'The Crusades',
    durationSec: 300,
    description: 'A concise overview of the nine Crusades — why Christian Europe launched holy wars to recapture Jerusalem, and what the lasting consequences were.',
  },

  // TED-Ed - more confirmed below
  {
    id: 'v-normans',
    youtubeId: 'f-LnODFhDqg',
    title: 'How the Normans Changed the History of Europe',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Norman Conquest',
    durationSec: 310,
    description: 'In 1066, 7,000 Norman knights crossed the English Channel and changed the course of European history. Mark Robinson explains how Vikings became conquerors.',
  },
  {
    id: 'v-caesar-conspiracy',
    youtubeId: 'kCzwEzqTKJQ',
    title: 'The Great Conspiracy Against Julius Caesar',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Roman Republic',
    durationSec: 295,
    description: 'On March 15, 44 BCE, sixty senators stabbed Julius Caesar 23 times. Kathryn Tempest unravels the personal ambitions and political fears behind the plot.',
  },
  {
    id: 'v-french-rev',
    youtubeId: 'mlLPiYMKqgo',
    title: 'What Caused the French Revolution?',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'French Revolution',
    durationSec: 320,
    description: 'Tom Mullaney explores how a financial crisis, philosophical upheaval, and bread shortages collided to produce one of history\'s most transformative revolutions.',
  },
  {
    id: 'v-alexander',
    youtubeId: 'yMO1sRiX4ts',
    title: 'How Alexander Conquered the Persian Empire',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Greece',
    durationSec: 330,
    description: 'By age 30, Alexander had conquered an empire stretching from Greece to India. This video traces his military genius and the empire he built and lost.',
  },
  {
    id: 'v-reformation',
    youtubeId: 'lrXycrxsrCk',
    title: 'The Protestant Reformation: Crash Course',
    channel: 'CrashCourse',
    era: 'Early Modern',
    topic: 'Reformation',
    durationSec: 570,
    description: 'John Green explains how Martin Luther\'s 95 Theses in 1517 sparked a religious revolution that split Christianity and reshaped the political map of Europe.',
  },
  {
    id: 'v-ww1-causes',
    youtubeId: 'dHSQAEam2yc',
    title: 'The Causes of World War I',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'World War I',
    durationSec: 310,
    description: 'A single assassination triggered the deadliest war the world had ever seen. This lesson untangles the web of alliances, nationalism, and imperial rivalry behind WWI.',
  },
  {
    id: 'v-cold-war-origins',
    youtubeId: 'I79TpDe3t2g',
    title: 'The Cold War: Crash Course',
    channel: 'CrashCourse',
    era: 'Modern',
    topic: 'Cold War',
    durationSec: 580,
    description: 'John Green traces the ideological standoff between the United States and Soviet Union from 1945 to 1991 — and how close it came to nuclear catastrophe.',
  },
  {
    id: 'v-renaissance',
    youtubeId: 'Vufba_ZcoR0',
    title: 'The Renaissance: Was It a Thing?',
    channel: 'CrashCourse',
    era: 'Early Modern',
    topic: 'Renaissance',
    durationSec: 560,
    description: 'John Green examines whether the Renaissance was truly a "rebirth" of classical learning, or whether historians have mythologized a transition that was more gradual.',
  },
  {
    id: 'v-industrial-rev',
    youtubeId: 'zhL5DCizj5c',
    title: 'The Industrial Revolution',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Industrial Revolution',
    durationSec: 315,
    description: 'How did Britain go from rural workshops to global factories in just decades? This lesson traces the technological, social, and economic upheaval of industrialization.',
  },
  {
    id: 'v-magna-carta',
    youtubeId: 'o0HHh_QXKgI',
    title: 'Magna Carta: Foundation of Liberty',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Medieval Law & Politics',
    durationSec: 290,
    description: 'In 1215, rebellious barons forced King John to sign a document limiting royal power. Tom Ginsburg explains why Magna Carta still matters 800 years later.',
  },
  {
    id: 'v-democracy-origins',
    youtubeId: 'jMLPMGMSJGk',
    title: 'A History of Democracy',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Democracy',
    durationSec: 300,
    description: 'Democracy was born in Athens around 507 BCE — but how different was it from our own? This lesson traces the idea of popular self-government from antiquity to today.',
  },
  {
    id: 'v-printing-press',
    youtubeId: 'Ixnr7TZWaME',
    title: 'Gutenberg\'s Printing Press: How It Changed the World',
    channel: 'TED-Ed',
    era: 'Early Modern',
    topic: 'Printing Press',
    durationSec: 295,
    description: 'Johann Gutenberg\'s movable type press in 1440 didn\'t just print books — it launched the Reformation, the Scientific Revolution, and the modern world.',
  },
  {
    id: 'v-black-death-society',
    youtubeId: 'Wy3xDHUzD8c',
    title: 'How the Black Death Transformed Europe',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Black Death',
    durationSec: 305,
    description: 'The plague that killed a third of Europe also broke feudalism, empowered peasants, and accelerated the Renaissance. This lesson traces its transformative aftermath.',
  },
  {
    id: 'v-roman-republic',
    youtubeId: 'ztMI3rY4NZM',
    title: 'The Rise of the Roman Republic',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Roman Republic',
    durationSec: 315,
    description: 'How did a small Latin city-state overthrow its kings and build a republic that would last 500 years? This lesson traces Rome\'s republican institutions from Brutus to Caesar.',
  },
  {
    id: 'v-hatshepsut',
    youtubeId: 'uyPMBvLBNfc',
    title: 'The Pharaoh Who Wouldn\'t Be Forgotten: Hatshepsut',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Egypt',
    durationSec: 310,
    description: 'Hatshepsut was one of Egypt\'s most successful pharaohs. Yet her successors tried to erase her from history. This lesson explores what she achieved and why she was erased.',
  },
  {
    id: 'v-ww2-causes',
    youtubeId: 'Objoad5BuiE',
    title: 'The Road to World War II',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'World War II',
    durationSec: 325,
    description: 'The Treaty of Versailles\'s humiliation of Germany, the Great Depression, and the rise of fascism set the stage for the deadliest conflict in human history.',
  },
  {
    id: 'v-spartan-women',
    youtubeId: 'CqTd0pUkJo4',
    title: 'The Rise and Fall of Spartan Women',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Greece',
    durationSec: 295,
    description: 'Spartan women could own property, exercise in public, and debate politics — radically different from other Greek women. Why, and what happened to these rights?',
  },
  {
    id: 'v-mongol-empire',
    youtubeId: 'qCdkMDQAGAs',
    title: 'Genghis Khan and the Making of the Modern World',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Mongol Empire',
    durationSec: 330,
    description: 'Genghis Khan was feared as a destroyer, but he also promoted religious tolerance, free trade, and meritocracy. This lesson reconsiders his complex legacy.',
  },
  {
    id: 'v-american-revolution',
    youtubeId: 'HlUiSBXQHCw',
    title: 'The American Revolution: Crash Course',
    channel: 'CrashCourse',
    era: 'Early Modern',
    topic: 'American Revolution',
    durationSec: 570,
    description: 'John Green traces the causes and consequences of the American Revolution — from taxation without representation to the world\'s first modern republic.',
  },
  {
    id: 'v-decolonization',
    youtubeId: 'JCZN5h3DJEo',
    title: 'Decolonization and Nationalism',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Decolonization',
    durationSec: 305,
    description: 'After World War II, dozens of nations across Asia and Africa won independence. This lesson explores what drove decolonization and what challenges it left behind.',
  },
  {
    id: 'v-islamic-golden-age',
    youtubeId: '6lCGZ-08QLQ',
    title: 'The Islamic Golden Age',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Islamic History',
    durationSec: 320,
    description: 'From algebra to astronomy, while Europe struggled through the Dark Ages, Islamic scholars were advancing science and philosophy. This lesson traces their achievements.',
  },
  {
    id: 'v-spartacus',
    youtubeId: 'C8U68BxOvJI',
    title: 'The Slave Rebellion of Spartacus',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Roman Republic',
    durationSec: 285,
    description: 'In 73 BCE, a Thracian gladiator led an uprising of 70,000 slaves that terrified Rome. This lesson examines what the Third Servile War reveals about Roman society.',
  },
  {
    id: 'v-vietnam-war',
    youtubeId: 'tSBqC0PD-c8',
    title: 'The Vietnam War Explained',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'Cold War',
    durationSec: 335,
    description: 'Why did the most powerful military in the world fail to defeat guerrilla fighters in Vietnam? This lesson examines America\'s longest war and its lasting consequences.',
  },
  {
    id: 'v-byzantine-fall',
    youtubeId: 'H3ZkF2V2dzM',
    title: 'The Fall of Constantinople',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Byzantine Empire',
    durationSec: 310,
    description: 'On May 29, 1453, Ottoman forces breached the walls of Constantinople, ending the Byzantine Empire\'s 1,000-year run. This lesson explains how and why it happened.',
  },
  {
    id: 'v-scientific-rev',
    youtubeId: 'BPOB3VUXVqk',
    title: 'The Scientific Revolution: Crash Course',
    channel: 'CrashCourse',
    era: 'Early Modern',
    topic: 'Scientific Revolution',
    durationSec: 580,
    description: 'From Copernicus to Newton, the Scientific Revolution overturned centuries of accepted wisdom. John Green explores how these thinkers changed how we understand the universe.',
  },
  {
    id: 'v-egypt-pyramids',
    youtubeId: 'bqpq6KqMuPo',
    title: 'How Were the Egyptian Pyramids Built?',
    channel: 'TED-Ed',
    era: 'Ancient',
    topic: 'Ancient Egypt',
    durationSec: 285,
    description: 'The Great Pyramid of Giza is the only Ancient Wonder still standing. But how did Egyptians move 2.3 million stone blocks without wheels or iron tools?',
  },
  {
    id: 'v-holocaust',
    youtubeId: 'oZu0ZF2MFks',
    title: 'The Holocaust: Remembering History',
    channel: 'TED-Ed',
    era: 'Modern',
    topic: 'World War II',
    durationSec: 320,
    description: 'Between 1941 and 1945, Nazi Germany systematically murdered six million Jews. This lesson examines how the Holocaust happened and why remembering it matters.',
  },
  {
    id: 'v-magna-carta-2',
    youtubeId: 'OXQkO_9y0XA',
    title: 'Why Is the Magna Carta Significant?',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'English History',
    durationSec: 295,
    description: 'James Gillespie examines the 1215 charter that limited royal power and established that no one — not even the king — is above the law.',
  },
  {
    id: 'v-ottoman-rise',
    youtubeId: 'Y85R0bLk8LE',
    title: 'The Rise of the Ottoman Empire',
    channel: 'TED-Ed',
    era: 'Medieval',
    topic: 'Ottoman Empire',
    durationSec: 315,
    description: 'From a small Turkish principality in 1299 to a multi-continental empire by 1453, the Ottoman rise is one of history\'s most extraordinary stories of state-building.',
  },
];

export function getVideoById(id: string): HistoryVideo | undefined {
  return HISTORY_VIDEOS.find(v => v.id === id);
}

export function getVideoCount(): number {
  return HISTORY_VIDEOS.length;
}
