// ─── Bake full static lesson translations (gateway-independent) ──────────────
// Translates every lesson's title / subtitle / key facts / section headings /
// section bodies into all five content languages (es, ru, mk, de, fr) via the
// Anthropic API, and writes them into src/i18n/lessonTranslationsGenerated.ts.
// Once run and committed, the app serves fully-translated lessons instantly with
// NO runtime AI dependency — even offline or without an API key in the deploy.
//
// Usage:
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/generate_lesson_translations.mjs
//   ANTHROPIC_API_KEY=sk-ant-... node scripts/generate_lesson_translations.mjs ancient-10 modern-14   # a subset
//
// Lessons 01–09 of each era already ship hand-authored translations, so they are
// skipped. Progress is written incrementally, so a re-run resumes cheaply
// (already-populated lessons are not re-translated).

import esbuild from 'esbuild';
import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';

const KEY = process.env.ANTHROPIC_API_KEY;
if (!KEY) { console.error('✗ Set ANTHROPIC_API_KEY in the environment first.'); process.exit(1); }

const ROOT = process.cwd();
const OUT = path.join(ROOT, 'src/i18n/lessonTranslationsGenerated.ts');
const LANGS = { es: 'Spanish', ru: 'Russian', mk: 'Macedonian', de: 'German', fr: 'French' };
const MODEL = 'claude-haiku-4-5-20251001';

// ── Load the lesson data by bundling the TS module (resolves the '@' alias) ──
const tmp = path.join(ROOT, 'scripts', '.lessons.tmp.mjs');
await esbuild.build({
  entryPoints: [path.join(ROOT, 'src/features/content/lessonsData.ts')],
  bundle: true, format: 'esm', outfile: tmp, platform: 'node', logLevel: 'silent',
  alias: { '@': path.join(ROOT, 'src') },
});
const { LESSONS } = await import(pathToFileURL(tmp).href);
fs.rmSync(tmp, { force: true });

// ── Existing output (resume support) ─────────────────────────────────────────
function loadExisting() {
  try {
    const src = fs.readFileSync(OUT, 'utf8');
    const m = src.match(/GENERATED_LESSON_T[^=]*=\s*(\{[\s\S]*?\});\s*$/);
    return m ? JSON.parse(m[1]) : {};
  } catch { return {}; }
}
const data = loadExisting();

// ── Anthropic call ───────────────────────────────────────────────────────────
async function anthropic(system, user) {
  for (let attempt = 0; attempt < 4; attempt++) {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-api-key': KEY, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({ model: MODEL, max_tokens: 4096, system, messages: [{ role: 'user', content: user }] }),
    });
    if (res.status === 429 || res.status >= 500) { await new Promise(r => setTimeout(r, 1500 * (attempt + 1))); continue; }
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 200)}`);
    const j = await res.json();
    return (j.content ?? []).map(c => c.text ?? '').join('');
  }
  throw new Error('rate-limited after retries');
}
const sys = (name) =>
  `You are a professional history translator. Translate every string in the JSON array "items" into ${name}. ` +
  `Produce natural, idiomatic ${name}; preserve all proper nouns, numbers, dates and meaning. ` +
  `Return ONLY {"items":[...]} with the SAME number of items in the SAME order. No markdown, no commentary.`;
async function batch(strings, name) {
  if (strings.length === 0) return [];
  const raw = await anthropic(sys(name), JSON.stringify({ items: strings }));
  const m = raw.match(/\{[\s\S]*\}/);
  let arr = [];
  try { arr = JSON.parse(m ? m[0] : '{}').items ?? []; } catch { /* keep source */ }
  return strings.map((o, i) => (typeof arr[i] === 'string' && arr[i].trim() ? arr[i] : o));
}

// ── Write the generated TS file ──────────────────────────────────────────────
function write() {
  const header = `// ─── Baked lesson translations (generated, gateway-independent) ──────────────
// AUTO-GENERATED by scripts/generate_lesson_translations.mjs — safe to commit.
// Re-run that script to refresh. See the script header for usage.

export interface GenLessonT { t?: string; s?: string; k?: string[]; h?: string[]; b?: string[]; }
export type GenContentLang = 'es' | 'ru' | 'mk' | 'de' | 'fr';

/** lessonId → language → baked translation. */
export const GENERATED_LESSON_T: Record<string, Partial<Record<GenContentLang, GenLessonT>>> = `;
  fs.writeFileSync(OUT, header + JSON.stringify(data) + ';\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────
const only = process.argv.slice(2);
const targets = LESSONS.filter(l => !/-0[1-9]$/.test(l.id) && (only.length === 0 || only.includes(l.id)));
console.log(`→ ${targets.length} lessons × ${Object.keys(LANGS).length} languages`);

for (const l of targets) {
  data[l.id] ??= {};
  for (const [code, name] of Object.entries(LANGS)) {
    if (data[l.id][code]?.b?.length) continue; // already done — resume
    const k = l.keyFacts.length;
    const metaT = await batch([l.title, l.subtitle, ...l.keyFacts, ...l.sections.map(s => s.heading)], name);
    const bodies = [];
    for (let i = 0; i < l.sections.length; i += 2) bodies.push(...await batch(l.sections.slice(i, i + 2).map(s => s.body), name));
    data[l.id][code] = { t: metaT[0], s: metaT[1], k: metaT.slice(2, 2 + k), h: metaT.slice(2 + k), b: bodies };
    write(); // incremental — resumable on crash
    console.log(`  ✓ ${l.id} · ${code}`);
  }
}
console.log(`\n✓ wrote ${OUT.replace(ROOT + '/', '')}`);
