import type { Quiz, EraId } from '@/types';

export const QUIZZES: Quiz[] = [
  { id: 'quiz-ancient', eraId: 'ancient', title: 'Ancient History Quiz', xpPerCorrect: 20, passingScore: 70, questions: [
    { id:'aq1', question:'What writing system did the Sumerians develop around 3100 BCE?', options:['Hieroglyphics','Cuneiform','Linear B','Phoenician alphabet'], correctIndex:1, explanation:'Cuneiform ("wedge-shaped") was pressed into clay tablets with a reed stylus. Hieroglyphics were Egyptian; Linear B was Mycenaean Greek.', difficulty:'easy' },
    { id:'aq2', question:'Which Athenian reformer introduced the world\'s first democratic system around 508 BCE?', options:['Solon','Pericles','Cleisthenes','Themistocles'], correctIndex:2, explanation:'Cleisthenes restructured Athenian governance to give ordinary citizens direct political power, earning the title "Father of Athenian Democracy."', difficulty:'medium' },
    { id:'aq3', question:'At which battle did the Athenians defeat the Persian invasion in 490 BCE?', options:['Thermopylae','Salamis','Marathon','Plataea'], correctIndex:2, explanation:'The Battle of Marathon saw a smaller Athenian force rout the Persians, preserving Greek independence.', difficulty:'easy' },
    { id:'aq4', question:'Julius Caesar was assassinated on which date in 44 BCE?', options:['January 1','March 15','July 4','December 25'], correctIndex:1, explanation:'The "Ides of March" (March 15) is when a group of senators, led by Brutus and Cassius, murdered Caesar in the Senate.', difficulty:'easy' },
    { id:'aq5', question:'The Pax Romana refers to a period of Roman peace that lasted approximately how long?', options:['50 years','100 years','200 years','400 years'], correctIndex:2, explanation:'The Pax Romana ("Roman Peace") lasted roughly 200 years from Augustus in 27 BCE to the death of Marcus Aurelius in 180 CE.', difficulty:'medium' },
    { id:'aq6', question:'Which Persian king issued the "Cyrus Cylinder," regarded as an early declaration of human rights?', options:['Darius I','Xerxes','Cyrus the Great','Artaxerxes'], correctIndex:2, explanation:'Cyrus the Great freed the Jewish exiles from Babylon and allowed conquered peoples to practice their own religions.', difficulty:'hard' },
    { id:'aq7', question:'The Silk Road primarily facilitated trade between which two civilizations?', options:['Egypt and Greece','Rome and India','China and Rome/Mediterranean','Persia and Egypt'], correctIndex:2, explanation:'The Silk Road connected Han China to the Mediterranean world, carrying silk, spices, and ideas in both directions.', difficulty:'medium' },
    { id:'aq8', question:'Which philosopher was sentenced to death in Athens in 399 BCE for "corrupting the youth"?', options:['Plato','Aristotle','Socrates','Diogenes'], correctIndex:2, explanation:'Socrates was tried and forced to drink hemlock. His student Plato wrote about the trial in the Apology.', difficulty:'easy' },
    { id:'aq9', question:'Emperor Ashoka of the Maurya Empire converted to which religion after the brutal conquest of Kalinga?', options:['Hinduism','Jainism','Buddhism','Zoroastrianism'], correctIndex:2, explanation:'Horrified by the suffering at Kalinga, Ashoka embraced Buddhism and governed by dharma, sending missionaries across Asia.', difficulty:'medium' },
    { id:'aq10', question:'What was the significance of Hammurabi\'s Code (~1754 BCE)?', options:['First democratic constitution','First written legal code in history','First international trade agreement','First monotheistic religious text'], correctIndex:1, explanation:'The Code of Hammurabi is one of the earliest and most complete written legal codes, covering crimes, commerce, and social relations.', difficulty:'easy' },
  ]},
  { id: 'quiz-medieval', eraId: 'middle-ages', title: 'Middle Ages Quiz', xpPerCorrect: 20, passingScore: 70, questions: [
    { id:'mq1', question:'In what year did the last Western Roman Emperor lose power, marking the fall of the Western Roman Empire?', options:['410 CE','455 CE','476 CE','500 CE'], correctIndex:2, explanation:'In 476 CE, the Germanic chieftain Odoacer deposed Romulus Augustulus — the conventional end date for the Western Roman Empire.', difficulty:'easy' },
    { id:'mq2', question:'On what date was Charlemagne crowned "Emperor of the Romans" by Pope Leo III?', options:['Easter Sunday 799','Christmas Day 800','New Year\'s Day 801','Good Friday 802'], correctIndex:1, explanation:'Christmas Day 800 CE in St. Peter\'s Basilica in Rome. The unexpected coronation allegedly surprised Charlemagne.', difficulty:'medium' },
    { id:'mq3', question:'The feudal system organized society primarily around which relationship?', options:['Trade and commerce','Land ownership and military service','Church authority and monks','Tribal kinship'], correctIndex:1, explanation:'Feudalism was based on lords granting land (fiefs) to vassals in exchange for military service and loyalty.', difficulty:'easy' },
    { id:'mq4', question:'The First Crusade was called by Pope Urban II in which year?', options:['1054','1095','1099','1147'], correctIndex:1, explanation:'In 1095 at Clermont, Pope Urban II called for Christian warriors to retake Jerusalem from the Seljuk Turks.', difficulty:'easy' },
    { id:'mq5', question:'Saladin, who recaptured Jerusalem in 1187, was Sultan of which region?', options:['Persia','Turkey','Egypt and Syria','Baghdad'], correctIndex:2, explanation:'Saladin was the Kurdish founder of the Ayyubid dynasty, ruler of Egypt and Syria. His chivalry was respected even by Crusaders.', difficulty:'hard' },
    { id:'mq6', question:'The Black Death is estimated to have killed what fraction of Europe\'s population between 1347 and 1353?', options:['One-tenth','One-quarter','One-third to one-half','Two-thirds'], correctIndex:2, explanation:'Estimates vary from 30–60% of Europe\'s population. Some cities like Florence lost over half their inhabitants.', difficulty:'medium' },
    { id:'mq7', question:'Which English document (1215) established that the king was subject to the rule of law?', options:['Domesday Book','Magna Carta','Bill of Rights','Common Law Code'], correctIndex:1, explanation:'Magna Carta ("Great Charter") was forced on King John by rebellious barons, establishing that even the king must follow the law.', difficulty:'easy' },
    { id:'mq8', question:'What was the primary language of scholarship and the Catholic Church throughout the Middle Ages?', options:['Greek','French','Arabic','Latin'], correctIndex:3, explanation:'Latin was the universal language of educated Europeans, enabling scholars from different countries to communicate and preserving ancient texts.', difficulty:'easy' },
    { id:'mq9', question:'The Islamic Golden Age was centered primarily in which city under the Abbasid Caliphate?', options:['Cairo','Cordoba','Baghdad','Istanbul'], correctIndex:2, explanation:'Baghdad\'s House of Wisdom was the world\'s greatest center of learning from the 8th–13th centuries, gathering scholars from across the known world.', difficulty:'medium' },
    { id:'mq10', question:'The Mongol Empire at its peak was the largest contiguous land empire in history. Who founded it?', options:['Kublai Khan','Timur','Genghis Khan','Ogedei Khan'], correctIndex:2, explanation:'Genghis Khan united the Mongol tribes in 1206 and began the conquests that eventually stretched from Korea to Hungary.', difficulty:'easy' },
  ]},
  { id: 'quiz-earlymod', eraId: 'early-modern', title: 'Early Modern Era Quiz', xpPerCorrect: 20, passingScore: 70, questions: [
    { id:'eq1', question:'Johannes Gutenberg\'s invention of movable-type printing (c.1440) most directly enabled which event?', options:['The Crusades','The Protestant Reformation','The Black Death','The Mongol invasions'], correctIndex:1, explanation:'The printing press made it possible to spread Luther\'s ideas across Germany within weeks — without it, the Reformation might have been suppressed like earlier reform movements.', difficulty:'medium' },
    { id:'eq2', question:'Columbus\'s first landfall in 1492 was in which region?', options:['Brazil','Florida','The Caribbean','Mexico'], correctIndex:2, explanation:'Columbus landed in the Bahamas in the Caribbean, believing he had reached Asia. He never realized he had found a continent previously unknown to Europeans.', difficulty:'easy' },
    { id:'eq3', question:'The "Columbian Exchange" refers to which phenomenon?', options:['Columbus trading gold for spices','The transfer of plants, animals, and diseases between hemispheres after 1492','A trade agreement between Spain and Portugal','Columbus exchanging maps with indigenous peoples'], correctIndex:1, explanation:'The Columbian Exchange brought horses, cattle, and deadly diseases to the Americas; it returned potatoes, tomatoes, and maize to Europe — transforming both hemispheres.', difficulty:'medium' },
    { id:'eq4', question:'Martin Luther posted his 95 Theses challenging Church corruption in which year?', options:['1492','1505','1517','1543'], correctIndex:2, explanation:'On October 31, 1517, Luther challenged the sale of indulgences, launching the Protestant Reformation.', difficulty:'easy' },
    { id:'eq5', question:'The Peace of Westphalia (1648) established which key principle of the modern international order?', options:['Free trade between nations','The supremacy of the Pope','National sovereignty and non-interference','The rights of religious minorities'], correctIndex:2, explanation:'Westphalia established that rulers could determine their territories\' religion and that outside powers should not interfere — the foundation of the modern nation-state system.', difficulty:'hard' },
    { id:'eq6', question:'Galileo Galilei was forced to recant his support for the heliocentric model by which institution in 1633?', options:['The Spanish Inquisition','The Venetian Republic','The Roman Catholic Church','The Holy Roman Emperor'], correctIndex:2, explanation:'The Roman Inquisition condemned Galileo for heresy. He reportedly muttered "And yet it moves" after recanting, though this is likely apocryphal.', difficulty:'easy' },
    { id:'eq7', question:'Isaac Newton\'s Principia Mathematica (1687) established laws governing which phenomena?', options:['Electricity and magnetism','Motion and gravity','Light and optics','Chemistry and atoms'], correctIndex:1, explanation:'The Principia described the three laws of motion and universal gravitation — showing the same force that made an apple fall kept the Moon in orbit.', difficulty:'easy' },
    { id:'eq8', question:'The Thirty Years\' War (1618–1648) began as a conflict over what?', options:['Colonial territory','Trade routes','Religion in the Holy Roman Empire','Succession to the French throne'], correctIndex:2, explanation:'It began as a religious war between Catholics and Protestants in Bohemia (today\'s Czech Republic) before becoming a general European power conflict.', difficulty:'medium' },
    { id:'eq9', question:'Which Enlightenment thinker wrote "The Social Contract" (1762) arguing government legitimacy comes from the people?', options:['Voltaire','Montesquieu','John Locke','Jean-Jacques Rousseau'], correctIndex:3, explanation:'Rousseau\'s Social Contract argued that legitimate government derives from popular consent — a direct influence on both the American and French Revolutions.', difficulty:'medium' },
    { id:'eq10', question:'Which explorer, sailing for Portugal, became the first to reach India by sea around Africa in 1498?', options:['Christopher Columbus','Amerigo Vespucci','Vasco da Gama','Ferdinand Magellan'], correctIndex:2, explanation:'Vasco da Gama\'s voyage around the Cape of Good Hope opened the direct sea route to Asia, breaking the Arab monopoly on the spice trade.', difficulty:'easy' },
  ]},
  { id: 'quiz-modern', eraId: 'modern', title: 'Modern Era Quiz', xpPerCorrect: 20, passingScore: 70, questions: [
    { id:'mq1', question:'The Industrial Revolution began in which country around 1760?', options:['France','Germany','United States','Britain'], correctIndex:3, explanation:'Britain\'s combination of coal, iron, stable government, and colonial markets made it the birthplace of industrialization.', difficulty:'easy' },
    { id:'mq2', question:'What was the immediate trigger of World War I in 1914?', options:['Germany invading Belgium','The sinking of the Lusitania','Assassination of Archduke Franz Ferdinand','Russia mobilizing its army'], correctIndex:2, explanation:'The assassination of Austro-Hungarian Archduke Franz Ferdinand in Sarajevo by Serbian nationalist Gavrilo Princip triggered the alliance system that drew Europe into war.', difficulty:'easy' },
    { id:'mq3', question:'The Treaty of Versailles (1919) blamed WWI on which country and imposed massive reparations?', options:['Austria-Hungary','Ottoman Empire','Germany','Russia'], correctIndex:2, explanation:'The "war guilt clause" (Article 231) assigned responsibility to Germany, leading to reparations and territorial losses that fueled resentment and ultimately WWII.', difficulty:'easy' },
    { id:'mq4', question:'The Holocaust was the Nazi genocide of primarily which group, among others?', options:['Slavic peoples','Roma people','Jewish people','Political opponents'], correctIndex:2, explanation:'Six million Jews — two-thirds of European Jewry — were systematically murdered. Millions of others (Roma, disabled, LGBTQ+, political prisoners) were also killed.', difficulty:'easy' },
    { id:'mq5', question:'The Cold War was primarily an ideological conflict between which two systems?', options:['Democracy and fascism','Capitalism/democracy and communism','Christianity and Islam','Colonialism and nationalism'], correctIndex:1, explanation:'The Cold War pitted the capitalist democratic West (led by the USA) against the communist East (led by the USSR).', difficulty:'easy' },
    { id:'mq6', question:'The Cuban Missile Crisis of 1962 brought the world to the brink of nuclear war when the USSR placed missiles in Cuba in response to what?', options:['The Bay of Pigs invasion','American missiles in Turkey','The Berlin Wall','The Korean War'], correctIndex:0, explanation:'Though American missiles in Turkey were also a factor, the immediate Soviet response was to the failed CIA-backed Bay of Pigs invasion of Cuba in 1961.', difficulty:'hard' },
    { id:'mq7', question:'Which Indian leader used nonviolent civil disobedience to lead India\'s independence movement against British rule?', options:['Jawaharlal Nehru','Subhas Chandra Bose','Muhammad Ali Jinnah','Mahatma Gandhi'], correctIndex:3, explanation:'Gandhi\'s philosophy of satyagraha (truth-force) and nonviolent resistance became an inspiration for civil rights movements worldwide.', difficulty:'easy' },
    { id:'mq8', question:'The Berlin Wall fell in which year, symbolizing the end of the Cold War?', options:['1985','1987','1989','1991'], correctIndex:2, explanation:'The Wall fell on November 9, 1989, after the East German government announced citizens could cross freely — crowds dismantled it that night.', difficulty:'easy' },
    { id:'mq9', question:'Who invented the World Wide Web in 1989, enabling the modern internet?', options:['Steve Jobs','Bill Gates','Tim Berners-Lee','Vint Cerf'], correctIndex:2, explanation:'Tim Berners-Lee, a British scientist at CERN, invented the World Wide Web (HTTP, HTML, and URLs) and made it freely available to the public.', difficulty:'medium' },
    { id:'mq10', question:'The September 11, 2001 attacks were carried out by which organization?', options:['Taliban','Hezbollah','ISIS','Al-Qaeda'], correctIndex:3, explanation:'Al-Qaeda, led by Osama bin Laden, orchestrated the attacks using hijacked airplanes. The Taliban government of Afghanistan sheltered al-Qaeda, triggering the US invasion.', difficulty:'easy' },
  ]},
];

export function getQuizByEraId(eraId: EraId) { return QUIZZES.find(q => q.eraId === eraId); }
export function getQuizById(id: string) { return QUIZZES.find(q => q.id === id); }
