// ─── CHRONOS IMPERIUM · Strict Localization Contract ─────────────────────────
// Every player-facing string the engine can emit — crisis narratives, option
// labels, alerts, roster/unit/leader names, combat modifier labels — lives in
// this catalog, keyed by id and resolved through the active UI language.
// Engine payloads carry ONLY keys (+ interpolation params); components resolve
// at the render boundary. That is the contract that makes English leakage on
// client devices structurally impossible: there is no English in the payloads
// to leak. Missing entries resolve to English by fallback, never to a raw key.
import type { Language } from '@/i18n/translations';

type Entry = Partial<Record<Language, string>> & { en: string };

const CATALOG: Record<string, Entry> = {
  // ── Rosters ──
  imp_roster_roman: { en: 'Roman Legion', es: 'Legión romana', ru: 'Римский легион', mk: 'Римска легија', de: 'Römische Legion', fr: 'Légion romaine' },
  imp_roster_macedonian: { en: 'Macedonian Phalanx', es: 'Falange macedonia', ru: 'Македонская фаланга', mk: 'Македонска фаланга', de: 'Makedonische Phalanx', fr: 'Phalange macédonienne' },
  imp_roster_persian: { en: 'Persian Host', es: 'Hueste persa', ru: 'Персидское войско', mk: 'Персиска војска', de: 'Persisches Heer', fr: 'Ost perse' },
  imp_roster_byzantine: { en: 'Byzantine Thematic Army', es: 'Ejército temático bizantino', ru: 'Византийская фемная армия', mk: 'Византиска темска војска', de: 'Byzantinisches Themenheer', fr: 'Armée thématique byzantine' },
  imp_roster_frankish: { en: 'Frankish Host', es: 'Hueste franca', ru: 'Франкское войско', mk: 'Франачка војска', de: 'Fränkisches Heer', fr: 'Ost franc' },
  imp_roster_mongol: { en: 'Mongol Tumen', es: 'Tumen mongol', ru: 'Монгольский тумен', mk: 'Монголски тумен', de: 'Mongolisches Tumen', fr: 'Tumen mongol' },
  imp_roster_tercio: { en: 'Spanish Tercio', es: 'Tercio español', ru: 'Испанская терция', mk: 'Шпанско терцио', de: 'Spanischer Tercio', fr: 'Tercio espagnol' },
  imp_roster_ottoman: { en: 'Ottoman Kapıkulu', es: 'Kapıkulu otomano', ru: 'Османский капыкулу', mk: 'Отомански капикулу', de: 'Osmanische Kapıkulu', fr: 'Kapıkulu ottoman' },
  imp_roster_swedish: { en: 'Swedish Brigade', es: 'Brigada sueca', ru: 'Шведская бригада', mk: 'Шведска бригада', de: 'Schwedische Brigade', fr: 'Brigade suédoise' },
  imp_roster_napoleonic: { en: 'Napoleonic Corps', es: 'Cuerpo napoleónico', ru: 'Наполеоновский корпус', mk: 'Наполеонов корпус', de: 'Napoleonisches Korps', fr: 'Corps napoléonien' },
  imp_roster_greatwar: { en: 'Great War Division', es: 'División de la Gran Guerra', ru: 'Дивизия Великой войны', mk: 'Дивизија од Големата војна', de: 'Weltkriegsdivision', fr: 'Division de la Grande Guerre' },
  imp_roster_crusader: { en: 'Crusader Host', es: 'Hueste cruzada', ru: 'Крестоносное войско', mk: 'Крстоносна војска', de: 'Kreuzfahrerheer', fr: 'Ost croisé' },
  imp_roster_han: { en: 'Han Army', es: 'Ejército Han', ru: 'Ханьская армия', mk: 'Хан војска', de: 'Han-Armee', fr: 'Armée Han' },
  // ── Units ──
  imp_unit_legionary: { en: 'Legionaries', es: 'Legionarios', ru: 'Легионеры', mk: 'Легионери', de: 'Legionäre', fr: 'Légionnaires' },
  imp_unit_velites: { en: 'Velites', es: 'Vélites', ru: 'Велиты', mk: 'Велити', de: 'Veliten', fr: 'Vélites' },
  imp_unit_equites: { en: 'Equites', es: 'Équites', ru: 'Эквиты', mk: 'Еквити', de: 'Equites', fr: 'Équites' },
  imp_unit_phalangite: { en: 'Phalangites', es: 'Falangitas', ru: 'Фалангиты', mk: 'Фалангити', de: 'Phalangiten', fr: 'Phalangites' },
  imp_unit_peltast: { en: 'Peltasts', es: 'Peltastas', ru: 'Пельтасты', mk: 'Пелтасти', de: 'Peltasten', fr: 'Peltastes' },
  imp_unit_companion: { en: 'Companion Cavalry', es: 'Caballería de compañeros', ru: 'Гетайры', mk: 'Хетајри', de: 'Hetairoi', fr: 'Cavalerie des compagnons' },
  imp_unit_immortal: { en: 'Immortals', es: 'Inmortales', ru: 'Бессмертные', mk: 'Бесмртници', de: 'Unsterbliche', fr: 'Immortels' },
  imp_unit_persian_archer: { en: 'Persian Archers', es: 'Arqueros persas', ru: 'Персидские лучники', mk: 'Персиски стрелци', de: 'Persische Bogenschützen', fr: 'Archers perses' },
  imp_unit_scythed_chariot: { en: 'Scythed Chariots', es: 'Carros falcados', ru: 'Серпоносные колесницы', mk: 'Коли со српови', de: 'Sichelwagen', fr: 'Chars à faux' },
  imp_unit_skutatos: { en: 'Skutatoi', es: 'Skutatoi', ru: 'Скутаты', mk: 'Скутати', de: 'Skutatoi', fr: 'Skutatoi' },
  imp_unit_toxotai: { en: 'Toxotai', es: 'Toxotai', ru: 'Токсоты', mk: 'Токсоти', de: 'Toxotai', fr: 'Toxotai' },
  imp_unit_cataphract: { en: 'Cataphracts', es: 'Catafractos', ru: 'Катафракты', mk: 'Катафракти', de: 'Kataphrakten', fr: 'Cataphractes' },
  imp_unit_menatarms: { en: 'Men-at-Arms', es: 'Hombres de armas', ru: 'Латники', mk: 'Оклопници', de: 'Waffenknechte', fr: 'Hommes d\'armes' },
  imp_unit_crossbowman: { en: 'Crossbowmen', es: 'Ballesteros', ru: 'Арбалетчики', mk: 'Самострелци', de: 'Armbrustschützen', fr: 'Arbalétriers' },
  imp_unit_knight: { en: 'Knights', es: 'Caballeros', ru: 'Рыцари', mk: 'Витези', de: 'Ritter', fr: 'Chevaliers' },
  imp_unit_auxiliary_spear: { en: 'Auxiliary Spearmen', es: 'Lanceros auxiliares', ru: 'Вспомогательные копейщики', mk: 'Помошни копјаници', de: 'Hilfsspeerträger', fr: 'Lanciers auxiliaires' },
  imp_unit_horse_archer: { en: 'Horse Archers', es: 'Arqueros a caballo', ru: 'Конные лучники', mk: 'Коњски стрелци', de: 'Berittene Bogenschützen', fr: 'Archers montés' },
  imp_unit_keshik: { en: 'Keshik Guard', es: 'Guardia keshik', ru: 'Кешиктены', mk: 'Кешик гарда', de: 'Keschik-Garde', fr: 'Garde kechik' },
  imp_unit_pikeman: { en: 'Pikemen', es: 'Piqueros', ru: 'Пикинёры', mk: 'Пикинери', de: 'Pikeniere', fr: 'Piquiers' },
  imp_unit_arquebusier: { en: 'Arquebusiers', es: 'Arcabuceros', ru: 'Аркебузиры', mk: 'Аркебузири', de: 'Arkebusiere', fr: 'Arquebusiers' },
  imp_unit_herreruelo: { en: 'Herreruelos', es: 'Herreruelos', ru: 'Эрреруэло', mk: 'Хереруело', de: 'Herreruelos', fr: 'Herreruelos' },
  imp_unit_janissary: { en: 'Janissaries', es: 'Jenízaros', ru: 'Янычары', mk: 'Јаничари', de: 'Janitscharen', fr: 'Janissaires' },
  imp_unit_topcu: { en: 'Topçu Artillery', es: 'Artillería topçu', ru: 'Топчу (артиллерия)', mk: 'Топчу артилерија', de: 'Topçu-Artillerie', fr: 'Artillerie topçu' },
  imp_unit_sipahi: { en: 'Sipahis', es: 'Sipahis', ru: 'Сипахи', mk: 'Спахии', de: 'Sipahis', fr: 'Sipahis' },
  imp_unit_musketeer_gv: { en: 'Musketeers', es: 'Mosqueteros', ru: 'Мушкетёры', mk: 'Мускетари', de: 'Musketiere', fr: 'Mousquetaires' },
  imp_unit_leather_gun: { en: 'Leather Guns', es: 'Cañones de cuero', ru: 'Кожаные пушки', mk: 'Кожни топови', de: 'Ledergeschütze', fr: 'Canons de cuir' },
  imp_unit_hakkapeliitta: { en: 'Hakkapeliitta', es: 'Hakkapeliitta', ru: 'Хаккапелиты', mk: 'Хакапелити', de: 'Hakkapeliten', fr: 'Hakkapélites' },
  imp_unit_line_infantry: { en: 'Line Infantry', es: 'Infantería de línea', ru: 'Линейная пехота', mk: 'Линиска пешадија', de: 'Linieninfanterie', fr: 'Infanterie de ligne' },
  imp_unit_grand_battery: { en: 'Grand Battery', es: 'Gran batería', ru: 'Большая батарея', mk: 'Голема батерија', de: 'Große Batterie', fr: 'Grande batterie' },
  imp_unit_cuirassier: { en: 'Cuirassiers', es: 'Coraceros', ru: 'Кирасиры', mk: 'Кирасири', de: 'Kürassiere', fr: 'Cuirassiers' },
  imp_unit_rifleman: { en: 'Riflemen', es: 'Fusileros', ru: 'Стрелки', mk: 'Пушкари', de: 'Schützen', fr: 'Fusiliers' },
  imp_unit_field_artillery: { en: 'Field Artillery', es: 'Artillería de campaña', ru: 'Полевая артиллерия', mk: 'Полска артилерија', de: 'Feldartillerie', fr: 'Artillerie de campagne' },
  imp_unit_stormtrooper: { en: 'Stormtroopers', es: 'Tropas de asalto', ru: 'Штурмовики', mk: 'Јуришници', de: 'Stoßtruppen', fr: 'Troupes d\'assaut' },
  imp_unit_sergeant: { en: 'Sergeants', es: 'Sargentos', ru: 'Сержанты', mk: 'Сержанти', de: 'Sergeanten', fr: 'Sergents' },
  imp_unit_turcopole: { en: 'Turcopoles', es: 'Turcópolos', ru: 'Туркополы', mk: 'Туркополи', de: 'Turkopolen', fr: 'Turcoples' },
  imp_unit_templar: { en: 'Templar Knights', es: 'Caballeros templarios', ru: 'Тамплиеры', mk: 'Темплари', de: 'Templerritter', fr: 'Chevaliers templiers' },
  imp_unit_halberdier: { en: 'Halberdiers', es: 'Alabarderos', ru: 'Алебардщики', mk: 'Халбардисти', de: 'Hellebardiere', fr: 'Hallebardiers' },
  imp_unit_chukonu: { en: 'Repeating Crossbows', es: 'Ballestas de repetición', ru: 'Многозарядные арбалеты', mk: 'Повторувачки самострели', de: 'Repetierarmbrüste', fr: 'Arbalètes à répétition' },
  imp_unit_han_lancer: { en: 'Han Lancers', es: 'Lanceros Han', ru: 'Ханьские копейщики', mk: 'Хан копјаници', de: 'Han-Lanzenreiter', fr: 'Lanciers Han' },
  // ── Leaders ──
  imp_leader_consul: { en: 'The Iron Consul', es: 'El Cónsul de Hierro', ru: 'Железный консул', mk: 'Железниот конзул', de: 'Der Eiserne Konsul', fr: 'Le Consul de fer' },
  imp_leader_khan: { en: 'The Steppe Khan', es: 'El Kan de la estepa', ru: 'Степной хан', mk: 'Степскиот хан', de: 'Der Steppenkhan', fr: 'Le Khan des steppes' },
  imp_leader_marshal: { en: 'The Lion Marshal', es: 'El Mariscal León', ru: 'Маршал-лев', mk: 'Маршалот Лав', de: 'Der Löwenmarschall', fr: 'Le Maréchal-lion' },
  imp_leader_strategos: { en: 'The Silent Strategos', es: 'El Estratego silencioso', ru: 'Молчаливый стратег', mk: 'Тивкиот стратег', de: 'Der Stille Stratege', fr: 'Le Stratège silencieux' },
  imp_leader_sultan: { en: 'The Storm Sultan', es: 'El Sultán de la tormenta', ru: 'Султан бури', mk: 'Султанот на бурата', de: 'Der Sturmsultan', fr: 'Le Sultan des tempêtes' },
  imp_leader_eagle: { en: 'The Young Eagle', es: 'El Águila joven', ru: 'Молодой орёл', mk: 'Младиот орел', de: 'Der Junge Adler', fr: 'Le Jeune Aigle' },
  // ── Combat modifier labels ──
  imp_mod_tactic_adv: { en: 'Tactical advantage', es: 'Ventaja táctica', ru: 'Тактическое преимущество', mk: 'Тактичка предност', de: 'Taktischer Vorteil', fr: 'Avantage tactique' },
  imp_mod_tactic_counter: { en: 'Countered tactic', es: 'Táctica contrarrestada', ru: 'Парированная тактика', mk: 'Контрирана тактика', de: 'Gekonterte Taktik', fr: 'Tactique contrée' },
  imp_mod_mountain_def: { en: 'Mountain defense', es: 'Defensa de montaña', ru: 'Горная оборона', mk: 'Планинска одбрана', de: 'Gebirgsverteidigung', fr: 'Défense de montagne' },
  imp_mod_charge_uphill: { en: 'Charging uphill', es: 'Carga cuesta arriba', ru: 'Атака в гору', mk: 'Јуриш угоре', de: 'Angriff bergauf', fr: 'Charge en montée' },
  imp_mod_river_crossing: { en: 'Contested river crossing', es: 'Cruce de río disputado', ru: 'Переправа под огнём', mk: 'Оспоруван премин на река', de: 'Umkämpfte Flussüberquerung', fr: 'Franchissement de rivière contesté' },
  imp_mod_desert_fatigue: { en: 'Desert fatigue', es: 'Fatiga del desierto', ru: 'Пустынное истощение', mk: 'Пустински замор', de: 'Wüstenerschöpfung', fr: 'Fatigue du désert' },
  imp_mod_high_ground: { en: 'High ground', es: 'Terreno elevado', ru: 'Господствующая высота', mk: 'Височинска положба', de: 'Erhöhte Stellung', fr: 'Position dominante' },
  imp_mod_rain_bowstrings: { en: 'Rain-soaked bowstrings', es: 'Cuerdas empapadas', ru: 'Промокшие тетивы', mk: 'Наводенети тетиви', de: 'Durchnässte Bogensehnen', fr: 'Cordes détrempées' },
  imp_mod_storm_chaos: { en: 'Storm chaos', es: 'Caos de tormenta', ru: 'Хаос бури', mk: 'Хаос од бура', de: 'Sturmchaos', fr: 'Chaos de tempête' },
  imp_mod_heat_exhaustion: { en: 'Heat exhaustion', es: 'Agotamiento por calor', ru: 'Тепловое изнеможение', mk: 'Топлотна исцрпеност', de: 'Hitzeerschöpfung', fr: 'Épuisement par la chaleur' },
  imp_mod_snow_slog: { en: 'Snowbound advance', es: 'Avance entre la nieve', ru: 'Наступление по снегу', mk: 'Напредување низ снег', de: 'Vormarsch im Schnee', fr: 'Avancée dans la neige' },
  imp_mod_leader_signature: { en: 'Leader\'s signature tactic', es: 'Táctica insignia del líder', ru: 'Коронный приём полководца', mk: 'Потписна тактика на водачот', de: 'Signaturtaktik des Anführers', fr: 'Tactique signature du chef' },
  imp_mod_leader_signature_def: { en: 'Defending commander\'s doctrine', es: 'Doctrina del comandante defensor', ru: 'Доктрина обороняющегося', mk: 'Доктрина на бранителот', de: 'Doktrin des Verteidigers', fr: 'Doctrine du défenseur' },
  // ── Crisis events ──
  imp_crisis_capital_lost_title: { en: 'The capital has fallen!', es: '¡La capital ha caído!', ru: 'Столица пала!', mk: 'Престолнината падна!', de: 'Die Hauptstadt ist gefallen!', fr: 'La capitale est tombée !' },
  imp_crisis_capital_lost_body: { en: 'With {territory} in enemy hands, provinces waver and the treasury flees the mint. Every turn it remains lost, morale across your realm decays.', es: 'Con {territory} en manos enemigas, las provincias vacilan y el tesoro huye de la ceca. Cada turno que siga perdida, la moral de tu reino decae.', ru: 'Пока {territory} в руках врага, провинции колеблются, а казна утекает. Каждый ход без столицы подтачивает боевой дух державы.', mk: 'Со {territory} во непријателски раце, провинциите се колебаат и трезорот бега. Секој потег додека е изгубена, моралот на царството опаѓа.', de: 'Mit {territory} in Feindeshand wanken die Provinzen und die Staatskasse flieht. Jede Runde des Verlusts zehrt an der Moral des Reiches.', fr: 'Avec {territory} aux mains de l\'ennemi, les provinces vacillent et le trésor s\'enfuit. Chaque tour de perte ronge le moral du royaume.' },
  imp_crisis_capital_opt_rally: { en: 'Rally the loyal provinces (+morale, -treasury)', es: 'Moviliza a las provincias leales (+moral, -tesoro)', ru: 'Сплотить верные провинции (+дух, -казна)', mk: 'Собери ги лојалните провинции (+морал, -трезор)', de: 'Die treuen Provinzen sammeln (+Moral, -Schatz)', fr: 'Rallier les provinces loyales (+moral, -trésor)' },
  imp_crisis_capital_opt_march: { en: 'March at once to retake it (forced march order)', es: 'Marcha de inmediato para recuperarla (marcha forzada)', ru: 'Немедленно выступить на её освобождение (форсированный марш)', mk: 'Веднаш маршираj да ја вратиш (принуден марш)', de: 'Sofort zum Rückeroberungsmarsch aufbrechen (Gewaltmarsch)', fr: 'Marcher aussitôt pour la reprendre (marche forcée)' },
  imp_crisis_capital_opt_regroup: { en: 'Accept the loss for now; fortify a new seat', es: 'Acepta la pérdida por ahora; fortifica una nueva sede', ru: 'Пока смириться с потерей; укрепить новую резиденцию', mk: 'Прифати ја загубата засега; утврди ново седиште', de: 'Den Verlust vorerst hinnehmen; einen neuen Sitz befestigen', fr: 'Accepter la perte pour l\'instant ; fortifier un nouveau siège' },
  imp_crisis_blockade_title: { en: 'Trade routes severed', es: 'Rutas comerciales cortadas', ru: 'Торговые пути перерезаны', mk: 'Трговските патишта се пресечени', de: 'Handelswege unterbrochen', fr: 'Routes commerciales coupées' },
  imp_crisis_blockade_body: { en: 'Enemy control of {territory} chokes the caravans. Supply costs rise until the corridor is reopened.', es: 'El control enemigo de {territory} estrangula las caravanas. Los costes de suministro suben hasta reabrir el corredor.', ru: 'Вражеский контроль над {territory} душит караваны. Снабжение дорожает, пока коридор не открыт вновь.', mk: 'Непријателската контрола над {territory} ги дави карваните. Трошоците за снабдување растат додека коридорот не се отвори.', de: 'Feindliche Kontrolle über {territory} erstickt die Karawanen. Die Versorgungskosten steigen, bis der Korridor wieder offen ist.', fr: 'Le contrôle ennemi de {territory} étrangle les caravanes. Les coûts de ravitaillement grimpent jusqu\'à la réouverture du corridor.' },
  imp_crisis_blockade_opt_reroute: { en: 'Reroute through the mountains (slower, safe)', es: 'Desvía por las montañas (más lento, seguro)', ru: 'Пустить обозы через горы (медленно, но надёжно)', mk: 'Пренасочи преку планините (побавно, безбедно)', de: 'Über die Berge umleiten (langsamer, sicher)', fr: 'Détourner par les montagnes (plus lent, sûr)' },
  imp_crisis_blockade_opt_convoy: { en: 'Run armed convoys (risk skirmishes)', es: 'Envía convoyes armados (riesgo de escaramuzas)', ru: 'Отправить вооружённые конвои (риск стычек)', mk: 'Прати вооружени конвои (ризик од судири)', de: 'Bewaffnete Konvois einsetzen (Gefechtsrisiko)', fr: 'Lancer des convois armés (risque d\'escarmouches)' },
  imp_crisis_coup_title: { en: 'Conspiracy in the war camp', es: 'Conspiración en el campamento', ru: 'Заговор в военном лагере', mk: 'Заговор во воениот логор', de: 'Verschwörung im Feldlager', fr: 'Conspiration dans le camp' },
  imp_crisis_coup_body: { en: 'Two lost battles and a starving army: your officers whisper of a new commander. Act before the whisper becomes a shout.', es: 'Dos batallas perdidas y un ejército hambriento: tus oficiales murmuran sobre un nuevo comandante. Actúa antes de que el murmullo sea un grito.', ru: 'Два поражения и голодающая армия: офицеры шепчутся о новом командующем. Действуйте, пока шёпот не стал криком.', mk: 'Две изгубени битки и гладна војска: твоите офицери шепотат за нов командант. Дејствувај пред шепотот да стане крик.', de: 'Zwei verlorene Schlachten und ein hungerndes Heer: Ihre Offiziere flüstern von einem neuen Befehlshaber. Handeln Sie, ehe aus Flüstern Rufe werden.', fr: 'Deux batailles perdues et une armée affamée : vos officiers murmurent le nom d\'un nouveau commandant. Agissez avant que le murmure ne devienne un cri.' },
  imp_crisis_coup_opt_purge: { en: 'Purge the ringleaders (-morale now, +discipline later)', es: 'Purga a los cabecillas (-moral ahora, +disciplina después)', ru: 'Устранить зачинщиков (-дух сейчас, +дисциплина потом)', mk: 'Исчисти ги водачите (-морал сега, +дисциплина потоа)', de: 'Die Rädelsführer beseitigen (-Moral jetzt, +Disziplin später)', fr: 'Purger les meneurs (-moral maintenant, +discipline ensuite)' },
  imp_crisis_coup_opt_concede: { en: 'Share command with the faction (-authority, +morale)', es: 'Comparte el mando con la facción (-autoridad, +moral)', ru: 'Разделить командование (-власть, +дух)', mk: 'Сподели ја командата (-авторитет, +морал)', de: 'Das Kommando teilen (-Autorität, +Moral)', fr: 'Partager le commandement (-autorité, +moral)' },
  imp_crisis_isolated_title: { en: 'Army cut off!', es: '¡Ejército aislado!', ru: 'Армия отрезана!', mk: 'Војската е отсечена!', de: 'Armee abgeschnitten!', fr: 'Armée isolée !' },
  imp_crisis_isolated_body: { en: 'The corridor to {territory} is severed. Attrition compounds every turn the pocket holds.', es: 'El corredor hacia {territory} está cortado. El desgaste se agrava cada turno que dure la bolsa.', ru: 'Коридор к {territory} перерезан. Потери нарастают с каждым ходом в котле.', mk: 'Коридорот кон {territory} е пресечен. Загубите се засилуваат секој потег во џебот.', de: 'Der Korridor nach {territory} ist durchtrennt. Die Verluste wachsen mit jeder Runde im Kessel.', fr: 'Le corridor vers {territory} est coupé. L\'attrition s\'aggrave à chaque tour dans la poche.' },
  // ── UI strings ──
  imp_title: { en: 'Chronos Imperium', es: 'Chronos Imperium', ru: 'Chronos Imperium', mk: 'Chronos Imperium', de: 'Chronos Imperium', fr: 'Chronos Imperium' },
  imp_subtitle: { en: 'Strategic conquest over the living map — logistics, tactics, and history in one campaign', es: 'Conquista estratégica sobre el mapa vivo: logística, táctica e historia en una campaña', ru: 'Стратегическое завоевание на живой карте — логистика, тактика и история в одной кампании', mk: 'Стратегиско освојување на живата карта — логистика, тактика и историја во една кампања', de: 'Strategische Eroberung auf der lebenden Karte — Logistik, Taktik und Geschichte in einem Feldzug', fr: 'Conquête stratégique sur la carte vivante — logistique, tactique et histoire en une campagne' },
  imp_gate: { en: 'Chronos Imperium is a Master Student exclusive: a full strategic-tactical campaign over the real historical map.', es: 'Chronos Imperium es exclusivo de Master Student: una campaña estratégico-táctica completa sobre el mapa histórico real.', ru: 'Chronos Imperium — эксклюзив Master Student: полная стратегико-тактическая кампания на реальной исторической карте.', mk: 'Chronos Imperium е ексклузивен за Master Student: целосна стратегиско-тактичка кампања на вистинската историска карта.', de: 'Chronos Imperium ist exklusiv für Master Student: ein vollständiger strategisch-taktischer Feldzug auf der realen historischen Karte.', fr: 'Chronos Imperium est une exclusivité Master Student : une campagne stratégico-tactique complète sur la vraie carte historique.' },
  imp_new_campaign: { en: 'New campaign', es: 'Nueva campaña', ru: 'Новая кампания', mk: 'Нова кампања', de: 'Neuer Feldzug', fr: 'Nouvelle campagne' },
  imp_theatre: { en: 'Theatre', es: 'Teatro', ru: 'Театр', mk: 'Театар', de: 'Kriegsschauplatz', fr: 'Théâtre' },
  imp_turn: { en: 'Turn', es: 'Turno', ru: 'Ход', mk: 'Потег', de: 'Runde', fr: 'Tour' },
  imp_end_turn: { en: 'End turn', es: 'Terminar turno', ru: 'Завершить ход', mk: 'Заврши потег', de: 'Runde beenden', fr: 'Fin du tour' },
  imp_your_armies: { en: 'Your armies', es: 'Tus ejércitos', ru: 'Ваши армии', mk: 'Твоите војски', de: 'Deine Armeen', fr: 'Tes armées' },
  imp_march_to: { en: 'March to…', es: 'Marchar a…', ru: 'Марш на…', mk: 'Марширај кон…', de: 'Marschieren nach…', fr: 'Marcher vers…' },
  imp_supplied: { en: 'Supplied', es: 'Abastecido', ru: 'Снабжается', mk: 'Снабдена', de: 'Versorgt', fr: 'Ravitaillée' },
  imp_isolated: { en: 'ISOLATED', es: 'AISLADO', ru: 'ОТРЕЗАНА', mk: 'ОТСЕЧЕНА', de: 'ABGESCHNITTEN', fr: 'ISOLÉE' },
  imp_strength: { en: 'Strength', es: 'Fuerza', ru: 'Сила', mk: 'Сила', de: 'Stärke', fr: 'Force' },
  imp_morale: { en: 'Morale', es: 'Moral', ru: 'Боевой дух', mk: 'Морал', de: 'Moral', fr: 'Moral' },
  imp_battle: { en: 'Battle', es: 'Batalla', ru: 'Сражение', mk: 'Битка', de: 'Schlacht', fr: 'Bataille' },
  imp_victory: { en: 'Victory!', es: '¡Victoria!', ru: 'Победа!', mk: 'Победа!', de: 'Sieg!', fr: 'Victoire !' },
  imp_defeat: { en: 'Defeat', es: 'Derrota', ru: 'Поражение', mk: 'Пораз', de: 'Niederlage', fr: 'Défaite' },
  imp_campaign_won: { en: 'The theatre is yours — every rival territory has fallen.', es: 'El teatro es tuyo: todos los territorios rivales han caído.', ru: 'Театр ваш — все территории соперника пали.', mk: 'Театарот е твој — сите ривалски територии паднаа.', de: 'Der Kriegsschauplatz gehört dir — jedes gegnerische Gebiet ist gefallen.', fr: 'Le théâtre est à toi — tous les territoires rivaux sont tombés.' },
  imp_campaign_lost: { en: 'Your realm has fallen. History will remember the attempt.', es: 'Tu reino ha caído. La historia recordará el intento.', ru: 'Ваша держава пала. История запомнит попытку.', mk: 'Твоето царство падна. Историјата ќе го памети обидот.', de: 'Dein Reich ist gefallen. Die Geschichte wird den Versuch erinnern.', fr: 'Ton royaume est tombé. L\'histoire retiendra la tentative.' },
  imp_rollback: { en: 'Rewind to turn', es: 'Rebobinar al turno', ru: 'Откатить к ходу', mk: 'Врати на потег', de: 'Zurück zu Runde', fr: 'Revenir au tour' },
  imp_weather: { en: 'Weather', es: 'Clima', ru: 'Погода', mk: 'Време', de: 'Wetter', fr: 'Météo' },
  imp_weather_clear: { en: 'Clear', es: 'Despejado', ru: 'Ясно', mk: 'Ведро', de: 'Klar', fr: 'Dégagé' },
  imp_weather_rain: { en: 'Rain', es: 'Lluvia', ru: 'Дождь', mk: 'Дожд', de: 'Regen', fr: 'Pluie' },
  imp_weather_storm: { en: 'Storm', es: 'Tormenta', ru: 'Буря', mk: 'Бура', de: 'Sturm', fr: 'Tempête' },
  imp_weather_heat: { en: 'Heat wave', es: 'Ola de calor', ru: 'Зной', mk: 'Горештина', de: 'Hitzewelle', fr: 'Canicule' },
  imp_weather_snow: { en: 'Snow', es: 'Nieve', ru: 'Снег', mk: 'Снег', de: 'Schnee', fr: 'Neige' },
  imp_log: { en: 'Campaign log', es: 'Diario de campaña', ru: 'Журнал кампании', mk: 'Дневник на кампањата', de: 'Feldzugstagebuch', fr: 'Journal de campagne' },
  imp_choose_tactic: { en: 'Choose your tactic', es: 'Elige tu táctica', ru: 'Выберите тактику', mk: 'Избери тактика', de: 'Wähle deine Taktik', fr: 'Choisis ta tactique' },
  imp_attrition_report: { en: '{army} lost {n} strength to attrition', es: '{army} perdió {n} de fuerza por desgaste', ru: '{army} потеряла {n} силы от истощения', mk: '{army} изгуби {n} сила од трошење', de: '{army} verlor {n} Stärke durch Abnutzung', fr: '{army} a perdu {n} de force par attrition' },
  imp_enemy_moves: { en: 'Enemy columns are moving', es: 'Las columnas enemigas se mueven', ru: 'Колонны противника выступили', mk: 'Непријателските колони се движат', de: 'Feindliche Kolonnen sind unterwegs', fr: 'Les colonnes ennemies se déplacent' },
  // ── Tactics ──
  imp_tactic_charge: { en: 'Charge', es: 'Carga', ru: 'Атака', mk: 'Јуриш', de: 'Sturmangriff', fr: 'Charge' },
  imp_tactic_volley: { en: 'Volley', es: 'Descarga', ru: 'Залп', mk: 'Салва', de: 'Salve', fr: 'Salve' },
  imp_tactic_hold: { en: 'Shield Wall', es: 'Muro de escudos', ru: 'Стена щитов', mk: 'Штитен ѕид', de: 'Schildwall', fr: 'Mur de boucliers' },
  imp_triangle_hint: { en: 'Charges break volleys · volleys break shield walls · shield walls break charges', es: 'Las cargas rompen descargas · las descargas rompen muros de escudos · los muros rompen cargas', ru: 'Атака бьёт залп · залп бьёт стену щитов · стена щитов бьёт атаку', mk: 'Јуришот ги крши салвите · салвите го кршат штитниот ѕид · штитниот ѕид го крши јуришот', de: 'Sturmangriffe schlagen Salven · Salven schlagen Schildwälle · Schildwälle schlagen Sturmangriffe', fr: 'La charge bat la salve · la salve bat le mur de boucliers · le mur de boucliers bat la charge' },
  // ── Clio's Tactical Read ──
  imp_read_title: { en: "Clio's Tactical Read", es: 'Lectura táctica de Clío', ru: 'Тактический разбор Клио', mk: 'Тактичко читање на Клио', de: 'Clios taktische Lesart', fr: 'Lecture tactique de Clio' },
  imp_read_vs: { en: 'vs the enemy doctrine', es: 'contra la doctrina enemiga', ru: 'против доктрины врага', mk: 'против непријателската доктрина', de: 'gegen die feindliche Doktrin', fr: 'contre la doctrine ennemie' },
  imp_read_beats: { en: 'beats', es: 'vence a', ru: 'бьёт', mk: 'победува', de: 'schlägt', fr: 'bat' },
  imp_read_loses: { en: 'loses to', es: 'pierde ante', ru: 'уступает', mk: 'губи од', de: 'unterliegt', fr: 'perd contre' },
  imp_read_headline_s: { en: 'Masterstroke — the field is yours to dictate.', es: 'Golpe maestro: el campo es tuyo.', ru: 'Мастерский ход — поле в вашей власти.', mk: 'Мајсторски потег — полето е твое.', de: 'Meisterstreich — das Feld gehorcht dir.', fr: 'Coup de maître — le terrain vous obéit.' },
  imp_read_headline_a: { en: 'Sound reasoning — the odds tilt your way.', es: 'Razonamiento sólido: las probabilidades te favorecen.', ru: 'Здравый расчёт — перевес на вашей стороне.', mk: 'Здраво расудување — предноста е на твоја страна.', de: 'Solides Kalkül — die Chancen neigen sich dir zu.', fr: 'Raisonnement solide — l’avantage penche vers vous.' },
  imp_read_headline_b: { en: 'Workable, but the edge is thin.', es: 'Viable, pero la ventaja es escasa.', ru: 'Приемлемо, но перевес невелик.', mk: 'Изводливо, но предноста е тенка.', de: 'Gangbar, doch der Vorsprung ist dünn.', fr: 'Jouable, mais l’avantage est mince.' },
  imp_read_headline_c: { en: 'Risky — you are fighting the ground and the enemy at once.', es: 'Arriesgado: luchas contra el terreno y el enemigo a la vez.', ru: 'Рискованно — вы бьётесь и с местностью, и с врагом.', mk: 'Ризично — се бориш и со теренот и со непријателот.', de: 'Riskant — du kämpfst gegen Gelände und Feind zugleich.', fr: 'Risqué — vous combattez le terrain et l’ennemi à la fois.' },
  imp_read_headline_d: { en: 'Reconsider — this plays straight into their strength.', es: 'Reconsidera: esto favorece justo su fuerza.', ru: 'Пересмотрите — это играет на их силу.', mk: 'Размисли повторно — ова оди право во нивната сила.', de: 'Überdenke es — das spielt genau ihrer Stärke zu.', fr: 'Reconsidérez — cela sert exactement leur force.' },
  imp_read_triangle_win: { en: 'Counters the enemy doctrine outright', es: 'Contrarresta de lleno la doctrina enemiga', ru: 'Прямо контрит доктрину врага', mk: 'Директно ја контрира непријателската доктрина', de: 'Kontert die feindliche Doktrin frontal', fr: 'Contre frontalement la doctrine ennemie' },
  imp_read_triangle_lose: { en: 'Walks into the enemy counter', es: 'Cae en el contraataque enemigo', ru: 'Попадает под контрудар врага', mk: 'Влегува во непријателскиот контранапад', de: 'Läuft in den feindlichen Konter', fr: 'Tombe dans le contre ennemi' },
  imp_read_triangle_mirror: { en: 'Mirror match — no doctrinal edge', es: 'Duelo en espejo: sin ventaja doctrinal', ru: 'Зеркальный бой — без доктринального перевеса', mk: 'Огледален дуел — без доктринарна предност', de: 'Spiegelduell — kein doktrinärer Vorteil', fr: 'Duel en miroir — aucun avantage doctrinal' },
  imp_read_charge_open: { en: 'Open ground gives cavalry room to build impetus', es: 'El terreno abierto da impulso a la caballería', ru: 'Открытое поле даёт коннице разгон', mk: 'Отворениот терен ѝ дава залет на коњицата', de: 'Offenes Gelände gibt der Reiterei Schwung', fr: 'Le terrain ouvert donne de l’élan à la cavalerie' },
  imp_read_charge_uphill: { en: 'Charging uphill blunts the impact', es: 'Cargar cuesta arriba mella el impacto', ru: 'Атака в гору гасит удар', mk: 'Јуриш нагоре го отапува ударот', de: 'Der Angriff bergauf bricht die Wucht', fr: 'Charger en côte émousse le choc' },
  imp_read_charge_river: { en: 'A river crossing scatters the charge', es: 'Cruzar un río dispersa la carga', ru: 'Переправа рассеивает атаку', mk: 'Преминот преку река го растура јуришот', de: 'Eine Flussüberquerung zersplittert den Angriff', fr: 'Une traversée de rivière disloque la charge' },
  imp_read_charge_broken: { en: 'Broken coastal ground slows the horse', es: 'El terreno costero irregular frena al caballo', ru: 'Изрезанный берег тормозит конницу', mk: 'Испресечениот брег го забавува коњот', de: 'Zerklüftetes Küstenland bremst die Pferde', fr: 'Le sol côtier accidenté freine les chevaux' },
  imp_read_volley_fields: { en: 'Clear fields give archers unbroken lanes of fire', es: 'Los campos despejados dan a los arqueros líneas de tiro', ru: 'Чистые поля дают лучникам линии огня', mk: 'Чистите полиња им даваат линии на оган на стрелците', de: 'Freie Felder geben Bogenschützen offene Schusslinien', fr: 'Les champs dégagés offrent aux archers des lignes de tir' },
  imp_read_volley_cover: { en: 'Mountain cover swallows the arrows', es: 'La cobertura montañosa se traga las flechas', ru: 'Горное укрытие поглощает стрелы', mk: 'Планинскиот заклон ги голта стрелите', de: 'Bergdeckung schluckt die Pfeile', fr: 'Le couvert montagneux avale les flèches' },
  imp_read_volley_rain: { en: 'Rain slackens the bowstrings', es: 'La lluvia afloja las cuerdas de los arcos', ru: 'Дождь ослабляет тетивы', mk: 'Дождот ги олабавува тетивите', de: 'Regen erschlafft die Bogensehnen', fr: 'La pluie détend les cordes d’arc' },
  imp_read_hold_highground: { en: 'A shield wall on high ground is near-unbreakable', es: 'Un muro de escudos en alto es casi inquebrantable', ru: 'Стена щитов на высоте почти несокрушима', mk: 'Штитен ѕид на висина е речиси непробоен', de: 'Ein Schildwall auf Höhe ist kaum zu brechen', fr: 'Un mur de boucliers en hauteur est presque incassable' },
  imp_read_hold_chokepoint: { en: 'The wall seals the river crossing like a plug', es: 'El muro sella el vado como un tapón', ru: 'Стена запирает переправу как пробка', mk: 'Ѕидот го затвора преминот како чеп', de: 'Der Wall verriegelt die Furt wie ein Pfropfen', fr: 'Le mur bouche le gué comme un bouchon' },
  imp_read_hold_exposed: { en: 'Standing still on open plain surrenders the initiative', es: 'Quedarse quieto en llano cede la iniciativa', ru: 'Стоять на равнине — отдать инициативу', mk: 'Да стоиш на рамнина значи да ја предадеш иницијативата', de: 'Stillstehen in der Ebene gibt die Initiative preis', fr: 'Rester immobile en plaine cède l’initiative' },
  imp_read_hold_weather: { en: 'A braced line weathers the storm better than a moving one', es: 'Una línea firme resiste la tormenta mejor que una en marcha', ru: 'Устойчивый строй лучше держит непогоду', mk: 'Зацврстена линија поарно ја издржува бурата', de: 'Eine gestemmte Linie trotzt dem Sturm besser', fr: 'Une ligne arc-boutée endure mieux la tempête' },
  imp_read_charge_heat: { en: 'Heat exhausts a galloping charge', es: 'El calor agota una carga al galope', ru: 'Жара изматывает конную атаку', mk: 'Горештината исцрпува галопирачки јуриш', de: 'Hitze erschöpft einen galoppierenden Angriff', fr: 'La chaleur épuise une charge au galop' },
  imp_read_charge_snow: { en: 'Snow founders the horses mid-charge', es: 'La nieve hunde a los caballos en plena carga', ru: 'Снег вязнет копыта на атаке', mk: 'Снегот ги заглавува коњите среде јуриш', de: 'Schnee lässt die Pferde im Angriff einbrechen', fr: 'La neige enlise les chevaux en pleine charge' },
  imp_read_leader_signature: { en: 'Plays to your marshal’s signature doctrine', es: 'Aprovecha la doctrina insignia de tu mariscal', ru: 'Играет на фирменную доктрину вашего маршала', mk: 'Игра на препознатливата доктрина на твојот маршал', de: 'Spielt der Signatur deines Marschalls zu', fr: 'Joue la doctrine de prédilection de votre maréchal' },
  imp_read_advises: { en: 'Clio advises', es: 'Clío aconseja', ru: 'Клио советует', mk: 'Клио советува', de: 'Clio rät', fr: 'Clio conseille' },
  imp_read_switch: { en: 'Switch to {tactic} — it counters their doctrine here.', es: 'Cambia a {tactic}: contrarresta su doctrina aquí.', ru: 'Смените на {tactic} — здесь это контрит их доктрину.', mk: 'Префрли на {tactic} — тука ја контрира нивната доктрина.', de: 'Wechsle zu {tactic} — es kontert hier ihre Doktrin.', fr: 'Passez à {tactic} — cela contre leur doctrine ici.' },
  imp_read_optimal: { en: 'This is the strongest read available here.', es: 'Es la mejor lectura disponible aquí.', ru: 'Это лучший расклад из возможных здесь.', mk: 'Ова е најсилното читање достапно тука.', de: 'Das ist die stärkste Lesart, die hier möglich ist.', fr: 'C’est la meilleure lecture possible ici.' },
  // ── Page chrome ──
  imp_setup_pick: { en: 'Choose your theatre of war', es: 'Elige tu teatro de guerra', ru: 'Выберите театр военных действий', mk: 'Избери го твојот воен театар', de: 'Wähle deinen Kriegsschauplatz', fr: 'Choisis ton théâtre de guerre' },
  imp_territories: { en: 'territories', es: 'territorios', ru: 'территорий', mk: 'територии', de: 'Gebiete', fr: 'territoires' },
  imp_resume: { en: 'Resume campaign', es: 'Reanudar campaña', ru: 'Продолжить кампанию', mk: 'Продолжи ја кампањата', de: 'Feldzug fortsetzen', fr: 'Reprendre la campagne' },
  imp_abandon: { en: 'Abandon', es: 'Abandonar', ru: 'Оставить', mk: 'Напушти', de: 'Aufgeben', fr: 'Abandonner' },
  imp_treasury: { en: 'Treasury', es: 'Tesoro', ru: 'Казна', mk: 'Трезор', de: 'Staatskasse', fr: 'Trésor' },
  imp_discipline: { en: 'Discipline', es: 'Disciplina', ru: 'Дисциплина', mk: 'Дисциплина', de: 'Disziplin', fr: 'Discipline' },
  imp_council: { en: 'War council', es: 'Consejo de guerra', ru: 'Военный совет', mk: 'Воен совет', de: 'Kriegsrat', fr: 'Conseil de guerre' },
  imp_crisis_council: { en: 'Crisis council', es: 'Consejo de crisis', ru: 'Кризисный совет', mk: 'Кризен совет', de: 'Krisenrat', fr: 'Conseil de crise' },
  imp_battle_report: { en: 'Battle report', es: 'Parte de batalla', ru: 'Донесение о сражении', mk: 'Извештај од битката', de: 'Gefechtsbericht', fr: 'Rapport de bataille' },
  imp_attacker: { en: 'Attacker', es: 'Atacante', ru: 'Атакующий', mk: 'Напаѓач', de: 'Angreifer', fr: 'Attaquant' },
  imp_defender: { en: 'Defender', es: 'Defensor', ru: 'Обороняющийся', mk: 'Бранител', de: 'Verteidiger', fr: 'Défenseur' },
  imp_modifiers: { en: 'Battle modifiers', es: 'Modificadores de batalla', ru: 'Модификаторы боя', mk: 'Модификатори на битката', de: 'Gefechtsmodifikatoren', fr: 'Modificateurs de bataille' },
  imp_continue: { en: 'Continue', es: 'Continuar', ru: 'Продолжить', mk: 'Продолжи', de: 'Weiter', fr: 'Continuer' },
  imp_select_hint: { en: 'Select an army, then tap a territory to order the march.', es: 'Selecciona un ejército y toca un territorio para ordenar la marcha.', ru: 'Выберите армию, затем коснитесь территории, чтобы отдать приказ о марше.', mk: 'Избери војска, па допри територија за да наредиш марш.', de: 'Wähle eine Armee und tippe dann auf ein Gebiet, um den Marsch zu befehlen.', fr: 'Sélectionne une armée, puis touche un territoire pour ordonner la marche.' },
  imp_supply_web: { en: 'Supply web', es: 'Red de suministro', ru: 'Сеть снабжения', mk: 'Мрежа за снабдување', de: 'Versorgungsnetz', fr: 'Réseau de ravitaillement' },
  imp_stalemate: { en: 'Stalemate', es: 'Empate', ru: 'Ничья', mk: 'Нерешено', de: 'Patt', fr: 'Impasse' },
  imp_routed: { en: 'Routed!', es: '¡En desbandada!', ru: 'Бегство!', mk: 'Разбиени!', de: 'Auf der Flucht!', fr: 'En déroute !' },
  imp_leader: { en: 'Commander', es: 'Comandante', ru: 'Полководец', mk: 'Командант', de: 'Feldherr', fr: 'Commandant' },
  imp_march_ordered: { en: 'March ordered', es: 'Marcha ordenada', ru: 'Марш назначен', mk: 'Маршот е нареден', de: 'Marschbefehl erteilt', fr: 'Marche ordonnée' },
  imp_marching: { en: 'Marching', es: 'En marcha', ru: 'На марше', mk: 'Во марш', de: 'Auf dem Marsch', fr: 'En marche' },
  imp_era_ancient: { en: 'Ancient World', es: 'Mundo antiguo', ru: 'Древний мир', mk: 'Античко време', de: 'Antike', fr: 'Monde antique' },
  imp_era_medieval: { en: 'Middle Ages', es: 'Edad Media', ru: 'Средневековье', mk: 'Среден век', de: 'Mittelalter', fr: 'Moyen Âge' },
  'imp_era_early-modern': { en: 'Early Modern', es: 'Edad Moderna', ru: 'Раннее Новое время', mk: 'Ран нов век', de: 'Frühe Neuzeit', fr: 'Époque moderne' },
  imp_era_modern: { en: 'Modern Era', es: 'Era contemporánea', ru: 'Новейшее время', mk: 'Модерна ера', de: 'Moderne', fr: 'Ère contemporaine' },
// ── Theatres ──
  imp_theatre_successors: { en: 'Wars of the Successors', es: 'Guerras de los sucesores', ru: 'Войны диадохов', mk: 'Војните на наследниците', de: 'Diadochenkriege', fr: 'Guerres des diadoques' },
  imp_theatre_successors_tag: { en: 'Alexander is dead. His marshals carve the world — 300 BCE.', es: 'Alejandro ha muerto. Sus mariscales se reparten el mundo — 300 a.C.', ru: 'Александр мёртв. Его полководцы делят мир — 300 г. до н.э.', mk: 'Александар е мртов. Неговите маршали го делат светот — 300 г.п.н.е.', de: 'Alexander ist tot. Seine Marschälle zerteilen die Welt — 300 v. Chr.', fr: 'Alexandre est mort. Ses maréchaux se partagent le monde — 300 av. J.-C.' },
  imp_theatre_crusades: { en: 'The Crusading Age', es: 'La era de las cruzadas', ru: 'Эпоха крестовых походов', mk: 'Ерата на крстоносните војни', de: 'Das Zeitalter der Kreuzzüge', fr: "L'âge des croisades" },
  imp_theatre_crusades_tag: { en: 'West and East collide across the whole Mediterranean — 1200 CE.', es: 'Occidente y Oriente chocan por todo el Mediterráneo — 1200 d.C.', ru: 'Запад и Восток сталкиваются по всему Средиземноморью — 1200 г.', mk: 'Западот и Истокот се судираат низ целиот Медитеран — 1200 г.', de: 'West und Ost prallen im ganzen Mittelmeerraum aufeinander — 1200 n. Chr.', fr: "L'Occident et l'Orient s'affrontent sur toute la Méditerranée — 1200." },
  imp_theatre_kings: { en: 'The Age of Kings', es: 'La era de los reyes', ru: 'Век королей', mk: 'Ерата на кралевите', de: 'Das Zeitalter der Könige', fr: "L'âge des rois" },
  imp_theatre_kings_tag: { en: 'Absolute monarchs and standing armies contest Europe — 1700 CE.', es: 'Monarcas absolutos y ejércitos permanentes se disputan Europa — 1700 d.C.', ru: 'Абсолютные монархи и постоянные армии борются за Европу — 1700 г.', mk: 'Апсолутни монарси и постојани војски се борат за Европа — 1700 г.', de: 'Absolute Monarchen und stehende Heere ringen um Europa — 1700 n. Chr.', fr: "Monarques absolus et armées permanentes se disputent l'Europe — 1700." },
  imp_theatre_napoleonic: { en: 'The Napoleonic World', es: 'El mundo napoleónico', ru: 'Наполеоновский мир', mk: 'Наполеоновиот свет', de: 'Die napoleonische Welt', fr: 'Le monde napoléonien' },
  imp_theatre_napoleonic_tag: { en: 'One empire against a continent in coalition — 1815 CE.', es: 'Un imperio contra un continente en coalición — 1815 d.C.', ru: 'Одна империя против континента в коалиции — 1815 г.', mk: 'Една империја против континент во коалиција — 1815 г.', de: 'Ein Kaiserreich gegen einen Kontinent in Koalition — 1815 n. Chr.', fr: 'Un empire contre un continent coalisé — 1815.' },
  // ── Factions ──
  imp_faction_antigonid: { en: 'League of Antigonus', es: 'Liga de Antígono', ru: 'Лига Антигона', mk: 'Лигата на Антигон', de: 'Bund des Antigonos', fr: "Ligue d'Antigone" },
  imp_faction_seleucid: { en: 'Empire of Seleucus', es: 'Imperio de Seleuco', ru: 'Держава Селевка', mk: 'Империјата на Селевк', de: 'Reich des Seleukos', fr: 'Empire de Séleucos' },
  imp_faction_crusaders: { en: 'The Crusader Kingdoms', es: 'Los reinos cruzados', ru: 'Королевства крестоносцев', mk: 'Крстоносните кралства', de: 'Die Kreuzfahrerreiche', fr: 'Les royaumes croisés' },
  imp_faction_caliphates: { en: 'The Caliphates', es: 'Los califatos', ru: 'Халифаты', mk: 'Калифатите', de: 'Die Kalifate', fr: 'Les califats' },
  imp_faction_bourbon: { en: 'The Bourbon Powers', es: 'Las potencias borbónicas', ru: 'Бурбонские державы', mk: 'Бурбонските сили', de: 'Die bourbonischen Mächte', fr: 'Les puissances Bourbon' },
  imp_faction_eastern: { en: 'The Eastern Crowns', es: 'Las coronas del este', ru: 'Восточные короны', mk: 'Источните круни', de: 'Die östlichen Kronen', fr: "Les couronnes de l'Est" },
  imp_faction_french: { en: 'The French Empire', es: 'El Imperio francés', ru: 'Французская империя', mk: 'Француската империја', de: 'Das französische Kaiserreich', fr: "L'Empire français" },
  imp_faction_coalition: { en: 'The Coalition', es: 'La Coalición', ru: 'Коалиция', mk: 'Коалицијата', de: 'Die Koalition', fr: 'La Coalition' },
  // ── Provinces: Successors ──
  imp_prov_antigonus: { en: 'Kingdom of Antigonus', es: 'Reino de Antígono', ru: 'Царство Антигона', mk: 'Кралство на Антигон', de: 'Reich des Antigonos', fr: "Royaume d'Antigone" },
  imp_prov_kassander: { en: 'Macedon of Kassander', es: 'Macedonia de Casandro', ru: 'Македония Кассандра', mk: 'Македонија на Касандар', de: 'Makedonien des Kassander', fr: 'Macédoine de Cassandre' },
  imp_prov_lysimachus: { en: 'Thrace of Lysimachus', es: 'Tracia de Lisímaco', ru: 'Фракия Лисимаха', mk: 'Тракија на Лизимах', de: 'Thrakien des Lysimachos', fr: 'Thrace de Lysimaque' },
  'imp_prov_greek-poleis': { en: 'Greek City-States', es: 'Ciudades-estado griegas', ru: 'Греческие полисы', mk: 'Грчките градови-држави', de: 'Griechische Stadtstaaten', fr: 'Cités grecques' },
  imp_prov_seleucid: { en: 'Seleucid Kingdom', es: 'Reino seléucida', ru: 'Царство Селевкидов', mk: 'Селевкидско кралство', de: 'Seleukidenreich', fr: 'Royaume séleucide' },
  imp_prov_ptolemaic: { en: 'Ptolemaic Egypt', es: 'Egipto ptolemaico', ru: 'Птолемеевский Египет', mk: 'Птолемејски Египет', de: 'Ptolemäisches Ägypten', fr: 'Égypte ptolémaïque' },
  imp_prov_cappadocia: { en: 'Cappadocia', es: 'Capadocia', ru: 'Каппадокия', mk: 'Кападокија', de: 'Kappadokien', fr: 'Cappadoce' },
  imp_prov_armenia: { en: 'Armenia', es: 'Armenia', ru: 'Армения', mk: 'Ерменија', de: 'Armenien', fr: 'Arménie' },
  imp_prov_nabatea: { en: 'Nabatean Kingdom', es: 'Reino nabateo', ru: 'Набатейское царство', mk: 'Набатејско кралство', de: 'Nabatäerreich', fr: 'Royaume nabatéen' },
  imp_prov_bithynia: { en: 'Bithynia', es: 'Bitinia', ru: 'Вифиния', mk: 'Витинија', de: 'Bithynien', fr: 'Bithynie' },
  // ── Provinces: Crusades ──
  imp_prov_hre: { en: 'Holy Roman Empire', es: 'Sacro Imperio', ru: 'Священная Римская империя', mk: 'Свето Римско Царство', de: 'Heiliges Römisches Reich', fr: 'Saint-Empire' },
  imp_prov_france: { en: 'Kingdom of France', es: 'Reino de Francia', ru: 'Королевство Франция', mk: 'Кралство Франција', de: 'Königreich Frankreich', fr: 'Royaume de France' },
  imp_prov_angevin: { en: 'Angevin Empire', es: 'Imperio angevino', ru: 'Анжуйская держава', mk: 'Анжуска империја', de: 'Angevinisches Reich', fr: 'Empire Plantagenêt' },
  imp_prov_hungary: { en: 'Kingdom of Hungary', es: 'Reino de Hungría', ru: 'Королевство Венгрия', mk: 'Кралство Унгарија', de: 'Königreich Ungarn', fr: 'Royaume de Hongrie' },
  imp_prov_poland: { en: 'Duchy of Poland', es: 'Ducado de Polonia', ru: 'Польское княжество', mk: 'Војводство Полска', de: 'Herzogtum Polen', fr: 'Duché de Pologne' },
  imp_prov_byzantium: { en: 'Byzantine Empire', es: 'Imperio bizantino', ru: 'Византийская империя', mk: 'Византиска империја', de: 'Byzantinisches Reich', fr: 'Empire byzantin' },
  imp_prov_cyprus: { en: 'Cyprus', es: 'Chipre', ru: 'Кипр', mk: 'Кипар', de: 'Zypern', fr: 'Chypre' },
  imp_prov_georgia: { en: 'Kingdom of Georgia', es: 'Reino de Georgia', ru: 'Грузинское царство', mk: 'Кралство Грузија', de: 'Königreich Georgien', fr: 'Royaume de Géorgie' },
  imp_prov_fatimid: { en: 'Fatimid Caliphate', es: 'Califato fatimí', ru: 'Фатимидский халифат', mk: 'Фатимидски калифат', de: 'Fatimiden-Kalifat', fr: 'Califat fatimide' },
  imp_prov_almohad: { en: 'Almohad Caliphate', es: 'Califato almohade', ru: 'Альмохадский халифат', mk: 'Алмохадски калифат', de: 'Almohaden-Kalifat', fr: 'Califat almohade' },
  // ── Provinces: Age of Kings ──
  'imp_prov_france-1700': { en: 'Kingdom of France', es: 'Reino de Francia', ru: 'Королевство Франция', mk: 'Кралство Франција', de: 'Königreich Frankreich', fr: 'Royaume de France' },
  'imp_prov_spain-1700': { en: 'Kingdom of Spain', es: 'Reino de España', ru: 'Королевство Испания', mk: 'Кралство Шпанија', de: 'Königreich Spanien', fr: "Royaume d'Espagne" },
  'imp_prov_england-1700': { en: 'England & Ireland', es: 'Inglaterra e Irlanda', ru: 'Англия и Ирландия', mk: 'Англија и Ирска', de: 'England & Irland', fr: 'Angleterre et Irlande' },
  'imp_prov_hre-1700': { en: 'Holy Roman Empire', es: 'Sacro Imperio', ru: 'Священная Римская империя', mk: 'Свето Римско Царство', de: 'Heiliges Römisches Reich', fr: 'Saint-Empire' },
  'imp_prov_austria-1700': { en: 'Austrian Monarchy', es: 'Monarquía austriaca', ru: 'Австрийская монархия', mk: 'Австриска монархија', de: 'Österreichische Monarchie', fr: "Monarchie d'Autriche" },
  'imp_prov_ottoman-1700': { en: 'Ottoman Empire', es: 'Imperio otomano', ru: 'Османская империя', mk: 'Отоманска империја', de: 'Osmanisches Reich', fr: 'Empire ottoman' },
  'imp_prov_sweden-1700': { en: 'Swedish Empire', es: 'Imperio sueco', ru: 'Шведская империя', mk: 'Шведска империја', de: 'Schwedisches Reich', fr: 'Empire suédois' },
  'imp_prov_plc-1700': { en: 'Poland–Lithuania', es: 'Polonia-Lituania', ru: 'Речь Посполитая', mk: 'Полска-Литванија', de: 'Polen-Litauen', fr: 'Pologne-Lituanie' },
  'imp_prov_muscovy-1700': { en: 'Tsardom of Russia', es: 'Zarato ruso', ru: 'Русское царство', mk: 'Руско царство', de: 'Zarentum Russland', fr: 'Tsarat de Russie' },
  'imp_prov_denmark-1700': { en: 'Denmark–Norway', es: 'Dinamarca-Noruega', ru: 'Дания-Норвегия', mk: 'Данска-Норвешка', de: 'Dänemark-Norwegen', fr: 'Danemark-Norvège' },
  // ── Provinces: Napoleonic ──
  'imp_prov_france-1815': { en: 'French Empire', es: 'Imperio francés', ru: 'Французская империя', mk: 'Француска империја', de: 'Französisches Kaiserreich', fr: 'Empire français' },
  'imp_prov_spain-1815': { en: 'Kingdom of Spain', es: 'Reino de España', ru: 'Королевство Испания', mk: 'Кралство Шпанија', de: 'Königreich Spanien', fr: "Royaume d'Espagne" },
  imp_prov_switzerland: { en: 'Switzerland', es: 'Suiza', ru: 'Швейцария', mk: 'Швајцарија', de: 'Schweiz', fr: 'Suisse' },
  'imp_prov_two-sicilies': { en: 'Two Sicilies', es: 'Dos Sicilias', ru: 'Королевство Обеих Сицилий', mk: 'Двете Сицилии', de: 'Königreich beider Sizilien', fr: 'Deux-Siciles' },
  imp_prov_sardinia: { en: 'Piedmont-Sardinia', es: 'Piamonte-Cerdeña', ru: 'Сардинское королевство', mk: 'Пиемонт-Сардинија', de: 'Piemont-Sardinien', fr: 'Piémont-Sardaigne' },
  'imp_prov_uk-1815': { en: 'United Kingdom', es: 'Reino Unido', ru: 'Соединённое Королевство', mk: 'Обединето Кралство', de: 'Vereinigtes Königreich', fr: 'Royaume-Uni' },
  imp_prov_prussia: { en: 'Kingdom of Prussia', es: 'Reino de Prusia', ru: 'Королевство Пруссия', mk: 'Кралство Прусија', de: 'Königreich Preußen', fr: 'Royaume de Prusse' },
  'imp_prov_austria-1815': { en: 'Austrian Empire', es: 'Imperio austriaco', ru: 'Австрийская империя', mk: 'Австриска империја', de: 'Kaisertum Österreich', fr: "Empire d'Autriche" },
  'imp_prov_russia-1815': { en: 'Russian Empire', es: 'Imperio ruso', ru: 'Российская империя', mk: 'Руска империја', de: 'Russisches Kaiserreich', fr: 'Empire russe' },
  'imp_prov_ottoman-1815': { en: 'Ottoman Empire', es: 'Imperio otomano', ru: 'Османская империя', mk: 'Отоманска империја', de: 'Osmanisches Reich', fr: 'Empire ottoman' },
  // ── Clarity UI ──
  imp_army_name: { en: '{n} Army', es: '{n} Ejército', ru: '{n}-я армия', mk: '{n} армија', de: '{n}. Armee', fr: '{n} armée' },
  imp_objective: { en: 'Objective: conquer every rival province', es: 'Objetivo: conquista todas las provincias rivales', ru: 'Цель: захватить все провинции соперника', mk: 'Цел: освои ги сите ривалски провинции', de: 'Ziel: erobere jede gegnerische Provinz', fr: 'Objectif : conquérir toutes les provinces rivales' },
  imp_provinces_held: { en: 'provinces held', es: 'provincias en tu poder', ru: 'провинций под контролем', mk: 'провинции под контрола', de: 'Provinzen gehalten', fr: 'provinces tenues' },
  imp_at: { en: 'at', es: 'en', ru: 'в', mk: 'во', de: 'bei', fr: 'à' },
  imp_neutral: { en: 'Neutral', es: 'Neutral', ru: 'Нейтральная', mk: 'Неутрална', de: 'Neutral', fr: 'Neutre' },
  imp_capital: { en: 'Capital', es: 'Capital', ru: 'Столица', mk: 'Престолнина', de: 'Hauptstadt', fr: 'Capitale' },
  imp_help: { en: 'How to play', es: 'Cómo se juega', ru: 'Как играть', mk: 'Како се игра', de: 'Spielanleitung', fr: 'Comment jouer' },
  imp_tut_1_t: { en: '1 · Command your armies', es: '1 · Comanda tus ejércitos', ru: '1 · Командуйте армиями', mk: '1 · Командувај со војските', de: '1 · Befehlige deine Armeen', fr: '1 · Commande tes armées' },
  imp_tut_1_b: { en: 'Tap one of your gold armies, then tap any province to order a march. The dashed line shows the exact route it will take.', es: 'Toca uno de tus ejércitos dorados y luego una provincia para ordenar la marcha. La línea discontinua muestra la ruta exacta.', ru: 'Нажмите на свою золотую армию, затем на провинцию — армия выступит. Пунктир показывает точный маршрут.', mk: 'Допри една од твоите златни војски, па допри провинција за марш. Испрекинатата линија го покажува точниот пат.', de: 'Tippe auf eine deiner goldenen Armeen und dann auf eine Provinz, um den Marsch zu befehlen. Die gestrichelte Linie zeigt die genaue Route.', fr: "Touche une de tes armées dorées, puis une province pour ordonner la marche. La ligne pointillée montre l'itinéraire exact." },
  imp_tut_2_t: { en: '2 · Pick a tactic', es: '2 · Elige una táctica', ru: '2 · Выберите тактику', mk: '2 · Избери тактика', de: '2 · Wähle eine Taktik', fr: '2 · Choisis une tactique' },
  imp_tut_2_b: { en: 'Charge beats Volley, Volley beats Shield Wall, Shield Wall beats Charge. Your tactic applies to every battle this turn.', es: 'La carga vence a la descarga, la descarga al muro de escudos y el muro a la carga. Tu táctica se aplica a todas las batallas del turno.', ru: 'Атака бьёт залп, залп бьёт стену щитов, стена щитов бьёт атаку. Тактика действует во всех битвах хода.', mk: 'Јуришот победува салва, салвата штитен ѕид, а ѕидот јуриш. Тактиката важи за секоја битка овој потег.', de: 'Sturmangriff schlägt Salve, Salve schlägt Schildwall, Schildwall schlägt Sturmangriff. Deine Taktik gilt für jede Schlacht dieser Runde.', fr: 'La charge bat la salve, la salve bat le mur de boucliers, le mur bat la charge. Ta tactique vaut pour chaque bataille du tour.' },
  imp_tut_3_t: { en: '3 · Guard your supply lines', es: '3 · Protege tus suministros', ru: '3 · Берегите снабжение', mk: '3 · Чувај го снабдувањето', de: '3 · Sichere deinen Nachschub', fr: '3 · Protège ton ravitaillement' },
  imp_tut_3_b: { en: 'Armies must trace a friendly path back to your capital. If the enemy cuts it, they starve — losses compound every turn.', es: 'Los ejércitos deben trazar un camino amigo hasta tu capital. Si el enemigo lo corta, pasan hambre — las pérdidas se agravan cada turno.', ru: 'Армии должны иметь дружественный путь к столице. Если враг его перережет — начнётся голод, и потери будут расти с каждым ходом.', mk: 'Војските мора да имаат пријателски пат до престолнината. Ако непријателот го пресече, гладуваат — загубите растат секој потег.', de: 'Armeen brauchen einen freundlichen Weg zurück zur Hauptstadt. Kappt ihn der Feind, hungern sie — die Verluste wachsen jede Runde.', fr: "Les armées doivent garder un chemin ami vers ta capitale. Si l'ennemi le coupe, elles meurent de faim — les pertes s'aggravent chaque tour." },
  imp_tut_4_t: { en: '4 · Take every rival province', es: '4 · Toma todas las provincias rivales', ru: '4 · Захватите все провинции врага', mk: '4 · Земи ги сите ривалски провинции', de: '4 · Nimm jede gegnerische Provinz', fr: '4 · Prends toutes les provinces rivales' },
  imp_tut_4_b: { en: 'March into neutral provinces to claim them freely. Win the campaign by holding everything your rival started with — and beware crises along the way.', es: 'Entra en provincias neutrales para reclamarlas sin lucha. Gana la campaña controlando todo lo que tu rival tenía al empezar — y cuidado con las crisis por el camino.', ru: 'Нейтральные провинции занимаются без боя. Победа — когда всё, с чем начинал соперник, ваше. И берегитесь кризисов по пути.', mk: 'Влези во неутрални провинции за да ги заземеш слободно. Победи ја кампањата држејќи сè со што почна ривалот — и внимавај на кризите попат.', de: 'Marschiere in neutrale Provinzen, um sie kampflos zu beanspruchen. Gewinne den Feldzug, indem du alles hältst, womit dein Rivale begann — und hüte dich vor Krisen.', fr: 'Entre dans les provinces neutres pour les prendre sans combat. Gagne la campagne en tenant tout ce que possédait ton rival — et gare aux crises en chemin.' },
  imp_got_it: { en: 'To battle!', es: '¡A la batalla!', ru: 'В бой!', mk: 'Во битка!', de: 'In die Schlacht!', fr: 'Au combat !' },
  imp_battlefield: { en: 'Battlefield', es: 'Campo de batalla', ru: 'Поле боя', mk: 'Бојно поле', de: 'Schlachtfeld', fr: 'Champ de bataille' },
  imp_new_here: { en: 'A new campaign will open on this theatre\'s living map.', es: 'Una nueva campaña se abrirá sobre el mapa vivo de este teatro.', ru: 'Новая кампания развернётся на живой карте этого театра.', mk: 'Нова кампања ќе се отвори на живата карта на овој театар.', de: 'Ein neuer Feldzug beginnt auf der lebenden Karte dieses Schauplatzes.', fr: 'Une nouvelle campagne s\'ouvrira sur la carte vivante de ce théâtre.' },
  // ── On-map battle theatre ──
  imp_theater_clash: { en: 'Clash at {territory}', es: 'Choque en {territory}', ru: 'Столкновение у {territory}', mk: 'Судир кај {territory}', de: 'Zusammenstoß bei {territory}', fr: 'Choc à {territory}' },
  imp_theater_round: { en: 'Round', es: 'Ronda', ru: 'Раунд', mk: 'Рунда', de: 'Runde', fr: 'Manche' },
  imp_theater_you: { en: 'You', es: 'Tú', ru: 'Вы', mk: 'Ти', de: 'Du', fr: 'Vous' },
  imp_theater_enemy: { en: 'Enemy', es: 'Enemigo', ru: 'Враг', mk: 'Непријател', de: 'Feind', fr: 'Ennemi' },
  imp_theater_your_move: { en: 'Your move', es: 'Tu jugada', ru: 'Ваш ход', mk: 'Твојот потег', de: 'Dein Zug', fr: 'Votre choix' },
  imp_theater_grading: { en: 'Clio grades your move', es: 'Clío califica tu jugada', ru: 'Клио оценивает ваш ход', mk: 'Клио го оценува твојот потег', de: 'Clio benotet deinen Zug', fr: 'Clio note votre choix' },
  imp_theater_skip: { en: 'Skip', es: 'Saltar', ru: 'Пропустить', mk: 'Прескокни', de: 'Überspringen', fr: 'Passer' },
  imp_theater_replay3d: { en: '3D replay', es: 'Repetición 3D', ru: '3D-повтор', mk: '3D повтор', de: '3D-Wiederholung', fr: 'Rejeu 3D' },
  imp_theater_next: { en: 'Next battle', es: 'Siguiente batalla', ru: 'Следующая битва', mk: 'Следна битка', de: 'Nächste Schlacht', fr: 'Bataille suivante' },
  imp_theater_you_win: { en: 'You hold the field', es: 'Dominas el campo', ru: 'Поле за вами', mk: 'Полето е твое', de: 'Du hältst das Feld', fr: 'Vous tenez le terrain' },
  imp_theater_you_lose: { en: 'Your line is broken', es: 'Tu línea se rompe', ru: 'Ваш строй сломлен', mk: 'Твојата линија е скршена', de: 'Deine Linie ist gebrochen', fr: 'Votre ligne est brisée' },
  imp_theater_draw: { en: 'A bloody stalemate', es: 'Un empate sangriento', ru: 'Кровавая ничья', mk: 'Крваво нерешено', de: 'Ein blutiges Patt', fr: 'Une impasse sanglante' },
  imp_clio_open: { en: 'Clio watches the lines close…', es: 'Clío observa cómo se cierran las líneas…', ru: 'Клио следит, как сходятся строи…', mk: 'Клио гледа како се спојуваат линиите…', de: 'Clio beobachtet, wie die Linien sich schließen…', fr: 'Clio observe les lignes se refermer…' },
  imp_clio_shatter_enemy: { en: 'Their line cracks — your read is paying off.', es: 'Su línea se agrieta: tu lectura da frutos.', ru: 'Их строй трещит — ваш расчёт оправдывается.', mk: 'Нивната линија пука — твоето читање се исплати.', de: 'Ihre Linie bricht — deine Lesart zahlt sich aus.', fr: 'Leur ligne se fissure — votre lecture porte ses fruits.' },
  imp_clio_shatter_you: { en: 'You are paying in blood for this ground.', es: 'Pagas con sangre este terreno.', ru: 'Вы платите кровью за эту землю.', mk: 'Плаќаш со крв за оваа земја.', de: 'Du bezahlst dieses Feld mit Blut.', fr: 'Vous payez ce terrain de votre sang.' },
  imp_clio_rout_enemy: { en: 'They break and run — textbook execution.', es: 'Se rompen y huyen: ejecución de manual.', ru: 'Они бегут — образцовое исполнение.', mk: 'Тие се кршат и бегаат — учебничко изведување.', de: 'Sie brechen und fliehen — mustergültig ausgeführt.', fr: 'Ils rompent et fuient — exécution de manuel.' },
  imp_clio_rout_you: { en: 'Your men rout — the counter was misjudged.', es: 'Tus hombres huyen: erraste el contraataque.', ru: 'Ваши бегут — контрманёвр был выбран неверно.', mk: 'Твоите луѓе бегаат — контрата беше погрешно проценета.', de: 'Deine Männer fliehen — der Konter war falsch gewählt.', fr: 'Vos hommes fuient — le contre a été mal jugé.' },
  imp_clio_waver_enemy: { en: 'Enemy resolve is wavering — press it.', es: 'La moral enemiga flaquea: presiona.', ru: 'Дух врага дрогнул — дожимайте.', mk: 'Непријателската волја се колеба — притисни.', de: 'Der Wille des Feindes wankt — setze nach.', fr: 'La résolution ennemie vacille — poussez.' },
  imp_clio_grind: { en: 'The lines grind — hold your nerve.', es: 'Las líneas se desgastan: mantén los nervios.', ru: 'Строи перемалывают друг друга — держите нервы.', mk: 'Линиите се мелат — задржи ги живците.', de: 'Die Linien mahlen — behalte die Nerven.', fr: 'Les lignes s’usent — gardez votre sang-froid.' },
};

/**
 * Resolve a catalog key for a language, with {param} interpolation.
 * Contract: components call this at the render boundary — payloads carry keys.
 */
export function impText(key: string, language: Language, params?: Record<string, string | number>): string {
  const entry = CATALOG[key];
  let text = entry ? (entry[language] ?? entry.en) : key;
  if (params) {
    for (const [k, v] of Object.entries(params)) text = text.split(`{${k}}`).join(String(v));
  }
  return text;
}

export function hasImpText(key: string): boolean {
  return key in CATALOG;
}
